import type { PreguntaEntrevista } from "../types";

export const entrevistaCorsCsrfXss: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es XSS y cómo te protege React?",
    respuestaEs:
      "Cross-Site Scripting es lograr que JavaScript del atacante se ejecute en la página de otro usuario, dentro de tu origen, con acceso a todo lo que ese usuario puede hacer: leer datos de la página, hacer requests con su sesión, cambiar el DOM para robar credenciales. Aparece cuando datos no confiables (un comentario, un nombre de usuario, un parámetro de la URL) se insertan en el HTML sin escapar. Hay tres variantes: almacenado (queda guardado en la base y afecta a todos los que lo ven), reflejado (viene en la URL y se devuelve en la respuesta) y basado en el DOM (el JS del cliente lo inserta). React protege por defecto porque ESCAPA todo lo que se renderiza como string en JSX: `<p>{comentario}</p>` muestra el texto literal. La protección se pierde con `dangerouslySetInnerHTML`, con URLs `javascript:` en un `href` construido con datos del usuario, al manipular el DOM directo con refs (`innerHTML`), o al renderizar HTML en el servidor sin escapar.",
    respuestaEn:
      "Cross-Site Scripting is getting the attacker's JavaScript to run in another user's page, within your origin, with access to everything that user can do: reading page data, making requests with their session, altering the DOM to steal credentials. It appears when untrusted data (a comment, a username, a URL parameter) is inserted into HTML without escaping. There are three variants: stored (saved in the database, affecting everyone who views it), reflected (comes in the URL and is echoed in the response) and DOM-based (client JS inserts it). React protects by default because it ESCAPES everything rendered as a string in JSX: `<p>{comment}</p>` shows the literal text. The protection is lost with `dangerouslySetInnerHTML`, `javascript:` URLs in an `href` built from user data, direct DOM manipulation via refs (`innerHTML`), or server-rendering HTML without escaping.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué es CSRF y cómo se diferencia de XSS?",
    respuestaEs:
      "Cross-Site Request Forgery es lograr que el navegador de un usuario logueado mande un request con efectos a tu sitio desde OTRO sitio, aprovechando que el navegador adjunta automáticamente las cookies de tu dominio. Por ejemplo, malicioso.com tiene un formulario oculto que hace POST a tubanco.com/transferir y se envía solo al cargar la página; si la cookie de sesión viaja, el banco ve un request autenticado. El atacante no puede LEER la respuesta (la same-origin policy lo impide), pero no le hace falta: el efecto ya ocurrió. La diferencia con XSS es que en CSRF el código del atacante nunca corre en tu página: solo dispara requests desde afuera usando las credenciales del usuario. Con XSS, en cambio, el atacante ejecuta código dentro de tu origen, lo que es mucho más grave: puede hacer todo lo que haría un CSRF y además leer las respuestas, y las defensas anti-CSRF no lo frenan.",
    respuestaEn:
      "Cross-Site Request Forgery is getting a logged-in user's browser to send a state-changing request to your site from ANOTHER site, exploiting that the browser automatically attaches your domain's cookies. For example, evil.com has a hidden form POSTing to yourbank.com/transfer that submits itself on page load; if the session cookie travels, the bank sees an authenticated request. The attacker can't READ the response (the same-origin policy prevents it), but doesn't need to: the effect already happened. The difference from XSS is that in CSRF the attacker's code never runs on your page: it only fires requests from outside using the user's credentials. With XSS, the attacker runs code inside your origin, which is much worse: it can do everything a CSRF can plus read responses, and anti-CSRF defenses don't stop it.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo se previene CSRF hoy?",
    respuestaEs:
      "En capas. La base es la cookie de sesión con `SameSite=Lax` (default en los navegadores modernos cuando no se especifica) o `Strict`: con Lax, la cookie no se envía en POST cross-site ni en requests embebidos (imágenes, iframes, fetch), solo en navegaciones de primer nivel con GET, que es lo que permite llegar logueado desde un link. Eso cubre la mayoría de los casos, siempre que los GET NUNCA cambien estado. Para operaciones sensibles se agrega una segunda capa: un token anti-CSRF (un valor aleatorio ligado a la sesión que va en el formulario o en un header y que otro sitio no puede conocer), o verificar los headers `Origin` o `Sec-Fetch-Site` en el servidor y rechazar los requests con efectos que vienen de otro sitio. Los frameworks suelen traerlo resuelto: las Server Actions de Next.js, por ejemplo, solo aceptan POST y comparan `Origin` con el host. Y SameSite no protege entre subdominios del mismo sitio, que son 'same-site'.",
    respuestaEn:
      "In layers. The base is the session cookie with `SameSite=Lax` (the default in modern browsers when unspecified) or `Strict`: with Lax, the cookie isn't sent on cross-site POSTs or embedded requests (images, iframes, fetch), only on top-level GET navigations, which is what lets users arrive logged in from a link. That covers most cases, as long as GETs NEVER change state. For sensitive operations a second layer is added: an anti-CSRF token (a random value tied to the session sent in the form or a header, which another site can't know), or checking the `Origin` or `Sec-Fetch-Site` headers on the server and rejecting state-changing requests coming from another site. Frameworks often handle it: Next.js Server Actions, for instance, only accept POST and compare `Origin` with the host. And SameSite doesn't protect between subdomains of the same site, which are 'same-site'.",
    tradeoffs:
      "SameSite=Strict protege más, pero un usuario que llega desde un link externo (un mail, Google) aparece deslogueado en esa primera navegación. Lax es el equilibrio habitual.",
  },
  {
    nivel: 2,
    pregunta: "Si necesitás renderizar HTML que escribió un usuario (un editor de texto enriquecido), ¿cómo lo hacés de forma segura?",
    respuestaEs:
      "Sanitizando con una librería probada y mantenida, como DOMPurify, justo antes de insertarlo: parsea el HTML y deja solo una allowlist de etiquetas y atributos seguros, eliminando scripts, atributos de eventos (`onerror`, `onclick`), URLs `javascript:` y otras vías de ejecución. Nunca con regex caseras: el HTML tiene demasiados casos raros (mayúsculas, codificaciones, etiquetas mal formadas, SVG, mXSS) y las regex fallan. Conviene sanitizar al RENDERIZAR (no solo al guardar), porque los datos de la base pueden venir de otros caminos o de antes de que existiera la sanitización, y configurar la allowlist al mínimo que necesita el editor. Alternativa más robusta: guardar el contenido en un formato estructurado (el JSON de un editor como Tiptap o Lexical, o Markdown) y renderizarlo con componentes, sin pasar nunca por `innerHTML`. Y como defensa en profundidad, una Content-Security-Policy que bloquee scripts inline.",
    respuestaEn:
      "By sanitizing with a proven, maintained library like DOMPurify right before inserting it: it parses the HTML and keeps only an allowlist of safe tags and attributes, removing scripts, event attributes (`onerror`, `onclick`), `javascript:` URLs and other execution vectors. Never with homemade regexes: HTML has too many odd cases (casing, encodings, malformed tags, SVG, mXSS) and regexes fail. Sanitize at RENDER time (not only on save), since database data may come from other paths or predate sanitization, and configure the allowlist to the minimum the editor needs. A more robust alternative: store content in a structured format (a Tiptap or Lexical editor's JSON, or Markdown) and render it with components, never going through `innerHTML`. And as defense in depth, a Content-Security-Policy blocking inline scripts.",
    codigo: `import DOMPurify from "isomorphic-dompurify";

function Comentario({ html }: { html: string }) {
  const limpio = DOMPurify.sanitize(html, {
    ALLOWED_TAGS: ["b", "i", "em", "strong", "a", "p", "ul", "li"],
    ALLOWED_ATTR: ["href"],
  });
  return <div dangerouslySetInnerHTML={{ __html: limpio }} />;
}`,
  },
  {
    nivel: 3,
    pregunta: "¿Cómo ayuda una Content-Security-Policy contra XSS y por qué se recomiendan nonces?",
    respuestaEs:
      "CSP es un header con el que el servidor le dice al navegador de dónde puede cargar y ejecutar recursos. Contra XSS, la directiva clave es `script-src`: si solo se permiten scripts propios y se prohíben los inline, un `<img onerror>` o un `<script>` inyectado no se ejecuta aunque haya llegado al DOM, así que CSP funciona como red de seguridad cuando falla el escapado. El problema práctico es que muchas apps necesitan algún script inline (el de hidratación, analytics). Permitirlos con `'unsafe-inline'` anula la protección. Por eso se usan NONCES: el servidor genera un valor aleatorio en cada request, lo pone en el header (`script-src 'nonce-abc123' 'strict-dynamic'`) y en los `<script nonce=\"abc123\">` legítimos; un script inyectado no conoce el nonce y se bloquea. `'strict-dynamic'` permite que esos scripts confiables carguen otros. Como el nonce cambia en cada request, la página no se puede cachear estáticamente: es un trade-off con el caching. Conviene desplegar primero en modo `Report-Only` para ver qué se rompería.",
    respuestaEn:
      "CSP is a header through which the server tells the browser where it may load and execute resources from. Against XSS, the key directive is `script-src`: if only your own scripts are allowed and inline ones are forbidden, an injected `<img onerror>` or `<script>` doesn't run even if it reached the DOM, so CSP acts as a safety net when escaping fails. The practical problem is many apps need some inline script (hydration, analytics). Allowing them with `'unsafe-inline'` voids the protection. That's why NONCES are used: the server generates a random value per request, puts it in the header (`script-src 'nonce-abc123' 'strict-dynamic'`) and on legitimate `<script nonce=\"abc123\">` tags; an injected script doesn't know the nonce and is blocked. `'strict-dynamic'` lets those trusted scripts load others. Since the nonce changes per request, the page can't be statically cached: it's a trade-off with caching. Deploy first in `Report-Only` mode to see what would break.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo se relacionan CORS, CSRF y la same-origin policy? ¿CORS protege contra CSRF?",
    respuestaEs:
      "La same-origin policy es la base: el JavaScript de un origen no puede LEER respuestas de otro. CORS es la forma controlada de relajarla: el servidor declara qué orígenes pueden leer sus respuestas. CSRF no necesita leer nada: le alcanza con que el request LLEGUE con las cookies del usuario y produzca un efecto. Por eso CORS no protege contra CSRF: un formulario HTML o una imagen hacen requests cross-site sin pasar por CORS, y un request 'simple' (POST de formulario) se envía sin preflight aunque el navegador después bloquee la lectura de la respuesta. Donde sí ayuda es indirectamente: un request que necesita preflight (un JSON con `Content-Type: application/json`, un header custom) no se envía si el preflight falla, así que una API que SOLO acepta JSON y rechaza los content-types de formulario queda protegida contra los CSRF por formulario. Pero no hay que depender de eso: las defensas contra CSRF son SameSite, tokens y verificación de Origin. Y una configuración de CORS demasiado abierta con credenciales empeora las cosas, porque le permite a otro sitio leer las respuestas.",
    respuestaEn:
      "The same-origin policy is the base: one origin's JavaScript can't READ another's responses. CORS is the controlled way to relax it: the server declares which origins may read its responses. CSRF doesn't need to read anything: it just needs the request to ARRIVE with the user's cookies and cause an effect. That's why CORS doesn't protect against CSRF: an HTML form or an image make cross-site requests without going through CORS, and a 'simple' request (a form POST) is sent without preflight even though the browser then blocks reading the response. Where it helps is indirectly: a request needing preflight (JSON with `Content-Type: application/json`, a custom header) isn't sent if the preflight fails, so an API that ONLY accepts JSON and rejects form content types is protected against form-based CSRF. But don't rely on that: CSRF defenses are SameSite, tokens and Origin checks. And an overly open CORS config with credentials makes things worse, since it lets another site read the responses.",
  },
];
