import type { PreguntaEntrevista } from "../types";

export const entrevistaOwaspTop10: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es el OWASP Top 10 y cuáles son las categorías que más te importan como full stack?",
    respuestaEs:
      "Es un documento de consenso de la fundación OWASP que lista los riesgos de seguridad más críticos en aplicaciones web, armado a partir de datos de vulnerabilidades reales; se actualiza cada algunos años (la edición 2021 es la más citada, y la de 2025 reordena la lista y suma categorías como las fallas en la cadena de suministro de software). No es un checklist exhaustivo, sino un piso de concientización. Las que más aparecen en el trabajo diario de un full stack: Broken Access Control (usuarios que acceden a datos o acciones que no deberían, como IDOR), Injection (SQL, NoSQL, comandos, y XSS, que en 2021 quedó dentro de esta categoría), Cryptographic Failures (contraseñas mal hasheadas, datos sensibles sin cifrar), Security Misconfiguration (errores detallados en producción, credenciales por defecto, CORS abierto), componentes vulnerables o desactualizados, y fallas de autenticación (sin rate limiting, sesiones mal manejadas).",
    respuestaEn:
      "It's a consensus document from the OWASP foundation listing the most critical security risks in web applications, built from real vulnerability data; it's updated every few years (the 2021 edition is the most cited, and the 2025 one reorders the list and adds categories like software supply chain failures). It's not an exhaustive checklist, but an awareness baseline. The ones that show up most in a full stack's daily work: Broken Access Control (users reaching data or actions they shouldn't, like IDOR), Injection (SQL, NoSQL, commands, and XSS, which in 2021 was folded into this category), Cryptographic Failures (poorly hashed passwords, unencrypted sensitive data), Security Misconfiguration (detailed errors in production, default credentials, open CORS), vulnerable or outdated components, and authentication failures (no rate limiting, mishandled sessions).",
  },
  {
    nivel: 1,
    pregunta: "¿Cómo se previene la inyección SQL si uso un ORM?",
    respuestaEs:
      "Un ORM como Prisma o Drizzle usa consultas parametrizadas en sus métodos normales (`findMany({ where: { nombre } })`), así que el input del usuario viaja como DATO, separado del texto de la consulta, y no puede cambiar su estructura. El riesgo vuelve cuando se escapa del ORM: las funciones de SQL crudo que aceptan un string (`$queryRawUnsafe`, `sequelize.query` con interpolación) concatenan el input y son tan vulnerables como SQL a mano. Las versiones seguras usan tagged templates o placeholders, que parametrizan automáticamente. Otros puntos: los nombres de columnas o de ordenamiento no se pueden parametrizar, así que si vienen del usuario (`?orden=precio`) se validan contra una allowlist; y en bases NoSQL existe la inyección de operadores (mandar `{ \"$gt\": \"\" }` en vez de un string), que se previene validando el tipo de cada campo con un esquema.",
    respuestaEn:
      "An ORM like Prisma or Drizzle uses parameterized queries in its normal methods (`findMany({ where: { name } })`), so user input travels as DATA, separate from the query text, and can't change its structure. The risk returns when you escape the ORM: raw SQL functions accepting a string (`$queryRawUnsafe`, `sequelize.query` with interpolation) concatenate input and are as vulnerable as hand-written SQL. Safe versions use tagged templates or placeholders, which parameterize automatically. Other points: column or sort names can't be parameterized, so if they come from the user (`?sort=price`) they're validated against an allowlist; and NoSQL databases have operator injection (sending `{ \"$gt\": \"\" }` instead of a string), prevented by validating each field's type with a schema.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo se deben guardar las contraseñas?",
    respuestaEs:
      "Nunca en texto plano ni cifradas de forma reversible, y tampoco con un hash rápido (MD5, SHA-1, SHA-256): esos algoritmos están diseñados para ser rápidos, y con una GPU un atacante que roba la base prueba miles de millones de contraseñas por segundo. Se usa un algoritmo de hashing de contraseñas deliberadamente LENTO y con uso de memoria configurable: Argon2id (la recomendación actual), scrypt o bcrypt. Todos incluyen una sal aleatoria por usuario, lo que impide usar tablas precalculadas y hace que dos usuarios con la misma contraseña tengan hashes distintos. El factor de costo se ajusta para que verificar tarde del orden de cientos de milisegundos en tu hardware, y se sube con el tiempo (re-hasheando en el siguiente login). Complementos: rechazar contraseñas conocidas por filtraciones, rate limiting en el login, y MFA.",
    respuestaEn:
      "Never in plain text nor reversibly encrypted, and not with a fast hash either (MD5, SHA-1, SHA-256): those algorithms are designed to be fast, and with a GPU an attacker who steals the database tries billions of passwords per second. Use a deliberately SLOW password hashing algorithm with configurable memory use: Argon2id (the current recommendation), scrypt or bcrypt. All include a random per-user salt, preventing precomputed tables and making two users with the same password have different hashes. The cost factor is tuned so verifying takes on the order of hundreds of milliseconds on your hardware, and raised over time (rehashing at the next login). Complements: rejecting passwords known from breaches, login rate limiting, and MFA.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué riesgos tiene la cadena de suministro de software y cómo los mitigás?",
    respuestaEs:
      "Una app moderna tiene cientos o miles de dependencias transitivas, y cualquiera puede ser un vector: una versión con una vulnerabilidad conocida (CVE), un paquete legítimo comprometido (el mantenedor pierde su cuenta y se publica una versión maliciosa que roba variables de entorno en el `postinstall`), typosquatting (un paquete con un nombre casi igual al real) o dependency confusion (un paquete público con el mismo nombre que uno interno). Mitigaciones: lockfile commiteado e instalación reproducible (`npm ci`), escaneo automático de vulnerabilidades (npm audit, Dependabot, Snyk) con actualizaciones frecuentes y chicas, revisar las dependencias nuevas antes de agregarlas (mantenimiento, popularidad, qué scripts corren al instalar), desactivar scripts de instalación donde sea posible, fijar versiones de las GitHub Actions por hash, y minimizar dependencias: cada paquete es código de un tercero corriendo con tus permisos.",
    respuestaEn:
      "A modern app has hundreds or thousands of transitive dependencies, and any can be a vector: a version with a known vulnerability (CVE), a legitimate package compromised (the maintainer loses their account and a malicious version is published that steals environment variables in `postinstall`), typosquatting (a package with a nearly identical name) or dependency confusion (a public package with the same name as an internal one). Mitigations: committed lockfile and reproducible installs (`npm ci`), automated vulnerability scanning (npm audit, Dependabot, Snyk) with frequent small updates, reviewing new dependencies before adding them (maintenance, popularity, which scripts run on install), disabling install scripts where possible, pinning GitHub Actions versions by hash, and minimizing dependencies: every package is third-party code running with your permissions.",
    tradeoffs:
      "Actualizar seguido reduce la ventana de exposición a CVEs pero introduce cambios constantes; actualizar poco acumula saltos grandes y riesgosos. Las actualizaciones chicas y automatizadas con buenos tests suelen ser el equilibrio.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es SSRF y por qué es especialmente grave en el cloud?",
    respuestaEs:
      "Server-Side Request Forgery es lograr que el SERVIDOR haga requests a destinos que elige el atacante, típicamente a través de una funcionalidad legítima que recibe una URL: vista previa de links, importar una imagen desde una URL, webhooks configurables, generadores de PDF que cargan recursos. Como el request sale desde adentro de la red, puede alcanzar servicios internos que no están expuestos a Internet (paneles de administración, bases, APIs internas) y saltearse firewalls. En el cloud es especialmente grave por el servicio de metadata de la instancia (`169.254.169.254`), que devuelve credenciales temporales del rol de la máquina: un SSRF puede terminar en acceso a buckets o bases de toda la cuenta (así fue la filtración de Capital One en 2019). Mitigaciones: allowlist de dominios cuando se puede; si no, resolver el DNS y rechazar IPs privadas, loopback y link-local (cuidando redirecciones y DNS rebinding); aislar en red a los servicios que hacen fetch de URLs externas; y en AWS usar IMDSv2, que exige un token y bloquea la mayoría de los SSRF simples.",
    respuestaEn:
      "Server-Side Request Forgery is getting the SERVER to make requests to attacker-chosen destinations, typically through a legitimate feature taking a URL: link previews, importing an image from a URL, configurable webhooks, PDF generators loading resources. Since the request originates inside the network, it can reach internal services not exposed to the Internet (admin panels, databases, internal APIs) and bypass firewalls. In the cloud it's especially severe because of the instance metadata service (`169.254.169.254`), which returns temporary credentials for the machine's role: an SSRF can end in access to buckets or databases across the whole account (as in the 2019 Capital One breach). Mitigations: a domain allowlist when possible; otherwise, resolve DNS and reject private, loopback and link-local IPs (handling redirects and DNS rebinding); network-isolate services that fetch external URLs; and on AWS use IMDSv2, which requires a token and blocks most simple SSRFs.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es 'Insecure Design' y en qué se diferencia de un bug de implementación?",
    respuestaEs:
      "Un bug de implementación es un error en cómo se escribió algo que estaba bien pensado: una consulta concatenada, un chequeo olvidado. Insecure Design es una falla en el DISEÑO: aunque se implemente perfecto, el flujo es inseguro porque nunca se consideró la amenaza. Ejemplos: un flujo de recuperación de cuenta basado en 'preguntas de seguridad' cuyas respuestas se encuentran en redes sociales; un checkout que confía en el precio que manda el cliente; un sistema de cupones sin límite de usos por usuario, explotable con cuentas creadas en masa; una API sin límites de negocio que permite reservar todas las entradas de un evento con un bot. No se arregla con un parche en una línea sino rediseñando. Se previene con threat modeling en la etapa de diseño (preguntarse qué puede salir mal y quién tiene incentivos para abusarlo, por ejemplo con STRIDE), casos de abuso junto a los casos de uso, y reglas de negocio validadas siempre en el servidor.",
    respuestaEn:
      "An implementation bug is a mistake in how something well-conceived was written: a concatenated query, a forgotten check. Insecure Design is a flaw in the DESIGN: even implemented perfectly, the flow is insecure because the threat was never considered. Examples: an account recovery flow based on 'security questions' whose answers are findable on social media; a checkout trusting the price the client sends; a coupon system with no per-user usage limit, exploitable with mass-created accounts; an API with no business limits letting a bot book every ticket for an event. It's not fixed with a one-line patch but by redesigning. It's prevented with threat modeling at design time (asking what can go wrong and who has incentives to abuse it, e.g. with STRIDE), abuse cases alongside use cases, and business rules always validated on the server.",
  },
];
