import type { PreguntaEntrevista } from "../types";

export const entrevistaAwsBasico: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué son EC2, S3, Lambda y RDS, y para qué usarías cada uno?",
    respuestaEs:
      "Son cuatro de los servicios base de AWS, uno por necesidad. EC2 son máquinas virtuales: elegís el tipo de instancia (CPU, memoria), la imagen del sistema operativo y la red, y corrés lo que quieras; lo usás cuando necesitás control del servidor o procesos que no encajan en servicios más gestionados. S3 es almacenamiento de objetos: guardás archivos (imágenes, PDFs, backups, logs, el build de un frontend) en buckets, accesibles por HTTP, con durabilidad altísima y costo bajo por gigabyte; no es un sistema de archivos ni una base de datos, sino un almacén de blobs identificados por clave. LAMBDA ejecuta funciones en respuesta a eventos (un request HTTP, un archivo subido a S3, un mensaje en una cola, un cron) sin administrar servidores, pagando por invocación y tiempo. RDS es una base relacional gestionada (Postgres, MySQL y otras): AWS se ocupa de instalar, parchear, hacer backups y failover, y vos de diseñar el schema y configurar el acceso. Una arquitectura típica los combina: una API en Lambda o en contenedores, datos en RDS, archivos en S3, y cada pieza con un rol IAM que le da solo los permisos que necesita.",
    respuestaEn:
      "They're four of AWS's foundational services, one per need. EC2 is virtual machines: you pick the instance type (CPU, memory), the OS image and the network, and run whatever you want; you use it when you need server control or processes that don't fit more managed services. S3 is object storage: you store files (images, PDFs, backups, logs, a frontend build) in buckets, accessible over HTTP, with very high durability and low per-gigabyte cost; it's neither a filesystem nor a database, but a blob store identified by key. LAMBDA runs functions in response to events (an HTTP request, a file uploaded to S3, a queue message, a cron) without managing servers, paying per invocation and time. RDS is a managed relational database (Postgres, MySQL and others): AWS handles installing, patching, backups and failover, and you handle schema design and access configuration. A typical architecture combines them: an API on Lambda or containers, data in RDS, files in S3, and each piece with an IAM role granting only the permissions it needs.",
  },
  {
    nivel: 1,
    pregunta: "¿Cómo funciona IAM y por qué se usan roles en vez de usuarios con claves?",
    respuestaEs:
      "IAM decide quién puede hacer qué sobre qué recurso. Las piezas: IDENTIDADES (usuarios para personas, roles para servicios o accesos temporales), POLÍTICAS (documentos JSON con Effect, Action, Resource y, opcionalmente, Condition) y la EVALUACIÓN: por defecto todo está denegado, un Allow lo habilita y un Deny explícito gana siempre. Un USUARIO IAM tiene credenciales de larga vida (una access key que no vence), y esas claves son la causa clásica de incidentes: terminan en un repo, un log o una laptop robada. Un ROL no tiene credenciales propias: se asume, y AWS entrega credenciales temporales que vencen solas. Una instancia EC2, una función Lambda o una tarea de ECS asumen su rol automáticamente, así que el código usa el SDK sin configurar ninguna clave; un workflow de CI asume un rol por OIDC; y las personas entran con SSO (IAM Identity Center) y asumen roles según su función. La regla práctica: ninguna access key de larga vida si se puede evitar, un rol por servicio con los permisos mínimos, y MFA para las personas.",
    respuestaEn:
      "IAM decides who can do what on which resource. The pieces: IDENTITIES (users for people, roles for services or temporary access), POLICIES (JSON documents with Effect, Action, Resource and optionally Condition) and EVALUATION: everything is denied by default, an Allow enables it and an explicit Deny always wins. An IAM USER has long-lived credentials (an access key that doesn't expire), and those keys are the classic cause of incidents: they end up in a repo, a log or a stolen laptop. A ROLE has no credentials of its own: it's assumed, and AWS issues temporary credentials that expire on their own. An EC2 instance, a Lambda function or an ECS task assumes its role automatically, so code uses the SDK without configuring any key; a CI workflow assumes a role via OIDC; and people sign in with SSO (IAM Identity Center) and assume roles by function. The practical rule: no long-lived access keys when avoidable, one role per service with least privilege, and MFA for people.",
    codigo: `{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": ["s3:GetObject", "s3:PutObject"],
    "Resource": "arn:aws:s3:::facturas-prod/*"
  }]
}
// adjunta al rol de la API: solo leer y escribir objetos de ese bucket`,
  },
  {
    nivel: 2,
    pregunta: "¿Qué tenés que saber de S3 para usarlo bien en una aplicación?",
    respuestaEs:
      "Primero, que es privado por defecto y conviene que siga así: Block Public Access activado a nivel de cuenta, y el acceso a archivos de usuarios mediante URLs FIRMADAS (presigned URLs), que dan permiso temporal para leer o subir un objeto puntual. Así el navegador sube directo a S3 sin pasar el archivo por tu API, y descarga sin que el bucket sea público. Para contenido público y cacheable, como los assets de un frontend, se pone un CDN (CloudFront) delante, con acceso restringido al bucket. Segundo, el modelo de datos: es un almacén clave-valor plano; las 'carpetas' son prefijos de la clave, no hay renombrar ni append, un objeto se reemplaza entero. Desde fines de 2020 tiene consistencia fuerte de lectura después de escritura. Tercero, el costo: las CLASES DE ALMACENAMIENTO (Standard, Infrequent Access, Glacier) cambian precio de almacenamiento por precio y demora de lectura, y las REGLAS DE CICLO DE VIDA mueven o borran objetos automáticamente según su edad. Y para datos importantes, VERSIONADO, que permite recuperar un objeto sobrescrito o borrado.",
    respuestaEn:
      "First, that it's private by default and should stay that way: Block Public Access enabled at the account level, and access to user files via SIGNED URLs (presigned URLs), which grant temporary permission to read or upload one specific object. That way the browser uploads straight to S3 without routing the file through your API, and downloads without the bucket being public. For public, cacheable content, like a frontend's assets, you put a CDN (CloudFront) in front, with restricted access to the bucket. Second, the data model: it's a flat key-value store; 'folders' are key prefixes, there's no rename or append, an object is replaced whole. Since late 2020 it has strong read-after-write consistency. Third, cost: STORAGE CLASSES (Standard, Infrequent Access, Glacier) trade storage price for retrieval price and latency, and LIFECYCLE RULES move or delete objects automatically by age. And for important data, VERSIONING, which lets you recover an overwritten or deleted object.",
    codigo: `import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// la API genera la URL; el navegador sube el archivo directo a S3
const url = await getSignedUrl(
  new S3Client({}),
  new PutObjectCommand({ Bucket: "comprobantes", Key: \`\${usuarioId}/\${crypto.randomUUID()}.pdf\` }),
  { expiresIn: 300 }, // 5 minutos
);`,
  },
  {
    nivel: 2,
    pregunta: "RDS, Aurora, DynamoDB o Postgres en una EC2: ¿cómo elegís?",
    respuestaEs:
      "POSTGRES EN EC2: control total (extensiones, configuración, versión), pero backups, réplicas, failover, parches y monitoreo son tuyos; rara vez compensa salvo necesidades muy específicas. RDS: el mismo Postgres o MySQL, gestionado; backups automáticos con point-in-time recovery, Multi-AZ para failover, réplicas de lectura, parches en ventanas de mantenimiento. Es el default razonable para una base relacional. AURORA: compatible con Postgres y MySQL, pero con una capa de almacenamiento propia distribuida entre zonas; failover más rápido, réplicas con menos lag, y almacenamiento que crece solo. Cuesta más y conviene cuando la escala o la disponibilidad lo justifican; su variante serverless escala la capacidad con la carga. DYNAMODB: NoSQL clave-valor totalmente gestionado, latencia baja y constante a cualquier escala, sin conexiones que administrar (ideal con Lambda); pero hay que diseñar el modelo alrededor de los patrones de acceso de antemano, no hay joins, y las consultas no previstas son caras o imposibles. Para la mayoría de las aplicaciones de negocio, RDS Postgres, y DynamoDB para piezas puntuales con acceso por clave y escala muy alta.",
    respuestaEn:
      "POSTGRES ON EC2: total control (extensions, configuration, version), but backups, replicas, failover, patching and monitoring are yours; it rarely pays off except for very specific needs. RDS: the same Postgres or MySQL, managed; automatic backups with point-in-time recovery, Multi-AZ for failover, read replicas, patches in maintenance windows. It's the reasonable default for a relational database. AURORA: Postgres- and MySQL-compatible, but with its own storage layer distributed across zones; faster failover, lower-lag replicas, and storage that grows on its own. It costs more and pays off when scale or availability justify it; its serverless variant scales capacity with load. DYNAMODB: fully managed key-value NoSQL, low and consistent latency at any scale, no connections to manage (ideal with Lambda); but you must design the model around access patterns up front, there are no joins, and unplanned queries are expensive or impossible. For most business applications, RDS Postgres, and DynamoDB for specific pieces with key-based access at very high scale.",
    tradeoffs:
      "Más gestionado es menos operación y menos control; DynamoDB cambia flexibilidad de consultas por escala y latencia predecibles.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo evalúa AWS una request cuando hay varias políticas involucradas?",
    respuestaEs:
      "Junta todas las políticas que aplican y sigue un orden fijo. Primero, si cualquiera tiene un DENY explícito que coincide con la request, se deniega, sin importar cuántos Allow haya. Después, los límites que no otorgan permisos sino que los acotan: las SCPs de la organización (si la cuenta está en AWS Organizations) y los permission boundaries del rol; si la acción no está permitida por ellos, se deniega aunque el rol la tenga. Luego se buscan los ALLOW: en la política de identidad (adjunta al rol o usuario) y en la política del recurso (la bucket policy, la key policy de KMS). Dentro de la misma cuenta, alcanza con un Allow en cualquiera de las dos; entre cuentas distintas hacen falta las dos: la cuenta del que pide tiene que dejarlo pedir y el recurso tiene que aceptarlo. Si no hay ningún Allow, rige el deny implícito. Las CONDITIONS afinan todo esto: `aws:SourceVpce` para aceptar solo tráfico por un VPC endpoint, `aws:PrincipalOrgID` para aceptar a cualquier cuenta de tu organización, `aws:SecureTransport` para exigir HTTPS. Para mantener el mínimo privilegio, IAM Access Analyzer detecta recursos compartidos hacia afuera y sugiere políticas a partir de la actividad real.",
    respuestaEn:
      "It gathers every applicable policy and follows a fixed order. First, if any has an explicit DENY matching the request, it's denied, no matter how many Allows exist. Next, the limits that don't grant permissions but bound them: the organization's SCPs (if the account is in AWS Organizations) and the role's permission boundaries; if they don't allow the action, it's denied even if the role has it. Then it looks for ALLOWs: in the identity policy (attached to the role or user) and in the resource policy (the bucket policy, the KMS key policy). Within the same account, one Allow in either is enough; across accounts both are needed: the requester's account must let them ask and the resource must accept them. With no Allow, the implicit deny applies. CONDITIONS refine all this: `aws:SourceVpce` to accept only traffic through a VPC endpoint, `aws:PrincipalOrgID` to accept any account in your organization, `aws:SecureTransport` to require HTTPS. To keep least privilege, IAM Access Analyzer finds resources shared externally and suggests policies from actual activity.",
  },
  {
    nivel: 3,
    pregunta: "Una API en AWS: ¿dónde aparecen los costos y las fallas que nadie esperaba?",
    respuestaEs:
      "Varios clásicos. NAT GATEWAY: los recursos en subredes privadas (una Lambda dentro de la VPC, tareas de ECS) salen a internet por un NAT, que cobra por hora y por gigabyte procesado; una API que baja muchas imágenes de S3 por el NAT puede pagar más de NAT que de cómputo. Para S3 y DynamoDB existen VPC endpoints de tipo gateway, sin costo, que evitan pasar por el NAT. TRANSFERENCIA DE DATOS: la salida a internet se cobra, y también el tráfico entre zonas de disponibilidad; un servicio que habla constantemente con una base en otra zona suma. RECURSOS OLVIDADOS: instancias de prueba, volúmenes EBS sueltos, snapshots viejos, IPs públicas; conviene etiquetar todo por proyecto y tener alertas de presupuesto. LÍMITES DE CUENTA (service quotas): concurrencia de Lambda, cantidad de instancias, direcciones IP; llegar a uno en un pico parece una caída sin explicación. UNA SOLA ZONA: una instancia o una base Single-AZ caen con su zona. Y UNA SOLA CUENTA para todo: producción, staging y experimentos compartiendo permisos y límites; la práctica es separar cuentas con AWS Organizations, al menos producción del resto.",
    respuestaEn:
      "Several classics. NAT GATEWAY: resources in private subnets (a Lambda inside the VPC, ECS tasks) reach the internet through a NAT, billed per hour and per gigabyte processed; an API pulling lots of images from S3 through the NAT can pay more for NAT than for compute. For S3 and DynamoDB there are gateway VPC endpoints, free, that avoid the NAT. DATA TRANSFER: egress to the internet is billed, and so is traffic between availability zones; a service constantly talking to a database in another zone adds up. FORGOTTEN RESOURCES: test instances, loose EBS volumes, old snapshots, public IPs; tag everything by project and set budget alerts. ACCOUNT LIMITS (service quotas): Lambda concurrency, instance counts, IP addresses; hitting one during a peak looks like an unexplained outage. A SINGLE ZONE: a Single-AZ instance or database goes down with its zone. And A SINGLE ACCOUNT for everything: production, staging and experiments sharing permissions and limits; the practice is separating accounts with AWS Organizations, at least production from the rest.",
  },
];
