import type { PreguntaEntrevista } from "../types";

export const entrevistaComputo: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué diferencias hay entre máquinas virtuales, contenedores y serverless?",
    respuestaEs:
      "Son tres niveles de abstracción sobre dónde corre tu código. Una MÁQUINA VIRTUAL (EC2, Compute Engine) es un servidor completo con su sistema operativo: control total (cualquier software, procesos de larga vida, conexiones persistentes, discos locales), pero vos instalás, parcheás y escalás, y una VM nueva tarda minutos en estar lista. Un CONTENEDOR empaqueta la app con sus dependencias y corre sobre un host compartido; en servicios gestionados (ECS con Fargate, Cloud Run) no administrás los hosts, arranca en segundos y la misma imagen corre igual en todos lados. Seguís pagando por instancias prendidas, aunque algunos servicios pueden bajar a cero. SERVERLESS de funciones (Lambda, Vercel Functions) ejecuta tu código por evento o por request: el proveedor escala automáticamente de cero a miles de instancias y cobra por invocación y tiempo de ejecución, sin nada que administrar. A cambio, tiene límites (duración máxima, sin estado entre invocaciones), cold starts, y es más difícil de reproducir en local. El eje es control y previsibilidad contra operación y elasticidad.",
    respuestaEn:
      "They're three abstraction levels over where your code runs. A VIRTUAL MACHINE (EC2, Compute Engine) is a full server with its operating system: total control (any software, long-lived processes, persistent connections, local disks), but you install, patch and scale, and a new VM takes minutes to be ready. A CONTAINER packages the app with its dependencies and runs on a shared host; in managed services (ECS with Fargate, Cloud Run) you don't manage hosts, it starts in seconds and the same image runs the same everywhere. You still pay for running instances, though some services can scale to zero. Function SERVERLESS (Lambda, Vercel Functions) runs your code per event or request: the provider scales automatically from zero to thousands of instances and bills per invocation and execution time, with nothing to manage. In exchange, it has limits (maximum duration, no state between invocations), cold starts, and is harder to reproduce locally. The axis is control and predictability versus operations and elasticity.",
  },
  {
    nivel: 1,
    pregunta: "Arrancás un producto nuevo. ¿En qué lo corrés?",
    respuestaEs:
      "Depende del tipo de carga, pero el default razonable es lo más gestionado que la cumpla, porque el tiempo del equipo es lo más caro al principio. Una app web o API con tráfico irregular y requests cortas encaja muy bien en serverless o en una plataforma que lo abstrae (Vercel, Cloud Run): cero operación, escala sola y cuesta casi nada con poco tráfico. Si la app necesita procesos de larga vida (WebSockets, workers que consumen colas todo el tiempo, jobs de más de 15 minutos) o tráfico alto y constante, los contenedores gestionados son el punto medio: la misma imagen que en local, sin administrar servidores, sin límites de duración. Las VMs quedan para casos puntuales: software que necesita el sistema operativo entero, licencias atadas a máquinas, GPUs con configuración especial, o cuando se necesita control fino del hardware. Y Kubernetes, recién cuando hay suficientes servicios y equipo de plataforma como para justificar su costo operativo. Lo importante es no casarse: con contenedores y buena separación, pasar de Cloud Run a ECS o de Lambda a contenedores es una migración acotada.",
    respuestaEn:
      "It depends on the workload, but the reasonable default is the most managed option that fits, because team time is the most expensive thing early on. A web app or API with irregular traffic and short requests fits serverless very well, or a platform abstracting it (Vercel, Cloud Run): zero operations, scales on its own and costs almost nothing at low traffic. If the app needs long-lived processes (WebSockets, workers constantly consuming queues, jobs over 15 minutes) or high, steady traffic, managed containers are the middle ground: the same image as locally, no servers to manage, no duration limits. VMs are for specific cases: software needing the whole operating system, machine-bound licenses, GPUs with special configuration, or when fine hardware control is needed. And Kubernetes only once there are enough services and a platform team to justify its operational cost. The key is not to marry any of them: with containers and good separation, moving from Cloud Run to ECS or from Lambda to containers is a bounded migration.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué es un cold start y cómo lo mitigás?",
    respuestaEs:
      "Es la demora de la primera invocación en una instancia nueva de una función: el proveedor tiene que conseguir un entorno de ejecución, descargar el código, arrancar el runtime y ejecutar la inicialización (imports, conexiones, lectura de configuración) antes de atender la request. Pasa cuando la función estuvo inactiva y sus instancias se reciclaron, y también durante un pico, cuando hacen falta instancias nuevas. Puede ir de decenas de milisegundos a varios segundos. Lo agravan: bundles grandes con muchas dependencias, runtimes más pesados (la JVM más que Node), inicializaciones costosas en el top level y, en algunos casos, configuraciones de red adicionales. Mitigaciones, de más barata a más cara: achicar el bundle y diferir la inicialización que no se usa en todas las requests; reutilizar conexiones y clientes entre invocaciones declarándolos fuera del handler; y pagar por instancias pre-calentadas (provisioned concurrency en Lambda, mínimo de instancias en Cloud Run), que elimina el cold start a cambio de pagar capacidad aunque no se use, o sea, volver en parte al modelo de instancias prendidas. Y medir antes de optimizar: si el p99 aceptable es 1 segundo y el cold start es de 300 ms, no es un problema.",
    respuestaEn:
      "It's the delay of the first invocation on a new function instance: the provider must get an execution environment, download the code, start the runtime and run initialization (imports, connections, reading configuration) before serving the request. It happens when the function was idle and its instances were recycled, and also during a spike, when new instances are needed. It can range from tens of milliseconds to several seconds. It's worsened by: large bundles with many dependencies, heavier runtimes (the JVM more than Node), expensive top-level initialization and, in some cases, extra network configuration. Mitigations, from cheapest to most expensive: shrink the bundle and defer initialization not used by every request; reuse connections and clients across invocations by declaring them outside the handler; and pay for pre-warmed instances (provisioned concurrency in Lambda, minimum instances in Cloud Run), which eliminates cold starts at the cost of paying for capacity even when unused, that is, partly going back to the always-on model. And measure before optimizing: if the acceptable p99 is 1 second and the cold start is 300 ms, it's not a problem.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué límites tiene serverless que te pueden hacer elegir contenedores?",
    respuestaEs:
      "DURACIÓN: cada invocación tiene un máximo (15 minutos en Lambda; en plataformas web suele ser mucho menos), así que procesamientos largos hay que partirlos o llevarlos a otro lado. SIN ESTADO: no hay memoria ni disco que sobreviva entre invocaciones de forma confiable, así que caches locales, sesiones o archivos temporales no sirven como en un servidor. CONEXIONES A LA BASE: cada instancia abre su propia conexión, y cien invocaciones concurrentes son cien conexiones contra un Postgres que admite pocas; se resuelve con un pooler (RDS Proxy, el endpoint pooled de Neon) o drivers sobre HTTP. CONEXIONES LARGAS: WebSockets o streams de minutos no encajan en el modelo de request/respuesta, aunque algunos proveedores ofrecen piezas específicas. COSTO con tráfico alto y constante: pagar por invocación sale más caro que tener instancias bien aprovechadas todo el día. Y OPERACIÓN distinta: reproducir el entorno en local, depurar y observar funciones distribuidas es más difícil, y el código tiende a acoplarse a los eventos y servicios del proveedor. Nada de esto lo descarta; define para qué partes del sistema conviene.",
    respuestaEn:
      "DURATION: each invocation has a maximum (15 minutes on Lambda; on web platforms usually much less), so long processing must be split up or moved elsewhere. STATELESS: no memory or disk reliably survives between invocations, so local caches, sessions or temp files don't work like on a server. DATABASE CONNECTIONS: each instance opens its own connection, and a hundred concurrent invocations are a hundred connections against a Postgres that allows few; solved with a pooler (RDS Proxy, Neon's pooled endpoint) or HTTP-based drivers. LONG CONNECTIONS: WebSockets or minutes-long streams don't fit the request/response model, though some providers offer specific pieces. COST at high, steady traffic: paying per invocation ends up more expensive than well-utilized instances running all day. And DIFFERENT OPERATIONS: reproducing the environment locally, debugging and observing distributed functions is harder, and code tends to couple to the provider's events and services. None of this rules it out; it defines which parts of the system it suits.",
    tradeoffs:
      "Serverless cambia operación y capacidad ociosa por límites de ejecución, cold starts y acoplamiento al proveedor; contenedores dan más control y previsibilidad a cambio de administrar escalado y un mínimo de instancias.",
  },
  {
    nivel: 3,
    pregunta: "¿Cuándo vale la pena Kubernetes?",
    respuestaEs:
      "Kubernetes es una plataforma para orquestar contenedores: agenda pods en nodos, los reinicia si fallan, maneja deploys rolling, service discovery, autoscaling y configuración, todo de forma declarativa y extensible. Su fortaleza es la estandarización: con muchos servicios y equipos, da una sola forma de desplegar, observar y operar, portable entre nubes, con un ecosistema enorme (operadores, service mesh, GitOps). Su costo es alto y se subestima: aunque el control plane sea gestionado (EKS, GKE, AKS), hay que operar nodos, actualizaciones de versión cada pocos meses, redes, políticas de seguridad, almacenamiento, y escribir y mantener mucha configuración; en la práctica requiere gente dedicada a la plataforma. Por eso la pregunta no es si es buena tecnología, sino si el problema lo justifica. Para un producto con un puñado de servicios, ECS con Fargate, Cloud Run o una plataforma tipo Vercel dan casi todo lo que se usa de Kubernetes sin ese costo. Tiene sentido con decenas de servicios, varios equipos que necesitan una plataforma común, requisitos de portabilidad o de correr on-premise, o cargas especiales (GPUs, cómputo por lotes) que se benefician de su scheduler.",
    respuestaEn:
      "Kubernetes is a platform for orchestrating containers: it schedules pods onto nodes, restarts them on failure, handles rolling deploys, service discovery, autoscaling and configuration, all declaratively and extensibly. Its strength is standardization: with many services and teams, it provides one way to deploy, observe and operate, portable across clouds, with a huge ecosystem (operators, service mesh, GitOps). Its cost is high and underestimated: even with a managed control plane (EKS, GKE, AKS), you operate nodes, version upgrades every few months, networking, security policies, storage, and write and maintain a lot of configuration; in practice it needs people dedicated to the platform. So the question isn't whether it's good technology, but whether the problem justifies it. For a product with a handful of services, ECS with Fargate, Cloud Run or a Vercel-like platform give almost everything people use from Kubernetes without that cost. It makes sense with dozens of services, several teams needing a common platform, portability or on-premise requirements, or special workloads (GPUs, batch computing) that benefit from its scheduler.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo escala cada modelo, y qué puede romperse cuando escala bien?",
    respuestaEs:
      "Las VMs y los contenedores escalan con un AUTOSCALER que mira una señal y agrega o quita instancias. La señal importa: la CPU es la clásica pero reacciona tarde en apps que esperan IO; la cantidad de requests concurrentes por instancia o el largo de una cola de trabajo suelen reflejar mejor la carga. Y hay una demora entre detectar y tener capacidad lista (minutos en VMs, segundos en contenedores), así que para picos previsibles conviene escalar por agenda antes de que lleguen. Serverless escala por invocación: cada request concurrente puede usar una instancia (en Lambda, una por request; otros modelos atienden varias por instancia), hasta un límite de concurrencia por cuenta y región; si se supera, las invocaciones se rechazan con throttling. Por dentro, Lambda aísla las instancias en microVMs Firecracker, que arrancan en milisegundos. Lo que se rompe cuando el cómputo escala bien son las DEPENDENCIAS que no escalan igual: mil funciones concurrentes abren mil conexiones contra una base que admite cien, o saturan una API externa con rate limit. Es un autoataque. Se protege con concurrencia reservada o máxima por función, poolers de conexiones, colas que absorban el pico y lo entreguen al ritmo que el backend soporta, y circuit breakers.",
    respuestaEn:
      "VMs and containers scale with an AUTOSCALER watching a signal and adding or removing instances. The signal matters: CPU is the classic one but reacts late for IO-bound apps; concurrent requests per instance or the length of a work queue usually reflect load better. And there's a delay between detecting and having capacity ready (minutes for VMs, seconds for containers), so for predictable peaks it's worth scaling on a schedule before they arrive. Serverless scales per invocation: each concurrent request may use an instance (on Lambda, one per request; other models serve several per instance), up to a concurrency limit per account and region; beyond it, invocations are throttled. Internally, Lambda isolates instances in Firecracker microVMs, which boot in milliseconds. What breaks when compute scales well are the DEPENDENCIES that don't scale the same way: a thousand concurrent functions open a thousand connections against a database that allows a hundred, or saturate a rate-limited external API. It's a self-inflicted attack. You protect against it with reserved or maximum concurrency per function, connection poolers, queues that absorb the spike and deliver it at the pace the backend can handle, and circuit breakers.",
  },
];
