import type { PreguntaEntrevista } from "../types";

export const entrevistaCostoEscalabilidad: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Cómo se cobra la nube y qué mirás para estimar el costo de un sistema?",
    respuestaEs:
      "Casi todo es pago por uso, con tres componentes grandes. CÓMPUTO: por hora de instancia o contenedor prendido (según CPU y memoria), o por invocación y tiempo de ejecución en serverless. ALMACENAMIENTO: por gigabyte al mes, que varía mucho según la clase (una base de datos cuesta bastante más por gigabyte que S3, y S3 Glacier mucho menos), más las operaciones de lectura y escritura. RED: la entrada suele ser gratis, pero la salida a internet, el tráfico entre zonas y regiones, y el que pasa por un NAT se cobran por gigabyte, y es el componente que más se subestima. A eso se suman los servicios gestionados, que cobran su propia prima (una base gestionada cuesta más que la misma base en una VM, a cambio de no operarla), y la observabilidad: logs y métricas también se pagan por volumen. Para estimar, se parte del uso esperado (requests por mes, datos guardados, tráfico de salida) y se usa la calculadora del proveedor, y una vez en producción se mira el costo real por servicio y por proyecto con etiquetas, porque la estimación inicial casi nunca coincide.",
    respuestaEn:
      "Almost everything is pay-per-use, with three big components. COMPUTE: per hour of a running instance or container (by CPU and memory), or per invocation and execution time in serverless. STORAGE: per gigabyte per month, varying widely by class (a database costs far more per gigabyte than S3, and S3 Glacier much less), plus read and write operations. NETWORK: ingress is usually free, but internet egress, cross-zone and cross-region traffic, and traffic through a NAT are billed per gigabyte, and it's the most underestimated component. On top of that come managed services, which charge their own premium (a managed database costs more than the same database on a VM, in exchange for not operating it), and observability: logs and metrics are billed by volume too. To estimate, start from expected usage (requests per month, stored data, egress) and use the provider's calculator, and once in production track real cost per service and per project with tags, because the initial estimate almost never matches.",
  },
  {
    nivel: 1,
    pregunta: "¿Cuándo es más barato serverless y cuándo instancias prendidas?",
    respuestaEs:
      "Depende de cuánto se usa la capacidad que pagás. Serverless cobra por request: con poco tráfico o tráfico muy irregular es mucho más barato, porque no se paga nada mientras no hay actividad y no hay capacidad ociosa. Pero su costo por request es fijo: si el tráfico crece diez veces, la factura crece diez veces. Las instancias prendidas cobran por hora aunque estén ociosas, así que con poco tráfico se paga casi todo en capacidad sin usar; pero cuando el tráfico es alto y constante, una instancia bien aprovechada atiende muchísimas requests por el mismo precio, y el costo por request baja. Hay entonces un punto de equilibrio, que depende de la duración y la memoria de cada request: por debajo gana serverless, por encima ganan las instancias. Además del precio de lista, cuenta el costo operativo: serverless no requiere administrar escalado ni capacidad, y el tiempo del equipo también es plata. Por eso muchas empresas empiezan en serverless y mueven a contenedores las partes con tráfico alto y estable cuando el número lo justifica.",
    respuestaEn:
      "It depends on how much of the capacity you pay for gets used. Serverless charges per request: with low or very irregular traffic it's much cheaper, because nothing is paid while there's no activity and there's no idle capacity. But its per-request cost is fixed: if traffic grows tenfold, the bill grows tenfold. Running instances charge per hour even when idle, so at low traffic you pay almost entirely for unused capacity; but when traffic is high and steady, a well-utilized instance serves a huge number of requests for the same price, and the per-request cost drops. So there's a break-even point, depending on each request's duration and memory: below it serverless wins, above it instances win. Beyond list price, operational cost matters: serverless doesn't require managing scaling or capacity, and team time is money too. That's why many companies start serverless and move the high, steady-traffic parts to containers when the numbers justify it.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué son las reservas, los savings plans y las instancias spot, y cuándo los usás?",
    respuestaEs:
      "Son formas de pagar menos a cambio de algo. RESERVAS y SAVINGS PLANS: te comprometés a un nivel de uso (una cantidad de gasto por hora, o instancias de cierto tipo) por uno o tres años, y a cambio pagás bastante menos que on-demand; los savings plans son más flexibles, porque el descuento se aplica aunque cambies de tipo de instancia o de servicio. Tienen sentido para la BASE de uso que va a existir sí o sí (la base de datos de producción, el mínimo de instancias siempre prendidas), no para los picos. El riesgo es comprometerse de más y pagar capacidad que después no usás. SPOT: capacidad sobrante del proveedor con descuentos muy grandes, pero que te pueden quitar con un aviso de minutos. Encaja con cargas que toleran interrupciones: jobs por lotes, procesamiento de colas donde un trabajo interrumpido se reintenta, CI, entornos de prueba, o parte de un pool de instancias sin estado detrás de un balanceador, combinado con instancias on-demand para la base. No encaja con una base de datos ni con nada que pierda trabajo al cortarse. La combinación típica: compromiso para la base estable, on-demand para lo variable, spot para lo interrumpible.",
    respuestaEn:
      "They're ways to pay less in exchange for something. RESERVATIONS and SAVINGS PLANS: you commit to a usage level (a spend per hour, or instances of a certain type) for one or three years, and pay considerably less than on-demand; savings plans are more flexible, since the discount applies even if you change instance type or service. They make sense for the BASELINE usage that will exist no matter what (the production database, the always-on minimum instances), not for peaks. The risk is overcommitting and paying for capacity you later don't use. SPOT: the provider's spare capacity at very large discounts, but it can be taken away with minutes of notice. It fits interruption-tolerant workloads: batch jobs, queue processing where an interrupted job is retried, CI, test environments, or part of a pool of stateless instances behind a load balancer, combined with on-demand instances for the base. It doesn't fit a database or anything that loses work when cut off. The typical mix: commitment for the stable baseline, on-demand for the variable part, spot for the interruptible.",
    tradeoffs:
      "El compromiso baja el precio a cambio de flexibilidad; spot lo baja todavía más a cambio de previsibilidad.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo controlás el costo cloud en un equipo, más allá de la factura total?",
    respuestaEs:
      "Midiéndolo con la misma granularidad que las decisiones. ETIQUETAS en todos los recursos (proyecto, entorno, equipo) para saber cuánto cuesta cada cosa; sin eso, la factura es un número grande que nadie puede explicar. PRESUPUESTOS y DETECCIÓN DE ANOMALÍAS con alertas, para enterarse del recurso olvidado o del loop que dispara invocaciones el mismo día y no a fin de mes. MÉTRICAS UNITARIAS: más útil que el total es el costo por unidad de negocio, como costo por cliente activo, por pedido o por millón de requests. Si la factura sube un 30% pero el costo por pedido baja, el negocio creció de forma sana; si el costo por pedido sube, algo se volvió ineficiente. VISIBILIDAD para quien toma las decisiones: que cada equipo vea el costo de sus servicios (showback) cambia cómo diseña, porque el costo pasa a ser una métrica más, como la latencia. Es lo que se conoce como FinOps: tratar el costo como una responsabilidad compartida entre ingeniería, producto y finanzas, no como un problema que se revisa una vez por trimestre.",
    respuestaEn:
      "By measuring it at the same granularity as decisions. TAGS on every resource (project, environment, team) to know what each thing costs; without them, the bill is a big number nobody can explain. BUDGETS and ANOMALY DETECTION with alerts, to learn about the forgotten resource or the loop triggering invocations the same day and not at month's end. UNIT METRICS: more useful than the total is the cost per business unit, like cost per active customer, per order or per million requests. If the bill rises 30% but cost per order falls, the business grew healthily; if cost per order rises, something became inefficient. VISIBILITY for decision-makers: letting each team see the cost of its services (showback) changes how it designs, because cost becomes one more metric, like latency. That's what's known as FinOps: treating cost as a shared responsibility across engineering, product and finance, not a problem reviewed once a quarter.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué decisiones de arquitectura hacen crecer la factura sin que nadie lo note?",
    respuestaEs:
      "Las que escalan con el tráfico en lugares que nadie mira. TRANSFERENCIA DE DATOS: servicios muy conversadores repartidos en zonas distintas pagan cada gigabyte entre zonas; respuestas sin comprimir o imágenes sin optimizar pagan salida a internet; todo lo que pasa por un NAT paga por gigabyte procesado. OBSERVABILIDAD: loguear cada request con payloads completos, o métricas con alta cardinalidad, puede costar más que el cómputo que observan; se controla con niveles de log, muestreo y retención. SOBREDIMENSIONAMIENTO: instancias y bases elegidas 'por las dudas' con mucha más capacidad de la que usan, que nadie revisa después; las recomendaciones de rightsizing del proveedor ayudan. ALMACENAMIENTO QUE SOLO CRECE: logs, backups, snapshots y archivos viejos en clases caras, sin reglas de ciclo de vida. Y ESCALADO SIN LÍMITES: una función con un bug que se reinvoca a sí misma, o un autoscaling sin máximo, puede generar en horas una factura de semanas. Las correcciones suelen ser de diseño: caché y CDN para no repetir trabajo, compresión, procesar por lotes en vez de uno por uno, clases de almacenamiento según antigüedad, y límites máximos de escala y concurrencia.",
    respuestaEn:
      "Those that scale with traffic in places nobody watches. DATA TRANSFER: chatty services spread across zones pay for every cross-zone gigabyte; uncompressed responses or unoptimized images pay internet egress; everything through a NAT pays per processed gigabyte. OBSERVABILITY: logging every request with full payloads, or high-cardinality metrics, can cost more than the compute being observed; it's controlled with log levels, sampling and retention. OVERPROVISIONING: instances and databases picked 'just in case' with far more capacity than they use, never revisited; the provider's rightsizing recommendations help. STORAGE THAT ONLY GROWS: logs, backups, snapshots and old files in expensive classes, without lifecycle rules. And UNBOUNDED SCALING: a buggy function that re-invokes itself, or autoscaling with no maximum, can produce weeks' worth of bill in hours. Fixes are usually design: caching and CDN to avoid repeated work, compression, batch processing instead of one-by-one, storage classes by age, and maximum scale and concurrency limits.",
  },
  {
    nivel: 3,
    pregunta: "¿Cuándo vale la pena optimizar costos, y cuándo sale más caro el tiempo del equipo?",
    respuestaEs:
      "Es una cuenta, no una virtud. Si la factura cloud es de 2.000 dólares por mes y optimizarla lleva dos semanas de un ingeniero, el ahorro tiene que ser grande para compensar su costo, y además ese tiempo no se usó en el producto. Al principio de un producto, la prioridad es la velocidad: servicios gestionados, serverless, la opción más simple, aunque no sea la más barata por unidad, porque el riesgo real es no encontrar mercado, no pagar de más en infraestructura. La optimización empieza a pagarse cuando el costo es una fracción relevante de los ingresos, cuando crece más rápido que el negocio (el costo unitario sube), o cuando hay un desperdicio obvio y barato de corregir (recursos olvidados, sobredimensionamiento, un NAT evitable). Y se prioriza por impacto: el 20% de los servicios suele explicar el 80% de la factura. Hay decisiones tempranas que conviene tomar igual porque cambiarlas después es caro: etiquetar desde el día uno, límites de escala, no acoplarse sin necesidad a un servicio propietario. Pero reescribir para ahorrar unos pocos cientos de dólares por mes rara vez es buena inversión.",
    respuestaEn:
      "It's arithmetic, not a virtue. If the cloud bill is 2,000 dollars a month and optimizing it takes an engineer two weeks, the savings must be large to offset that cost, and that time also wasn't spent on the product. Early in a product, the priority is speed: managed services, serverless, the simplest option, even if not the cheapest per unit, because the real risk is not finding a market, not overpaying for infrastructure. Optimization starts paying off when cost is a meaningful fraction of revenue, when it grows faster than the business (unit cost rises), or when there's obvious, cheap-to-fix waste (forgotten resources, overprovisioning, an avoidable NAT). And it's prioritized by impact: 20% of services usually explain 80% of the bill. Some early decisions are worth making anyway because changing them later is expensive: tagging from day one, scale limits, not coupling to a proprietary service without need. But rewriting to save a few hundred dollars a month is rarely a good investment.",
    tradeoffs:
      "Optimizar temprano ahorra infraestructura a costa de velocidad del equipo; optimizar tarde acumula ineficiencia a cambio de foco en el producto.",
  },
];
