import type { PreguntaEntrevista } from "../types";

export const entrevistaRedesBasicas: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es una VPC y cómo se organizan sus subredes?",
    respuestaEs:
      "Una VPC (virtual private cloud) es tu red privada dentro del proveedor: un rango de direcciones IP propio (por ejemplo 10.0.0.0/16) aislado de las demás cuentas, dentro del cual creás tus recursos. Se divide en SUBREDES, cada una en una zona de disponibilidad, y lo que las diferencia es su tabla de rutas. Una subred PÚBLICA tiene una ruta hacia internet a través de un Internet Gateway, así que sus recursos con IP pública son alcanzables desde afuera; ahí van los balanceadores y los NAT gateways. Una subred PRIVADA no tiene esa ruta: sus recursos no se pueden alcanzar desde internet, y si necesitan salir (llamar a una API externa, bajar paquetes) lo hacen a través de un NAT Gateway ubicado en una subred pública, que permite conexiones salientes pero no entrantes. Ahí van la API, los workers y las bases de datos. El diseño típico: subredes públicas y privadas en al menos dos zonas, el balanceador en las públicas, todo lo demás en las privadas, y los SECURITY GROUPS, firewalls a nivel de recurso, permitiendo solo el tráfico necesario entre capas.",
    respuestaEn:
      "A VPC (virtual private cloud) is your private network inside the provider: your own IP range (for example 10.0.0.0/16) isolated from other accounts, in which you create your resources. It's split into SUBNETS, each in one availability zone, and what distinguishes them is their route table. A PUBLIC subnet has a route to the internet through an Internet Gateway, so its resources with a public IP are reachable from outside; load balancers and NAT gateways go there. A PRIVATE subnet has no such route: its resources can't be reached from the internet, and if they need to go out (call an external API, download packages) they do so through a NAT Gateway placed in a public subnet, which allows outbound but not inbound connections. The API, workers and databases go there. The typical design: public and private subnets in at least two zones, the load balancer in the public ones, everything else in the private ones, and SECURITY GROUPS, resource-level firewalls, allowing only the necessary traffic between layers.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué hacen un load balancer y un CDN en una arquitectura web?",
    respuestaEs:
      "El LOAD BALANCER es la puerta de entrada a tu aplicación: recibe las requests en una dirección estable y las reparte entre varias instancias. Con eso se gana escala horizontal (se agregan instancias detrás sin que el cliente se entere), disponibilidad (hace health checks y deja de mandar tráfico a instancias caídas, también durante los deploys) y un lugar central para terminar TLS, con el certificado en el balanceador en vez de en cada servidor. El CDN es una red de servidores distribuidos por el mundo (edge locations) que cachean contenido cerca de los usuarios. Un usuario en Buenos Aires recibe el JavaScript desde un servidor cercano en vez de cruzar el continente hasta el origen, lo que baja la latencia, y el origen recibe una fracción de las requests. Sirve sobre todo para contenido estático (assets, imágenes, el build de un frontend), y también para respuestas dinámicas cacheables por unos segundos. Además absorbe picos y ataques de denegación de servicio antes de que lleguen a tu infraestructura. En una arquitectura típica van en cadena: usuario, CDN, load balancer, aplicación.",
    respuestaEn:
      "The LOAD BALANCER is your application's front door: it receives requests at a stable address and spreads them across several instances. That brings horizontal scaling (you add instances behind it without clients noticing), availability (it runs health checks and stops sending traffic to down instances, including during deploys) and a central place to terminate TLS, with the certificate on the balancer instead of on each server. The CDN is a network of servers distributed around the world (edge locations) caching content close to users. A user in Buenos Aires gets the JavaScript from a nearby server instead of crossing the continent to the origin, lowering latency, and the origin receives a fraction of the requests. It's mainly for static content (assets, images, a frontend build), and also for dynamic responses cacheable for a few seconds. It also absorbs spikes and denial-of-service attacks before they reach your infrastructure. In a typical architecture they're chained: user, CDN, load balancer, application.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué diferencia hay entre security groups y network ACLs?",
    respuestaEs:
      "Los dos filtran tráfico, a distinto nivel y con distinta lógica. Un SECURITY GROUP se asocia a un recurso (una instancia, una base, un balanceador), solo tiene reglas de PERMITIR y es STATEFUL: si permite una conexión entrante, la respuesta sale automáticamente, sin regla de salida. Su característica más útil es que una regla puede referenciar a otro security group en vez de un rango de IPs: 'el SG de la base acepta 5432 desde el SG de la API'. Así la regla sigue valiendo aunque las instancias de la API cambien de IP al escalar, y expresa la intención en vez de direcciones. Una NETWORK ACL se asocia a una subred entera, tiene reglas de permitir y DENEGAR, se evalúan en orden por número, y es STATELESS: hay que permitir explícitamente también el tráfico de respuesta, incluidos los puertos efímeros, lo que la hace fácil de romper. En la práctica, los security groups hacen casi todo el trabajo, y las NACLs se usan como una capa gruesa adicional, por ejemplo para bloquear un rango de IPs a nivel de subred, que los security groups no pueden hacer porque no tienen reglas de denegar.",
    respuestaEn:
      "Both filter traffic, at different levels and with different logic. A SECURITY GROUP is attached to a resource (an instance, a database, a load balancer), has only ALLOW rules and is STATEFUL: if it allows an inbound connection, the response goes out automatically, without an outbound rule. Its most useful feature is that a rule can reference another security group instead of an IP range: 'the database SG accepts 5432 from the API SG'. That way the rule holds even as API instances change IPs while scaling, and it expresses intent instead of addresses. A NETWORK ACL is attached to an entire subnet, has ALLOW and DENY rules, evaluated in order by number, and is STATELESS: you must also explicitly allow the response traffic, including ephemeral ports, which makes it easy to break. In practice, security groups do almost all the work, and NACLs are used as an extra coarse layer, for example to block an IP range at the subnet level, which security groups can't do since they have no deny rules.",
  },
  {
    nivel: 2,
    pregunta: "ALB, NLB o API Gateway: ¿cuál ponés delante de tu servicio?",
    respuestaEs:
      "Dependen de en qué capa trabajan. El ALB (application load balancer) trabaja en HTTP: puede rutear por path o por host (`/api` a un servicio, `/admin` a otro), terminar TLS, hacer health checks HTTP, soporta WebSockets y HTTP/2, y se integra con un WAF para filtrar ataques comunes. Es el default para aplicaciones web y APIs. El NLB (network load balancer) trabaja en TCP/UDP: no entiende HTTP, pero maneja muchísimas conexiones con latencia muy baja, conserva la IP de origen del cliente y ofrece IPs estáticas por zona, útiles cuando un cliente necesita permitir tu dirección en su firewall; encaja en protocolos no HTTP, como una base o un servidor de juegos, o tráfico masivo. API GATEWAY es más que un balanceador: agrega autenticación, rate limiting y cuotas por cliente, transformación de requests, y se integra directo con Lambda; cobra por request, lo que con poco tráfico es barato y con mucho sale más caro que un ALB. Un punto común a todos: el health check tiene que verificar que la instancia puede atender de verdad, pero sin depender de servicios externos, porque si la base tiene un problema momentáneo, todas las instancias fallan el check a la vez y el balanceador se queda sin destinos.",
    respuestaEn:
      "It depends on which layer they work at. The ALB (application load balancer) works at HTTP: it can route by path or host (`/api` to one service, `/admin` to another), terminate TLS, run HTTP health checks, supports WebSockets and HTTP/2, and integrates with a WAF to filter common attacks. It's the default for web apps and APIs. The NLB (network load balancer) works at TCP/UDP: it doesn't understand HTTP, but handles huge numbers of connections with very low latency, preserves the client's source IP and offers static IPs per zone, useful when a client must allowlist your address in their firewall; it fits non-HTTP protocols, like a database or a game server, or massive traffic. API GATEWAY is more than a balancer: it adds authentication, rate limiting and per-client quotas, request transformation, and integrates directly with Lambda; it bills per request, which is cheap at low traffic and costlier than an ALB at high traffic. One point common to all: the health check must verify the instance can really serve, but without depending on external services, because if the database has a momentary problem, every instance fails the check at once and the balancer is left with no targets.",
    tradeoffs:
      "ALB da ruteo HTTP y funciones de aplicación; NLB da rendimiento, IPs fijas y protocolos no HTTP; API Gateway da gestión de APIs a cambio de costo por request.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué tenés que cuidar al poner un CDN delante de tu aplicación?",
    respuestaEs:
      "LA CLAVE DE CACHÉ: por defecto el CDN cachea por URL; si la respuesta cambia según un header (idioma, dispositivo) o una cookie, eso tiene que entrar en la clave, o un usuario recibe la versión de otro. Y al revés: incluir en la clave cosas que no cambian la respuesta (todos los query params, todas las cookies) hace que casi nunca haya hit. Lo más peligroso es cachear respuestas personalizadas o autenticadas: una página con datos de un usuario cacheada y servida a todos es una filtración; por eso las respuestas privadas llevan `Cache-Control: private` o `no-store`. INVALIDACIÓN: invalidar rutas en el CDN es lento y a veces cobra; para assets, lo correcto es nombres con hash del contenido (`app.3f9a1c.js`) cacheados por un año como inmutables, así un deploy nuevo cambia el nombre en vez de invalidar. PROTEGER EL ORIGEN: si el origen es accesible directamente, un atacante saltea el CDN y su protección; en S3 se restringe el bucket para que solo lo lea el CDN (origin access control), y en un balanceador se exige un header secreto que agrega el CDN o se limita a sus rangos de IP. Y un escudo de origen (origin shield), una capa de caché intermedia, reduce las requests que llegan al origen cuando hay muchos puntos de presencia.",
    respuestaEn:
      "THE CACHE KEY: by default the CDN caches by URL; if the response varies by a header (language, device) or a cookie, that must be in the key, or one user gets another's version. And conversely: including things that don't change the response (all query params, all cookies) means there's almost never a hit. The most dangerous thing is caching personalized or authenticated responses: a page with one user's data cached and served to everyone is a data leak; that's why private responses carry `Cache-Control: private` or `no-store`. INVALIDATION: invalidating paths on the CDN is slow and sometimes billed; for assets, the right approach is content-hashed names (`app.3f9a1c.js`) cached for a year as immutable, so a new deploy changes the name instead of invalidating. PROTECTING THE ORIGIN: if the origin is directly reachable, an attacker bypasses the CDN and its protection; on S3 the bucket is restricted so only the CDN can read it (origin access control), and on a load balancer you require a secret header added by the CDN or limit to its IP ranges. And an origin shield, an intermediate cache layer, reduces requests reaching the origin when there are many points of presence.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo conectás de forma privada servicios, VPCs y cuentas, y qué costos trae?",
    respuestaEs:
      "Para llegar a servicios del proveedor sin pasar por internet ni por el NAT existen los VPC ENDPOINTS: de tipo gateway para S3 y DynamoDB, que son gratuitos y solo agregan una ruta; y de tipo interfaz (PrivateLink) para casi todo lo demás (Secrets Manager, SQS, ECR), que ponen una interfaz de red privada en tu subred y cobran por hora y por gigabyte, pero evitan exponer ese tráfico y pueden ahorrar costo de NAT. Para conectar VPCs entre sí: PEERING conecta dos VPCs directamente, es simple y barato, pero no es transitivo (si A conecta con B y B con C, A no llega a C), así que con muchas VPCs se vuelve una malla inmanejable; TRANSIT GATEWAY actúa como un hub central al que se conectan todas, con ruteo centralizado, a cambio de un costo por conexión y por gigabyte. Un requisito que se descubre tarde: los rangos de IP de las VPCs que se van a conectar no pueden superponerse, así que conviene planificar los CIDR desde el principio, en vez de crear todas las VPCs con el 10.0.0.0/16 por defecto. Y el costo de la red suele sorprender: NAT por gigabyte, tráfico entre zonas y regiones, y salida a internet aparecen en la factura como líneas grandes que nadie estimó.",
    respuestaEn:
      "To reach provider services without going through the internet or the NAT there are VPC ENDPOINTS: gateway type for S3 and DynamoDB, free and only adding a route; and interface type (PrivateLink) for almost everything else (Secrets Manager, SQS, ECR), which place a private network interface in your subnet and bill per hour and per gigabyte, but keep that traffic private and can save NAT cost. To connect VPCs to each other: PEERING connects two VPCs directly, simple and cheap, but not transitive (if A connects to B and B to C, A doesn't reach C), so with many VPCs it becomes an unmanageable mesh; TRANSIT GATEWAY acts as a central hub everyone connects to, with centralized routing, at a per-attachment and per-gigabyte cost. A requirement discovered late: the IP ranges of VPCs to be connected can't overlap, so plan CIDRs from the start instead of creating every VPC with the default 10.0.0.0/16. And network cost often surprises: NAT per gigabyte, cross-zone and cross-region traffic, and internet egress show up on the bill as big lines nobody estimated.",
  },
];
