import type { PreguntaEntrevista } from "../types";

export const entrevistaResponsabilidadCompartida: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es el modelo de responsabilidad compartida?",
    respuestaEs:
      "Es la división explícita, entre el proveedor cloud y el cliente, de quién se ocupa de qué en seguridad y operación. AWS lo resume como seguridad DE la nube contra seguridad EN la nube. El proveedor es responsable de la infraestructura que opera: los datacenters, el hardware, la red física, la virtualización y, según el servicio, el sistema operativo y el runtime. El cliente es responsable de lo que pone y configura encima: sus datos, quién tiene acceso (IAM), la configuración de red y de los servicios, su código y sus dependencias. La línea se mueve según el tipo de servicio: en una máquina virtual (EC2) el sistema operativo y sus parches son tuyos; en Lambda los maneja el proveedor. Pero hay cosas que nunca pasan al proveedor, en ningún modelo: los datos, las identidades y la configuración. Un bucket público, un usuario con permisos de administrador y sin MFA o una clave commiteada son responsabilidad del cliente aunque todo corra en la infraestructura más segura del mundo.",
    respuestaEn:
      "It's the explicit split, between the cloud provider and the customer, of who handles what in security and operations. AWS summarizes it as security OF the cloud versus security IN the cloud. The provider is responsible for the infrastructure it operates: datacenters, hardware, physical network, virtualization and, depending on the service, the operating system and runtime. The customer is responsible for what they put and configure on top: their data, who has access (IAM), network and service configuration, their code and dependencies. The line moves with the service type: on a virtual machine (EC2) the operating system and its patches are yours; on Lambda the provider handles them. But some things never move to the provider, in any model: data, identities and configuration. A public bucket, a user with admin permissions and no MFA, or a committed key are the customer's responsibility even if everything runs on the most secure infrastructure in the world.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué cambia entre IaaS, contenedores gestionados, serverless y SaaS?",
    respuestaEs:
      "Cuánto del stack te llevás vos. En IaaS (EC2, Compute Engine) alquilás máquinas virtuales: el proveedor pone el hardware y la virtualización, y vos instalás, parcheás y endurecés el sistema operativo, el runtime y todo lo de arriba. Máximo control, máxima responsabilidad. En CONTENEDORES GESTIONADOS (Fargate, Cloud Run) entregás una imagen: el proveedor opera los hosts y su sistema operativo, pero lo que va dentro de la imagen, incluidas las librerías del sistema de la imagen base, sigue siendo tuyo; por eso hay que reconstruirla cuando salen parches. En SERVERLESS (Lambda, Vercel Functions) entregás código: el proveedor parchea el sistema y el runtime de Node, y vos respondés por tu código y tus dependencias de npm, además de elegir una versión de runtime soportada. En SaaS (Gmail, Salesforce, un CRM) usás un producto terminado: el proveedor opera todo el software, y a vos te quedan los datos que cargás, quién accede y cómo configurás las opciones de seguridad. La tendencia general: cuanto más gestionado el servicio, menos trabajo operativo y menos control, pero las responsabilidades de datos, identidades y configuración no se delegan nunca.",
    respuestaEn:
      "How much of the stack you own. In IaaS (EC2, Compute Engine) you rent virtual machines: the provider supplies hardware and virtualization, and you install, patch and harden the operating system, runtime and everything above. Maximum control, maximum responsibility. In MANAGED CONTAINERS (Fargate, Cloud Run) you hand over an image: the provider operates the hosts and their operating system, but what's inside the image, including the base image's system libraries, is still yours; that's why you rebuild it when patches ship. In SERVERLESS (Lambda, Vercel Functions) you hand over code: the provider patches the system and the Node runtime, and you answer for your code and npm dependencies, plus choosing a supported runtime version. In SaaS (Gmail, Salesforce, a CRM) you use a finished product: the provider operates all the software, and you keep the data you load, who accesses it and how you configure the security options. The general trend: the more managed the service, the less operational work and the less control, but data, identity and configuration responsibilities are never delegated.",
  },
  {
    nivel: 2,
    pregunta: "¿Por qué la mayoría de los incidentes de seguridad en la nube son del lado del cliente?",
    respuestaEs:
      "Porque la infraestructura del proveedor es muy difícil de atacar y la configuración del cliente es muy fácil de equivocar. Los patrones que se repiten: buckets o bases expuestas a internet por una política mal escrita; permisos IAM demasiado amplios (`\"Action\": \"*\"` porque 'así funciona'); claves de acceso de larga vida filtradas en un repo, un log o una imagen; cuentas sin MFA; y recursos olvidados, como una instancia de pruebas con un puerto abierto que nadie monitorea. Las mitigaciones son en su mayoría de proceso y de guardrails, no de tecnología nueva. MÍNIMO PRIVILEGIO: roles por servicio con los permisos justos, credenciales temporales en vez de claves. GUARDRAILS a nivel de cuenta u organización: bloquear el acceso público a S3 para toda la cuenta, políticas de organización (SCPs en AWS) que impiden ciertas acciones aunque un rol las permita. INFRAESTRUCTURA COMO CÓDIGO revisada en PRs, en vez de cambios a mano en la consola. Y DETECCIÓN continua de mala configuración (AWS Config, Security Hub, herramientas CSPM), porque siempre se escapa algo.",
    respuestaEn:
      "Because the provider's infrastructure is very hard to attack and the customer's configuration is very easy to get wrong. Recurring patterns: buckets or databases exposed to the internet by a badly written policy; overly broad IAM permissions (`\"Action\": \"*\"` because 'that way it works'); long-lived access keys leaked in a repo, a log or an image; accounts without MFA; and forgotten resources, like a test instance with an open port nobody monitors. Mitigations are mostly process and guardrails, not new technology. LEAST PRIVILEGE: per-service roles with exactly the needed permissions, temporary credentials instead of keys. GUARDRAILS at the account or organization level: blocking S3 public access for the whole account, organization policies (SCPs in AWS) that forbid certain actions even if a role allows them. INFRASTRUCTURE AS CODE reviewed in PRs, instead of manual console changes. And continuous misconfiguration DETECTION (AWS Config, Security Hub, CSPM tools), because something always slips through.",
  },
  {
    nivel: 2,
    pregunta: "La disponibilidad y los backups, ¿también son compartidos?",
    respuestaEs:
      "Sí, y es una confusión frecuente pensar que 'está en la nube, así que no se cae ni se pierde'. El proveedor garantiza la disponibilidad de SU servicio según su SLA, por zona o por región, y si no la cumple devuelve créditos sobre la factura, que no cubren lo que perdió tu negocio. Que tu aplicación sobreviva a la caída de una zona depende de tu arquitectura: una sola instancia en una zona cae con ella; varias instancias en varias zonas detrás de un balanceador, y una base con réplica en otra zona (Multi-AZ en RDS), no. Con los datos pasa lo mismo: RDS hace backups automáticos, pero su retención, probar la restauración, y protegerse de un borrado accidental o malicioso (alguien con permisos borra la base y sus snapshots, o un ransomware cifra el bucket) son del cliente. De ahí prácticas como copias en otra cuenta o región con permisos separados, versionado y object lock en S3, y protección contra borrado en los recursos críticos. La regla: el proveedor te da los bloques para ser resiliente, pero armarlos es tu trabajo.",
    respuestaEn:
      "Yes, and a frequent confusion is thinking 'it's in the cloud, so it won't go down or get lost'. The provider guarantees ITS service's availability per its SLA, by zone or region, and if it misses it you get credits on the bill, which don't cover what your business lost. Whether your application survives a zone outage depends on your architecture: a single instance in one zone goes down with it; several instances across zones behind a load balancer, and a database with a replica in another zone (Multi-AZ in RDS), don't. Data works the same way: RDS takes automatic backups, but their retention, testing restores, and protecting against accidental or malicious deletion (someone with permissions deletes the database and its snapshots, or ransomware encrypts the bucket) are the customer's. Hence practices like copies in another account or region with separate permissions, versioning and object lock in S3, and deletion protection on critical resources. The rule: the provider gives you the building blocks for resilience, but assembling them is your job.",
    tradeoffs:
      "Más zonas y regiones dan más resiliencia a cambio de más costo y complejidad (datos replicados, latencia entre regiones); la decisión depende de cuánto cuesta una hora caído.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo encaja la responsabilidad compartida con compliance (SOC 2, PCI, GDPR)?",
    respuestaEs:
      "Heredás parte de los controles, no la certificación. El proveedor audita su infraestructura contra esos estándares y publica los reportes (en AWS, desde AWS Artifact), así que los controles físicos, de hardware y de su personal ya están cubiertos y tu auditor los acepta como evidencia. Pero tu sistema no queda certificado por correr ahí: los controles de tu lado (quién accede a qué, cifrado, retención, logs de auditoría, gestión de cambios, respuesta a incidentes) los tenés que implementar y demostrar vos. Además, no todos los servicios del proveedor están en el alcance de cada certificación, así que para PCI, por ejemplo, hay que usar los servicios que lo están. Tres temas que aparecen siempre. RESIDENCIA DE DATOS: GDPR y regulaciones locales pueden exigir que los datos queden en ciertas regiones; eso lo elegís vos al crear los recursos, incluidas réplicas y backups. CLAVES DE CIFRADO: los datos cifrados con claves gestionadas por el proveedor están protegidos, pero con claves gestionadas por el cliente en KMS controlás quién puede usarlas, podés revocarlas, y queda registro de cada uso. AUDITORÍA: activar y proteger los logs de actividad de la cuenta (CloudTrail), en una cuenta separada, para poder responder quién hizo qué y cuándo.",
    respuestaEn:
      "You inherit part of the controls, not the certification. The provider audits its infrastructure against those standards and publishes the reports (in AWS, via AWS Artifact), so physical, hardware and staff controls are covered and your auditor accepts them as evidence. But your system isn't certified by running there: the controls on your side (who accesses what, encryption, retention, audit logs, change management, incident response) you must implement and prove yourself. Also, not every provider service is in scope for each certification, so for PCI, for example, you must use in-scope services. Three topics always come up. DATA RESIDENCY: GDPR and local regulations may require data to stay in certain regions; you choose that when creating resources, including replicas and backups. ENCRYPTION KEYS: data encrypted with provider-managed keys is protected, but with customer-managed keys in KMS you control who can use them, can revoke them, and every use is logged. AUDITING: enable and protect the account's activity logs (CloudTrail), in a separate account, to answer who did what and when.",
  },
  {
    nivel: 3,
    pregunta: "¿Dónde está la línea en un servicio gestionado como RDS, y qué hacés cuando el que falla es el proveedor?",
    respuestaEs:
      "En un servicio gestionado la línea pasa por el medio del servicio, y hay que conocerla en detalle. En RDS, por ejemplo, el proveedor instala y parchea el motor de Postgres (en ventanas de mantenimiento que vos elegís), opera el hardware, hace los backups automáticos y el failover Multi-AZ. Vos elegís la versión y cuándo actualizar de versión mayor, decidís si la base es accesible desde internet (no debería), configurás los security groups, creás los usuarios y sus permisos, activás el cifrado y definís la retención de backups. Un Postgres expuesto con una contraseña débil es tu incidente aunque el servicio sea gestionado. Cuando falla el PROVEEDOR (una región caída, un servicio degradado), la responsabilidad de la infraestructura es de ellos, pero el impacto en tus usuarios lo gestionás vos: depende de qué tan acoplado estás a esa zona, región o servicio. Por eso se diseña según el costo de estar caído: multi-AZ como piso para producción, multi-región solo si el negocio lo justifica (duplica costo y complejidad), dependencias externas con timeouts, reintentos y degradación elegante, y un plan de continuidad ensayado. También cuentan los proveedores SaaS que integrás: si tu autenticación depende de un tercero, su caída es tu caída.",
    respuestaEn:
      "In a managed service the line runs through the middle of the service, and you need to know it in detail. In RDS, for example, the provider installs and patches the Postgres engine (in maintenance windows you choose), operates the hardware, takes automatic backups and does Multi-AZ failover. You choose the version and when to do major upgrades, decide whether the database is reachable from the internet (it shouldn't be), configure security groups, create users and their permissions, enable encryption and define backup retention. An exposed Postgres with a weak password is your incident even though the service is managed. When the PROVIDER fails (a region down, a degraded service), the infrastructure is their responsibility, but the impact on your users is yours to manage: it depends on how coupled you are to that zone, region or service. That's why you design by the cost of being down: multi-AZ as the production baseline, multi-region only if the business justifies it (it doubles cost and complexity), external dependencies with timeouts, retries and graceful degradation, and a rehearsed continuity plan. Integrated SaaS providers count too: if your authentication depends on a third party, their outage is your outage.",
  },
];
