import type { PreguntaEntrevista } from "../types";

export const entrevistaVercelVsAws: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué te dan Vercel o Netlify que no te da AWS directamente?",
    respuestaEs:
      "Son plataformas: resuelven de punta a punta el camino de un repositorio a producción para aplicaciones web. Conectás el repo y cada push despliega; cada PR tiene su propia URL de preview para revisar la funcionalidad andando; el contenido estático se sirve desde un CDN global con TLS automático; las rutas dinámicas corren como funciones que escalan solas; y en frameworks como Next.js, funcionalidades como el renderizado incremental, la optimización de imágenes y el cacheo vienen configuradas sin tocar infraestructura. Además hay rollback instantáneo a cualquier deploy anterior. AWS, en cambio, da piezas: CDN, funciones, contenedores, bases, redes, colas, y armarlas en ese mismo flujo requiere diseño, configuración (idealmente como código) y alguien que lo mantenga. A cambio, AWS da control total sobre cada pieza, servicios que las plataformas no tienen (colas, bases gestionadas, redes privadas, cómputo de larga duración) y, a cierta escala, menor costo por unidad. Es la diferencia entre comprar una solución opinada y construir la tuya con bloques.",
    respuestaEn:
      "They're platforms: they solve the whole path from repository to production for web applications. You connect the repo and each push deploys; each PR gets its own preview URL to review the feature working; static content is served from a global CDN with automatic TLS; dynamic routes run as functions that scale on their own; and with frameworks like Next.js, features like incremental rendering, image optimization and caching come configured without touching infrastructure. There's also instant rollback to any previous deploy. AWS, instead, gives building blocks: CDN, functions, containers, databases, networking, queues, and assembling them into that same flow takes design, configuration (ideally as code) and someone to maintain it. In exchange, AWS gives full control over each piece, services the platforms don't have (queues, managed databases, private networking, long-running compute) and, at some scale, lower unit cost. It's the difference between buying an opinionated solution and building your own from blocks.",
  },
  {
    nivel: 1,
    pregunta: "¿Cuándo elegís una plataforma tipo Vercel y cuándo AWS?",
    respuestaEs:
      "Una plataforma encaja cuando el producto es principalmente una aplicación web, el equipo es chico o no tiene gente de infraestructura, y la velocidad de iteración importa más que el control fino: la mayoría de los productos en etapa temprana, sitios de contenido, dashboards y SaaS con backend simple. AWS encaja cuando aparecen necesidades que las plataformas no cubren bien: procesos de larga duración o workers permanentes, conexiones persistentes propias, datos que tienen que vivir en una red privada o requisitos de compliance estrictos, tráfico muy alto donde el precio por uso de la plataforma se dispara, o una organización que ya opera AWS y tiene contratos y equipo. Y muchas veces la respuesta es híbrida: el frontend y las rutas de servidor livianas en la plataforma, y la base de datos, las colas, los workers y lo pesado en AWS. La elección no es para siempre, pero conviene no atarse sin necesidad a funcionalidades exclusivas de una plataforma, así mover una parte después es una migración acotada.",
    respuestaEn:
      "A platform fits when the product is mainly a web application, the team is small or has no infrastructure people, and iteration speed matters more than fine control: most early-stage products, content sites, dashboards and SaaS with a simple backend. AWS fits when needs appear that platforms don't cover well: long-running processes or permanent workers, your own persistent connections, data that must live in a private network or strict compliance requirements, very high traffic where the platform's usage pricing spikes, or an organization already operating AWS with contracts and a team. And often the answer is hybrid: the frontend and light server routes on the platform, and the database, queues, workers and heavy lifting on AWS. The choice isn't forever, but it's worth not tying yourself unnecessarily to a platform's exclusive features, so moving a part later is a bounded migration.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo se compara el costo de una plataforma con el de AWS?",
    respuestaEs:
      "Hay que comparar el costo total, no solo la factura. Las plataformas cobran una suscripción (en general por integrante del equipo) más el uso: invocaciones y tiempo de las funciones, transferencia de datos, optimización de imágenes, y otros componentes medidos. Con tráfico bajo o moderado suele ser barato, y el trabajo de operación es casi cero. Con mucho tráfico, sobre todo mucho ancho de banda o muchas funciones, el costo por unidad es más alto que el de AWS, y la factura puede crecer rápido: un bot que recorre el sitio, imágenes sin cachear, una ruta que se invoca de más. Por eso conviene configurar límites y alertas de gasto. AWS suele tener menor costo por unidad a escala, pero suma el costo de las personas que diseñan, operan y actualizan esa infraestructura, que para un equipo chico puede ser mucho mayor que la diferencia en la factura. La decisión razonable es mirar en qué punto la diferencia de factura paga el tiempo de ingeniería necesario para operar la alternativa, y mover primero solo las partes que concentran el costo, no todo.",
    respuestaEn:
      "You compare total cost, not just the bill. Platforms charge a subscription (usually per team member) plus usage: function invocations and duration, data transfer, image optimization and other metered components. At low or moderate traffic it's usually cheap, and operations work is nearly zero. With lots of traffic, especially lots of bandwidth or many functions, the unit cost is higher than AWS's, and the bill can grow fast: a bot crawling the site, uncached images, a route invoked too often. That's why it's worth configuring spend limits and alerts. AWS usually has lower unit cost at scale, but adds the cost of the people designing, operating and upgrading that infrastructure, which for a small team can far exceed the difference in the bill. The reasonable decision is finding the point where the bill difference pays for the engineering time needed to operate the alternative, and moving first only the parts that concentrate the cost, not everything.",
    tradeoffs:
      "La plataforma cambia costo por unidad más alto por operación casi nula; AWS cambia costo por unidad más bajo por tiempo de ingeniería.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué limitaciones de estas plataformas tenés que conocer antes de elegirlas?",
    respuestaEs:
      "DURACIÓN de las funciones: tienen un tiempo máximo por invocación, más corto que un contenedor sin límite, así que procesamientos largos se derivan a colas y servicios de jobs (Inngest, Trigger.dev, QStash) o a infraestructura propia. SIN PROCESOS PERMANENTES: no hay dónde correr un worker que consume una cola todo el día ni un servidor de WebSockets propio; el tiempo real se resuelve con servicios externos (Pusher, Ably, Liveblocks) o fuera de la plataforma. CONEXIONES A LA BASE: como en todo serverless, hace falta un pooler o un driver sobre HTTP para no agotar las conexiones de Postgres. REGIÓN: si las funciones corren en una región y la base en otra, cada consulta paga la latencia entre ambas; hay que ubicar las funciones cerca de los datos, no del usuario. Y ACOPLAMIENTO: algunas funcionalidades dependen de la infraestructura de la plataforma (su caché, su CDN, sus funciones en el borde); usarlas está bien, pero conviene saber cuáles habría que reemplazar si un día se migra. En Next.js, el adapter de Vercel usa la misma API pública de adapters que cualquier otra plataforma, lo que acota ese riesgo.",
    respuestaEn:
      "Function DURATION: there's a maximum time per invocation, shorter than an unlimited container, so long processing is offloaded to queues and job services (Inngest, Trigger.dev, QStash) or your own infrastructure. NO PERMANENT PROCESSES: there's nowhere to run a worker consuming a queue all day or your own WebSocket server; real-time is solved with external services (Pusher, Ably, Liveblocks) or outside the platform. DATABASE CONNECTIONS: as in any serverless setup, you need a pooler or an HTTP-based driver to avoid exhausting Postgres connections. REGION: if functions run in one region and the database in another, every query pays the latency between them; place functions near the data, not the user. And COUPLING: some features depend on the platform's infrastructure (its cache, CDN, edge functions); using them is fine, but know which you'd have to replace if you migrate someday. In Next.js, Vercel's adapter uses the same public adapter API as any other platform, which bounds that risk.",
  },
  {
    nivel: 3,
    pregunta: "Frontend en Vercel y backend en AWS: ¿qué hay que resolver para que funcione bien?",
    respuestaEs:
      "LATENCIA: las funciones del frontend que consultan la API o la base tienen que correr en la misma región que el backend en AWS; si no, cada request suma un cruce de región, y con varias consultas por página se nota. RED: la base y los servicios internos viven en subredes privadas, y la plataforma está afuera; se resuelve exponiendo solo la API detrás de un balanceador público con autenticación, no la base, o con las opciones de conectividad privada o IPs de salida fijas que algunas plataformas ofrecen en planes superiores, para poder permitirlas en los security groups. AUTENTICACIÓN entre dominios: si el frontend está en `app.ejemplo.com` y la API en `api.ejemplo.com`, las cookies de sesión tienen que configurarse para el dominio padre, con `SameSite` adecuado, y CORS tiene que permitir el origen del frontend con credenciales; usar subdominios del mismo dominio simplifica mucho frente a dos dominios distintos. OBSERVABILIDAD: una request que cruza de la plataforma a AWS tiene que mantener la misma traza; se propaga el header `traceparent` y se envían las dos fuentes al mismo backend de observabilidad. Y DEPLOYS COORDINADOS: el frontend y el backend se despliegan por separado, así que los cambios de contrato de la API tienen que ser compatibles hacia atrás.",
    respuestaEn:
      "LATENCY: frontend functions querying the API or database must run in the same region as the AWS backend; otherwise every request adds a cross-region hop, noticeable with several queries per page. NETWORK: the database and internal services live in private subnets, and the platform is outside; you solve it by exposing only the API behind a public load balancer with authentication, not the database, or with the private connectivity or fixed egress IP options some platforms offer on higher plans, so you can allow them in security groups. AUTHENTICATION across domains: if the frontend is on `app.example.com` and the API on `api.example.com`, session cookies must be scoped to the parent domain with a suitable `SameSite`, and CORS must allow the frontend origin with credentials; subdomains of the same domain simplify a lot compared to two different domains. OBSERVABILITY: a request crossing from the platform to AWS must keep the same trace; propagate the `traceparent` header and send both sources to the same observability backend. And COORDINATED DEPLOYS: frontend and backend deploy separately, so API contract changes must be backward-compatible.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué implica sacar una app Next.js de Vercel y correrla en tu propia infraestructura?",
    respuestaEs:
      "Next.js se puede auto-hospedar sin perder funcionalidades: un solo proceso `next start` soporta todo, incluidos Server Components, ISR, Server Actions y el proxy. Para contenedores, `output: \"standalone\"` genera una salida mínima con solo los archivos necesarios, y la optimización de imágenes requiere el paquete `sharp`. Lo que cambia es lo que la plataforma resolvía por vos. CACHÉ CON VARIAS INSTANCIAS: cada instancia mantiene su propia caché; todo sigue funcionando, pero una revalidación en una instancia no se propaga a las demás, así que distintos usuarios pueden ver versiones distintas. Para coordinarlas se configura una caché compartida (por ejemplo sobre Redis) con `cacheHandler` para ISR y caché del servidor, y `cacheHandlers` para `'use cache'`. STREAMING: el balanceador o proxy delante no tiene que bufferear las respuestas, o se pierde la entrega progresiva. CDN: configurar qué se cachea en el borde y cómo se invalida, que antes era automático. GRACEFUL SHUTDOWN: funciones como `after()` necesitan que el proceso termine su trabajo antes de apagarse. Y los PREVIEWS por PR y el rollback instantáneo hay que reconstruirlos en el pipeline. Existe además una API pública de adapters para que otras plataformas integren Next.js con el mismo nivel de soporte.",
    respuestaEn:
      "Next.js can be self-hosted without losing features: a single `next start` process supports everything, including Server Components, ISR, Server Actions and the proxy. For containers, `output: \"standalone\"` produces a minimal output with only the needed files, and image optimization requires the `sharp` package. What changes is what the platform handled for you. CACHE ACROSS INSTANCES: each instance keeps its own cache; everything still works, but a revalidation on one instance doesn't propagate to the others, so different users can see different versions. To coordinate them you configure a shared cache (for example on Redis) with `cacheHandler` for ISR and server caching, and `cacheHandlers` for `'use cache'`. STREAMING: the load balancer or proxy in front must not buffer responses, or progressive delivery is lost. CDN: configure what's cached at the edge and how it's invalidated, which used to be automatic. GRACEFUL SHUTDOWN: features like `after()` need the process to finish its work before stopping. And per-PR PREVIEWS and instant rollback must be rebuilt in the pipeline. There's also a public adapter API so other platforms can integrate Next.js with the same level of support.",
    codigo: `// next.config.js para correr en contenedores con varias instancias
module.exports = {
  output: "standalone",
  // caché de ISR y del servidor compartida entre instancias (por ejemplo, en Redis)
  cacheHandler: require.resolve("./cache-handler.js"),
  cacheMaxMemorySize: 0, // sin caché en memoria local: todo pasa por la compartida
};`,
  },
];
