import type { PreguntaEntrevista } from "../types";

export const entrevistaSsrSsgIsr: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué diferencia hay entre SSR, SSG, ISR y CSR, y cuándo usarías cada uno?",
    respuestaEs:
      "Cambia CUÁNDO se genera el HTML. SSG (Static Site Generation) lo genera en el build: se sirve desde un CDN, es lo más rápido y barato, pero el contenido queda fijo hasta el próximo deploy; ideal para landings, documentación, blogs que cambian poco. SSR (Server-Side Rendering) lo genera en cada request: siempre fresco y puede personalizarse por usuario (cookies, sesión), a cambio de trabajo del servidor en cada visita y más latencia; para dashboards, carritos, contenido por usuario. ISR (Incremental Static Regeneration) es estático pero se regenera después de un tiempo o a demanda sin redeploy: la velocidad de SSG con contenido que se actualiza; para e-commerce, noticias, sitios alimentados por un CMS. CSR (Client-Side Rendering) manda un HTML casi vacío y el navegador arma la página con JavaScript; sirve para partes muy interactivas detrás de login, pero es peor para SEO y para la primera carga.",
    respuestaEn:
      "What changes is WHEN the HTML is generated. SSG (Static Site Generation) generates it at build time: served from a CDN, fastest and cheapest, but content is fixed until the next deploy; ideal for landings, docs, rarely-changing blogs. SSR (Server-Side Rendering) generates it on every request: always fresh and can be personalized per user (cookies, session), at the cost of server work per visit and more latency; for dashboards, carts, per-user content. ISR (Incremental Static Regeneration) is static but regenerates after a time or on demand without redeploying: SSG speed with updating content; for e-commerce, news, CMS-driven sites. CSR (Client-Side Rendering) ships a near-empty HTML and the browser builds the page with JavaScript; it fits highly interactive parts behind login, but is worse for SEO and first load.",
  },
  {
    nivel: 1,
    pregunta: "En el App Router no hay `getStaticProps` ni `getServerSideProps`. ¿Cómo decide Next si una ruta es estática o dinámica?",
    respuestaEs:
      "Lo infiere del código. Por defecto intenta prerenderizar la ruta en el build (estática). Pasa a renderizarse por request cuando usa algo que solo existe en el momento del request: `cookies()`, `headers()`, `searchParams`, `connection()`, o datos marcados explícitamente como no cacheables. Por eso una línea como `await cookies()` en un componente puede cambiar la estrategia de toda la ruta en el modelo clásico; con Cache Components esa lectura queda contenida en su `<Suspense>` y el resto sigue en el shell estático. La salida de `next build` indica qué rutas quedaron estáticas y cuáles dinámicas, y conviene revisarla: es muy común que una ruta que debería ser estática se vuelva dinámica por un acceso a cookies en un layout.",
    respuestaEn:
      "It infers it from the code. By default it tries to prerender the route at build time (static). It switches to per-request rendering when it uses something that only exists at request time: `cookies()`, `headers()`, `searchParams`, `connection()`, or data explicitly marked uncacheable. That's why a line like `await cookies()` in a component can change the whole route's strategy in the classic model; with Cache Components that read stays contained in its `<Suspense>` and the rest remains in the static shell. The `next build` output shows which routes ended up static and which dynamic, and it's worth checking: it's very common for a route that should be static to turn dynamic because of a cookie read in a layout.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo funciona ISR por tiempo, y por qué el primer visitante después del vencimiento ve contenido viejo?",
    respuestaEs:
      "Con `export const revalidate = 3600`, la página se genera y se sirve desde el cache. Pasada la hora, NO se regenera sola: el próximo request que llega recibe igual la versión cacheada (stale) al instante, y ese request dispara la regeneración en segundo plano. Cuando termina, la versión nueva reemplaza a la vieja y la reciben los siguientes visitantes. Es stale-while-revalidate: se prioriza que nadie espere un render, a cambio de que un visitante vea la versión anterior. Si la regeneración falla, se sigue sirviendo la última versión buena. La documentación recomienda tiempos de revalidación altos (una hora antes que un segundo) y, si hace falta precisión, pasar a revalidación a demanda en vez de bajar el tiempo. El header `x-nextjs-cache` (HIT, STALE, MISS, REVALIDATED) permite ver qué pasó en cada respuesta.",
    respuestaEn:
      "With `export const revalidate = 3600`, the page is generated and served from cache. After the hour it does NOT regenerate by itself: the next incoming request still gets the cached (stale) version instantly, and that request triggers background regeneration. When it finishes, the new version replaces the old one and following visitors get it. It's stale-while-revalidate: nobody waits for a render, at the cost of one visitor seeing the previous version. If regeneration fails, the last good version keeps being served. The docs recommend high revalidation times (an hour rather than a second) and, if you need precision, switching to on-demand revalidation instead of lowering the time. The `x-nextjs-cache` header (HIT, STALE, MISS, REVALIDATED) shows what happened on each response.",
    tradeoffs:
      "Un revalidate bajo parece dar frescura, pero genera renders constantes en segundo plano (costo de cómputo) y sigue sirviendo una versión vieja por request. Si el contenido cambia por eventos conocidos, la revalidación a demanda es más precisa y más barata.",
  },
  {
    nivel: 2,
    pregunta: "Tenés un e-commerce con 200.000 productos. ¿Los generás todos en el build?",
    respuestaEs:
      "No: el build tardaría muchísimo y la mayoría de esas páginas casi no se visitan. Con `generateStaticParams` se pregeneran solo los más visitados (los top 1.000 por tráfico, por ejemplo), y el resto se genera la primera vez que alguien lo visita y queda cacheado para los siguientes, porque `dynamicParams` es `true` por defecto. Para mantener actualizados precio y descripción se usa ISR a demanda: cuando el sistema de productos cambia algo, llama a `revalidateTag` o `revalidatePath` para ese producto. Y lo que cambia segundo a segundo, como el stock, no conviene meterlo en la página estática: va en un componente dinámico aparte (streaming con Suspense) o se pide en el cliente. Así el grueso de la página es estático y barato, y solo lo volátil se calcula por request.",
    respuestaEn:
      "No: the build would take forever and most of those pages are barely visited. With `generateStaticParams` you pregenerate only the most visited ones (say the top 1,000 by traffic), and the rest are generated on first visit and cached for subsequent ones, since `dynamicParams` is `true` by default. To keep price and description current, use on-demand ISR: when the product system changes something, it calls `revalidateTag` or `revalidatePath` for that product. And what changes second by second, like stock, shouldn't go in the static page: it goes in a separate dynamic component (streamed with Suspense) or fetched on the client. That way the bulk of the page is static and cheap, and only the volatile part is computed per request.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué problemas aparecen con ISR al hacer self-hosting con varias instancias?",
    respuestaEs:
      "Por defecto, el cache de ISR vive en el sistema de archivos de cada instancia. Eso trae tres problemas. Primero, consistencia: una revalidación a demanda solo invalida la instancia que recibió la llamada, así que las demás siguen sirviendo la versión vieja y distintos usuarios ven contenido distinto según a qué instancia caen. Segundo, eficiencia: cada instancia regenera por su cuenta, multiplicando el trabajo. Tercero, en contenedores efímeros el cache se pierde al reiniciar. La solución es configurar un cache handler compartido (por ejemplo sobre Redis) para que todas las instancias lean y escriban el mismo cache y una invalidación llegue a todas. Otros detalles: la regeneración en segundo plano corre en la instancia que recibió el request y cuenta como cómputo extra; el Proxy no se ejecuta en las revalidaciones a demanda, así que hay que revalidar la ruta real y no una reescrita; e ISR no existe en un Static Export.",
    respuestaEn:
      "By default the ISR cache lives on each instance's file system. That brings three problems. First, consistency: an on-demand revalidation only invalidates the instance that received the call, so the others keep serving the old version and different users see different content depending on which instance they hit. Second, efficiency: each instance regenerates on its own, multiplying work. Third, in ephemeral containers the cache is lost on restart. The fix is configuring a shared cache handler (e.g. on Redis) so all instances read and write the same cache and an invalidation reaches all of them. Other details: background regeneration runs on the instance that received the request and counts as extra compute; Proxy doesn't run on on-demand revalidations, so you must revalidate the real path, not a rewritten one; and ISR doesn't exist in a Static Export.",
  },
  {
    nivel: 3,
    pregunta:
      "¿Por qué se dice que Partial Prerendering vuelve menos relevante la elección entre SSG y SSR?",
    respuestaEs:
      "Porque SSG, SSR e ISR deciden a nivel de RUTA: toda la página es estática o toda es dinámica. Si una ficha de producto casi estática tiene un solo dato por usuario (el carrito en el header, un precio con descuento personalizado), había que volver dinámica toda la página, o armar ese pedazo en el cliente. Con Partial Prerendering (lo que habilita Cache Components), una misma respuesta tiene un shell estático prerenderizado, que se sirve al instante y puede venir de un CDN, con 'huecos' dinámicos dentro de límites de `<Suspense>` que se completan por streaming en el mismo request. La pregunta deja de ser '¿esta página es SSG o SSR?' y pasa a ser '¿qué partes de esta página dependen del request?'. La contracara es la infraestructura: requiere streaming y una plataforma capaz de servir el shell y continuar el render dinámico, que no todos los hostings soportan igual.",
    respuestaEn:
      "Because SSG, SSR and ISR decide at the ROUTE level: the whole page is static or the whole page is dynamic. If a mostly-static product page had one per-user piece (the cart in the header, a personalized discounted price), you had to make the whole page dynamic, or build that piece on the client. With Partial Prerendering (what Cache Components enables), a single response has a prerendered static shell, served instantly and possibly from a CDN, with dynamic 'holes' inside `<Suspense>` boundaries filled by streaming in the same request. The question stops being 'is this page SSG or SSR?' and becomes 'which parts of this page depend on the request?'. The flip side is infrastructure: it requires streaming and a platform able to serve the shell and resume the dynamic render, which not every host supports equally.",
  },
];
