import type { PreguntaEntrevista } from "../types";

export const entrevistaEstrategiasDeploy: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué estrategias de deploy conocés y cuándo usás cada una?",
    respuestaEs:
      "Cuatro principales. RECREATE: apagar todas las instancias viejas y levantar las nuevas; es lo más simple y no necesita capacidad extra, pero hay downtime, así que queda para entornos internos o cuando las dos versiones no pueden convivir. ROLLING: reemplazar las instancias de a tandas, sacando una vieja y poniendo una nueva hasta completar; no hay downtime ni hace falta el doble de infraestructura, y es el default en Kubernetes y en la mayoría de las plataformas, a costa de que durante el deploy conviven las dos versiones. BLUE-GREEN: levantar el entorno nuevo completo al lado del actual, probarlo, y cambiar todo el tráfico de golpe en el balanceador; el rollback es instantáneo (volver a apuntar al viejo), pero requiere el doble de capacidad durante el deploy y el cambio es todo o nada. CANARY: mandar a la versión nueva un porcentaje chico del tráfico, mirar las métricas, e ir subiendo si están sanas; limita el impacto de un bug a pocos usuarios, pero necesita buena observabilidad y un balanceador que reparta por porcentaje. Para una app web típica, rolling es el piso razonable, y canary cuando el costo de un error en producción es alto.",
    respuestaEn:
      "Four main ones. RECREATE: shut down all old instances and start the new ones; it's the simplest and needs no extra capacity, but there's downtime, so it's for internal environments or when both versions can't coexist. ROLLING: replace instances in batches, removing an old one and adding a new one until done; no downtime and no double infrastructure, and it's the default in Kubernetes and most platforms, at the cost that both versions coexist during the deploy. BLUE-GREEN: bring up the full new environment next to the current one, test it, and switch all traffic at once at the load balancer; rollback is instant (point back to the old one), but it needs double capacity during the deploy and the switch is all-or-nothing. CANARY: send a small percentage of traffic to the new version, watch metrics, and increase if they're healthy; it limits a bug's impact to few users, but needs good observability and a load balancer that splits by percentage. For a typical web app, rolling is the reasonable baseline, and canary when the cost of a production error is high.",
  },
  {
    nivel: 1,
    pregunta: "Un deploy rompió producción. ¿Cómo hacés rollback?",
    respuestaEs:
      "Lo primero es restaurar el servicio, y después investigar. El rollback más confiable es volver a desplegar el artefacto anterior, no revertir el código y reconstruir: si cada build produce una imagen o artefacto inmutable etiquetado con el SHA del commit, volver atrás es desplegar el tag anterior, que ya se sabe que funcionaba, en minutos. Las plataformas lo facilitan: Vercel y Netlify tienen rollback instantáneo a un deploy previo, Kubernetes tiene `kubectl rollout undo`, y en blue-green alcanza con volver a apuntar el balanceador. La trampa está en la base de datos: si el deploy incluyó una migración que la versión vieja no tolera (una columna borrada o renombrada), el rollback del código no alcanza y la versión vieja también falla. Por eso las migraciones tienen que ser compatibles hacia atrás, con expand/contract. Después del incidente: revertir el commit en main para que el próximo deploy no lo vuelva a subir, y un postmortem sin culpas sobre qué no detectó el pipeline.",
    respuestaEn:
      "First restore service, then investigate. The most reliable rollback is redeploying the previous artifact, not reverting code and rebuilding: if each build produces an immutable image or artifact tagged with the commit SHA, rolling back means deploying the previous tag, known to work, in minutes. Platforms make it easy: Vercel and Netlify have instant rollback to a previous deploy, Kubernetes has `kubectl rollout undo`, and in blue-green you just point the load balancer back. The trap is the database: if the deploy included a migration the old version can't tolerate (a dropped or renamed column), rolling back code isn't enough and the old version fails too. That's why migrations must be backward-compatible, with expand/contract. After the incident: revert the commit on main so the next deploy doesn't ship it again, and a blameless postmortem on what the pipeline didn't catch.",
  },
  {
    nivel: 2,
    pregunta: "¿Blue-green o canary? ¿Qué gana y qué pierde cada una?",
    respuestaEs:
      "Blue-green optimiza el rollback y la posibilidad de probar antes: el entorno nuevo está completo, se le pueden correr smoke tests con tráfico interno antes de exponerlo, y si algo sale mal se vuelve atrás con un switch. Lo que pierde: necesita el doble de capacidad durante el deploy (en cloud es temporal, pero en bases o servicios con estado es más difícil duplicar), y cuando se hace el switch, un bug que las pruebas no detectaron le llega al 100% de los usuarios de golpe. Canary optimiza el radio de impacto: un bug lo ve el 1 o 5% del tráfico durante unos minutos, y las métricas reales de producción, no los tests, deciden si seguir. Lo que pierde: el deploy tarda más, conviven dos versiones durante un rato (compatibilidad de API y de schema obligatoria), y sin buenas métricas por versión el canary no sirve de nada porque no hay con qué decidir. Con poco tráfico, además, el 5% puede ser tan pocas requests que un error no se nota estadísticamente. En la práctica se combinan: levantar la versión nueva al costado como en blue-green y pasarle el tráfico gradualmente como en canary.",
    respuestaEn:
      "Blue-green optimizes rollback and the ability to test first: the new environment is complete, you can run smoke tests with internal traffic before exposing it, and if something goes wrong you switch back. What it loses: it needs double capacity during the deploy (temporary in the cloud, but harder to duplicate for databases or stateful services), and at switch time, a bug the tests missed reaches 100% of users at once. Canary optimizes blast radius: a bug is seen by 1 or 5% of traffic for a few minutes, and real production metrics, not tests, decide whether to continue. What it loses: the deploy takes longer, two versions coexist for a while (API and schema compatibility required), and without good per-version metrics the canary is useless because there's nothing to decide with. With low traffic, 5% may also be so few requests that an error isn't statistically noticeable. In practice they're combined: bring up the new version alongside as in blue-green and shift traffic gradually as in canary.",
    tradeoffs:
      "Blue-green: rollback instantáneo y pruebas previas, a cambio del doble de capacidad y un cambio todo o nada. Canary: impacto acotado y decisiones con datos reales, a cambio de deploys más lentos y dependencia de la observabilidad.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué hace falta para que un rolling deploy no corte requests en curso?",
    respuestaEs:
      "Que el balanceador solo mande tráfico a instancias listas y que las que se van terminen lo que tienen. Del lado de ARRANCAR: un readiness check que responda OK recién cuando la app puede atender (conectada a la base, caches calentadas), distinto del liveness check, que solo indica si el proceso está vivo; sin eso, el balanceador manda requests a una instancia que todavía está arrancando. Del lado de APAGAR: graceful shutdown. La plataforma manda SIGTERM, la app deja de aceptar conexiones nuevas, termina las requests en curso, cierra las conexiones a la base y sale; si no termina en un plazo (30 segundos por default en Kubernetes), recibe SIGKILL. Hay una carrera sutil: el balanceador tarda unos segundos en enterarse de que la instancia se va, así que conviene esperar un poco antes de cerrar el servidor (un preStop hook o un delay). Y el ritmo: `maxSurge` y `maxUnavailable` definen cuántas instancias extra se crean y cuántas pueden faltar a la vez, un balance entre velocidad del deploy y capacidad disponible. Todo esto además de la compatibilidad entre versiones, porque durante el rolling conviven v1 y v2.",
    respuestaEn:
      "That the load balancer only sends traffic to ready instances and that leaving ones finish what they have. On STARTUP: a readiness check that returns OK only when the app can serve (connected to the database, caches warmed), distinct from the liveness check, which only says whether the process is alive; without it, the balancer sends requests to an instance still booting. On SHUTDOWN: graceful shutdown. The platform sends SIGTERM, the app stops accepting new connections, finishes in-flight requests, closes database connections and exits; if it doesn't finish within a deadline (30 seconds by default in Kubernetes), it gets SIGKILL. There's a subtle race: the balancer takes a few seconds to learn the instance is leaving, so it's worth waiting a bit before closing the server (a preStop hook or a delay). And the pace: `maxSurge` and `maxUnavailable` define how many extra instances are created and how many can be missing at once, a balance between deploy speed and available capacity. All this on top of version compatibility, since v1 and v2 coexist during the rolling deploy.",
    codigo: `process.on("SIGTERM", async () => {
  listo = false;                      // el readiness check empieza a fallar
  await esperar(5_000);               // el balanceador deja de mandar tráfico
  server.close(async () => {          // no acepta conexiones nuevas, termina las activas
    await prisma.$disconnect();
    process.exit(0);
  });
});`,
  },
  {
    nivel: 3,
    pregunta: "¿Qué complica un deploy cuando conviven dos versiones?",
    respuestaEs:
      "Todo lo que las dos versiones comparten. LA BASE DE DATOS: el schema tiene que funcionar con v1 y v2 a la vez, así que los cambios incompatibles se parten con expand/contract en varios deploys. LAS COLAS Y EVENTOS: un mensaje que produce v2 puede consumirlo un worker v1 todavía no actualizado, y al revés; los formatos de mensaje se versionan y los consumidores toleran campos nuevos y faltantes, igual que una API. LAS CACHÉS: si v2 cambia la forma de un objeto cacheado, v1 puede leer lo que escribió v2 y fallar; se evita versionando las claves (`producto:v2:7`). LAS SESIONES: si viven en memoria de cada instancia, reemplazarla desloguea a sus usuarios; tienen que estar en un store compartido o en un token. LAS CONEXIONES LARGAS: WebSockets y streams no se drenan en segundos, así que el cliente tiene que saber reconectarse. Y LOS CLIENTES que no controlás: una app mobile vieja puede seguir llamando a la API durante meses, así que los cambios de contrato se hacen aditivos o se versiona la API. La regla general: cada deploy tiene que ser compatible con la versión anterior y con la siguiente.",
    respuestaEn:
      "Everything both versions share. THE DATABASE: the schema must work with v1 and v2 at once, so incompatible changes are split with expand/contract across several deploys. QUEUES AND EVENTS: a message produced by v2 may be consumed by a not-yet-updated v1 worker, and vice versa; message formats are versioned and consumers tolerate new and missing fields, just like an API. CACHES: if v2 changes the shape of a cached object, v1 may read what v2 wrote and fail; avoid it by versioning keys (`product:v2:7`). SESSIONS: if they live in each instance's memory, replacing it logs its users out; they must be in a shared store or a token. LONG-LIVED CONNECTIONS: WebSockets and streams don't drain in seconds, so the client must know how to reconnect. And CLIENTS you don't control: an old mobile app may keep calling the API for months, so contract changes are made additive or the API is versioned. The general rule: every deploy must be compatible with the previous version and the next one.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es separar deploy de release, y cómo medís si tu proceso de deploy es bueno?",
    respuestaEs:
      "DEPLOY es poner código nuevo en producción; RELEASE es exponer una funcionalidad a los usuarios. Separarlos permite desplegar seguido y con poco riesgo: el código llega apagado detrás de un feature flag y se activa después, gradualmente o por segmento, independientemente del deploy. Técnicas del mismo espíritu: DARK LAUNCH (la funcionalidad corre en producción pero sus resultados no se muestran, para medir carga), SHADOW TRAFFIC (duplicar requests reales hacia la versión nueva y descartar sus respuestas, comparándolas con las de la actual) y canaries por segmento (primero empleados, después un país). Para medir el proceso, las métricas DORA son el estándar: FRECUENCIA DE DEPLOY (cuántas veces por día o semana), LEAD TIME (de commit a producción), TASA DE FALLA DE CAMBIOS (qué porcentaje de deploys causa un incidente o rollback) y TIEMPO DE RECUPERACIÓN (cuánto se tarda en restaurar el servicio). Lo interesante es que no hay un trade-off entre velocidad y estabilidad: los equipos que despliegan más seguido en cambios chicos suelen tener también menos fallas y recuperaciones más rápidas, porque cada deploy es chico, fácil de entender y fácil de revertir.",
    respuestaEn:
      "DEPLOY is putting new code in production; RELEASE is exposing a feature to users. Separating them lets you deploy often with low risk: code ships turned off behind a feature flag and is enabled later, gradually or by segment, independent of the deploy. Techniques in the same spirit: DARK LAUNCH (the feature runs in production but its results aren't shown, to measure load), SHADOW TRAFFIC (duplicating real requests to the new version and discarding its responses, comparing them with the current one's) and segment canaries (employees first, then one country). To measure the process, DORA metrics are the standard: DEPLOYMENT FREQUENCY (how many times per day or week), LEAD TIME (from commit to production), CHANGE FAILURE RATE (what percentage of deploys cause an incident or rollback) and TIME TO RESTORE (how long to restore service). The interesting part is there's no trade-off between speed and stability: teams that deploy more often in small changes also tend to have fewer failures and faster recoveries, because each deploy is small, easy to understand and easy to revert.",
  },
];
