import type { PreguntaEntrevista } from "../types";

export const entrevistaFeatureFlags: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es un feature flag y para qué lo usarías?",
    respuestaEs:
      "Es un condicional en el código cuyo valor se decide afuera, en configuración, en tiempo de ejecución: `if (flags.nuevoCheckout) { ... }`. Permite cambiar el comportamiento de producción sin desplegar. Su uso principal es separar DEPLOY de RELEASE: el código de una funcionalidad a medio hacer llega a producción apagado, se integra a main todos los días (sin branches de semanas) y se activa cuando está lista, primero para el equipo, después para un porcentaje de usuarios, después para todos. Hay varios tipos, con vidas distintas. RELEASE FLAGS: para lanzar algo gradualmente; deberían vivir semanas y borrarse. KILL SWITCHES u operacionales: para apagar rápido algo costoso o riesgoso (una integración con un proveedor externo, una funcionalidad pesada durante un pico) sin deploy; pueden ser permanentes. EXPERIMENTOS: para mostrar variantes distintas y medir cuál funciona mejor. De PERMISO: para habilitar funcionalidades por plan o por cliente, que en realidad son lógica de negocio y a veces conviene modelar como tal.",
    respuestaEn:
      "It's a conditional in the code whose value is decided outside, in configuration, at runtime: `if (flags.newCheckout) { ... }`. It lets you change production behavior without deploying. Its main use is separating DEPLOY from RELEASE: the code for an unfinished feature ships to production turned off, gets merged to main daily (no weeks-long branches) and is enabled when ready, first for the team, then for a percentage of users, then for everyone. There are several types, with different lifespans. RELEASE FLAGS: to launch something gradually; they should live weeks and be deleted. KILL SWITCHES or operational flags: to quickly turn off something costly or risky (an integration with an external provider, a heavy feature during a peak) without deploying; they can be permanent. EXPERIMENTS: to show different variants and measure which works best. PERMISSION flags: to enable features per plan or per customer, which are really business logic and sometimes better modeled as such.",
  },
  {
    nivel: 1,
    pregunta: "¿Cómo implementás feature flags: variables de entorno, tu propia tabla o un servicio?",
    respuestaEs:
      "Depende de qué tan dinámicos tienen que ser. Una VARIABLE DE ENTORNO es lo más simple, pero cambiarla requiere reiniciar o redesplegar, y es la misma para todos los usuarios: sirve como kill switch grueso, no para rollouts graduales. Una TABLA PROPIA en la base (o en Redis) permite cambiar valores en caliente y agregar reglas simples, pero hay que construir la interfaz, el historial de cambios, la caché y la evaluación por usuario, y con el tiempo se termina reinventando un producto. Un SERVICIO dedicado (LaunchDarkly, Unleash, Flagsmith, GrowthBook; algunos open source y autohospedables) trae targeting por atributos, rollouts por porcentaje, auditoría de quién cambió qué, SDKs que evalúan localmente sin latencia y actualizaciones en tiempo real. Para no acoplarse a un proveedor existe OpenFeature, una API estándar con proveedores intercambiables. Mi criterio: variables de entorno para un par de kill switches al principio, y un servicio en cuanto hacen falta rollouts graduales o targeting, porque el costo de construirlo bien suele ser mayor que el de usarlo.",
    respuestaEn:
      "It depends on how dynamic they need to be. An ENVIRONMENT VARIABLE is simplest, but changing it requires a restart or redeploy, and it's the same for every user: it works as a coarse kill switch, not for gradual rollouts. YOUR OWN TABLE in the database (or Redis) allows changing values live and adding simple rules, but you must build the UI, change history, caching and per-user evaluation, and over time you end up reinventing a product. A dedicated SERVICE (LaunchDarkly, Unleash, Flagsmith, GrowthBook; some open source and self-hostable) brings attribute targeting, percentage rollouts, audit of who changed what, SDKs that evaluate locally without latency and real-time updates. To avoid vendor lock-in there's OpenFeature, a standard API with swappable providers. My criterion: environment variables for a couple of kill switches early on, and a service as soon as gradual rollouts or targeting are needed, because building it well usually costs more than using one.",
    codigo: `// OpenFeature: el código no sabe qué proveedor evalúa la flag
const cliente = OpenFeature.getClient();

const nuevoCheckout = await cliente.getBooleanValue(
  "nuevo-checkout",
  false,                                  // default seguro si el servicio no responde
  { targetingKey: usuario.id, plan: usuario.plan },
);`,
  },
  {
    nivel: 2,
    pregunta: "¿Cómo funciona un rollout por porcentaje, y dónde conviene evaluar la flag?",
    respuestaEs:
      "Con un hash determinista, no con un número aleatorio. Se calcula `hash(clave_de_la_flag + id_del_usuario) % 100` y el usuario ve la funcionalidad si ese bucket es menor al porcentaje. Así cada usuario cae siempre en el mismo bucket: no ve la versión nueva en una request y la vieja en la siguiente, y al subir del 10% al 20% todos los que ya la tenían la conservan, porque solo se suman buckets. Incluir la clave de la flag en el hash hace que los buckets de distintas flags sean independientes; si no, los mismos usuarios serían siempre los primeros en recibir todo. Sobre dónde evaluar: en el SERVIDOR, las reglas y los atributos del usuario no salen del backend y el resultado es consistente; es lo más seguro. En el CLIENTE, el SDK del navegador necesita las reglas o los resultados, lo que puede exponer funcionalidades no lanzadas o datos de targeting, y aparece un parpadeo mientras carga la configuración. Con renderizado en el servidor, lo sano es evaluar en el servidor y pasarle los resultados al cliente al renderizar, para que server y client vean lo mismo y no haya un hydration mismatch.",
    respuestaEn:
      "With a deterministic hash, not a random number. You compute `hash(flag_key + user_id) % 100` and the user sees the feature if that bucket is below the percentage. So each user always lands in the same bucket: they don't see the new version on one request and the old one on the next, and going from 10% to 20% everyone who had it keeps it, because buckets are only added. Including the flag key in the hash makes different flags' buckets independent; otherwise the same users would always be first to get everything. On where to evaluate: on the SERVER, rules and user attributes don't leave the backend and the result is consistent; it's the safest. On the CLIENT, the browser SDK needs the rules or results, which can expose unreleased features or targeting data, and there's a flicker while configuration loads. With server rendering, the healthy approach is evaluating on the server and passing the results to the client when rendering, so server and client see the same thing and there's no hydration mismatch.",
    tradeoffs:
      "Evaluar en el servidor es más seguro y consistente; en el cliente permite cambios sin ida y vuelta al backend, a costa de exponer configuración y de parpadeos.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué problemas traen los feature flags a largo plazo?",
    respuestaEs:
      "DEUDA: cada flag es un `if` con dos caminos que hay que mantener y probar. Una flag de release que quedó al 100% hace meses es código muerto con riesgo: nadie recuerda qué hace el camino apagado, y un día alguien la apaga por error. Por eso toda flag de release necesita un responsable y una fecha de vencimiento, y su limpieza se planifica como parte de la tarea (muchos equipos abren el ticket de borrado junto con el de creación; algunos servicios avisan de flags que no cambian hace tiempo). COMBINATORIA: con diez flags hay más de mil combinaciones posibles; no se pueden probar todas, así que se prueba el estado actual de producción y el estado objetivo de cada flag, y se evita que las flags dependan unas de otras. REUTILIZAR FLAGS VIEJAS es peligroso: el caso de Knight Capital en 2012 es el ejemplo clásico, donde reactivar una flag abandonada, con un servidor que no recibió el código nuevo, ejecutó lógica vieja y generó pérdidas de cientos de millones de dólares en menos de una hora. Y LÓGICA DE NEGOCIO disfrazada: los permisos por plan que viven como flags terminan siendo el modelo de negocio más importante del sistema sin tests ni tipos; esos conviene migrarlos a entitlements explícitos.",
    respuestaEn:
      "DEBT: each flag is an `if` with two paths to maintain and test. A release flag left at 100% for months is dead code with risk: nobody remembers what the off path does, and one day someone turns it off by mistake. That's why every release flag needs an owner and an expiry date, and its cleanup is planned as part of the work (many teams open the removal ticket along with the creation one; some services flag stale flags). COMBINATORICS: with ten flags there are over a thousand possible combinations; you can't test them all, so you test the current production state and each flag's target state, and avoid flags depending on each other. REUSING OLD FLAGS is dangerous: Knight Capital in 2012 is the classic example, where reactivating an abandoned flag, with one server that hadn't received the new code, ran old logic and caused losses of hundreds of millions of dollars in under an hour. And BUSINESS LOGIC in disguise: per-plan permissions living as flags end up being the system's most important business model without tests or types; those are worth migrating to explicit entitlements.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué pasa con los feature flags en un sistema distribuido?",
    respuestaEs:
      "LATENCIA Y DISPONIBILIDAD: llamar al servicio de flags en cada request sumaría latencia y lo convertiría en un punto único de falla. Los SDKs serios descargan las reglas, las evalúan en memoria y reciben cambios por streaming o polling; si el servicio se cae, siguen con la última configuración conocida, y si nunca la tuvieron (un arranque en frío), usan el DEFAULT del código. Ese default tiene que ser el comportamiento seguro, normalmente el viejo. CONSISTENCIA ENTRE SERVICIOS: si el frontend, la API y un worker evalúan la misma flag por separado, pueden no coincidir durante unos segundos después de un cambio, o por usar atributos distintos del usuario. Para flujos que cruzan servicios conviene evaluar una vez en el borde y propagar el resultado (en un header o en el mensaje), o asegurarse de que todos usan la misma clave de targeting. DATOS: una flag puede elegir qué código corre, pero no puede proteger un cambio de schema; si el camino nuevo escribe en una columna nueva, la migración tiene que existir antes, y apagar la flag no deshace los datos ya escritos con el formato nuevo, así que el camino viejo tiene que tolerarlos. Y CACHÉ: si una respuesta cacheada depende de una flag, la flag o la variante tienen que ser parte de la clave de caché, o un usuario puede recibir la versión de otro.",
    respuestaEn:
      "LATENCY AND AVAILABILITY: calling the flag service on every request would add latency and make it a single point of failure. Serious SDKs download the rules, evaluate them in memory and receive changes via streaming or polling; if the service goes down, they keep the last known configuration, and if they never had one (a cold start), they use the code's DEFAULT. That default must be the safe behavior, usually the old one. CROSS-SERVICE CONSISTENCY: if the frontend, the API and a worker evaluate the same flag separately, they may disagree for a few seconds after a change, or by using different user attributes. For flows spanning services, evaluate once at the edge and propagate the result (in a header or the message), or make sure all use the same targeting key. DATA: a flag can choose which code runs, but can't protect a schema change; if the new path writes to a new column, the migration must exist first, and turning the flag off doesn't undo data already written in the new format, so the old path must tolerate it. And CACHING: if a cached response depends on a flag, the flag or variant must be part of the cache key, or a user may receive someone else's version.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo se usa un feature flag para un experimento A/B, y qué lo puede invalidar?",
    respuestaEs:
      "La flag asigna a cada usuario una variante de forma estable (el mismo hash del rollout), y se mide una métrica objetivo por variante: conversión del checkout, por ejemplo. Lo que hace válido el experimento está en los detalles. EXPOSICIÓN: solo cuentan los usuarios que efectivamente vieron la diferencia, así que se registra un evento de exposición cuando se evalúa la flag en el punto donde cambia la experiencia, no al asignar. SAMPLE RATIO MISMATCH: si se configuró 50/50 y los datos muestran 52/48 con muchos usuarios, algo sesga la asignación o el registro (una variante que falla más al cargar y no registra), y los resultados no son confiables. PEEKING: mirar los resultados todos los días y cortar el experimento en cuanto 'da significativo' infla muchísimo los falsos positivos; se fija de antemano el tamaño de muestra y la duración, o se usan métodos secuenciales pensados para mirar en el camino. GUARDRAILS: además de la métrica objetivo, métricas que no se pueden empeorar (latencia, errores, reembolsos), porque una variante puede subir la conversión y romper otra cosa. Y la unidad de asignación tiene que coincidir con la de análisis: si se asigna por usuario pero se analiza por sesión, las observaciones no son independientes.",
    respuestaEn:
      "The flag assigns each user a variant stably (the same hash as the rollout), and a target metric is measured per variant: checkout conversion, for example. What makes the experiment valid is in the details. EXPOSURE: only users who actually saw the difference count, so an exposure event is logged when the flag is evaluated at the point where the experience changes, not at assignment. SAMPLE RATIO MISMATCH: if it was configured 50/50 and the data shows 52/48 with many users, something is biasing assignment or logging (a variant that fails to load more often and doesn't log), and the results aren't trustworthy. PEEKING: checking results daily and stopping the experiment as soon as it 'looks significant' greatly inflates false positives; fix the sample size and duration in advance, or use sequential methods designed for looking along the way. GUARDRAILS: besides the target metric, metrics that must not get worse (latency, errors, refunds), because a variant can raise conversion and break something else. And the assignment unit must match the analysis unit: if you assign by user but analyze by session, observations aren't independent.",
  },
];
