import type { PreguntaEntrevista } from "../types";

export const entrevistaObservabilidad: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué diferencia hay entre monitoreo y observabilidad?",
    respuestaEs:
      "MONITOREO es vigilar lo que ya sabés que puede fallar: dashboards y alertas sobre métricas predefinidas, como CPU, tasa de errores o latencia. Responde '¿está funcionando?'. OBSERVABILIDAD es poder entender el estado interno de un sistema a partir de lo que emite, incluso ante problemas que nadie anticipó: responde '¿por qué está fallando, y solo para quiénes?'. Se apoya en tres tipos de señales: MÉTRICAS (números agregados en el tiempo, baratos de guardar, ideales para dashboards y alertas), LOGS (eventos individuales con detalle, idealmente estructurados) y TRAZAS (el recorrido de un request por los servicios, con la duración de cada tramo). La diferencia práctica aparece en un incidente: con monitoreo sabés que la latencia subió; con observabilidad podés partir esa latencia por endpoint, por cliente o por versión, saltar a las trazas lentas y de ahí a los logs de ese request, hasta encontrar que es un tenant puntual con una consulta sin índice. Para eso las señales tienen que estar correlacionadas, con el mismo trace id en logs y trazas.",
    respuestaEn:
      "MONITORING is watching what you already know can fail: dashboards and alerts on predefined metrics, like CPU, error rate or latency. It answers 'is it working?'. OBSERVABILITY is being able to understand a system's internal state from what it emits, even for problems nobody anticipated: it answers 'why is it failing, and only for whom?'. It relies on three kinds of signals: METRICS (numbers aggregated over time, cheap to store, ideal for dashboards and alerts), LOGS (individual events with detail, ideally structured) and TRACES (a request's path through services, with each hop's duration). The practical difference shows during an incident: with monitoring you know latency went up; with observability you can split that latency by endpoint, customer or version, jump to the slow traces and from there to that request's logs, until you find it's one tenant with an unindexed query. For that, the signals must be correlated, with the same trace id in logs and traces.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué medís en un servicio web, y por qué percentiles en vez de promedios?",
    respuestaEs:
      "Un punto de partida probado son las cuatro GOLDEN SIGNALS de Google: LATENCIA (cuánto tardan las requests, separando las exitosas de las fallidas), TRÁFICO (requests por segundo), ERRORES (tasa de requests fallidas) y SATURACIÓN (qué tan lleno está el recurso más limitado: CPU, memoria, conexiones del pool). Para servicios que atienden requests se resume en RED: Rate, Errors, Duration; para recursos como una base o una cola, en USE: Utilization, Saturation, Errors. Sobre la latencia: el PROMEDIO esconde lo que importa. Si el 98% de las requests tarda 100 ms y el 2% tarda 3 segundos, el promedio da unos 160 ms y parece sano, pero esas requests lentas son usuarios reales frustrados, y como un usuario hace muchas requests por sesión, la mayoría se cruza con alguna. Los PERCENTILES lo muestran: el p50 es la experiencia típica, el p95 y el p99 son la cola, donde suelen estar los problemas (contención de locks, pausas de GC, un cliente con muchos datos). Por eso los SLOs de latencia se definen sobre percentiles.",
    respuestaEn:
      "A proven starting point is Google's four GOLDEN SIGNALS: LATENCY (how long requests take, separating successful from failed ones), TRAFFIC (requests per second), ERRORS (failed request rate) and SATURATION (how full the most constrained resource is: CPU, memory, pool connections). For request-serving services it's summarized as RED: Rate, Errors, Duration; for resources like a database or a queue, as USE: Utilization, Saturation, Errors. On latency: the AVERAGE hides what matters. If 98% of requests take 100 ms and 2% take 3 seconds, the average is about 160 ms and looks healthy, but those slow requests are real frustrated users, and since a user makes many requests per session, most will hit one. PERCENTILES show it: p50 is the typical experience, p95 and p99 are the tail, where problems usually live (lock contention, GC pauses, a customer with lots of data). That's why latency SLOs are defined on percentiles.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué son los SLI, SLO y error budgets, y cómo se usan?",
    respuestaEs:
      "Un SLI (service level indicator) es una medición de algo que le importa al usuario, expresada como proporción de eventos buenos: 'porcentaje de requests al checkout que responden sin error en menos de 500 ms'. Un SLO (objective) es el objetivo para ese indicador en una ventana: 'el 99,5% en los últimos 28 días'. Un SLA es un contrato con consecuencias (créditos, multas) y suele ser más laxo que el SLO interno. El ERROR BUDGET es lo que el SLO permite fallar: con 99,5% sobre un millón de requests al mes, hay 5.000 requests malas 'disponibles'. Lo valioso es que convierte la discusión entre velocidad y estabilidad en un número: si queda presupuesto, se puede desplegar seguido y experimentar; si se está agotando, se prioriza confiabilidad sobre funcionalidades nuevas. Dos criterios importantes: el SLO no debería ser 100%, porque es inalcanzable y paraliza los cambios (y el usuario no nota la diferencia entre 99,99% y 100% porque su propia conexión falla más), y se mide lo más cerca posible del usuario (en el balanceador o el cliente), no en el uso de CPU.",
    respuestaEn:
      "An SLI (service level indicator) is a measurement of something users care about, expressed as a proportion of good events: 'percentage of checkout requests answering without error in under 500 ms'. An SLO (objective) is the target for that indicator over a window: '99.5% over the last 28 days'. An SLA is a contract with consequences (credits, penalties) and is usually looser than the internal SLO. The ERROR BUDGET is what the SLO allows to fail: with 99.5% over a million requests a month, there are 5,000 bad requests 'available'. Its value is that it turns the speed-vs-stability debate into a number: if budget remains, you can deploy often and experiment; if it's running out, reliability takes priority over new features. Two important criteria: the SLO shouldn't be 100%, since it's unreachable and freezes change (and users can't tell 99.99% from 100% because their own connection fails more often), and it's measured as close to the user as possible (at the load balancer or the client), not on CPU usage.",
    tradeoffs:
      "Un SLO más exigente da más confiabilidad a cambio de menos velocidad de cambio y más costo; el error budget hace explícito ese intercambio.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué tipos de métricas hay y qué es el problema de la cardinalidad?",
    respuestaEs:
      "Tres tipos básicos. COUNTER: solo sube (requests totales, errores totales); lo útil es su tasa de cambio, requests por segundo. GAUGE: un valor que sube y baja (memoria en uso, conexiones activas, largo de una cola). HISTOGRAM: cuenta observaciones en buckets de rango (cuántas requests tardaron menos de 100 ms, de 250, de 500...) y es lo que permite calcular percentiles de forma agregable. Un detalle importante: los percentiles no se pueden promediar. El p99 de un servicio con diez instancias no es el promedio de los diez p99; con histogramas se suman los buckets de todas las instancias y se calcula el percentil sobre el total. Las métricas llevan LABELS (endpoint, método, status) para poder filtrarlas, y cada combinación distinta de valores es una serie de tiempo aparte que el sistema guarda. Ahí está el problema de CARDINALIDAD: un label con valores ilimitados, como el user id, el request id o una URL con ids adentro (`/pedidos/8123`), crea millones de series, dispara el costo y puede tirar el backend de métricas. Los labels tienen que tener pocos valores posibles (la ruta como plantilla, `/pedidos/:id`); el detalle por usuario va en logs y trazas.",
    respuestaEn:
      "Three basic types. COUNTER: only goes up (total requests, total errors); what's useful is its rate of change, requests per second. GAUGE: a value that goes up and down (memory in use, active connections, queue length). HISTOGRAM: counts observations in range buckets (how many requests took under 100 ms, 250, 500...) and is what enables computing percentiles in an aggregatable way. An important detail: percentiles can't be averaged. The p99 of a service with ten instances isn't the average of the ten p99s; with histograms you add up every instance's buckets and compute the percentile over the total. Metrics carry LABELS (endpoint, method, status) so you can filter them, and each distinct combination of values is a separate time series the system stores. That's the CARDINALITY problem: a label with unbounded values, like user id, request id or a URL with ids in it (`/orders/8123`), creates millions of series, drives up cost and can take down the metrics backend. Labels must have few possible values (the route as a template, `/orders/:id`); per-user detail goes in logs and traces.",
    codigo: `// bien: la ruta como plantilla, pocos valores posibles
duracion.observe({ ruta: "/pedidos/:id", metodo: "GET", status: 200 }, ms);

// mal: una serie de tiempo nueva por cada pedido y cada usuario
duracion.observe({ ruta: "/pedidos/8123", usuario: "u_91823" }, ms);`,
  },
  {
    nivel: 3,
    pregunta: "¿Qué es OpenTelemetry y cómo se propaga una traza entre servicios?",
    respuestaEs:
      "OpenTelemetry (OTel) es el estándar abierto para instrumentar aplicaciones: define APIs y SDKs por lenguaje para emitir trazas, métricas y logs, un protocolo común (OTLP) y un COLLECTOR, un proceso que recibe esa telemetría, la procesa (filtra, agrega atributos, muestrea) y la exporta a cualquier backend (Grafana, Datadog, Honeycomb, Jaeger). La ventaja es no atarse a un proveedor: se instrumenta una vez y se cambia de backend configurando el collector. Además tiene instrumentación automática para librerías comunes (HTTP, Express, Prisma, pg, Redis), que genera spans sin tocar el código. Una TRAZA es un árbol de SPANS: cada span es una operación con inicio, duración, atributos y un parent. Para que un request que pasa por varios servicios forme una sola traza, el contexto se PROPAGA: el servicio que llama agrega el header `traceparent` (estándar W3C Trace Context) con el trace id y el id del span actual, y el que recibe lo lee y crea sus spans como hijos. Las colas son el caso fácil de romper: si el productor no guarda el contexto en los metadatos del mensaje, el consumidor arranca una traza nueva y se pierde la relación. Y para correlacionar, el trace id se agrega a cada línea de log.",
    respuestaEn:
      "OpenTelemetry (OTel) is the open standard for instrumenting applications: it defines per-language APIs and SDKs to emit traces, metrics and logs, a common protocol (OTLP) and a COLLECTOR, a process that receives that telemetry, processes it (filters, adds attributes, samples) and exports it to any backend (Grafana, Datadog, Honeycomb, Jaeger). The advantage is avoiding vendor lock-in: you instrument once and change backends by configuring the collector. It also has automatic instrumentation for common libraries (HTTP, Express, Prisma, pg, Redis), producing spans without touching code. A TRACE is a tree of SPANS: each span is an operation with a start, duration, attributes and a parent. For a request crossing several services to form one trace, context is PROPAGATED: the caller adds the `traceparent` header (W3C Trace Context standard) with the trace id and current span id, and the receiver reads it and creates its spans as children. Queues are the easy case to break: if the producer doesn't store the context in the message metadata, the consumer starts a new trace and the relationship is lost. And to correlate, the trace id is added to every log line.",
    codigo: `traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01
             │  └──────── trace id ─────────────┘ └─ span padre ─┘ └ sampled`,
  },
  {
    nivel: 3,
    pregunta: "¿Cómo controlás el costo de la telemetría y cómo diseñás alertas que no molesten?",
    respuestaEs:
      "COSTO: trazar el 100% de las requests en un sistema grande es carísimo, así que se MUESTREA. El head sampling decide al inicio de la traza (por ejemplo, el 5%) y es barato, pero descarta a ciegas: la traza del error raro probablemente no quede. El tail sampling decide al final, en el collector, cuando ya se sabe cómo terminó: guarda todas las trazas con error o lentas y una fracción de las normales; es mucho más útil, pero el collector tiene que retener trazas completas en memoria. En logs, niveles bien usados y retención distinta según el valor; en métricas, controlar la cardinalidad. ALERTAS: alertar por SÍNTOMAS que siente el usuario (el SLO se está rompiendo), no por CAUSAS (CPU al 90%, que a veces no importa), y que cada alerta requiera una acción humana; si no, genera fatiga y el equipo aprende a ignorarlas. La técnica recomendada son las alertas por BURN RATE: medir a qué velocidad se consume el error budget. Un burn rate de 1 lo agota justo al final de la ventana; uno de 14 lo agota en unos dos días. Se combinan dos alertas: una rápida (burn rate alto en una ventana corta, que despierta a alguien) y una lenta (burn rate moderado sostenido, que abre un ticket). Así se detecta tanto una caída como una degradación lenta, sin alertar por picos de un minuto.",
    respuestaEn:
      "COST: tracing 100% of requests in a large system is very expensive, so you SAMPLE. Head sampling decides at the start of the trace (say, 5%) and is cheap, but discards blindly: the trace of the rare error likely won't be kept. Tail sampling decides at the end, in the collector, once it's known how it ended: it keeps every error or slow trace and a fraction of normal ones; far more useful, but the collector must hold complete traces in memory. For logs, well-used levels and retention by value; for metrics, controlling cardinality. ALERTS: alert on SYMPTOMS users feel (the SLO is breaking), not CAUSES (CPU at 90%, which sometimes doesn't matter), and every alert should require human action; otherwise it causes fatigue and the team learns to ignore them. The recommended technique is BURN RATE alerts: measure how fast the error budget is being consumed. A burn rate of 1 exhausts it exactly at the end of the window; one of 14 exhausts it in about two days. Two alerts are combined: a fast one (high burn rate over a short window, which pages someone) and a slow one (moderate sustained burn rate, which opens a ticket). That catches both an outage and a slow degradation, without alerting on one-minute spikes.",
    tradeoffs:
      "Head sampling es barato pero pierde los casos raros; tail sampling los conserva a cambio de más memoria y complejidad en el collector.",
  },
];
