import type { PreguntaEntrevista } from "../types";

export const entrevistaEscalabilidadDb: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "La base de datos no da más. ¿Qué hacés, y en qué orden?",
    respuestaEs:
      "De lo más barato a lo más caro, midiendo en cada paso. Primero, ver QUÉ la satura: con `pg_stat_statements` y las métricas de CPU, memoria, IO y conexiones. Muchas veces son unas pocas consultas sin índice, un N+1 o un endpoint que trae de más, y arreglarlas da más margen que cualquier cambio de infraestructura. Segundo, CONEXIONES: si el problema es la cantidad de conexiones, un pooler (PgBouncer o el de tu proveedor). Tercero, CACHÉ para las lecturas repetidas. Cuarto, ESCALAR VERTICALMENTE: una máquina más grande; es un cambio de configuración, sin tocar código, y un Postgres bien afinado en una máquina grande aguanta muchísimo. Quinto, RÉPLICAS DE LECTURA si la carga es mayormente de lectura: mandar reportes y listados a réplicas y dejar el primario para escrituras. Sexto, PARTICIONAR tablas enormes para que las consultas y el mantenimiento toquen menos datos. Y último, SHARDING, repartir los datos entre varios servidores: es lo único que escala las escrituras sin límite, pero complica todo lo demás, así que se llega cuando los pasos anteriores ya no alcanzan.",
    respuestaEn:
      "From cheapest to most expensive, measuring at each step. First, see WHAT saturates it: with `pg_stat_statements` and CPU, memory, IO and connection metrics. Often it's a few unindexed queries, an N+1 or an endpoint over-fetching, and fixing them buys more headroom than any infrastructure change. Second, CONNECTIONS: if the problem is connection count, a pooler (PgBouncer or your provider's). Third, CACHING for repeated reads. Fourth, SCALE VERTICALLY: a bigger machine; it's a configuration change, no code, and a well-tuned Postgres on a big machine handles a lot. Fifth, READ REPLICAS if the load is mostly reads: send reports and listings to replicas and keep the primary for writes. Sixth, PARTITION huge tables so queries and maintenance touch less data. And last, SHARDING, spreading data across several servers: it's the only thing that scales writes without limit, but it complicates everything else, so you get there when the previous steps no longer suffice.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué es una réplica de lectura y qué problema trae?",
    respuestaEs:
      "Es una copia de la base que recibe continuamente los cambios del primario (en Postgres, aplicando el WAL que el primario le envía) y acepta solo lecturas. Todas las escrituras van al primario, y las lecturas se pueden repartir entre las réplicas, así que sirve cuando la carga es mayormente de lectura: listados, búsquedas, reportes, analytics. También sirve como respaldo listo para promover si el primario falla. El problema es el REPLICATION LAG: la replicación suele ser asíncrona, así que la réplica va unos milisegundos (o segundos, bajo carga) atrás del primario. El caso típico: un usuario edita su perfil, la escritura va al primario, la página siguiente lee de una réplica que todavía no recibió el cambio, y el usuario ve sus datos viejos y cree que no se guardó. Por eso no todo se puede leer de una réplica: lo que el usuario acaba de escribir, o lo que se usa para tomar una decisión (el stock antes de vender), se lee del primario.",
    respuestaEn:
      "It's a copy of the database continuously receiving the primary's changes (in Postgres, by applying the WAL the primary sends it) and accepting only reads. All writes go to the primary, and reads can be spread across replicas, so it helps when the load is mostly reads: listings, searches, reports, analytics. It's also a standby ready to promote if the primary fails. The problem is REPLICATION LAG: replication is usually asynchronous, so the replica runs a few milliseconds (or seconds, under load) behind the primary. The typical case: a user edits their profile, the write goes to the primary, the next page reads from a replica that hasn't received the change yet, and the user sees their old data and thinks it wasn't saved. That's why not everything can be read from a replica: what the user just wrote, or what's used to make a decision (stock before selling), is read from the primary.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo garantizás que un usuario vea lo que acaba de escribir si leés de réplicas?",
    respuestaEs:
      "Es la garantía de READ-YOUR-WRITES, y hay varias formas de darla, de más simple a más precisa. Leer del primario lo que el usuario acaba de tocar: después de una escritura, las lecturas de ese usuario van al primario durante unos segundos (una cookie o una marca en la sesión con la hora de la última escritura). Es simple y cubre la mayoría de los casos, a costa de algo de carga extra en el primario. Rutear por tipo de dato: el perfil propio, el carrito o el checkout siempre del primario; el catálogo y los reportes, de réplicas. Seguir la posición del WAL: después de escribir, guardar el LSN del primario (`pg_current_wal_lsn()`) y leer de una réplica solo si ya lo alcanzó (`pg_last_wal_replay_lsn()`); es preciso, pero más complejo. Otra garantía relacionada es la de LECTURAS MONÓTONAS: si un usuario lee de réplicas distintas con lags distintos, puede ver un dato nuevo y después uno más viejo; se evita fijando cada usuario a una réplica. La alternativa de raíz es la replicación sincrónica, donde el primario espera a que la réplica confirme antes de responder el COMMIT: elimina el lag para esa réplica, pero cada escritura paga la latencia de la red, y si la réplica se cae las escrituras se frenan.",
    respuestaEn:
      "It's the READ-YOUR-WRITES guarantee, and there are several ways to provide it, from simplest to most precise. Read from the primary what the user just touched: after a write, that user's reads go to the primary for a few seconds (a cookie or session flag with the last write time). It's simple and covers most cases, at the cost of some extra primary load. Route by data type: your own profile, the cart or checkout always from the primary; the catalog and reports, from replicas. Track the WAL position: after writing, store the primary's LSN (`pg_current_wal_lsn()`) and read from a replica only if it has reached it (`pg_last_wal_replay_lsn()`); precise, but more complex. A related guarantee is MONOTONIC READS: if a user reads from different replicas with different lags, they can see new data and then older data; you avoid it by pinning each user to one replica. The root alternative is synchronous replication, where the primary waits for the replica to confirm before returning COMMIT: it eliminates lag for that replica, but every write pays network latency, and if the replica goes down writes stall.",
    tradeoffs:
      "Replicación asíncrona: escrituras rápidas y disponibles, lecturas potencialmente viejas. Sincrónica: lecturas consistentes, escrituras más lentas y dependientes de la réplica.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué diferencia hay entre particionar y shardear?",
    respuestaEs:
      "Los dos parten una tabla grande en pedazos, pero en lugares distintos. PARTICIONAR divide una tabla en varias tablas físicas dentro del MISMO servidor: en Postgres, con particionado declarativo por rango (por mes), por lista (por país) o por hash. La aplicación sigue consultando la tabla `eventos` como siempre, y el planner hace partition pruning: si la consulta filtra por fecha, solo lee las particiones relevantes. Los beneficios son de mantenimiento y de consultas acotadas: borrar los datos de hace dos años es un `DROP` de la partición (instantáneo) en vez de un DELETE de millones de filas, los índices por partición son más chicos, y VACUUM trabaja sobre pedazos. No agrega capacidad: sigue siendo una máquina. SHARDEAR reparte los datos entre VARIOS servidores, cada uno con su parte; eso sí escala escrituras, almacenamiento y memoria más allá de una máquina, pero las consultas que cruzan shards, las transacciones entre shards y las constraints globales se complican mucho. Por eso el orden natural es particionar primero, y shardear cuando una sola máquina ya no alcanza.",
    respuestaEn:
      "Both split a large table into pieces, but in different places. PARTITIONING divides a table into several physical tables within the SAME server: in Postgres, with declarative partitioning by range (by month), list (by country) or hash. The application keeps querying the `events` table as always, and the planner does partition pruning: if the query filters by date, it only reads the relevant partitions. The benefits are maintenance and bounded queries: deleting two-year-old data is a partition `DROP` (instant) instead of a DELETE of millions of rows, per-partition indexes are smaller, and VACUUM works on pieces. It doesn't add capacity: it's still one machine. SHARDING spreads data across SEVERAL servers, each with its part; that does scale writes, storage and memory beyond one machine, but cross-shard queries, cross-shard transactions and global constraints get much harder. That's why the natural order is partitioning first, and sharding when a single machine no longer suffices.",
    codigo: `CREATE TABLE eventos (
  id         bigint GENERATED ALWAYS AS IDENTITY,
  creado_el  timestamptz NOT NULL,
  payload    jsonb,
  PRIMARY KEY (id, creado_el)   -- la clave de partición tiene que estar en la PK
) PARTITION BY RANGE (creado_el);

CREATE TABLE eventos_2026_09 PARTITION OF eventos
  FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

-- borrar un mes viejo: instantáneo, sin DELETE masivo
DROP TABLE eventos_2024_09;`,
  },
  {
    nivel: 3,
    pregunta: "¿Cómo elegís la shard key, y qué se complica al shardear?",
    respuestaEs:
      "La shard key decide en qué shard vive cada fila, y cambiarla después es casi una migración completa, así que se elige con tres criterios. DISTRIBUCIÓN: muchos valores posibles y repartidos parejo; una clave con pocos valores o con un valor gigante (un cliente que es la mitad del negocio) crea hotspots. ESCRITURAS: que no se concentren; una clave monótona como la fecha o un id autoincremental manda todas las escrituras nuevas al mismo shard. LOCALIDAD DE LAS CONSULTAS: que las consultas más frecuentes incluyan la clave y se resuelvan en un solo shard; en un SaaS, el tenant_id suele ser la clave natural porque casi todo se consulta por tenant y los joins quedan dentro del shard. Lo que se complica: consultas sin la clave son scatter-gather a todos los shards; JOINs y transacciones entre shards necesitan coordinación (2PC) o se rediseñan con sagas; las constraints UNIQUE y las foreign keys solo valen dentro de un shard; los ids tienen que ser globalmente únicos (UUID v7 o esquemas tipo Snowflake en vez de secuencias); y RESHARDING, agregar shards, implica mover datos. Para eso se usan muchos shards lógicos mapeados a pocos servidores físicos, o consistent hashing, así mover un shard lógico es más simple que re-hashear todo. Herramientas como Citus (Postgres) o Vitess (MySQL) resuelven parte de esto.",
    respuestaEn:
      "The shard key decides which shard each row lives in, and changing it later is nearly a full migration, so it's chosen by three criteria. DISTRIBUTION: many possible values, spread evenly; a key with few values or one giant value (a customer that's half the business) creates hotspots. WRITES: they shouldn't concentrate; a monotonic key like a date or an auto-increment id sends every new write to the same shard. QUERY LOCALITY: the most frequent queries should include the key and resolve on a single shard; in a SaaS, tenant_id is usually the natural key because almost everything is queried by tenant and joins stay within the shard. What gets harder: queries without the key are scatter-gather across all shards; cross-shard JOINs and transactions need coordination (2PC) or are redesigned with sagas; UNIQUE constraints and foreign keys only hold within a shard; ids must be globally unique (UUID v7 or Snowflake-like schemes instead of sequences); and RESHARDING, adding shards, means moving data. For that you use many logical shards mapped to few physical servers, or consistent hashing, so moving a logical shard is simpler than re-hashing everything. Tools like Citus (Postgres) or Vitess (MySQL) solve part of this.",
  },
  {
    nivel: 3,
    pregunta: "El primario se cae. ¿Qué pasa y cómo diseñás el failover?",
    respuestaEs:
      "Se promueve una réplica a primario y la aplicación pasa a escribir en ella. Las decisiones de diseño giran alrededor de dos métricas: el RPO (cuántos datos podés perder) y el RTO (cuánto tiempo podés estar sin servicio). Con replicación asíncrona, las últimas transacciones confirmadas en el primario pueden no haber llegado a la réplica, y se pierden al promoverla: el RPO no es cero. Con replicación sincrónica hacia al menos una réplica, ninguna transacción confirmada se pierde, a cambio de latencia en cada escritura; una opción intermedia es sincrónica con una réplica en la misma región y asíncrona con las demás. Para el RTO, el failover automático (Patroni en Postgres autogestionado, o el que hacen RDS y los proveedores gestionados) detecta la caída y promueve en segundos o pocos minutos. El riesgo clásico es el SPLIT BRAIN: por una partición de red, el viejo primario sigue vivo, se promueve otro, y dos nodos aceptan escrituras que después no se pueden reconciliar; se evita con consenso para decidir quién es primario (etcd en Patroni) y aislando al viejo (fencing). Del lado de la aplicación: conectarse por un endpoint o DNS que apunte siempre al primario actual, reintentar las conexiones caídas, y que las operaciones sean idempotentes para poder reintentar las que quedaron en el aire. Y probar el failover periódicamente: un plan que nunca se ejecutó no es un plan.",
    respuestaEn:
      "A replica is promoted to primary and the application starts writing to it. Design decisions revolve around two metrics: RPO (how much data you can lose) and RTO (how long you can be down). With asynchronous replication, the last transactions committed on the primary may not have reached the replica, and they're lost on promotion: RPO isn't zero. With synchronous replication to at least one replica, no committed transaction is lost, at the cost of latency on every write; a middle ground is synchronous to one replica in the same region and asynchronous to the rest. For RTO, automatic failover (Patroni for self-managed Postgres, or what RDS and managed providers do) detects the failure and promotes in seconds or a few minutes. The classic risk is SPLIT BRAIN: due to a network partition, the old primary stays alive, another is promoted, and two nodes accept writes that can't be reconciled later; you avoid it with consensus to decide who's primary (etcd in Patroni) and by isolating the old one (fencing). On the application side: connect through an endpoint or DNS that always points to the current primary, retry dropped connections, and make operations idempotent so in-flight ones can be retried. And test failover periodically: a plan that has never been run isn't a plan.",
    repregunta: "¿Una réplica reemplaza a los backups?",
    respuestaRepreguntaEs:
      "No. Una réplica copia todo lo que pasa en el primario, incluidos los errores: un `DELETE` sin WHERE o una migración que borra una columna se replica en milisegundos. La réplica protege contra fallas de hardware, no contra errores humanos ni corrupción lógica. Para eso hacen falta backups con point-in-time recovery (backup base más el archivo del WAL), que permiten volver al estado de un minuto antes del error, y probar la restauración con regularidad.",
    respuestaRepreguntaEn:
      "No. A replica copies everything happening on the primary, including mistakes: a `DELETE` without WHERE or a migration dropping a column replicates in milliseconds. A replica protects against hardware failure, not human error or logical corruption. For that you need backups with point-in-time recovery (base backup plus WAL archive), which let you return to the state one minute before the mistake, and you need to test restores regularly.",
  },
];
