import type { PreguntaEntrevista } from "../types";

export const entrevistaMigraciones: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es una migración y por qué se versiona el schema?",
    respuestaEs:
      "Una migración es un archivo que describe un cambio de schema (crear una tabla, agregar una columna, un índice) y que se aplica en orden. Se guardan en el repositorio junto al código, y la base registra en una tabla cuáles ya se aplicaron (`_prisma_migrations` en Prisma), así que cualquier entorno, desde la máquina de un desarrollador hasta producción, llega al mismo schema aplicando las pendientes. Sin eso, los cambios se hacen a mano en cada base, los entornos divergen y nadie sabe cuál es el schema real. Con Prisma el flujo es: cambiás `schema.prisma`, `prisma migrate dev` genera el SQL de la migración y lo aplica en tu base local, revisás ese SQL y lo commiteás; en producción, `prisma migrate deploy` aplica las pendientes sin generar nada. Dos reglas: una migración ya aplicada en un entorno compartido no se edita (se crea otra que corrija), y el SQL generado se lee antes de commitear, porque un rename puede aparecer como DROP + ADD y borrar datos.",
    respuestaEn:
      "A migration is a file describing a schema change (create a table, add a column, an index) that's applied in order. They're stored in the repository with the code, and the database records in a table which ones were applied (`_prisma_migrations` in Prisma), so any environment, from a developer's machine to production, reaches the same schema by applying the pending ones. Without that, changes are made by hand on each database, environments diverge and nobody knows the real schema. With Prisma the flow is: you change `schema.prisma`, `prisma migrate dev` generates the migration SQL and applies it to your local database, you review that SQL and commit it; in production, `prisma migrate deploy` applies pending ones without generating anything. Two rules: a migration already applied in a shared environment isn't edited (you create another one that fixes it), and the generated SQL is read before committing, because a rename may appear as DROP + ADD and delete data.",
  },
  {
    nivel: 1,
    pregunta: "¿En qué momento del deploy se corren las migraciones?",
    respuestaEs:
      "Como un paso propio del pipeline, antes de que arranque la versión nueva de la app: CI construye, un job corre `prisma migrate deploy` contra la base de producción, y recién si termina bien se despliega el código. Así, si la migración falla, la versión vieja sigue funcionando y el deploy se corta. No conviene correrlas al arrancar cada instancia de la app: con varias réplicas, todas intentan migrar a la vez (Prisma usa un advisory lock para que no se pisen, pero igual el arranque queda atado a la migración), y una migración lenta demora o hace fallar los health checks. Además conviene tener un backup o snapshot reciente antes de migraciones riesgosas, y probar las migraciones contra una copia con datos parecidos a los de producción (con Neon, una branch de la base), porque una migración que tarda un segundo con 100 filas puede tardar veinte minutos con 50 millones.",
    respuestaEn:
      "As its own pipeline step, before the new app version starts: CI builds, a job runs `prisma migrate deploy` against the production database, and only if it succeeds is the code deployed. That way, if the migration fails, the old version keeps working and the deploy stops. Running them at every app instance's startup isn't a good idea: with several replicas, they all try to migrate at once (Prisma uses an advisory lock so they don't collide, but startup is still tied to the migration), and a slow migration delays or fails health checks. It's also worth having a recent backup or snapshot before risky migrations, and testing migrations against a copy with production-like data (with Neon, a database branch), because a migration taking one second with 100 rows can take twenty minutes with 50 million.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo renombrás una columna sin downtime?",
    respuestaEs:
      "No con un RENAME directo. Durante un rolling deploy conviven instancias de la versión vieja y de la nueva, y además la migración corre antes del código: si renombro `nombre` a `nombre_completo`, la versión vieja empieza a fallar apenas corre la migración. La técnica es EXPAND / CONTRACT (o parallel change), que parte el cambio en pasos donde cada estado del schema es compatible con las dos versiones de la app que pueden estar corriendo. Expand: agregar `nombre_completo` como nullable. Deploy de una versión que escribe en las dos columnas y sigue leyendo la vieja. Backfill: copiar los datos existentes por lotes. Deploy de una versión que lee y escribe solo la nueva. Contract: borrar `nombre` cuando ninguna versión la usa. Un detalle que se olvida: si la columna vieja era NOT NULL, hay que quitarle esa restricción antes de desplegar la versión que ya no la escribe. Es más lento (varios deploys en vez de uno), así que se reserva para tablas que están en uso; en una tabla nueva o en una ventana de mantenimiento, el rename directo alcanza.",
    respuestaEn:
      "Not with a direct RENAME. During a rolling deploy, instances of the old and new version coexist, and the migration also runs before the code: if I rename `name` to `full_name`, the old version starts failing as soon as the migration runs. The technique is EXPAND / CONTRACT (or parallel change), which splits the change into steps where each schema state is compatible with both app versions that may be running. Expand: add `full_name` as nullable. Deploy a version that writes to both columns and still reads the old one. Backfill: copy existing data in batches. Deploy a version that reads and writes only the new one. Contract: drop `name` when no version uses it. A detail people forget: if the old column was NOT NULL, you must drop that constraint before deploying the version that stops writing it. It's slower (several deploys instead of one), so it's reserved for tables in use; for a new table or during a maintenance window, a direct rename is enough.",
    tradeoffs:
      "Expand/contract cambia un deploy riesgoso por varios deploys seguros; el costo es tiempo y código de transición que hay que acordarse de limpiar.",
  },
  {
    nivel: 2,
    pregunta: "Una migración rompió algo en producción. ¿Hacés rollback?",
    respuestaEs:
      "Depende de qué hizo. Hay dos filosofías. DOWN MIGRATIONS: cada migración tiene su inversa (Knex, TypeORM y Rails las usan); suenan bien, pero casi nunca se prueban y muchas no se pueden invertir de verdad: un DROP COLUMN no devuelve los datos. ROLL FORWARD: arreglar con una migración nueva que corrige el problema; es lo que propone Prisma, que no genera migraciones down (se puede armar el SQL inverso con `prisma migrate diff` si hace falta). En la práctica, lo que más protege es que las migraciones sean compatibles hacia atrás: si el schema nuevo funciona con la versión vieja del código, revertir el deploy de la app alcanza y la migración puede quedarse. Por eso expand/contract también es una estrategia de rollback. Otra ventaja de Postgres: el DDL es transaccional, así que si una migración falla a mitad de camino se revierte entera; en MySQL no, y puede quedar aplicada a medias. Y si una migración de Prisma falla en producción, queda marcada como fallida y hay que resolverla a mano con `prisma migrate resolve` después de corregir el estado.",
    respuestaEn:
      "It depends on what it did. There are two philosophies. DOWN MIGRATIONS: each migration has its inverse (Knex, TypeORM and Rails use them); they sound good, but they're almost never tested and many can't truly be reversed: a DROP COLUMN doesn't bring the data back. ROLL FORWARD: fix it with a new migration that corrects the problem; that's Prisma's approach, which doesn't generate down migrations (you can build the inverse SQL with `prisma migrate diff` if needed). In practice, what protects you most is backward-compatible migrations: if the new schema works with the old code version, rolling back the app deploy is enough and the migration can stay. That's why expand/contract is also a rollback strategy. Another Postgres advantage: DDL is transactional, so if a migration fails midway it's fully rolled back; in MySQL it isn't, and it can be left half-applied. And if a Prisma migration fails in production, it's marked as failed and must be resolved by hand with `prisma migrate resolve` after fixing the state.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué migraciones pueden bloquear una tabla grande en Postgres y cómo las evitás?",
    respuestaEs:
      "La mayoría de los ALTER TABLE toman un lock ACCESS EXCLUSIVE, que bloquea hasta las lecturas mientras dura. Si la operación es instantánea (solo cambia el catálogo) no importa; el problema son las que reescriben o recorren la tabla. Casos típicos. CAMBIAR EL TIPO de una columna (int a bigint) reescribe la tabla entera. ADD COLUMN con DEFAULT es instantáneo desde Postgres 11 si el default es constante, pero reescribe si es volátil (`DEFAULT gen_random_uuid()`). SET NOT NULL recorre toda la tabla para verificar; se evita agregando antes un `CHECK (col IS NOT NULL) NOT VALID`, validándolo aparte, y desde Postgres 12 SET NOT NULL usa ese check y no recorre. FOREIGN KEYS y CHECKs nuevos verifican todas las filas; con `NOT VALID` se agregan al instante y `VALIDATE CONSTRAINT` después verifica con un lock más liviano que no bloquea escrituras. CREATE INDEX sin CONCURRENTLY bloquea las escrituras; con CONCURRENTLY no, pero no puede correr dentro de una transacción. Y una trampa menos conocida: aunque el ALTER sea instantáneo, si espera un lock detrás de una consulta larga, todas las consultas que llegan después quedan en cola detrás de él. Por eso las migraciones setean `lock_timeout` (unos segundos) y se reintentan si fallan.",
    respuestaEn:
      "Most ALTER TABLEs take an ACCESS EXCLUSIVE lock, which blocks even reads while it lasts. If the operation is instant (catalog-only) it doesn't matter; the problem is those that rewrite or scan the table. Typical cases. CHANGING a column's TYPE (int to bigint) rewrites the whole table. ADD COLUMN with DEFAULT is instant since Postgres 11 if the default is constant, but rewrites if it's volatile (`DEFAULT gen_random_uuid()`). SET NOT NULL scans the whole table to verify; you avoid it by first adding a `CHECK (col IS NOT NULL) NOT VALID`, validating it separately, and since Postgres 12 SET NOT NULL uses that check and skips the scan. New FOREIGN KEYs and CHECKs verify every row; with `NOT VALID` they're added instantly and `VALIDATE CONSTRAINT` later verifies with a lighter lock that doesn't block writes. CREATE INDEX without CONCURRENTLY blocks writes; with CONCURRENTLY it doesn't, but it can't run inside a transaction. And a lesser-known trap: even if the ALTER is instant, if it waits for a lock behind a long query, every query arriving afterwards queues behind it. That's why migrations set `lock_timeout` (a few seconds) and are retried if they fail.",
    codigo: `SET lock_timeout = '5s';

-- FK sin recorrer la tabla bajo lock exclusivo
ALTER TABLE pedidos ADD CONSTRAINT pedidos_cliente_fk
  FOREIGN KEY (cliente_id) REFERENCES clientes (id) NOT VALID;
ALTER TABLE pedidos VALIDATE CONSTRAINT pedidos_cliente_fk;

-- NOT NULL sin scan bajo lock (Postgres 12+)
ALTER TABLE pedidos ADD CONSTRAINT total_nn CHECK (total IS NOT NULL) NOT VALID;
ALTER TABLE pedidos VALIDATE CONSTRAINT total_nn;
ALTER TABLE pedidos ALTER COLUMN total SET NOT NULL;
ALTER TABLE pedidos DROP CONSTRAINT total_nn;`,
  },
  {
    nivel: 3,
    pregunta: "¿Cómo hacés un backfill de millones de filas?",
    respuestaEs:
      "Separado de la migración de schema y por lotes. Un `UPDATE usuarios SET nombre_completo = nombre` sobre 50 millones de filas es una sola transacción enorme: bloquea todas esas filas hasta terminar, genera una ola de WAL que atrasa las réplicas, deja millones de versiones muertas de golpe, y si falla al 90% se revierte todo. En cambio, un script o job que procesa lotes de unos miles de filas, cada lote en su propia transacción, recorriendo por clave primaria (`WHERE id > $ultimo ORDER BY id LIMIT 5000`) en vez de OFFSET. Tiene que ser IDEMPOTENTE, para poder cortarlo y retomarlo (`AND nombre_completo IS NULL`), y conviene que haga pausas entre lotes y se pueda frenar si sube la carga o el lag de las réplicas. Mientras corre, la aplicación ya tiene que estar escribiendo los datos nuevos en los dos lugares (el paso de doble escritura de expand/contract), así que las filas que cambian durante el backfill no quedan desactualizadas. Por último, se verifica que no queden filas sin migrar antes del paso de contract.",
    respuestaEn:
      "Separate from the schema migration and in batches. An `UPDATE users SET full_name = name` over 50 million rows is one huge transaction: it locks all those rows until it finishes, produces a wave of WAL that makes replicas lag, leaves millions of dead versions at once, and if it fails at 90% everything rolls back. Instead, a script or job processing batches of a few thousand rows, each batch in its own transaction, walking by primary key (`WHERE id > $last ORDER BY id LIMIT 5000`) instead of OFFSET. It must be IDEMPOTENT, so it can be stopped and resumed (`AND full_name IS NULL`), and it should pause between batches and be throttleable if load or replica lag grows. While it runs, the application must already be writing new data to both places (the dual-write step of expand/contract), so rows changing during the backfill don't end up stale. Finally, verify no rows remain unmigrated before the contract step.",
  },
];
