import type { PreguntaEntrevista } from "../types";

export const entrevistaSqlVsNosql: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Cuándo elegirías una base relacional y cuándo una NoSQL?",
    respuestaEs:
      "Por defecto, una relacional como Postgres: sirve para la gran mayoría de las aplicaciones, garantiza consistencia con transacciones ACID y constraints, permite combinar los datos de cualquier forma con SQL (reportes, consultas que nadie anticipó), y hoy también maneja documentos JSON con JSONB, búsqueda de texto y más. Una NoSQL se elige por una necesidad concreta que la relacional resuelve peor: un modelo de documentos (MongoDB) cuando los datos son jerárquicos, cambian de forma a menudo y se leen casi siempre juntos; clave-valor (Redis, DynamoDB) para accesos ultra rápidos por clave, caches o sesiones; columnar ancha (Cassandra) para escrituras masivas distribuidas en varias regiones; grafos (Neo4j) cuando lo central son las relaciones y recorrerlas. 'NoSQL escala y SQL no' es un mito a esta altura: Postgres escala muy lejos antes de que haga falta otra cosa. Lo importante es elegir por los patrones de acceso y las garantías que necesitás.",
    respuestaEn:
      "By default, a relational database like Postgres: it fits the vast majority of applications, guarantees consistency with ACID transactions and constraints, lets you combine data any way with SQL (reports, queries nobody anticipated), and today also handles JSON documents with JSONB, text search and more. A NoSQL database is chosen for a specific need the relational one handles worse: a document model (MongoDB) when data is hierarchical, changes shape often and is almost always read together; key-value (Redis, DynamoDB) for ultra-fast key access, caches or sessions; wide-column (Cassandra) for massive writes distributed across regions; graphs (Neo4j) when relationships and traversing them are central. 'NoSQL scales and SQL doesn't' is a myth by now: Postgres scales very far before you need something else. What matters is choosing by access patterns and the guarantees you need.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué significa que MongoDB sea 'schemaless'? ¿No tiene esquema?",
    respuestaEs:
      "Significa que la BASE no impone un esquema: dos documentos de la misma colección pueden tener campos distintos. Pero el esquema existe igual, solo que vive en el código de la aplicación, que asume ciertos campos con ciertos tipos al leer. Eso da flexibilidad para iterar rápido o guardar datos de forma variable (atributos que dependen del tipo de producto), pero traslada a la aplicación la responsabilidad de validar y de lidiar con documentos viejos que tienen otra forma: en vez de una migración de la base, aparece código que contempla varias versiones del documento. Por eso en la práctica se suele volver a imponer un esquema: con validación de JSON Schema en la colección, o con un ODM como Mongoose, o con Zod en la aplicación. Una forma más precisa de decirlo es 'schema-on-read' (se interpreta al leer) frente al 'schema-on-write' de una relacional (se valida al escribir).",
    respuestaEn:
      "It means the DATABASE doesn't enforce a schema: two documents in the same collection can have different fields. But the schema exists anyway, it just lives in application code, which assumes certain fields of certain types when reading. That gives flexibility to iterate fast or store variable data (attributes depending on product type), but shifts to the application the responsibility of validating and dealing with old documents of a different shape: instead of a database migration, you get code handling several document versions. So in practice a schema is usually reimposed: with JSON Schema validation on the collection, an ODM like Mongoose, or Zod in the app. A more precise way to say it is 'schema-on-read' (interpreted when reading) versus a relational database's 'schema-on-write' (validated when writing).",
  },
  {
    nivel: 2,
    pregunta: "En una base de documentos, ¿cuándo embebés datos y cuándo referenciás?",
    respuestaEs:
      "Se embebe lo que se lee junto y pertenece al documento padre: los ítems de un pedido, las direcciones de un cliente, los comentarios de un post si son pocos y acotados. Una sola lectura trae todo y las escrituras sobre ese conjunto son atómicas. Se referencia (guardando el id, como una foreign key) cuando el dato tiene vida propia y se comparte entre muchos documentos (el producto, el cliente), cuando cambia seguido (actualizar todas las copias embebidas es caro), o cuando la lista puede crecer sin límite (los millones de eventos de un usuario: un documento tiene un tamaño máximo, 16 MB en MongoDB, y documentos enormes son lentos de leer y escribir). Un patrón intermedio muy usado es embeber una COPIA parcial de lo que se muestra (el nombre del cliente en el pedido) sabiendo que es una foto del momento, lo cual a veces es justo lo que se quiere: el precio con el que se compró no debería cambiar si después cambia el precio del producto. La pregunta guía siempre es qué consultas vas a hacer.",
    respuestaEn:
      "You embed what's read together and belongs to the parent document: an order's items, a customer's addresses, a post's comments if few and bounded. A single read brings everything and writes on that set are atomic. You reference (storing the id, like a foreign key) when the data has its own life and is shared across many documents (the product, the customer), when it changes often (updating every embedded copy is expensive), or when the list can grow without bound (a user's millions of events: a document has a maximum size, 16 MB in MongoDB, and huge documents are slow to read and write). A widely used middle pattern is embedding a partial COPY of what's displayed (the customer's name in the order) knowing it's a snapshot of that moment, which sometimes is exactly what you want: the price paid shouldn't change if the product's price changes later. The guiding question is always which queries you'll run.",
    tradeoffs:
      "Embeber optimiza lecturas y atomicidad a costa de duplicación y actualizaciones más caras; referenciar evita duplicar a costa de más lecturas o de $lookup, que es menos eficiente que un JOIN relacional.",
  },
  {
    nivel: 2,
    pregunta: "¿Podés usar Postgres como base de documentos?",
    respuestaEs:
      "En buena medida sí, con el tipo JSONB: guarda JSON en un formato binario indexable, permite consultar campos internos (`datos->>'color'`), operadores de contención (`@>`), e índices GIN sobre el documento entero o índices sobre expresiones para campos puntuales. Eso permite un modelo híbrido muy práctico: columnas normales con constraints para lo estructurado y crítico (ids, precios, estados, fechas, relaciones) y una columna JSONB para lo variable (atributos que dependen del tipo de producto, configuraciones, metadata de integraciones), todo en la misma base y con transacciones. Es muchas veces mejor opción que sumar una segunda base solo para los datos flexibles. Los límites: las consultas sobre JSONB son menos eficientes y menos expresivas que sobre columnas tipadas, las estadísticas del planner sobre su contenido son pobres, los constraints dentro del JSON son limitados, y actualizar un campo reescribe el valor entero. La regla: si un campo se filtra, se ordena o se relaciona seguido, merece ser una columna.",
    respuestaEn:
      "Largely yes, with the JSONB type: it stores JSON in an indexable binary format, allows querying inner fields (`data->>'color'`), containment operators (`@>`), and GIN indexes on the whole document or expression indexes for specific fields. That enables a very practical hybrid model: regular columns with constraints for structured, critical data (ids, prices, statuses, dates, relations) and a JSONB column for variable data (type-dependent product attributes, settings, integration metadata), all in the same database with transactions. It's often a better option than adding a second database just for flexible data. The limits: queries on JSONB are less efficient and expressive than on typed columns, planner statistics about its contents are poor, constraints inside the JSON are limited, and updating a field rewrites the whole value. The rule: if a field is filtered, sorted or related often, it deserves to be a column.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué diferencia hay entre las garantías ACID y el modelo BASE de muchas NoSQL distribuidas?",
    respuestaEs:
      "ACID (atomicidad, consistencia, aislamiento, durabilidad) es el modelo de las bases relacionales: una transacción ocurre entera o no ocurre, deja los datos respetando las reglas, no ve estados intermedios de otras transacciones (según el nivel de aislamiento) y una vez confirmada no se pierde. BASE (basically available, soft state, eventual consistency) describe a muchas bases distribuidas que priorizan disponibilidad y escalado: aceptan escrituras aunque haya particiones de red o réplicas atrasadas, y las réplicas convergen 'eventualmente', así que una lectura puede devolver un dato viejo. Detrás está el teorema CAP: ante una partición de red, un sistema distribuido tiene que elegir entre consistencia y disponibilidad. La realidad es más matizada que la dicotomía: MongoDB soporta transacciones ACID multi-documento, DynamoDB y Cassandra permiten elegir el nivel de consistencia por operación (lecturas fuertes o eventuales, quorum), y bases como CockroachDB o Spanner ofrecen SQL distribuido con consistencia fuerte a costa de latencia. La pregunta útil es qué garantías necesita cada operación del negocio.",
    respuestaEn:
      "ACID (atomicity, consistency, isolation, durability) is the relational model: a transaction happens entirely or not at all, leaves data respecting the rules, doesn't see other transactions' intermediate states (depending on isolation level) and once committed isn't lost. BASE (basically available, soft state, eventual consistency) describes many distributed databases prioritizing availability and scaling: they accept writes despite network partitions or lagging replicas, and replicas converge 'eventually', so a read may return stale data. Behind it is the CAP theorem: during a network partition, a distributed system must choose between consistency and availability. Reality is more nuanced than the dichotomy: MongoDB supports multi-document ACID transactions, DynamoDB and Cassandra let you choose consistency per operation (strong or eventual reads, quorum), and databases like CockroachDB or Spanner offer distributed SQL with strong consistency at a latency cost. The useful question is which guarantees each business operation needs.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo se diseña una tabla en DynamoDB y por qué es tan distinto de SQL?",
    respuestaEs:
      "En DynamoDB se diseña a partir de los PATRONES DE ACCESO, no de las entidades: primero se listan todas las consultas que la aplicación va a hacer ('pedidos de un cliente ordenados por fecha', 'un pedido por id', 'pedidos pendientes') y después se elige la clave de partición y la de ordenamiento, y los índices secundarios, para que cada consulta sea una lectura directa por clave o un rango sobre una partición. No hay JOINs ni consultas ad hoc eficientes: consultar por un atributo que no es clave implica un scan de toda la tabla, carísimo. Es común el diseño de TABLA ÚNICA, donde entidades distintas conviven en la misma tabla con claves compuestas (`PK = CLIENTE#7`, `SK = PEDIDO#2026-09-20#1042`) para traer un cliente y sus pedidos en una sola consulta. A cambio, la latencia es predecible y de un dígito de milisegundos a cualquier escala, sin administrar servidores. El costo es la rigidez: un patrón de acceso nuevo puede requerir un índice nuevo o reestructurar datos, mientras que en SQL se escribe una consulta nueva y listo.",
    respuestaEn:
      "In DynamoDB you design from ACCESS PATTERNS, not entities: first list every query the app will make ('a customer's orders sorted by date', 'an order by id', 'pending orders') and then choose the partition and sort keys, and secondary indexes, so each query is a direct key read or a range over a partition. There are no JOINs or efficient ad hoc queries: querying by a non-key attribute means scanning the whole table, very expensive. SINGLE-TABLE design is common, where different entities live in the same table with composite keys (`PK = CUSTOMER#7`, `SK = ORDER#2026-09-20#1042`) to fetch a customer and their orders in a single query. In exchange, latency is predictable single-digit milliseconds at any scale, with no servers to manage. The cost is rigidity: a new access pattern may require a new index or restructuring data, while in SQL you just write a new query.",
  },
];
