import type { PreguntaEntrevista } from "../types";

export const entrevistaEvaluacionOutputIa: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Cómo revisás código generado por un asistente de IA?",
    respuestaEs:
      "Con el mismo estándar que un PR de un colega, más atención a los modos de falla propios de este tipo de código. El punto de partida es que yo soy responsable de lo que se mergea, no el modelo, así que no apruebo nada que no entiendo línea por línea. Primero verifico que resuelva lo que se pidió, y solo eso: es común que haga más de lo pedido (refactors no solicitados, archivos tocados de más) o que resuelva una versión parecida del problema. Después reviso lo que el código generado suele hacer mal: casos borde (listas vacías, nulos, parámetros opcionales, concurrencia), seguridad (de dónde salen los datos y quién está autorizado a verlos, consultas armadas con strings, secretos), manejo de errores (que no los trague ni los esconda), y consistencia con el proyecto (convenciones, patrones existentes, dependencias nuevas). Después lo corro: typecheck, linter, tests, y una prueba manual del flujo. Y si algo no me cierra, pido que me explique esa parte o lo reescribo; un código que 'parece funcionar' pero no entiendo es deuda que va a cobrarse en producción.",
    respuestaEn:
      "With the same standard as a colleague's PR, plus attention to this kind of code's specific failure modes. The starting point is that I'm responsible for what gets merged, not the model, so I don't approve anything I don't understand line by line. First I check it solves what was asked, and only that: it often does more than requested (unrequested refactors, extra files touched) or solves a similar version of the problem. Then I review what generated code tends to get wrong: edge cases (empty lists, nulls, optional parameters, concurrency), security (where data comes from and who's authorized to see it, string-built queries, secrets), error handling (not swallowing or hiding errors), and consistency with the project (conventions, existing patterns, new dependencies). Then I run it: typecheck, linter, tests, and a manual test of the flow. And if something doesn't add up, I ask it to explain that part or rewrite it; code that 'seems to work' but I don't understand is debt that will come due in production.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué errores son típicos del código generado por IA?",
    respuestaEs:
      "Errores que tienen en común que el código se ve plausible. APIS INVENTADAS: métodos, opciones de configuración o parámetros que no existen en la versión de la librería que usás, o que existían en otra versión; compila en la cabeza de quien lee rápido, pero no en la realidad. DEPENDENCIAS INNECESARIAS O INEXISTENTES: una librería para algo que ya resuelve el proyecto o la plataforma, o directamente un paquete con un nombre que no existe (lo que abre la puerta a que alguien publique un paquete malicioso con ese nombre). CASOS BORDE ignorados: funciona con el ejemplo típico y falla con la lista vacía o el parámetro ausente. SEGURIDAD: consultas armadas con interpolación, datos tomados del request sin verificar autorización, validaciones que están en el cliente pero no en el servidor. TESTS QUE NO PRUEBAN NADA: tests que verifican el mock que ellos mismos configuraron, o que se ajustaron para pasar en vez de detectar el bug. Y EXCESO DE ALCANCE: cambios de formato, renombres o refactors que nadie pidió mezclados con el cambio real, que agrandan el diff y esconden lo importante.",
    respuestaEn:
      "Errors whose common trait is that the code looks plausible. INVENTED APIS: methods, config options or parameters that don't exist in your library version, or existed in another one; it compiles in the head of a quick reader, but not in reality. UNNECESSARY OR NONEXISTENT DEPENDENCIES: a library for something the project or platform already handles, or outright a package name that doesn't exist (opening the door for someone to publish a malicious package under that name). Ignored EDGE CASES: works with the typical example and fails on the empty list or missing parameter. SECURITY: interpolated queries, data taken from the request without checking authorization, validations on the client but not the server. TESTS THAT TEST NOTHING: tests verifying the mock they themselves set up, or adjusted to pass instead of catching the bug. And SCOPE CREEP: unrequested formatting changes, renames or refactors mixed with the real change, enlarging the diff and hiding what matters.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo verificás que el código generado es correcto, más allá de leerlo?",
    respuestaEs:
      "Haciendo que la verificación no dependa de lo que genera el mismo modelo. TESTS COMO ESPECIFICACIÓN: para lógica importante, escribo o reviso primero los tests que definen el comportamiento esperado (incluidos los casos borde) y después dejo que el asistente implemente hasta que pasen. Si el mismo asistente escribe el código y los tests juntos, pueden compartir el mismo malentendido y validarse entre sí. LEER LOS TESTS CON DESCONFIANZA: un test que mockea todo y verifica que se llamó al mock no prueba el comportamiento; un test que se modificó para que pase es una alarma. HERRAMIENTAS AUTOMÁTICAS: typecheck estricto, linter, análisis de seguridad y de dependencias en el CI, que atrapan APIs inexistentes, tipos incorrectos y paquetes sospechosos sin depender de la atención de nadie. DIFFS CHICOS: pedir cambios acotados, porque un diff de 40 líneas se revisa bien y uno de 800 se aprueba por cansancio. Y EJECUTARLO de verdad en el flujo real, con datos parecidos a los de producción, no solo con el ejemplo feliz.",
    respuestaEn:
      "By making verification independent of what the same model generates. TESTS AS SPECIFICATION: for important logic, I write or review first the tests defining the expected behavior (including edge cases) and then let the assistant implement until they pass. If the same assistant writes code and tests together, they can share the same misunderstanding and validate each other. READING TESTS SKEPTICALLY: a test that mocks everything and checks the mock was called doesn't test behavior; a test modified to pass is a red flag. AUTOMATED TOOLS: strict typecheck, linter, security and dependency analysis in CI, catching nonexistent APIs, wrong types and suspicious packages without relying on anyone's attention. SMALL DIFFS: ask for scoped changes, because a 40-line diff gets reviewed well and an 800-line one gets approved out of fatigue. And actually RUNNING it in the real flow, with production-like data, not just the happy example.",
    tradeoffs:
      "Escribir los tests primero y pedir diffs chicos es más lento que aceptar un cambio grande generado de una vez, a cambio de poder confiar en lo que se mergea.",
  },
  {
    nivel: 2,
    pregunta: "¿Sirve usar IA para hacer code review?",
    respuestaEs:
      "Sí, como una revisión adicional, no como reemplazo de la humana. Es buena para lo mecánico y lo exhaustivo: detectar patrones riesgosos (consultas sin parametrizar, errores sin manejar, recursos que no se cierran), inconsistencias con el resto del código, casos borde no contemplados, nombres confusos, y para resumir un PR grande antes de leerlo. No se cansa en la línea 700 y revisa siempre con la misma atención. Sus límites: ve el diff y parte del contexto, pero no conoce la intención del producto ni las decisiones que se tomaron fuera del código; genera falsos positivos (comentarios correctos en abstracto pero irrelevantes en ese caso) que hay que filtrar; y puede aprobar con confianza algo sutilmente mal. Por eso lo útil es usarla como primera pasada que libera a la revisión humana para enfocarse en lo que requiere criterio: si el diseño es el correcto, si resuelve el problema real, si encaja con la dirección del sistema. La responsabilidad del merge sigue siendo de una persona, y conviene medir si los comentarios automáticos se aceptan o se ignoran, para ajustar o descartar la herramienta.",
    respuestaEn:
      "Yes, as an additional review, not a replacement for human review. It's good at the mechanical and exhaustive: spotting risky patterns (unparameterized queries, unhandled errors, unclosed resources), inconsistencies with the rest of the code, unconsidered edge cases, confusing names, and summarizing a large PR before reading it. It doesn't tire at line 700 and always reviews with the same attention. Its limits: it sees the diff and part of the context, but doesn't know the product intent or decisions made outside the code; it produces false positives (comments correct in the abstract but irrelevant in that case) that must be filtered; and it can confidently approve something subtly wrong. So it's useful as a first pass that frees human review to focus on what needs judgment: whether the design is right, whether it solves the real problem, whether it fits the system's direction. Responsibility for the merge stays with a person, and it's worth measuring whether automated comments are accepted or ignored, to tune or drop the tool.",
  },
  {
    nivel: 3,
    pregunta: "Si tu producto usa un LLM, ¿cómo evaluás la calidad de sus respuestas?",
    respuestaEs:
      "Como cualquier comportamiento que tiene que mantenerse, pero con salidas que no son deterministas ni tienen una única respuesta correcta. La base es un CONJUNTO DE EVALUACIÓN (evals): casos representativos con el input y lo que se espera, incluidos casos difíciles, adversariales y los que ya fallaron en producción. Para cada caso se define cómo se califica: comprobaciones exactas cuando se puede (el JSON es válido, el campo tiene el valor correcto, la respuesta cita solo documentos existentes), rúbricas cuando no (¿responde la pregunta?, ¿inventa datos?, ¿respeta el tono?), y LLM-as-judge, otro modelo que califica con la rúbrica, útil a escala pero que hay que calibrar contra calificaciones humanas porque tiene sus propios sesgos. El eval se corre ante cada cambio de prompt, de modelo o de la lógica de recuperación de contexto, como un test de regresión: un cambio que mejora un caso puede empeorar otros diez. En producción se suma observabilidad: registrar inputs y outputs (cuidando la privacidad), feedback de los usuarios, y muestreo para revisión humana. Y los casos que fallan en producción se agregan al eval, así el conjunto crece con los problemas reales.",
    respuestaEn:
      "Like any behavior that must be maintained, but with outputs that aren't deterministic and have no single correct answer. The foundation is an EVALUATION SET (evals): representative cases with the input and what's expected, including hard, adversarial cases and those that already failed in production. For each case, define how it's scored: exact checks when possible (valid JSON, correct field value, the answer cites only existing documents), rubrics when not (does it answer the question?, does it make things up?, does it keep the tone?), and LLM-as-judge, another model scoring with the rubric, useful at scale but needing calibration against human ratings since it has its own biases. The eval runs on every prompt, model or context-retrieval change, like a regression test: a change improving one case can worsen ten others. In production, add observability: logging inputs and outputs (minding privacy), user feedback, and sampling for human review. And cases failing in production are added to the eval, so the set grows with real problems.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué cambia en el proceso del equipo cuando gran parte del código se genera con IA?",
    respuestaEs:
      "Se invierte el costo: generar código se vuelve barato y revisarlo pasa a ser el cuello de botella, así que el proceso tiene que proteger la revisión. PRs CHICOS y enfocados, con un límite práctico de tamaño, porque la tentación es generar mucho de una vez y la calidad de la revisión cae con el tamaño. RESPONSABILIDAD CLARA: quien abre el PR es el autor y responde por cada línea, aunque la haya escrito un asistente; 'lo generó la IA' no es una explicación aceptable de un bug. VERIFICACIÓN AUTOMÁTICA fuerte en el CI (tipos estrictos, tests, análisis de seguridad, control de dependencias nuevas), porque es la red que no se cansa. ATENCIÓN A LA CADENA DE SUMINISTRO: toda dependencia sugerida se verifica, que exista, que sea la correcta y que se mantenga, porque los nombres de paquetes inventados son un vector de ataque conocido. CONOCIMIENTO DEL SISTEMA: si nadie entiende en profundidad partes del código porque 'las escribió la IA', el equipo pierde la capacidad de depurarlas bajo presión; conviene que las partes críticas tengan dueños que las conozcan. Y MÉTRICAS: tasa de defectos, reverts, tiempo de revisión y retrabajo, para saber si el uso de IA está acelerando al equipo o solo moviendo el trabajo a la revisión y al soporte.",
    respuestaEn:
      "The cost flips: generating code becomes cheap and reviewing it becomes the bottleneck, so the process must protect review. SMALL, focused PRs with a practical size limit, because the temptation is to generate a lot at once and review quality drops with size. CLEAR RESPONSIBILITY: whoever opens the PR is the author and answers for every line, even if an assistant wrote it; 'the AI generated it' isn't an acceptable explanation for a bug. Strong AUTOMATED VERIFICATION in CI (strict types, tests, security analysis, control over new dependencies), because it's the net that doesn't tire. SUPPLY CHAIN ATTENTION: every suggested dependency is verified, that it exists, is the right one and is maintained, since invented package names are a known attack vector. SYSTEM KNOWLEDGE: if nobody deeply understands parts of the code because 'the AI wrote them', the team loses the ability to debug them under pressure; critical parts should have owners who know them. And METRICS: defect rate, reverts, review time and rework, to know whether AI use is speeding up the team or just shifting work to review and support.",
  },
];
