import type { PreguntaEntrevista } from "../types";

export const entrevistaMcpServers: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es MCP y qué problema resuelve?",
    respuestaEs:
      "MCP (Model Context Protocol) es un protocolo abierto para conectar aplicaciones de IA con herramientas y fuentes de datos externas: una base de datos, GitHub, el sistema de archivos, un servicio interno. El problema que resuelve es el de N por M integraciones: sin un estándar, cada aplicación de IA (un asistente de código, un chat de escritorio, un IDE) tenía que integrar a mano cada servicio, cada una a su manera. Con MCP, un servicio se expone una vez como servidor MCP y lo puede usar cualquier aplicación compatible, y una aplicación compatible puede usar cualquier servidor. La arquitectura tiene tres roles. El HOST es la aplicación que usa la persona y que contiene al modelo. Dentro del host, un CLIENTE mantiene la conexión con cada servidor. Y el SERVIDOR expone capacidades: principalmente tools (acciones que el modelo puede invocar), resources (datos que la aplicación agrega como contexto) y prompts (plantillas que el usuario elige). Los mensajes siguen JSON-RPC 2.0. En la práctica, es lo que permite que un asistente de código consulte tu base, lea tus issues o busque en tu documentación interna sin que alguien tenga que construir esa integración para cada herramienta.",
    respuestaEn:
      "MCP (Model Context Protocol) is an open protocol for connecting AI applications to external tools and data sources: a database, GitHub, the filesystem, an internal service. The problem it solves is N-by-M integrations: without a standard, every AI application (a coding assistant, a desktop chat, an IDE) had to integrate each service by hand, each its own way. With MCP, a service is exposed once as an MCP server and any compatible application can use it, and a compatible application can use any server. The architecture has three roles. The HOST is the application the person uses, which contains the model. Inside the host, a CLIENT maintains the connection to each server. And the SERVER exposes capabilities: mainly tools (actions the model can invoke), resources (data the application adds as context) and prompts (templates the user picks). Messages follow JSON-RPC 2.0. In practice, it's what lets a coding assistant query your database, read your issues or search your internal docs without someone building that integration for each tool.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué diferencia hay entre tools, resources y prompts en MCP?",
    respuestaEs:
      "La diferencia es quién decide usarlos, y la especificación lo define así. Las TOOLS las controla el MODELO: son funciones con un nombre, una descripción y un schema de parámetros, y el modelo decide cuándo llamarlas según la conversación (consultar la base, crear un issue, escribir un archivo). Por eso su descripción importa tanto: es lo que el modelo lee para decidir. Los RESOURCES los controla la APLICACIÓN: son datos identificados por una URI (el contenido de un archivo, un esquema de base, un historial de commits) que el host agrega al contexto según su propia lógica o la elección del usuario, no por decisión del modelo. Los PROMPTS los controla el USUARIO: son plantillas predefinidas que la persona invoca explícitamente, por ejemplo como un comando de barra (`/revisar-pr`), y que el servidor completa con sus parámetros. Esta separación tiene consecuencias de diseño y de seguridad: una acción con efectos va como tool, con la aprobación del usuario cuando corresponde; un dato que siempre conviene tener a mano va como resource; un flujo de trabajo repetido que el usuario dispara va como prompt.",
    respuestaEn:
      "The difference is who decides to use them, and the specification defines it this way. TOOLS are MODEL-controlled: functions with a name, a description and a parameter schema, and the model decides when to call them based on the conversation (query the database, create an issue, write a file). That's why their description matters so much: it's what the model reads to decide. RESOURCES are APPLICATION-controlled: data identified by a URI (a file's contents, a database schema, a commit history) that the host adds to context by its own logic or the user's choice, not by the model's decision. PROMPTS are USER-controlled: predefined templates the person invokes explicitly, for example as a slash command (`/review-pr`), which the server fills in with its parameters. This separation has design and security consequences: an action with effects goes as a tool, with user approval when appropriate; data always worth having at hand goes as a resource; a repeated workflow the user triggers goes as a prompt.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué transportes tiene MCP y cómo se maneja la autenticación en cada uno?",
    respuestaEs:
      "La especificación define dos transportes estándar. STDIO: el cliente lanza el servidor como un subproceso local y se comunican por la entrada y salida estándar, con un mensaje JSON-RPC por línea. Es lo habitual para servidores que corren en la máquina del desarrollador (acceso al sistema de archivos, a git, a una base local). Como el servidor es un proceso propio, no usa el flujo de autorización del protocolo: toma las credenciales del entorno, por ejemplo de variables de entorno configuradas al lanzarlo. STREAMABLE HTTP: el servidor es un servicio independiente con un único endpoint HTTP, que recibe cada mensaje como un POST y responde con un JSON o con un stream de eventos; reemplazó al transporte anterior basado en HTTP con SSE. Es el que se usa para servidores remotos y compartidos. Para HTTP, la especificación define un marco de autorización basado en OAuth 2.1, donde el servidor MCP actúa como un recurso protegido y el cliente obtiene un token para él. Un detalle de versiones que vale conocer: las primeras revisiones del protocolo establecían una sesión por conexión con un handshake inicial, y la revisión de 2026 lo volvió stateless, con los metadatos del protocolo en cada request; conviene revisar qué versión soporta cada herramienta.",
    respuestaEn:
      "The specification defines two standard transports. STDIO: the client launches the server as a local subprocess and they communicate over standard input and output, with one JSON-RPC message per line. It's the usual choice for servers running on the developer's machine (filesystem, git, a local database). Since the server is its own process, it doesn't use the protocol's authorization flow: it takes credentials from the environment, for example environment variables set when launching it. STREAMABLE HTTP: the server is an independent service with a single HTTP endpoint, receiving each message as a POST and replying with JSON or an event stream; it replaced the earlier HTTP-with-SSE transport. It's used for remote, shared servers. For HTTP, the specification defines an authorization framework based on OAuth 2.1, where the MCP server acts as a protected resource and the client obtains a token for it. A versioning detail worth knowing: early protocol revisions established a per-connection session with an initial handshake, and the 2026 revision made it stateless, with protocol metadata in every request; check which version each tool supports.",
    tradeoffs:
      "stdio es simple y queda aislado en la máquina local, pero cada usuario lo instala y ejecuta con sus propios permisos; HTTP centraliza el servidor y su control de acceso a cambio de operarlo y protegerlo como cualquier API.",
  },
  {
    nivel: 2,
    pregunta: "¿Cuándo conviene un servidor MCP en vez de llamar una API directamente o usar function calling?",
    respuestaEs:
      "Depende de quién consume la integración. Si estás construyendo UNA aplicación propia que usa un LLM y necesita llamar a tu API, el function calling de la API del modelo alcanza: definís las funciones en tu código y las ejecutás vos, sin protocolo intermedio. MCP aporta cuando la misma capacidad tiene que estar disponible para VARIAS aplicaciones de IA, o para herramientas que no controlás: exponer la base de documentación interna, el sistema de tickets o los datos de la empresa a los asistentes de código, chats y agentes que usa el equipo, sin reintegrar en cada uno. También cuando querés reutilizar servidores que ya existen (hay servidores para GitHub, bases de datos, navegadores, servicios cloud) en vez de escribir la integración. El costo es una pieza más para operar y asegurar, y una capa de abstracción que agrega latencia y otra superficie de ataque. Por eso, para un flujo interno de una sola aplicación, llamar la API directamente suele ser más simple; MCP rinde cuando la integración es un producto compartido entre varias herramientas o equipos.",
    respuestaEn:
      "It depends on who consumes the integration. If you're building ONE application of your own that uses an LLM and needs to call your API, the model API's function calling is enough: you define the functions in your code and run them yourself, with no intermediate protocol. MCP helps when the same capability must be available to SEVERAL AI applications, or to tools you don't control: exposing the internal docs, the ticketing system or company data to the coding assistants, chats and agents the team uses, without reintegrating in each. Also when you want to reuse existing servers (there are servers for GitHub, databases, browsers, cloud services) instead of writing the integration. The cost is one more piece to operate and secure, and an abstraction layer adding latency and another attack surface. So for a single application's internal flow, calling the API directly is usually simpler; MCP pays off when the integration is a product shared across several tools or teams.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué riesgos de seguridad trae conectar servidores MCP y cómo los mitigás?",
    respuestaEs:
      "Un servidor MCP le da al modelo capacidad de actuar, así que hereda los riesgos de ejecutar código y de delegar credenciales. SERVIDORES LOCALES: un servidor stdio es un programa que corre con los permisos del usuario; un servidor malicioso, o un comando de instalación alterado, puede leer claves SSH o archivos sensibles. La especificación pide que el cliente muestre el comando exacto y pida consentimiento, y recomienda sandboxing; del lado del equipo, fijar versiones en vez de instalar siempre la última y usar solo servidores de fuentes confiables. PROMPT INJECTION: lo que devuelve una tool (un archivo, un issue, una página web) puede contener instrucciones escritas por un tercero; el modelo tiene que tratarlo como datos, y como eso no es infalible, se agregan capas: aprobación humana para acciones con efectos y permisos mínimos para cada servidor. PERMISOS: aplicar mínimo privilegio, con credenciales de solo lectura cuando alcanza y scopes acotados, que suben solo cuando hace falta. Y en servidores remotos, dos antipatrones que la especificación nombra: el TOKEN PASSTHROUGH, aceptar tokens que no fueron emitidos para el servidor y reenviarlos a otra API (está prohibido), y el CONFUSED DEPUTY, cuando un servidor que actúa como proxy hacia una API de terceros permite obtener acceso sin el consentimiento del usuario.",
    respuestaEn:
      "An MCP server gives the model the ability to act, so it inherits the risks of running code and delegating credentials. LOCAL SERVERS: a stdio server is a program running with the user's permissions; a malicious server, or a tampered install command, can read SSH keys or sensitive files. The specification asks clients to show the exact command and request consent, and recommends sandboxing; on the team side, pin versions instead of always installing the latest and only use servers from trusted sources. PROMPT INJECTION: what a tool returns (a file, an issue, a web page) can contain instructions written by a third party; the model must treat it as data, and since that isn't foolproof, layers are added: human approval for actions with effects and minimal permissions per server. PERMISSIONS: apply least privilege, with read-only credentials when enough and narrow scopes that grow only when needed. And for remote servers, two anti-patterns the specification names: TOKEN PASSTHROUGH, accepting tokens not issued for the server and forwarding them to another API (it's forbidden), and the CONFUSED DEPUTY, when a server acting as a proxy to a third-party API allows obtaining access without the user's consent.",
  },
  {
    nivel: 3,
    pregunta: "Si tuvieras que construir un servidor MCP para tu equipo, ¿cómo diseñarías sus tools?",
    respuestaEs:
      "Pensando en que el usuario de la API es un modelo, que decide qué llamar leyendo nombres y descripciones. POCAS TOOLS ORIENTADAS A TAREAS, no un espejo uno a uno de cada endpoint: 'buscar_pedidos_de_cliente' que resuelve el caso completo es mejor que tres llamadas encadenadas que el modelo tiene que coordinar. DESCRIPCIONES CLARAS y schemas precisos: qué hace, cuándo usarla, qué devuelve y qué no hace; parámetros con tipos, valores permitidos y ejemplos. RESULTADOS ACOTADOS: paginación y límites, y respuestas resumidas en vez de volcar diez mil filas, porque todo lo que devuelve la tool ocupa contexto. ERRORES ÚTILES: mensajes que el modelo pueda usar para corregir el siguiente intento ('el estado debe ser uno de: pendiente, pagado, enviado'), en vez de un error genérico. SEPARAR LECTURA DE ESCRITURA: tools de solo lectura por un lado y las que modifican algo por otro, marcadas como tales, así el host puede pedir aprobación solo donde hace falta; y operaciones idempotentes cuando se pueda, porque el modelo puede reintentar. SEGURIDAD Y OPERACIÓN: autenticación por usuario (que cada persona vea solo lo que puede ver), registro de cada llamada para auditoría, límites de uso, y versionado de las tools, porque cambiar una descripción cambia el comportamiento de los asistentes que la usan.",
    respuestaEn:
      "Keeping in mind that the API's user is a model, which decides what to call by reading names and descriptions. FEW TASK-ORIENTED TOOLS, not a one-to-one mirror of every endpoint: 'find_customer_orders' solving the whole case beats three chained calls the model has to coordinate. CLEAR DESCRIPTIONS and precise schemas: what it does, when to use it, what it returns and what it doesn't do; parameters with types, allowed values and examples. BOUNDED RESULTS: pagination and limits, and summarized responses instead of dumping ten thousand rows, because everything a tool returns takes up context. USEFUL ERRORS: messages the model can use to fix the next attempt ('status must be one of: pending, paid, shipped'), instead of a generic error. SEPARATE READS FROM WRITES: read-only tools on one side and those that modify something on the other, marked as such, so the host can ask for approval only where needed; and idempotent operations where possible, since the model may retry. SECURITY AND OPERATIONS: per-user authentication (each person sees only what they're allowed to), logging every call for audit, usage limits, and tool versioning, because changing a description changes the behavior of the assistants using it.",
  },
];
