import type { PreguntaEntrevista } from "../types";

export const entrevistaMetodologiaIa: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Usás IA para programar? ¿Cómo?",
    respuestaEs:
      "Sí, todos los días, y con un criterio bastante definido. La uso sobre todo donde hay patrones claros y verificación rápida: tests para código existente, componentes o endpoints que siguen convenciones del proyecto, refactors mecánicos, scripts, y para entender rápido código que no conozco. En decisiones de diseño la uso como sparring, para contrastar alternativas o buscar casos borde que no consideré, pero la decisión la tomo yo. Mi proceso: antes de pedir código le doy contexto (el stack, las convenciones del proyecto, un archivo de ejemplo), y en tareas grandes le pido primero un plan y lo reviso, porque corregir un plan es mucho más barato que corregir código. Todo lo que genera lo trato como un PR de otra persona: pasa por typecheck, tests y mi revisión línea por línea, y no mergeo nada que no pueda explicar. No le paso secretos ni datos de clientes, y uso las herramientas aprobadas. Un ejemplo concreto: [un caso propio, con qué hizo la IA, qué hiciste vos y qué resultado tuvo]. En resumen: me hace más rápido en lo que ya entiendo, no reemplaza entender.",
    respuestaEn:
      "Yes, every day, with a fairly defined criterion. I mostly use it where there are clear patterns and fast verification: tests for existing code, components or endpoints following project conventions, mechanical refactors, scripts, and to quickly understand unfamiliar code. In design decisions I use it as a sparring partner, to contrast alternatives or find edge cases I missed, but I make the decision. My process: before asking for code I give it context (the stack, project conventions, an example file), and for large tasks I ask for a plan first and review it, because fixing a plan is much cheaper than fixing code. I treat everything it generates like another person's PR: it goes through typecheck, tests and my line-by-line review, and I don't merge anything I can't explain. I don't give it secrets or customer data, and I use approved tools. A concrete example: [your own case, what the AI did, what you did and the outcome]. In short: it makes me faster at what I already understand; it doesn't replace understanding.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué hace que una respuesta sobre tu uso de IA suene senior?",
    respuestaEs:
      "Lo mismo que en cualquier otra pregunta técnica: criterio, proceso y responsabilidad, contados con ejemplos concretos. CRITERIO: saber dónde conviene y dónde no, y por qué; no 'la uso para todo' ni 'no la uso nunca', sino una línea razonada. PROCESO: cómo le das contexto, cómo partís una tarea grande, cómo iterás cuando se equivoca. VERIFICACIÓN: cómo sabés que lo que generó está bien, más allá de que funcionó una vez. RESPONSABILIDAD: el código que mergeás es tuyo, con la misma vara que si lo hubieras escrito vos. Y un EJEMPLO REAL con un resultado medible, que vale más que cualquier generalización. Lo que suena junior es lo contrario: listar herramientas sin decir cómo se usan, porcentajes de código generado como si fueran un logro, 'si funciona lo subo', o hablar de la IA como si supiera más que uno y por eso no hiciera falta revisar. Una frase que conviene evitar: cualquier cosa que suene a delegar el criterio. Lo que un equipo quiere saber es si va a poder confiar en lo que mergeás.",
    respuestaEn:
      "The same as in any technical question: judgment, process and ownership, told with concrete examples. JUDGMENT: knowing where it helps and where it doesn't, and why; not 'I use it for everything' or 'I never use it', but a reasoned line. PROCESS: how you give context, how you split a big task, how you iterate when it's wrong. VERIFICATION: how you know what it generated is right, beyond it working once. OWNERSHIP: the code you merge is yours, held to the same bar as if you'd written it. And a REAL EXAMPLE with a measurable outcome, worth more than any generalization. What sounds junior is the opposite: listing tools without saying how they're used, percentages of generated code as if they were an achievement, 'if it works I ship it', or talking about AI as if it knew more than you so review wasn't needed. A phrase to avoid: anything that sounds like delegating judgment. What a team wants to know is whether they can trust what you merge.",
  },
  {
    nivel: 2,
    pregunta: "Contame una vez que la IA te llevó por mal camino.",
    respuestaEs:
      "Es una de las mejores preguntas para mostrar criterio, así que conviene tener una historia preparada, real, con esta forma: la situación, qué salió mal, cómo te diste cuenta, y qué cambiaste en tu forma de trabajar. Un ejemplo de estructura: 'Estaba integrando un proveedor de pagos y el asistente me generó el manejo de webhooks usando un método de la librería que parecía correcto. Los tests unitarios pasaban porque mockeaban esa librería. En staging, los eventos de reembolso no se procesaban: el método no existía en la versión que usábamos, y el error quedaba tragado por un try/catch que también había generado. Lo detecté porque tenía una alerta por webhooks fallidos. Desde ahí hago tres cosas: verifico contra la documentación de la versión exacta cualquier API que no conozco, reviso con especial cuidado el manejo de errores del código generado, y en integraciones externas escribo al menos un test contra el entorno de pruebas del proveedor, no solo contra mocks.' Lo que se evalúa no es que la IA se haya equivocado, que es esperable, sino que tu proceso lo detectó y que aprendiste algo concreto.",
    respuestaEn:
      "It's one of the best questions to show judgment, so have a real story ready, shaped like this: the situation, what went wrong, how you noticed, and what you changed in how you work. An example structure: 'I was integrating a payment provider and the assistant generated webhook handling using a library method that looked right. Unit tests passed because they mocked that library. In staging, refund events weren't processed: the method didn't exist in our version, and the error was swallowed by a try/catch it had also generated. I caught it because I had an alert on failed webhooks. Since then I do three things: check against the exact version's docs any API I don't know, review generated error handling with special care, and for external integrations write at least one test against the provider's sandbox, not just mocks.' What's evaluated isn't that the AI made a mistake, which is expected, but that your process caught it and you learned something concrete.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo manejás el uso de IA en un live coding o en un ejercicio para hacer en casa?",
    respuestaEs:
      "Con transparencia y siguiendo las reglas del proceso, que conviene preguntar si no están claras: '¿puedo usar un asistente, y en qué medida?'. Si está permitido, se usa como en el trabajo real, y se piensa en voz alta: qué le pedís, por qué, y cómo revisás lo que devuelve. En un live coding, lo que se evalúa es tu razonamiento, así que el asistente no debería hacer el trabajo intelectual: vos definís el enfoque, él puede ayudar con sintaxis o boilerplate, y vos explicás el código. En un ejercicio para hacer en casa, lo sano es declararlo en el README: qué partes hiciste con ayuda, qué decisiones tomaste vos y por qué, y qué verificaste; muchas empresas lo valoran, porque muestra cómo trabajarías con ellas. Si no está permitido, no se usa: presentar como propio algo generado en un proceso que lo prohíbe es un problema de confianza, y además suele notarse en la entrevista de seguimiento, cuando te preguntan por detalles del código. En los dos casos, lo que te protege es poder explicar y defender cada línea que entregás.",
    respuestaEn:
      "With transparency and following the process rules, which are worth asking about if unclear: 'can I use an assistant, and to what extent?'. If allowed, use it as in real work, and think out loud: what you ask, why, and how you review what it returns. In a live coding session, what's evaluated is your reasoning, so the assistant shouldn't do the intellectual work: you define the approach, it can help with syntax or boilerplate, and you explain the code. In a take-home, the healthy thing is to disclose it in the README: which parts you did with help, which decisions were yours and why, and what you verified; many companies value this, since it shows how you'd work with them. If it's not allowed, don't use it: presenting generated work as your own in a process that forbids it is a trust problem, and it usually shows in the follow-up interview when they ask about code details. In both cases, what protects you is being able to explain and defend every line you submit.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo introducirías el uso de IA en un equipo que no la usa, o que la usa mal?",
    respuestaEs:
      "Como cualquier cambio de herramientas en un equipo: con un objetivo, una prueba acotada y medición, no por entusiasmo. Primero entender el punto de partida: qué problema queremos resolver (tiempo en tareas repetitivas, onboarding lento, tests que nadie escribe) y qué restricciones hay (datos sensibles, regulación, presupuesto). Después las BASES: herramientas aprobadas con garantías de privacidad, una política clara de qué se puede compartir, y archivos de instrucciones del proyecto con las convenciones, para que los resultados sean consistentes. Luego un PILOTO con algunas personas y algunos tipos de tarea donde la IA rinde bien (tests, migraciones mecánicas), compartiendo en el equipo qué funcionó y qué no. Si el equipo ya la usa mal (PRs enormes, código que nadie entiende, dependencias sin revisar), el foco es el proceso: límites de tamaño de PR, el autor responde por cada línea, verificación automática fuerte en el CI y revisión de dependencias nuevas. Y MEDIR: tiempo de ciclo, tasa de defectos, reverts y tiempo de revisión, antes y después, para decidir con datos si ampliar, ajustar o recortar. Lo que conviene evitar es imponerla o prohibirla por decreto: las dos cosas generan uso a escondidas y sin cuidado.",
    respuestaEn:
      "Like any tooling change in a team: with a goal, a scoped trial and measurement, not out of enthusiasm. First understand the starting point: what problem we want to solve (time on repetitive tasks, slow onboarding, tests nobody writes) and what constraints exist (sensitive data, regulation, budget). Then the FOUNDATIONS: approved tools with privacy guarantees, a clear policy on what may be shared, and project instruction files with conventions, so results are consistent. Then a PILOT with a few people and a few task types where AI performs well (tests, mechanical migrations), sharing with the team what worked and what didn't. If the team already uses it badly (huge PRs, code nobody understands, unreviewed dependencies), the focus is process: PR size limits, the author answers for every line, strong automated verification in CI and review of new dependencies. And MEASURE: cycle time, defect rate, reverts and review time, before and after, to decide with data whether to expand, adjust or cut back. What to avoid is imposing or banning it by decree: both lead to hidden, careless use.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo sabés si la IA realmente te hace más productivo?",
    respuestaEs:
      "Midiendo resultados, no actividad. Las líneas de código generadas o el porcentaje de sugerencias aceptadas miden cuánto se usa la herramienta, no si se entrega mejor: más código no es mejor, y código generado que después se corrige o se revierte es trabajo negativo. Lo que sí importa: el TIEMPO DE CICLO de una funcionalidad de punta a punta (desde que se empieza hasta que está en producción funcionando), la TASA DE DEFECTOS y de reverts, el TIEMPO DE REVISIÓN de los PRs (si sube mucho, el costo se mudó a quien revisa), y el RETRABAJO en las semanas siguientes. A nivel personal, una práctica honesta es registrar durante un tiempo qué tareas hiciste con asistencia y cuánto tardaste en total, incluida la revisión y la corrección, y compararlo con tareas parecidas. Lo esperable, y lo que conviene decir en una entrevista, es un resultado matizado: aceleración clara en tareas mecánicas y bien verificables, poca o ninguna en problemas nuevos o de diseño, y un costo real de revisión que hay que gestionar. Una respuesta del tipo 'me hace diez veces más productivo en todo' suele leerse como falta de medición, no como un logro.",
    respuestaEn:
      "By measuring outcomes, not activity. Lines of code generated or percentage of accepted suggestions measure how much the tool is used, not whether delivery improved: more code isn't better, and generated code later fixed or reverted is negative work. What matters: end-to-end CYCLE TIME of a feature (from start until it's working in production), DEFECT and revert rate, PR REVIEW TIME (if it rises a lot, the cost moved to the reviewer), and REWORK in the following weeks. Personally, an honest practice is to log for a while which tasks you did with assistance and how long they took in total, including review and fixes, and compare with similar tasks. The expected result, and what's worth saying in an interview, is nuanced: clear speedup on mechanical, well-verifiable tasks, little or none on novel or design problems, and a real review cost that must be managed. An answer like 'it makes me ten times more productive at everything' usually reads as lack of measurement, not an achievement.",
    tradeoffs:
      "Las métricas de uso son fáciles de obtener y engañosas; las de resultado (tiempo de ciclo, defectos) son más difíciles de medir y son las que importan.",
  },
];
