import type { PreguntaEntrevista } from "../types";

export const entrevistaPromptEngineering: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué hace que un pedido a un asistente de código salga bien a la primera?",
    respuestaEs:
      "Lo mismo que hace que un ticket esté bien escrito para un compañero que no conoce el proyecto: que no quede nada importante librado a la interpretación. CONTEXTO: en qué stack y en qué parte del código se trabaja, y qué patrones ya existen. OBJETIVO CONCRETO: no 'agregá paginación', sino 'paginación por cursor en GET /api/pedidos, 20 por página, ordenada por fecha'. RESTRICCIONES: lo que no hay que tocar ni agregar (dependencias nuevas, firmas de funciones que usan otros módulos, archivos fuera del alcance). UN EJEMPLO del repositorio que siga la convención buscada, que vale más que describirla. FORMATO de salida: solo los cambios, un plan primero, o una explicación antes del código. Y CRITERIOS DE VERIFICACIÓN: qué casos tienen que funcionar, idealmente como tests. El modelo no tiene forma de saber lo que no está escrito ni visible en su contexto, y cuando algo falta completa el hueco con lo más probable en general, que casi nunca es lo que tu proyecto necesita. Por eso un pedido vago no ahorra tiempo: lo traslada a revisar y corregir código que resolvía otro problema.",
    respuestaEn:
      "The same thing that makes a ticket well written for a teammate who doesn't know the project: nothing important left to interpretation. CONTEXT: which stack and which part of the code, and which patterns already exist. A CONCRETE GOAL: not 'add pagination', but 'cursor pagination on GET /api/orders, 20 per page, sorted by date'. CONSTRAINTS: what not to touch or add (new dependencies, function signatures other modules use, files out of scope). AN EXAMPLE from the repository following the intended convention, worth more than describing it. OUTPUT FORMAT: only the changes, a plan first, or an explanation before code. And VERIFICATION CRITERIA: which cases must work, ideally as tests. The model can't know what isn't written or visible in its context, and when something's missing it fills the gap with what's most likely in general, which is rarely what your project needs. That's why a vague request doesn't save time: it moves it to reviewing and fixing code that solved a different problem.",
  },
  {
    nivel: 1,
    pregunta: "¿Cómo le das contexto del proyecto a un asistente de forma sostenible?",
    respuestaEs:
      "Con información persistente en el repositorio, en vez de repetirla en cada conversación. La mayoría de las herramientas leen archivos de instrucciones del proyecto (como AGENTS.md, CLAUDE.md o reglas específicas del editor): ahí van el stack, cómo se corren los tests y el linter, las convenciones de nombres y de estructura, lo que no hay que hacer, y dónde está cada cosa. Es documentación que además le sirve a una persona nueva en el equipo. Para cada tarea, el contexto específico: los archivos relevantes (referenciarlos o abrirlos, en vez de describirlos), el mensaje de error completo con su stack trace, y el comportamiento esperado contra el observado. También conviene acotar la tarea: pedidos chicos y bien delimitados funcionan mucho mejor que 'implementá el módulo de facturación', porque cada paso se puede verificar antes de seguir. Y cuando algo sale mal por falta de contexto, la corrección que escala no es explicarlo de nuevo en el chat, sino agregarlo al archivo de instrucciones para que no vuelva a pasar.",
    respuestaEn:
      "With persistent information in the repository, instead of repeating it in every conversation. Most tools read project instruction files (like AGENTS.md, CLAUDE.md or editor-specific rules): that's where the stack goes, how to run tests and the linter, naming and structure conventions, what not to do, and where things live. It's documentation that also helps a new person on the team. For each task, the specific context: the relevant files (reference or open them instead of describing them), the full error message with its stack trace, and expected versus observed behavior. It also helps to scope the task: small, well-bounded requests work far better than 'implement the billing module', because each step can be verified before moving on. And when something goes wrong for lack of context, the fix that scales isn't explaining it again in the chat but adding it to the instruction file so it doesn't happen again.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué técnicas usás para tareas más grandes o ambiguas?",
    respuestaEs:
      "PLAN ANTES DEL CÓDIGO: pedir primero un plan (qué archivos cambia, qué enfoque sigue, qué supuestos hace) y revisarlo; corregir un plan cuesta segundos, corregir doscientas líneas escritas sobre un malentendido cuesta mucho más. DESCOMPOSICIÓN: partir la tarea en pasos que se puedan verificar por separado (primero el modelo de datos y su migración, después el servicio con sus tests, después el endpoint), revisando y corriendo los tests entre paso y paso. PEDIR PREGUNTAS: indicar explícitamente que pregunte lo que no esté claro antes de empezar, en vez de suponer. EJEMPLOS del propio repositorio (few-shot): mostrar un endpoint, un test o un componente existente como modelo. Y ITERAR CON FEEDBACK CONCRETO: cuando la salida no sirve, decir exactamente qué está mal y por qué ('esto rompe a los otros llamadores de listarPedidos porque cambiaste el tipo de retorno'), no 'no funciona, arreglalo'. Un matiz: más texto no siempre es mejor. Un prompt con mucha información irrelevante diluye lo importante; conviene incluir lo necesario para la tarea, no todo lo que se sabe del proyecto.",
    respuestaEn:
      "PLAN BEFORE CODE: first ask for a plan (which files change, what approach, what assumptions) and review it; fixing a plan takes seconds, fixing two hundred lines built on a misunderstanding costs far more. DECOMPOSITION: split the task into separately verifiable steps (first the data model and its migration, then the service with tests, then the endpoint), reviewing and running tests between steps. ASKING QUESTIONS: explicitly say to ask about anything unclear before starting instead of assuming. EXAMPLES from your own repository (few-shot): show an existing endpoint, test or component as the model. And ITERATE WITH CONCRETE FEEDBACK: when the output doesn't work, say exactly what's wrong and why ('this breaks other callers of listOrders because you changed the return type'), not 'it doesn't work, fix it'. A nuance: more text isn't always better. A prompt with a lot of irrelevant information dilutes what matters; include what the task needs, not everything known about the project.",
    tradeoffs:
      "Pedir plan y descomponer cuesta más interacción al principio, a cambio de mucho menos retrabajo; ir directo al código es más rápido solo cuando la tarea es chica y no ambigua.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo pedís ayuda para debuggear un problema con un asistente?",
    respuestaEs:
      "Dando lo que le darías a un colega para que te ayude sin estar en tu máquina. El SÍNTOMA exacto: el mensaje de error completo con el stack trace, no un resumen, y en qué condiciones aparece. Cómo REPRODUCIRLO: los pasos, el input, el entorno. El COMPORTAMIENTO ESPERADO contra el observado. Lo que YA PROBASTE y lo que descartaste, para no recorrer el mismo camino. Y el código relevante, no todo el proyecto. Después, pedir DIAGNÓSTICO ANTES QUE ARREGLO: que explique qué cree que está pasando y por qué, y qué evidencia lo confirmaría. Así se evita el patrón más común y dañino, un parche que hace desaparecer el síntoma sin entender la causa (un try/catch que traga el error, un timeout más largo, un null check que esconde un dato inválido). Si propone una hipótesis, se verifica con un log, un test o una prueba, antes de aceptar la corrección. Y si el problema es de comportamiento en tiempo de ejecución, la información real (logs, valores, un test que falla) vale mucho más que razonar sobre el código leído.",
    respuestaEn:
      "By giving what you'd give a colleague to help you without being at your machine. The exact SYMPTOM: the full error message with the stack trace, not a summary, and under what conditions it appears. How to REPRODUCE it: the steps, the input, the environment. EXPECTED versus observed BEHAVIOR. What you ALREADY TRIED and ruled out, to avoid retracing the same path. And the relevant code, not the whole project. Then ask for DIAGNOSIS BEFORE FIX: have it explain what it thinks is happening and why, and what evidence would confirm it. That avoids the most common and harmful pattern, a patch that makes the symptom disappear without understanding the cause (a try/catch swallowing the error, a longer timeout, a null check hiding invalid data). If it proposes a hypothesis, verify it with a log, a test or an experiment before accepting the fix. And if the problem is runtime behavior, real information (logs, values, a failing test) is worth far more than reasoning about code read statically.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué límites tiene el contexto de un modelo y cómo trabajás alrededor de ellos?",
    respuestaEs:
      "El modelo solo 've' lo que entra en su ventana de contexto: las instrucciones, la conversación y los archivos que se incluyeron. Aunque las ventanas actuales son grandes, tienen límites prácticos. CAPACIDAD: un repositorio mediano no entra entero, así que hay que elegir qué incluir. ATENCIÓN: con mucho contenido, la información relevante compite con la irrelevante, y el modelo puede pasar por alto un detalle importante que está en medio de mucho texto; más contexto no garantiza mejores respuestas. DERIVA en conversaciones largas: decisiones y correcciones del principio pueden perder peso, y el historial se llena de intentos descartados. Las prácticas que ayudan: incluir los archivos relevantes para la tarea en vez de volcar todo (las herramientas con búsqueda en el código lo hacen de forma más selectiva); tareas acotadas en sesiones nuevas, en vez de una conversación infinita; resumir el estado y las decisiones tomadas al retomar; y mantener lo permanente en archivos de instrucciones, que se cargan siempre, en lugar de depender de algo dicho hace cien mensajes.",
    respuestaEn:
      "The model only 'sees' what fits in its context window: the instructions, the conversation and the included files. Though current windows are large, they have practical limits. CAPACITY: a medium repository doesn't fit whole, so you choose what to include. ATTENTION: with a lot of content, relevant information competes with irrelevant, and the model can miss an important detail buried in the middle of lots of text; more context doesn't guarantee better answers. DRIFT in long conversations: early decisions and corrections can lose weight, and history fills with discarded attempts. Practices that help: include the files relevant to the task instead of dumping everything (tools with code search do this more selectively); scoped tasks in fresh sessions instead of an endless conversation; summarize the state and decisions made when resuming; and keep the permanent stuff in instruction files, always loaded, instead of relying on something said a hundred messages ago.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo tratás los prompts y las instrucciones como parte de la ingeniería del equipo?",
    respuestaEs:
      "Como artefactos del repositorio, con el mismo cuidado que el código. Los archivos de instrucciones se VERSIONAN y se revisan en PRs: un cambio ahí modifica el comportamiento del asistente para todo el equipo, igual que cambiar una regla del linter. Los flujos repetidos (crear un endpoint siguiendo el patrón del proyecto, escribir la migración y sus tests, preparar la descripción de un PR) se convierten en COMANDOS O PLANTILLAS reutilizables, que dan resultados consistentes sin que cada persona reinvente el prompt. Se escriben de forma PRECISA y VERIFICABLE: 'corré npx tsc --noEmit antes de terminar' en vez de 'asegurate de que funcione'; reglas concretas con su motivo, así el modelo puede aplicar el criterio a casos nuevos. Y se EVALÚAN: cuando se cambia una instrucción importante, se prueba contra un puñado de tareas conocidas para ver si mejora sin romper otras, del mismo modo que se prueba un cambio de configuración. El objetivo es que la calidad del resultado dependa del proceso del equipo, no de la habilidad individual de cada uno para escribir prompts.",
    respuestaEn:
      "As repository artifacts, with the same care as code. Instruction files are VERSIONED and reviewed in PRs: a change there alters the assistant's behavior for the whole team, like changing a linter rule. Repeated workflows (creating an endpoint following the project pattern, writing a migration and its tests, drafting a PR description) become reusable COMMANDS OR TEMPLATES, giving consistent results without each person reinventing the prompt. They're written PRECISELY and VERIFIABLY: 'run npx tsc --noEmit before finishing' instead of 'make sure it works'; concrete rules with their reason, so the model can apply the criterion to new cases. And they're EVALUATED: when an important instruction changes, test it against a handful of known tasks to see whether it improves without breaking others, just as you'd test a configuration change. The goal is for result quality to depend on the team's process, not on each individual's prompt-writing skill.",
  },
];
