import type { PreguntaEntrevista } from "../types";

export const entrevistaRiesgosLimitesIa: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿En qué tareas de desarrollo rinde la IA y en cuáles no?",
    respuestaEs:
      "Rinde mucho en tareas con patrones claros y verificación rápida: código que sigue una convención existente en el repo (otro endpoint, otro componente, otro test), transformaciones mecánicas (migrar una sintaxis, renombrar, tipar), boilerplate, scripts de un solo uso, explicar código desconocido, escribir tests para código existente, y como primer borrador de documentación. También como sparring: contrastar alternativas de diseño, buscar casos borde que no consideraste, o encontrar la causa probable de un error con un stack trace. Rinde menos donde el contexto relevante no está en el código: decisiones de arquitectura que dependen del negocio, del equipo y de cómo va a evolucionar el sistema; requisitos ambiguos, donde completa lo que falta con lo más probable en vez de preguntar; problemas nuevos sin patrones parecidos; comportamiento en producción (carga real, datos reales, concurrencia) que no se ve leyendo el código; y código crítico de seguridad, donde un error sutil es muy caro. El criterio práctico no es qué tan difícil es la tarea, sino cuánto cuesta un error y qué tan fácil es detectarlo.",
    respuestaEn:
      "It performs very well on tasks with clear patterns and fast verification: code following an existing repo convention (another endpoint, component or test), mechanical transformations (migrating syntax, renaming, adding types), boilerplate, one-off scripts, explaining unfamiliar code, writing tests for existing code, and as a first draft of documentation. Also as a sparring partner: contrasting design alternatives, finding edge cases you missed, or locating the likely cause of an error from a stack trace. It performs less well where the relevant context isn't in the code: architecture decisions depending on the business, the team and how the system will evolve; ambiguous requirements, where it fills gaps with what's most likely instead of asking; novel problems without similar patterns; production behavior (real load, real data, concurrency) not visible by reading code; and security-critical code, where a subtle error is very expensive. The practical criterion isn't how hard the task is, but how costly an error is and how easy it is to catch.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué riesgos tiene desarrollar confiando completamente en la IA?",
    respuestaEs:
      "El riesgo central es que la velocidad de generación supere a la capacidad de entender lo que se genera. DEUDA DE COMPRENSIÓN: si el equipo mergea código que nadie entiende del todo, el día que falla en producción nadie sabe depurarlo, y cada cambio posterior es más riesgoso. ERRORES PLAUSIBLES: el código generado suele verse correcto; los errores sutiles (un caso borde, una condición de carrera, un permiso mal chequeado) pasan una revisión apurada con mucha más facilidad que un error evidente. INCOHERENCIA: cada respuesta resuelve bien su pedazo local, pero sin una visión de conjunto el sistema acumula formas distintas de hacer lo mismo, duplicación y abstracciones que no encajan. SEGURIDAD Y DEPENDENCIAS: consultas inseguras, validaciones faltantes, paquetes innecesarios o inexistentes. Y PÉRDIDA DE HABILIDADES: sobre todo en perfiles que están aprendiendo, delegar todo impide desarrollar el criterio que después hace falta para revisar. Ninguno de estos riesgos implica no usarla; implica que la responsabilidad, la comprensión y las decisiones de fondo siguen siendo de las personas.",
    respuestaEn:
      "The core risk is generation speed outpacing the ability to understand what's generated. COMPREHENSION DEBT: if the team merges code nobody fully understands, the day it fails in production nobody knows how to debug it, and every later change is riskier. PLAUSIBLE ERRORS: generated code usually looks right; subtle errors (an edge case, a race condition, a wrongly checked permission) slip through a rushed review far more easily than an obvious one. INCOHERENCE: each answer solves its local piece well, but without an overall vision the system accumulates different ways of doing the same thing, duplication and abstractions that don't fit. SECURITY AND DEPENDENCIES: unsafe queries, missing validations, unnecessary or nonexistent packages. And SKILL LOSS: especially for people still learning, delegating everything prevents developing the judgment later needed to review. None of these risks means not using it; it means responsibility, understanding and the fundamental decisions stay with people.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué riesgos de privacidad y propiedad intelectual hay al usar asistentes de IA?",
    respuestaEs:
      "Todo lo que se incluye en el contexto se envía al proveedor del modelo: código propietario, datos de clientes pegados para depurar, archivos de configuración con secretos. Las preguntas que hay que poder responder: ¿el proveedor retiene esos datos, por cuánto tiempo, y los usa para entrenar? Los planes empresariales suelen garantizar que no se entrena con los datos del cliente y ofrecen retención acotada, contratos de procesamiento de datos y, a veces, residencia de datos; los planes personales pueden tener otras condiciones. De ahí las prácticas: usar las herramientas aprobadas por la empresa con esas garantías, no pegar datos personales ni secretos en el contexto (usar datos de ejemplo o anonimizados), excluir archivos sensibles de lo que el asistente puede leer, y tener una política clara de qué se puede compartir. Del lado de la propiedad: el código generado puede parecerse a código con licencia existente; algunas herramientas filtran coincidencias textuales con código público, y para piezas relevantes conviene revisarlo. Y en sectores regulados (salud, finanzas, datos personales) estas decisiones pasan por legal y seguridad, no solo por el equipo.",
    respuestaEn:
      "Everything included in the context is sent to the model provider: proprietary code, customer data pasted for debugging, config files with secrets. The questions you need to answer: does the provider retain that data, for how long, and train on it? Enterprise plans usually guarantee no training on customer data and offer bounded retention, data processing agreements and sometimes data residency; personal plans may have different terms. Hence the practices: use the company-approved tools with those guarantees, don't paste personal data or secrets into context (use sample or anonymized data), exclude sensitive files from what the assistant can read, and have a clear policy on what may be shared. On the ownership side: generated code can resemble existing licensed code; some tools filter verbatim matches with public code, and for significant pieces it's worth checking. And in regulated sectors (health, finance, personal data) these decisions go through legal and security, not just the team.",
    tradeoffs:
      "Restringir qué se comparte reduce el riesgo de filtración a cambio de respuestas con menos contexto; la solución habitual es un plan empresarial con garantías contractuales, no prohibir la herramienta.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo evitás que el equipo pierda comprensión del sistema cuando mucho código lo genera la IA?",
    respuestaEs:
      "Tratando la comprensión como un requisito explícito, no como un efecto colateral. EL AUTOR EXPLICA: quien abre un PR puede explicar qué hace cada parte y por qué, sin 'lo generó la IA'; si no puede, no está listo para mergear. DUEÑOS de las partes críticas (pagos, permisos, el modelo de datos central) que las conozcan en profundidad, aunque el código lo haya escrito un asistente. DECISIONES DOCUMENTADAS: los registros de decisiones de arquitectura (ADRs) y un modelo del sistema escrito por personas, porque la IA genera implementación pero no conserva el porqué. PRÁCTICA DELIBERADA en quienes están aprendiendo: resolver primero sin asistente, o pedirle explicaciones en vez de soluciones, y revisar código ajeno; el criterio para revisar se construye escribiendo y equivocándose. Y SEÑALES de alarma para mirar: incidentes que nadie sabe diagnosticar, preguntas sobre el propio código que se responden preguntándole al asistente, o áreas que todos evitan tocar. La meta es usar la IA para ir más rápido en lo que el equipo entiende, no para operar un sistema que nadie entiende.",
    respuestaEn:
      "By treating comprehension as an explicit requirement, not a side effect. THE AUTHOR EXPLAINS: whoever opens a PR can explain what each part does and why, without 'the AI generated it'; if they can't, it's not ready to merge. OWNERS for critical areas (payments, permissions, the core data model) who know them deeply, even if an assistant wrote the code. DOCUMENTED DECISIONS: architecture decision records (ADRs) and a human-written system model, because AI generates implementation but doesn't preserve the why. DELIBERATE PRACTICE for people learning: solving first without an assistant, or asking it for explanations instead of solutions, and reviewing others' code; the judgment to review is built by writing and making mistakes. And WARNING SIGNS to watch: incidents nobody can diagnose, questions about your own code answered by asking the assistant, or areas everyone avoids touching. The goal is using AI to go faster on what the team understands, not to operate a system nobody understands.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué riesgos agregan los agentes que ejecutan comandos y modifican código solos, y cómo los acotás?",
    respuestaEs:
      "Un agente no solo propone: ejecuta comandos, edita archivos, corre migraciones, llama APIs. El riesgo pasa de 'código incorrecto que alguien revisa' a 'acciones con efectos reales antes de que alguien mire'. Los incidentes típicos: borrar o sobrescribir datos, correr algo contra producción creyendo que era desarrollo, instalar dependencias sin revisar, filtrar secretos que encontró en el entorno, o quedar en un bucle que consume tiempo y dinero. Las defensas se diseñan como para cualquier proceso automatizado con permisos. MÍNIMO PRIVILEGIO: el agente trabaja con credenciales de desarrollo, nunca con las de producción, y con acceso solo al repositorio y los servicios que la tarea necesita. SANDBOX: un contenedor o entorno aislado, con red y sistema de archivos restringidos. APROBACIÓN para lo destructivo o irreversible: borrar, migrar, desplegar, hacer push, enviar mensajes. ALLOWLISTS de comandos y dominios en vez de libertad total. CAMBIOS REVERSIBLES: trabajar en una rama, con commits chicos, así cualquier cosa se deshace. LÍMITES de tiempo, iteraciones y costo, para cortar bucles. Y REGISTRO de todo lo que hizo, para entender después qué pasó. La autonomía se amplía a medida que el entorno demuestra que el daño posible está acotado, no por comodidad.",
    respuestaEn:
      "An agent doesn't just propose: it runs commands, edits files, runs migrations, calls APIs. The risk shifts from 'wrong code someone reviews' to 'actions with real effects before anyone looks'. Typical incidents: deleting or overwriting data, running something against production thinking it was development, installing unreviewed dependencies, leaking secrets found in the environment, or getting stuck in a loop consuming time and money. Defenses are designed as for any automated process with permissions. LEAST PRIVILEGE: the agent works with development credentials, never production ones, and with access only to the repository and services the task needs. SANDBOX: a container or isolated environment, with restricted network and filesystem. APPROVAL for anything destructive or irreversible: deleting, migrating, deploying, pushing, sending messages. ALLOWLISTS of commands and domains instead of full freedom. REVERSIBLE CHANGES: working on a branch with small commits, so anything can be undone. LIMITS on time, iterations and cost, to cut loops. And LOGGING everything it did, to understand later what happened. Autonomy expands as the environment proves the possible damage is bounded, not for convenience.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué límites estructurales tienen los modelos que conviene tener presentes al diseñar tu forma de trabajar?",
    respuestaEs:
      "Varios, y conviene diseñar el proceso asumiendo que existen, no esperando que desaparezcan. NO DETERMINISMO: el mismo pedido puede dar resultados distintos; por eso lo que importa se verifica con tests y herramientas, no con haberlo visto funcionar una vez. CONOCIMIENTO CON FECHA DE CORTE: el modelo puede no conocer la última versión de una librería y sugerir APIs viejas o que cambiaron; la documentación actual y el typecheck son la fuente de verdad. CONTEXTO LIMITADO: en un sistema grande no ve todo a la vez, así que puede resolver bien un cambio local y romper una convención o una invariante que vive en otro lado; los tipos, los tests y las reglas del proyecto por escrito ayudan a que esas invariantes sean visibles. CONFIANZA MAL CALIBRADA: responde con el mismo tono seguro cuando acierta y cuando inventa, así que su seguridad no es una señal de corrección. Y SIN ACCESO AL MUNDO REAL salvo el que le das: no sabe cómo se comporta el sistema en producción si no le mostrás logs, métricas o resultados de ejecución. Todo esto empuja en la misma dirección: invertir en lo que hace verificable el trabajo (tipos estrictos, tests, CI, observabilidad), porque eso protege tanto del error humano como del generado.",
    respuestaEn:
      "Several, and it's worth designing the process assuming they exist, not hoping they'll disappear. NON-DETERMINISM: the same request can give different results; so what matters is verified with tests and tools, not by having seen it work once. KNOWLEDGE CUTOFF: the model may not know a library's latest version and suggest old or changed APIs; current docs and the typecheck are the source of truth. LIMITED CONTEXT: in a large system it doesn't see everything at once, so it can solve a local change well and break a convention or invariant living elsewhere; types, tests and written project rules help make those invariants visible. MISCALIBRATED CONFIDENCE: it answers with the same assured tone when right and when inventing, so its confidence isn't a signal of correctness. And NO ACCESS TO THE REAL WORLD beyond what you give it: it doesn't know how the system behaves in production unless you show it logs, metrics or execution results. All of this points the same way: invest in what makes work verifiable (strict types, tests, CI, observability), because it protects from human error and generated error alike.",
  },
];
