import type { PreguntaEntrevista } from "../types";

export const entrevistaArquitecturaCapas: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué responsabilidad tiene cada capa en controller / service / repository?",
    respuestaEs:
      "El CONTROLLER es el adaptador de HTTP: lee el request (params, body, usuario de la sesión), valida la forma de la entrada, llama al servicio y traduce el resultado o el error a una respuesta con el status adecuado. No tiene reglas de negocio ni consultas. El SERVICE contiene la lógica de negocio: las reglas (un cupón vencido no se aplica), la orquestación de pasos, los cálculos y los permisos del dominio; no sabe nada de HTTP (no conoce `req`, `res` ni status codes) ni de SQL. El REPOSITORY encapsula el acceso a datos: las consultas, el ORM, cómo se mapean las filas; expone métodos con nombres del dominio (`buscarConItems`, `guardarDescuento`) en vez de exponer el ORM. Las dependencias van en un solo sentido: controller → service → repository. El beneficio concreto: la lógica de negocio se testea sin levantar un servidor ni una base, se reutiliza desde otras entradas (un job, una CLI, un consumidor de colas), y cambiar el ORM o el framework HTTP toca una sola capa.",
    respuestaEn:
      "The CONTROLLER is the HTTP adapter: it reads the request (params, body, session user), validates input shape, calls the service and translates the result or error into a response with the right status. It holds no business rules or queries. The SERVICE contains business logic: the rules (an expired coupon isn't applied), step orchestration, calculations and domain permissions; it knows nothing of HTTP (no `req`, `res` or status codes) or SQL. The REPOSITORY encapsulates data access: queries, the ORM, how rows are mapped; it exposes methods with domain names (`findWithItems`, `saveDiscount`) rather than exposing the ORM. Dependencies flow one way: controller → service → repository. The concrete benefit: business logic is tested without spinning up a server or database, reused from other entry points (a job, a CLI, a queue consumer), and changing the ORM or HTTP framework touches a single layer.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué problema tiene un 'fat controller'?",
    respuestaEs:
      "Mezcla todo en el handler: validación, reglas de negocio, consultas a la base, llamadas a servicios externos y armado de la respuesta. Funciona, pero trae varios problemas a medida que crece. No se puede testear una regla sin levantar HTTP y una base, así que los tests son lentos o no existen. La lógica no se puede reutilizar: si el mismo cálculo hace falta en un job nocturno o en otro endpoint, se copia y pega, y las copias divergen. Los cambios de infraestructura (cambiar el ORM, agregar cache) obligan a tocar cada handler. Y es difícil de leer: la regla de negocio importante queda enterrada entre `req.body`, `res.status` y consultas. El síntoma típico son handlers de cien o doscientas líneas con varios `try/catch` anidados. La solución no es necesariamente aplicar todas las capas en todos lados, sino sacar primero las reglas de negocio a funciones o servicios sin dependencias de HTTP.",
    respuestaEn:
      "It mixes everything in the handler: validation, business rules, database queries, external service calls and building the response. It works, but brings problems as it grows. A rule can't be tested without spinning up HTTP and a database, so tests are slow or nonexistent. Logic can't be reused: if the same calculation is needed in a nightly job or another endpoint, it's copy-pasted, and the copies diverge. Infrastructure changes (switching ORM, adding a cache) force touching every handler. And it's hard to read: the important business rule is buried among `req.body`, `res.status` and queries. The typical symptom is handlers of one or two hundred lines with several nested `try/catch`. The fix isn't necessarily applying every layer everywhere, but first extracting business rules into functions or services with no HTTP dependency.",
  },
  {
    nivel: 2,
    pregunta: "¿Dónde van las transacciones en una arquitectura en capas?",
    respuestaEs:
      "La transacción delimita una operación de NEGOCIO que tiene que ser atómica ('aplicar el cupón y descontar un uso del cupón'), así que su frontera la decide el SERVICE, que es quien sabe qué pasos forman una unidad. Pero el service no debería conocer detalles de la base. Las formas habituales: el service abre una unidad de trabajo (`unitOfWork.run(async (tx) => ...)` o `prisma.$transaction(async (tx) => ...)`) y le pasa el contexto transaccional a los repositorios que usa; o se usa un mecanismo que propaga la transacción implícitamente (con `AsyncLocalStorage`, o decoradores `@Transactional` en NestJS con librerías como `@nestjs-cls/transactional`), así los repositorios la toman sin recibirla por parámetro. Lo que conviene evitar: transacciones dentro de cada repositorio (dos llamadas quedan en transacciones separadas y no hay atomicidad), abrirlas en el controller (mezcla HTTP con consistencia de datos), y mantener una transacción abierta mientras se llama a un servicio externo lento, porque retiene locks y conexiones.",
    respuestaEn:
      "A transaction bounds a BUSINESS operation that must be atomic ('apply the coupon and decrement the coupon's uses'), so its boundary is decided by the SERVICE, which knows which steps form a unit. But the service shouldn't know database details. Common approaches: the service opens a unit of work (`unitOfWork.run(async (tx) => ...)` or `prisma.$transaction(async (tx) => ...)`) and passes the transactional context to the repositories it uses; or a mechanism propagates the transaction implicitly (with `AsyncLocalStorage`, or `@Transactional` decorators in NestJS with libraries like `@nestjs-cls/transactional`), so repositories pick it up without receiving it as a parameter. What to avoid: transactions inside each repository (two calls end up in separate transactions with no atomicity), opening them in the controller (mixing HTTP with data consistency), and keeping a transaction open while calling a slow external service, since it holds locks and connections.",
    codigo: `async aplicarCupon(pedidoId: string, codigo: string) {
  return this.uow.run(async (tx) => {
    const cupon = await this.cupones.buscarPorCodigo(codigo, tx);
    if (!cupon || cupon.usosRestantes === 0) throw new CuponInvalido(codigo);
    await this.cupones.descontarUso(cupon.id, tx);
    await this.pedidos.guardarDescuento(pedidoId, cupon, tx);
  }); // los dos cambios se confirman juntos o ninguno
}`,
  },
  {
    nivel: 2,
    pregunta: "¿Hace falta un repository si ya usás un ORM como Prisma?",
    respuestaEs:
      "Es un debate válido. Un ORM moderno ya es, en buena medida, una capa de acceso a datos: agregar un repository que solo reenvía cada llamada (`findById(id) { return prisma.x.findUnique(...) }`) es indirección sin beneficio. El repository suma valor cuando: las consultas son complejas y conviene darles un nombre de dominio y un solo lugar (`buscarPedidosPendientesDeFacturar`); se quiere testear el servicio con un repositorio en memoria sin mockear el cliente del ORM; hay reglas de acceso transversales (filtrar siempre por organización en un SaaS multi-tenant, excluir borrados lógicos); o se prevé cambiar la fuente de datos. En apps chicas o CRUDs, usar el ORM directamente desde el servicio es razonable. La regla práctica: que el servicio no dependa de detalles del ORM que se filtren por todo el código, y que las consultas no se dupliquen; si hace falta un repository para eso, se agrega, pero no por ritual.",
    respuestaEn:
      "It's a fair debate. A modern ORM is already largely a data access layer: adding a repository that merely forwards each call (`findById(id) { return prisma.x.findUnique(...) }`) is indirection without benefit. A repository adds value when: queries are complex and deserve a domain name and a single home (`findOrdersPendingInvoicing`); you want to test the service with an in-memory repository without mocking the ORM client; there are cross-cutting access rules (always filter by organization in a multi-tenant SaaS, exclude soft-deleted rows); or a data source change is anticipated. In small apps or CRUDs, using the ORM directly from the service is reasonable. The practical rule: the service shouldn't depend on ORM details leaking everywhere, and queries shouldn't be duplicated; if a repository is needed for that, add one, but not as a ritual.",
    tradeoffs:
      "Un repository da nombres de dominio, un lugar para reglas transversales y tests sin base, a cambio de una capa más de código. Con un ORM expresivo y un dominio simple, ese costo muchas veces no se recupera.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es un 'modelo anémico' y por qué se critica?",
    respuestaEs:
      "Es cuando las entidades del dominio son solo estructuras de datos (propiedades sin comportamiento) y TODA la lógica vive en servicios que las manipulan desde afuera. Por ejemplo, `Pedido` es un objeto con `items`, `estado` y `descuento`, y cualquier servicio puede cambiar su estado a 'enviado' aunque no esté pagado. Martin Fowler lo llamó antipatrón porque las invariantes del negocio ('un pedido pagado no se puede editar', 'el descuento no supera al subtotal') quedan dispersas en varios servicios, se duplican, y nada impide dejar una entidad en un estado inválido. La alternativa, un modelo de dominio rico, pone ese comportamiento en la entidad: `pedido.aplicarCupon(cupon)` verifica sus propias reglas y es la única forma de cambiar el descuento. En la práctica, con TypeScript y ORMs que devuelven objetos planos, muchos equipos usan servicios con funciones puras de dominio; es un punto medio razonable siempre que las reglas estén en un solo lugar y testeadas, y no copiadas en cada servicio.",
    respuestaEn:
      "It's when domain entities are just data structures (properties without behavior) and ALL logic lives in services manipulating them from outside. For example, `Order` is an object with `items`, `status` and `discount`, and any service can set its status to 'shipped' even if unpaid. Martin Fowler called it an antipattern because business invariants ('a paid order can't be edited', 'the discount can't exceed the subtotal') end up scattered across services, get duplicated, and nothing prevents leaving an entity in an invalid state. The alternative, a rich domain model, puts that behavior in the entity: `order.applyCoupon(coupon)` checks its own rules and is the only way to change the discount. In practice, with TypeScript and ORMs returning plain objects, many teams use services with pure domain functions; it's a reasonable middle ground as long as rules live in one place and are tested, not copied into every service.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo se relaciona la arquitectura en capas con Clean / Hexagonal?",
    respuestaEs:
      "La arquitectura en capas clásica es vertical: controller → service → repository → base de datos, y en su forma tradicional el service DEPENDE del repository concreto, que depende del ORM; o sea, la lógica de negocio depende de la infraestructura. Clean y Hexagonal invierten esa última dependencia: el servicio (caso de uso) define la INTERFAZ del repositorio que necesita (un puerto), y la implementación con Prisma (un adaptador) depende de esa interfaz, no al revés. Así el núcleo no conoce la base de datos ni el framework, y todas las dependencias apuntan hacia el dominio. En la práctica, el controller/service/repository de NestJS o de un proyecto Express bien ordenado ya está a mitad de camino: si el servicio recibe el repositorio por inyección a través de una interfaz y no importa Prisma, se parece mucho a hexagonal. La diferencia importa más cuanto más lógica de negocio hay y más cambian las dependencias externas.",
    respuestaEn:
      "Classic layered architecture is vertical: controller → service → repository → database, and in its traditional form the service DEPENDS on the concrete repository, which depends on the ORM; that is, business logic depends on infrastructure. Clean and Hexagonal invert that last dependency: the service (use case) defines the INTERFACE of the repository it needs (a port), and the Prisma implementation (an adapter) depends on that interface, not the other way around. So the core knows neither the database nor the framework, and all dependencies point toward the domain. In practice, the controller/service/repository of NestJS or a well-organized Express project is already halfway there: if the service receives the repository via injection through an interface and doesn't import Prisma, it looks a lot like hexagonal. The difference matters more the more business logic there is and the more external dependencies change.",
  },
];
