import type { PreguntaEntrevista } from "../types";

export const entrevistaRateLimiting: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Para qué sirve el rate limiting y cómo se comunica al cliente?",
    respuestaEs:
      "Limita cuántos requests puede hacer un cliente en un período, para proteger al sistema y a los demás usuarios. Sirve contra abuso (fuerza bruta en el login, scraping, spam de registros o de mails), contra clientes con bugs que reintentan en loop, para repartir capacidad de forma justa entre usuarios de una API, y para cuidar costos (un endpoint que llama a un servicio pago o a un LLM). Cuando se supera, el servidor responde `429 Too Many Requests` con el header `Retry-After` indicando cuándo volver a intentar, y es buena práctica informar el estado en headers (`RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset`, o las variantes `X-RateLimit-*` más difundidas) para que los clientes bien hechos se autorregulen. La clave de identificación depende del caso: por usuario autenticado, por API key, por IP para tráfico anónimo, o combinaciones (por IP y por cuenta en el login).",
    respuestaEn:
      "It limits how many requests a client can make in a period, to protect the system and other users. It guards against abuse (login brute force, scraping, signup or email spam), against buggy clients retrying in a loop, fairly shares capacity among API users, and controls costs (an endpoint calling a paid service or an LLM). When exceeded, the server responds `429 Too Many Requests` with a `Retry-After` header indicating when to retry, and it's good practice to expose the state in headers (`RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset`, or the more widespread `X-RateLimit-*` variants) so well-behaved clients self-regulate. The identification key depends on the case: per authenticated user, per API key, per IP for anonymous traffic, or combinations (per IP and per account on login).",
  },
  {
    nivel: 1,
    pregunta: "¿Por qué un rate limiter en memoria no alcanza cuando tenés varias instancias?",
    respuestaEs:
      "Porque cada instancia cuenta por su lado. Con un límite de 100 requests por minuto y 4 instancias detrás de un balanceador, un cliente puede hacer hasta 400, y el límite real depende de cómo reparta el balanceador; además, al reiniciar o escalar, los contadores se pierden. En serverless es peor: cada invocación puede caer en una instancia nueva y el contador en memoria no sirve de nada. La solución es un almacén compartido y rápido, normalmente Redis, con operaciones atómicas (`INCR` con expiración, o scripts Lua para algoritmos más elaborados) que todas las instancias consultan. Otra opción es aplicar el límite antes de llegar a la aplicación: en el API gateway, el CDN o el WAF (Cloudflare, AWS API Gateway, Nginx), que además frena el tráfico abusivo antes de que consuma recursos del backend. Lo habitual es combinar: límites gruesos por IP en el borde, y límites finos por usuario o por plan en la aplicación.",
    respuestaEn:
      "Because each instance counts on its own. With a 100 requests per minute limit and 4 instances behind a load balancer, a client can make up to 400, and the real limit depends on how the balancer distributes; plus, counters are lost on restart or scaling. Serverless is worse: each invocation may land on a fresh instance and an in-memory counter is useless. The fix is a shared, fast store, typically Redis, with atomic operations (`INCR` with expiry, or Lua scripts for more elaborate algorithms) that every instance queries. Another option is enforcing the limit before reaching the app: at the API gateway, CDN or WAF (Cloudflare, AWS API Gateway, Nginx), which also stops abusive traffic before it consumes backend resources. The usual approach combines both: coarse per-IP limits at the edge, and fine per-user or per-plan limits in the app.",
    codigo: `// ventana fija con Redis: atómico y compartido entre instancias
const clave = \`rl:\${usuarioId}:\${Math.floor(Date.now() / 60_000)}\`;
const usados = await redis.incr(clave);
if (usados === 1) await redis.expire(clave, 60);
if (usados > 100) {
  return res.status(429).set("Retry-After", "60").json({ codigo: "RATE_LIMIT" });
}`,
  },
  {
    nivel: 2,
    pregunta: "Compará ventana fija, ventana deslizante y token bucket.",
    respuestaEs:
      "VENTANA FIJA cuenta requests por bloques de tiempo alineados (de 12:00:00 a 12:00:59): un solo contador con expiración, muy barato. Su defecto es el borde: un cliente puede hacer el máximo al final de una ventana y otra vez el máximo al principio de la siguiente, el doble del límite en pocos segundos. VENTANA DESLIZANTE mira siempre los últimos N segundos desde el request actual: con un log de timestamps (un sorted set en Redis) es exacta pero guarda un registro por request; la variante por aproximación combina el contador de la ventana actual y el de la anterior ponderado, precisa y barata. TOKEN BUCKET modela un balde con capacidad C que se recarga a una tasa fija; cada request consume una ficha: permite ráfagas cortas hasta la capacidad y limita el promedio a largo plazo, lo que refleja bien el uso real de una API (un usuario que abre la app dispara varias llamadas juntas y después descansa). Existe también el leaky bucket, que suaviza la salida a una tasa constante, más usado como cola que como limitador de requests.",
    respuestaEn:
      "FIXED WINDOW counts requests in aligned time blocks (12:00:00 to 12:00:59): a single counter with expiry, very cheap. Its flaw is the boundary: a client can make the max at the end of one window and the max again at the start of the next, double the limit within seconds. SLIDING WINDOW always looks at the last N seconds from the current request: with a timestamp log (a Redis sorted set) it's exact but stores a record per request; the approximation variant combines the current window's counter and the previous one's weighted, accurate and cheap. TOKEN BUCKET models a bucket of capacity C refilled at a fixed rate; each request consumes a token: it allows short bursts up to capacity and limits the long-term average, which matches real API usage well (a user opening the app fires several calls together and then rests). There's also the leaky bucket, which smooths output to a constant rate, used more as a queue than a request limiter.",
    tradeoffs:
      "Precisión vs costo: la ventana fija es la más barata pero permite ráfagas del doble en el borde; el log deslizante es exacto pero guarda cada request; token bucket y la ventana deslizante aproximada son el equilibrio habitual.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo protegés un endpoint de login contra fuerza bruta sin bloquear a usuarios legítimos?",
    respuestaEs:
      "Con varios límites combinados, porque un solo criterio se esquiva. Por IP: frena a un atacante desde una máquina, pero no a una botnet con miles de IPs, y puede afectar a muchos usuarios detrás de una misma IP (una oficina, una red móvil). Por cuenta: frena el ataque a un usuario puntual desde muchas IPs, pero si se bloquea la cuenta por completo, el atacante puede dejar sin acceso a cualquiera a propósito (denegación de servicio dirigida). Por eso, en vez de bloqueos duros, se usa backoff progresivo (cada intento fallido agrega demora), CAPTCHA o desafío después de algunos fallos, y notificación al usuario. Contra credential stuffing (listas de contraseñas filtradas probadas en muchas cuentas), ayudan los límites globales de intentos fallidos, detectar contraseñas comprometidas y MFA. Y siempre responder el mismo mensaje y en un tiempo similar para no revelar si el usuario existe.",
    respuestaEn:
      "With several combined limits, since a single criterion can be dodged. Per IP: stops an attacker on one machine, but not a botnet with thousands of IPs, and may affect many users behind the same IP (an office, a mobile network). Per account: stops attacks on a specific user from many IPs, but fully locking the account lets an attacker deliberately lock anyone out (targeted denial of service). So instead of hard lockouts, use progressive backoff (each failed attempt adds delay), CAPTCHA or a challenge after a few failures, and notifying the user. Against credential stuffing (leaked password lists tried across many accounts), global failed-attempt limits, compromised password detection and MFA help. And always respond with the same message and in similar time so you don't reveal whether the user exists.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué diferencia hay entre rate limiting, throttling, cuotas y load shedding?",
    respuestaEs:
      "Son mecanismos relacionados con objetivos distintos. RATE LIMITING rechaza (429) los requests que superan una tasa por cliente: protege contra abuso y reparte capacidad. THROTTLING, en cambio, no rechaza sino que DEMORA o encola los requests para mantener una tasa de salida, útil cuando llamás a una API de terceros con límites estrictos y preferís esperar antes que fallar. Las CUOTAS son límites de uso acumulado en períodos largos ligados al negocio (10.000 llamadas por mes en el plan gratuito, tokens de un LLM por día), se miden y facturan, y su superación suele implicar un 402 o un upgrade más que un reintento. El LOAD SHEDDING es una defensa del sistema entero y no por cliente: cuando el servicio está saturado (colas largas, latencia disparada), rechaza parte del tráfico de forma deliberada, idealmente priorizando (se descarta primero lo menos crítico, como el tráfico de bots o los reportes, y se preserva el checkout), para que el resto siga funcionando en vez de degradarse todo hasta caer.",
    respuestaEn:
      "They're related mechanisms with different goals. RATE LIMITING rejects (429) requests exceeding a per-client rate: it protects against abuse and shares capacity. THROTTLING doesn't reject but DELAYS or queues requests to keep an output rate, useful when calling a third-party API with strict limits and you'd rather wait than fail. QUOTAS are long-period cumulative usage limits tied to the business (10,000 calls per month on the free plan, LLM tokens per day), measured and billed, and exceeding them usually means a 402 or an upgrade rather than a retry. LOAD SHEDDING is a whole-system defense, not per client: when the service is saturated (long queues, spiking latency), it deliberately rejects part of the traffic, ideally by priority (dropping the least critical first, like bot traffic or reports, and preserving checkout), so the rest keeps working instead of everything degrading until it falls over.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo implementarías un token bucket distribuido y atómico en Redis?",
    respuestaEs:
      "El problema de hacerlo con varios comandos sueltos (leer las fichas, calcular, escribir) es la condición de carrera: dos instancias leen el mismo valor y ambas consumen la última ficha. Hay que hacerlo ATÓMICO, con un script Lua que Redis ejecuta sin intercalar otros comandos: el script lee el estado guardado para la clave del cliente (fichas y timestamp de la última recarga), calcula cuántas fichas se recargaron desde entonces según la tasa, aplica el tope de capacidad, decide si hay al menos una ficha, la descuenta y guarda el nuevo estado con una expiración (para que las claves de clientes inactivos desaparezcan), y devuelve si se aceptó y cuánto falta para la próxima ficha (el valor de `Retry-After`). Se usa el reloj del servidor de Redis o se pasa el tiempo como argumento, para no depender de relojes desincronizados entre instancias. Librerías como `rate-limiter-flexible` o `@upstash/ratelimit` ya lo implementan; también conviene decidir qué pasa si Redis no responde: fallar abierto (dejar pasar) o cerrado (rechazar) según el riesgo.",
    respuestaEn:
      "The problem with separate commands (read tokens, compute, write) is the race condition: two instances read the same value and both consume the last token. It must be ATOMIC, with a Lua script Redis runs without interleaving other commands: the script reads the stored state for the client's key (tokens and last refill timestamp), computes how many tokens refilled since then per the rate, applies the capacity cap, decides whether there's at least one token, deducts it and saves the new state with an expiry (so inactive clients' keys disappear), and returns whether it was accepted and how long until the next token (the `Retry-After` value). Use Redis's server clock or pass the time as an argument, to avoid depending on unsynchronized instance clocks. Libraries like `rate-limiter-flexible` or `@upstash/ratelimit` already implement it; you should also decide what happens if Redis doesn't respond: fail open (let through) or closed (reject) depending on the risk.",
  },
];
