import type { PreguntaEntrevista } from "../types";

export const entrevistaWebsocketsTiempoReal: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Cómo funciona una conexión WebSocket y en qué se diferencia de HTTP?",
    respuestaEs:
      "Empieza como un request HTTP normal con un header `Upgrade: websocket`; si el servidor acepta, responde `101 Switching Protocols` y, desde ese momento, la misma conexión TCP queda abierta como un canal bidireccional y persistente donde cualquiera de los dos lados puede mandar mensajes (frames de texto o binarios) en cualquier momento, con muy poco overhead por mensaje. En HTTP, en cambio, cada interacción es un request del cliente con una respuesta del servidor, y el servidor no puede hablar por iniciativa propia. Eso hace a WebSocket ideal para chat, colaboración en tiempo real, juegos, notificaciones o dashboards en vivo. El costo es que el servidor mantiene estado por conexión (memoria, un socket abierto por cliente), la conexión se puede cortar en cualquier momento (redes móviles, proxies que cierran conexiones inactivas, deploys), y cosas que HTTP resuelve solo (caching, reintentos, status codes, balanceo por request) hay que resolverlas a mano.",
    respuestaEn:
      "It starts as a normal HTTP request with an `Upgrade: websocket` header; if the server accepts, it responds `101 Switching Protocols` and from then on the same TCP connection stays open as a persistent bidirectional channel where either side can send messages (text or binary frames) at any time, with very little per-message overhead. In HTTP, by contrast, every interaction is a client request with a server response, and the server can't speak on its own initiative. That makes WebSocket ideal for chat, real-time collaboration, games, notifications or live dashboards. The cost is that the server holds per-connection state (memory, an open socket per client), the connection can drop at any time (mobile networks, proxies closing idle connections, deploys), and things HTTP handles for free (caching, retries, status codes, per-request load balancing) must be solved by hand.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué pasa con los mensajes que se emiten mientras un cliente está desconectado?",
    respuestaEs:
      "Por defecto se pierden: un WebSocket es un canal en vivo, no una cola. Si el cliente entra a un túnel, cambia de red o la pestaña queda suspendida, lo que el servidor emitió en ese lapso no le llega nunca. Para no perder información hay que diseñarlo: cada mensaje lleva un id secuencial o un timestamp, el cliente recuerda el último que procesó, y al reconectar lo manda para que el servidor le reenvíe lo que falta desde un buffer reciente (o que el cliente pida esos datos por un endpoint HTTP). Muchos sistemas usan un enfoque más simple y robusto: tratar el WebSocket solo como aviso ('hay novedades') y, al reconectar, volver a pedir el estado actual por HTTP. Como el replay suele reenviar algún mensaje ya visto, el cliente tiene que deduplicar por id: es entrega 'al menos una vez' más idempotencia del lado del cliente.",
    respuestaEn:
      "By default they're lost: a WebSocket is a live channel, not a queue. If the client enters a tunnel, switches networks or the tab gets suspended, what the server emitted during that time never reaches it. To avoid losing information you must design for it: each message carries a sequential id or timestamp, the client remembers the last one processed, and on reconnect sends it so the server replays what's missing from a recent buffer (or the client fetches that data via an HTTP endpoint). Many systems use a simpler, sturdier approach: treat the WebSocket only as a notification ('there's news') and, on reconnect, refetch the current state over HTTP. Since replay usually resends some already-seen message, the client must deduplicate by id: it's 'at least once' delivery plus client-side idempotency.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo manejás la reconexión del lado del cliente y la detección de conexiones muertas?",
    respuestaEs:
      "La reconexión tiene que ser automática, con backoff exponencial y jitter (esperar 1 s, 2 s, 4 s... con un componente aleatorio y un máximo): si el servidor se reinicia o cae, miles de clientes reconectando todos a la vez en el mismo instante generan un pico que puede volver a tirarlo (thundering herd). Al reconectar hay que re-autenticar, volver a suscribirse a los canales o salas, y resincronizar lo perdido. Para detectar conexiones muertas, TCP no alcanza: una conexión puede quedar 'abierta' en un extremo aunque el otro ya no exista (el celular perdió señal sin cerrar el socket). Por eso se usan HEARTBEATS: el servidor manda un ping cada N segundos (los frames ping/pong del protocolo o un mensaje propio) y, si no recibe respuesta en un plazo, cierra la conexión y libera sus recursos; el cliente hace lo mismo para darse cuenta de que tiene que reconectar. Además, muchos proxies y balanceadores cierran conexiones inactivas después de un tiempo, y el heartbeat las mantiene vivas.",
    respuestaEn:
      "Reconnection must be automatic, with exponential backoff and jitter (wait 1 s, 2 s, 4 s... with a random component and a cap): if the server restarts or goes down, thousands of clients reconnecting at the same instant create a spike that can knock it down again (thundering herd). On reconnect you must re-authenticate, resubscribe to channels or rooms, and resync what was missed. To detect dead connections, TCP isn't enough: a connection can stay 'open' on one end even though the other no longer exists (the phone lost signal without closing the socket). So HEARTBEATS are used: the server sends a ping every N seconds (the protocol's ping/pong frames or a custom message) and, if there's no reply within a deadline, closes the connection and frees its resources; the client does the same to realize it must reconnect. Many proxies and load balancers also close idle connections after a while, and the heartbeat keeps them alive.",
    codigo: `function reconectar(intento = 0) {
  const espera = Math.min(30_000, 1000 * 2 ** intento) * (0.5 + Math.random());
  setTimeout(() => {
    const ws = new WebSocket(url);
    ws.onopen = () => ws.send(JSON.stringify({ tipo: "resync", desde: ultimoId }));
    ws.onclose = () => reconectar(intento + 1);
  }, espera);
}`,
  },
  {
    nivel: 2,
    pregunta: "¿Cómo autenticás y autorizás una conexión WebSocket?",
    respuestaEs:
      "La API de WebSocket del navegador no permite headers custom, así que no se puede mandar un `Authorization: Bearer`. Las opciones: usar la cookie de sesión, que el navegador manda automáticamente en el handshake (es la más simple y consistente con una app que ya usa cookies HttpOnly), verificando además el header `Origin` para evitar cross-site WebSocket hijacking, ya que las cookies viajan aunque la página que abre la conexión sea de otro sitio; o pedir primero un token de un solo uso y corta duración por HTTP (autenticado) y mandarlo en la query string del handshake o en el primer mensaje. Evitar poner tokens de larga duración en la URL, porque quedan en logs de proxies. La autenticación se valida en el handshake, antes de aceptar la conexión. Y la autorización es por mensaje o por suscripción: que el usuario esté conectado no significa que pueda unirse a cualquier sala o recibir cualquier evento, así que cada suscripción se verifica contra sus permisos, igual que un endpoint HTTP. Si la sesión se revoca, hay que poder cerrar sus conexiones abiertas.",
    respuestaEn:
      "The browser WebSocket API doesn't allow custom headers, so you can't send `Authorization: Bearer`. Options: use the session cookie, which the browser sends automatically in the handshake (the simplest and consistent with an app already using HttpOnly cookies), also checking the `Origin` header to prevent cross-site WebSocket hijacking, since cookies travel even when the page opening the connection is from another site; or first request a short-lived single-use token over (authenticated) HTTP and send it in the handshake query string or first message. Avoid putting long-lived tokens in the URL, since they end up in proxy logs. Authentication is validated at the handshake, before accepting the connection. And authorization is per message or per subscription: being connected doesn't mean the user may join any room or receive any event, so each subscription is checked against their permissions, just like an HTTP endpoint. If the session is revoked, you must be able to close its open connections.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es el backpressure en una conexión WebSocket y cómo lo manejás?",
    respuestaEs:
      "Ocurre cuando el servidor produce mensajes más rápido de lo que un cliente puede recibirlos: un cliente en una red móvil lenta suscripto a un feed de precios que emite 100 actualizaciones por segundo. Los mensajes que no se pueden enviar se acumulan en el buffer de escritura del socket en el servidor (en `ws` se ve en `bufferedAmount`), y si nadie lo controla, la memoria crece sin límite y un puñado de clientes lentos puede tumbar el proceso. Estrategias: vigilar el buffer y, al superar un umbral, dejar de mandar a ese cliente, descartar mensajes intermedios quedándose con el último estado (para datos donde solo importa el valor actual, como un precio o una posición), agrupar o muestrear (mandar como mucho N actualizaciones por segundo por cliente), o directamente desconectar a los clientes que no dan abasto y que se resincronicen al reconectar. La decisión depende de si cada mensaje importa (un chat: no se descarta) o solo el estado final (un marcador en vivo: sí).",
    respuestaEn:
      "It happens when the server produces messages faster than a client can receive them: a client on a slow mobile network subscribed to a price feed emitting 100 updates per second. Unsendable messages pile up in the socket's write buffer on the server (visible in `ws` as `bufferedAmount`), and if nobody controls it, memory grows unbounded and a handful of slow clients can bring the process down. Strategies: monitor the buffer and, past a threshold, stop sending to that client; drop intermediate messages keeping the latest state (for data where only the current value matters, like a price or a position); batch or sample (send at most N updates per second per client); or simply disconnect clients that can't keep up and let them resync on reconnect. The choice depends on whether every message matters (a chat: don't drop) or only the final state (a live scoreboard: do).",
  },
  {
    nivel: 3,
    pregunta: "¿Qué garantías de entrega tiene un WebSocket y cómo construís algo más confiable?",
    respuestaEs:
      "El protocolo corre sobre TCP, así que mientras la conexión vive, los mensajes llegan en orden y sin corrupción. Pero no hay garantía de que un mensaje enviado haya sido PROCESADO por la aplicación del otro lado: si la conexión se corta, no sabés qué llegó y qué no, así que en la práctica es 'como mucho una vez'. Para algo más confiable hay que agregar capas: ids secuenciales por mensaje o por canal; ACKs de aplicación (el cliente confirma los ids procesados y el servidor reintenta los no confirmados); persistencia de los mensajes importantes en una base o un stream (Redis Streams, Kafka) para poder hacer replay desde cualquier punto; y deduplicación por id en quien recibe, porque los reintentos pueden duplicar. Eso da 'al menos una vez' más idempotencia, que en la práctica funciona como 'exactamente una vez'. Muchos servicios administrados (Pusher, Ably, Supabase Realtime) ofrecen parte de esto (historial, reconexión con recuperación) y ahorran construirlo desde cero.",
    respuestaEn:
      "The protocol runs over TCP, so while the connection lives, messages arrive in order and uncorrupted. But there's no guarantee a sent message was PROCESSED by the application on the other side: if the connection drops, you don't know what arrived and what didn't, so in practice it's 'at most once'. For something more reliable you add layers: sequential ids per message or channel; application-level ACKs (the client confirms processed ids and the server retries unconfirmed ones); persisting important messages in a database or stream (Redis Streams, Kafka) to replay from any point; and deduplication by id on the receiver, since retries may duplicate. That yields 'at least once' plus idempotency, which in practice works like 'exactly once'. Many managed services (Pusher, Ably, Supabase Realtime) offer part of this (history, reconnection with recovery) and save building it from scratch.",
  },
];
