import type { PreguntaEntrevista } from "../types";

export const entrevistaPiramideTesting: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es la pirámide de testing y qué idea transmite?",
    respuestaEs:
      "Es un modelo para distribuir el esfuerzo de testing en capas: en la base muchos tests unitarios, en el medio menos tests de integración y arriba pocos tests end-to-end. La idea es que cuanto más alto en la pirámide, más confianza da cada test (porque ejercita más partes reales del sistema juntas), pero también es más lento, más caro de escribir y mantener, más frágil y más difícil de diagnosticar cuando falla. Los unitarios corren en milisegundos y señalan exactamente qué se rompió; un e2e tarda segundos, depende de navegador, red y datos, y cuando falla hay que investigar dónde. Por eso conviene cubrir la mayor parte de la lógica abajo, donde es barato, y reservar los e2e para los flujos críticos de negocio. Debajo de todo suele agregarse una capa de análisis estático (TypeScript, ESLint), que atrapa errores sin escribir un solo test.",
    respuestaEn:
      "It's a model for distributing testing effort in layers: many unit tests at the base, fewer integration tests in the middle and few end-to-end tests at the top. The idea is that the higher up, the more confidence each test gives (since it exercises more real parts of the system together), but it's also slower, costlier to write and maintain, more brittle and harder to diagnose when it fails. Unit tests run in milliseconds and point exactly at what broke; an e2e takes seconds, depends on browser, network and data, and when it fails you have to investigate where. So most logic should be covered at the bottom, where it's cheap, reserving e2e tests for critical business flows. A static analysis layer (TypeScript, ESLint) is often added underneath, catching errors without writing a single test.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué es el antipatrón del 'cono de helado'?",
    respuestaEs:
      "Es la pirámide invertida: pocos o ningún test unitario, algunos de integración y la mayoría del testing en e2e automatizados o, peor, en pruebas manuales. Suele aparecer en equipos que agregan tests 'desde afuera' sobre código difícil de testear por partes. Los síntomas son una suite que tarda decenas de minutos o horas, que falla seguido sin que haya bugs (flakiness), cuyos fallos cuesta ubicar, y que por lo tanto el equipo termina ignorando o re-ejecutando hasta que pase. El feedback llega tarde, justo lo contrario de lo que se busca. Salir de ahí implica refactorizar para separar la lógica de la UI y de la infraestructura, así se puede testear barato, y convertir los e2e redundantes en tests de nivel más bajo, dejando solo los que cubren flujos críticos.",
    respuestaEn:
      "It's the inverted pyramid: few or no unit tests, some integration tests and most testing in automated e2e or, worse, manual testing. It tends to appear in teams that add tests 'from the outside' over code that's hard to test in parts. Symptoms are a suite taking tens of minutes or hours, frequently failing with no bugs (flakiness), whose failures are hard to pinpoint, and which the team therefore ends up ignoring or re-running until it passes. Feedback arrives late, the opposite of the goal. Getting out means refactoring to separate logic from UI and infrastructure so it can be tested cheaply, and converting redundant e2e tests into lower-level ones, keeping only those covering critical flows.",
  },
  {
    nivel: 2,
    pregunta: "¿Pirámide o 'testing trophy'? ¿Qué cambia?",
    respuestaEs:
      "El testing trophy (propuesto por Kent C. Dodds) pone el grueso del esfuerzo en tests de INTEGRACIÓN, con análisis estático en la base, unitarios en un volumen menor y pocos e2e arriba. El argumento es que en frontend muchos unitarios terminan probando detalles de implementación (que se llamó tal función, qué estado interno tiene un componente) y se rompen con cada refactor sin encontrar bugs reales, mientras que un test de integración que renderiza varios componentes juntos, con la red simulada, y los usa como un usuario da mucha más confianza por test sin llegar al costo de un e2e. No contradice la pirámide en lo esencial (menos e2e, feedback rápido); cambia dónde está el punto óptimo según el tipo de código. En lógica de dominio pura, algoritmos o librerías, la pirámide clásica sigue siendo ideal; en UIs que coordinan muchas piezas, el trofeo suele rendir más.",
    respuestaEn:
      "The testing trophy (proposed by Kent C. Dodds) puts most effort into INTEGRATION tests, with static analysis at the base, a smaller volume of unit tests and few e2e at the top. The argument is that in frontend many unit tests end up testing implementation details (that some function was called, a component's internal state) and break on every refactor without finding real bugs, while an integration test rendering several components together, with the network mocked, and using them like a user gives much more confidence per test without reaching e2e cost. It doesn't contradict the pyramid in essence (fewer e2e, fast feedback); it changes where the sweet spot is depending on the kind of code. For pure domain logic, algorithms or libraries, the classic pyramid is still ideal; for UIs coordinating many pieces, the trophy usually pays off more.",
    tradeoffs:
      "Los tests de integración dan más confianza por test pero, cuando fallan, localizan peor el problema que un unitario. La combinación sensata: unitarios para lógica con muchos casos, integración para flujos de UI.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué hacés con los tests flaky?",
    respuestaEs:
      "Tratarlos como un problema serio, porque destruyen la confianza en el CI: si una corrida roja 'seguro es el flaky', el día que falle por un bug real nadie lo va a mirar. Primero, medirlos: registrar qué tests fallan y pasan sin cambios de código. Segundo, poner en cuarentena al flaky conocido (se sigue ejecutando pero no bloquea el merge) con un responsable y un plazo, en vez de dejarlo romper el build o borrarlo en silencio. Tercero, arreglar la causa, que casi siempre es una de estas: esperas por tiempo fijo en vez de esperar una condición, dependencia del orden de ejecución o de estado compartido entre tests, datos no aislados, dependencia de la hora o de servicios externos reales, o animaciones. Los reintentos automáticos (retries) sirven como parche para no bloquear al equipo, pero esconden el problema si no se reportan: un test que pasa al segundo intento sigue siendo flaky.",
    respuestaEn:
      "Treat them as a serious problem, because they destroy trust in CI: if a red run 'is surely the flaky one', the day it fails from a real bug nobody will look. First, measure them: record which tests fail and pass with no code changes. Second, quarantine the known flaky test (it still runs but doesn't block merges) with an owner and deadline, rather than letting it break the build or silently deleting it. Third, fix the cause, which is almost always one of these: fixed-time waits instead of waiting for a condition, dependence on execution order or shared state between tests, non-isolated data, dependence on the clock or real external services, or animations. Automatic retries help as a patch so the team isn't blocked, but they hide the problem if not reported: a test that passes on the second try is still flaky.",
  },
  {
    nivel: 3,
    pregunta: "¿Por qué la cobertura de código es una mala meta, y qué la complementa?",
    respuestaEs:
      "Porque mide qué líneas se EJECUTARON durante los tests, no qué se VERIFICÓ. Un test que llama a una función sin ningún `expect` sube la cobertura igual que uno bueno. Cuando se fija como meta obligatoria (por ejemplo 90%), aparece la ley de Goodhart: la métrica deja de ser útil porque el equipo optimiza para ella, escribiendo tests triviales de getters o de código sin lógica mientras las ramas difíciles siguen sin verificar. La cobertura sirve como señal inversa: una zona crítica con 20% de cobertura seguro está sin probar. Para medir la calidad de los tests existe el mutation testing (Stryker en JavaScript): la herramienta introduce pequeños cambios en el código (cambiar un `>` por `>=`, borrar una línea) y verifica que algún test falle; si ninguno falla, el 'mutante sobrevivió' y hay un comportamiento sin verificar. Es caro de correr, así que se aplica a los módulos más críticos.",
    respuestaEn:
      "Because it measures which lines EXECUTED during tests, not what was VERIFIED. A test calling a function without any `expect` raises coverage as much as a good one. When set as a mandatory target (e.g. 90%), Goodhart's law kicks in: the metric stops being useful because the team optimizes for it, writing trivial tests for getters or logic-free code while hard branches remain unverified. Coverage works as an inverse signal: a critical area at 20% coverage is surely untested. To measure test quality there's mutation testing (Stryker in JavaScript): the tool introduces small code changes (turning a `>` into `>=`, deleting a line) and checks that some test fails; if none fails, the 'mutant survived' and there's unverified behavior. It's expensive to run, so it's applied to the most critical modules.",
  },
  {
    nivel: 3,
    pregunta: "En una arquitectura de microservicios, ¿cómo evitás depender de e2e que levantan todos los servicios?",
    respuestaEs:
      "Los e2e que levantan todo el sistema escalan mal: son lentos, frágiles, requieren entornos compartidos que se rompen, y un servicio caído bloquea a todos los equipos. La alternativa son los contract tests (por ejemplo con Pact): el consumidor (el frontend o un servicio) define en sus tests qué requests hace y qué respuestas espera, eso genera un contrato, y el proveedor verifica en SU pipeline que cumple todos los contratos de sus consumidores, sin levantar al consumidor. Así cada servicio se testea de forma aislada y rápida, y un cambio que rompe a un consumidor se detecta en el CI del proveedor antes del deploy. Se complementa con unos pocos e2e de humo sobre los flujos críticos en un entorno integrado, y con observabilidad en producción (monitoreo sintético, alertas, feature flags para desplegar de forma gradual), que asume que algunos problemas solo aparecen con tráfico real.",
    respuestaEn:
      "E2e tests spinning up the whole system scale poorly: they're slow, brittle, need shared environments that break, and one down service blocks every team. The alternative is contract tests (e.g. with Pact): the consumer (the frontend or a service) defines in its tests which requests it makes and which responses it expects, generating a contract, and the provider verifies in ITS pipeline that it fulfills all its consumers' contracts, without spinning up the consumer. Each service is tested in isolation and fast, and a change breaking a consumer is caught in the provider's CI before deploy. It's complemented by a few smoke e2e tests on critical flows in an integrated environment, and by production observability (synthetic monitoring, alerts, feature flags for gradual rollout), acknowledging that some problems only show up with real traffic.",
  },
];
