import type { PreguntaEntrevista } from "../types";

export const entrevistaCapConsistencia: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué dice el teorema CAP?",
    respuestaEs:
      "Que un sistema distribuido que replica datos entre nodos no puede garantizar a la vez tres propiedades: CONSISTENCIA (toda lectura ve la última escritura confirmada, como si hubiera una sola copia), DISPONIBILIDAD (todo nodo que funciona responde a cada request) y TOLERANCIA A PARTICIONES (el sistema sigue operando aunque se corte la comunicación entre nodos). La lectura habitual de 'elegí dos de tres' es engañosa: en una red real las particiones pasan, así que la P no es opcional. Lo que el teorema dice en realidad es que CUANDO hay una partición, hay que elegir: o un nodo que no puede hablar con los demás deja de responder para no devolver datos viejos (consistencia, CP), o responde con lo que tiene, aunque pueda estar desactualizado o divergir (disponibilidad, AP). Mientras la red funciona, un sistema puede ser consistente y disponible a la vez. Por eso CAP no clasifica bases de datos de forma absoluta: describe qué hace el sistema en el peor momento.",
    respuestaEn:
      "That a distributed system replicating data across nodes can't simultaneously guarantee three properties: CONSISTENCY (every read sees the latest confirmed write, as if there were a single copy), AVAILABILITY (every working node answers every request) and PARTITION TOLERANCE (the system keeps operating even if communication between nodes is cut). The usual 'pick two of three' reading is misleading: in a real network partitions happen, so P isn't optional. What the theorem actually says is that WHEN there's a partition, you must choose: either a node that can't talk to the others stops answering to avoid returning stale data (consistency, CP), or it answers with what it has, even if outdated or diverging (availability, AP). While the network works, a system can be both consistent and available. That's why CAP doesn't classify databases absolutely: it describes what the system does at the worst moment.",
  },
  {
    nivel: 1,
    pregunta: "En la práctica, ¿cuándo elegís consistencia y cuándo disponibilidad?",
    respuestaEs:
      "Según qué es peor para el negocio: un error o un dato incorrecto. Se elige CONSISTENCIA cuando actuar sobre un dato viejo causa daño real: saldos y transferencias (no se puede gastar dos veces el mismo dinero), stock al vender la última unidad, reservas de asientos, unicidad de un nombre de usuario, locks distribuidos. Ahí es preferible responder 'no disponible, reintentá' antes que confirmar algo falso. Se elige DISPONIBILIDAD cuando un dato un poco desactualizado es tolerable y no responder es peor: un carrito de compras (mejor agregar el producto y reconciliar después que mostrar un error), contadores de likes o vistas, feeds, recomendaciones, métricas. Además, la decisión no es para todo el sistema: una misma aplicación puede usar una base consistente para pagos y un almacén disponible para el feed. En una entrevista, lo valioso es explicar qué pasaría en cada caso ante una partición y por qué ese comportamiento es el correcto para ese dato.",
    respuestaEn:
      "Based on what's worse for the business: an error or wrong data. You choose CONSISTENCY when acting on stale data causes real harm: balances and transfers (you can't spend the same money twice), stock when selling the last unit, seat reservations, username uniqueness, distributed locks. There it's better to answer 'unavailable, retry' than to confirm something false. You choose AVAILABILITY when slightly stale data is tolerable and not answering is worse: a shopping cart (better to add the item and reconcile later than show an error), like or view counters, feeds, recommendations, metrics. And the decision isn't system-wide: one application can use a consistent database for payments and an available store for the feed. In an interview, what's valuable is explaining what would happen in each case during a partition and why that behavior is right for that data.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué agrega PACELC a CAP, y qué es la consistencia configurable por quórum?",
    respuestaEs:
      "CAP solo habla del comportamiento durante una partición, que es poco frecuente. PACELC completa la otra mitad: si hay Partición, elegís entre Availability y Consistency; Else, en funcionamiento normal, elegís entre Latency y Consistency. Porque aun sin fallas, garantizar consistencia fuerte exige esperar a que otras réplicas confirmen cada escritura, y eso suma latencia, sobre todo entre regiones. Muchos sistemas relajan la consistencia no por las particiones sino por la latencia de todos los días. Una forma de elegir por operación es la CONSISTENCIA POR QUÓRUM (Dynamo, Cassandra): con N réplicas, una escritura espera la confirmación de W y una lectura consulta R. Si R + W > N, los conjuntos de lectura y escritura siempre se superponen, y la lectura ve la última escritura confirmada. Con N = 3, W = 2 y R = 2 hay consistencia y se tolera la caída de una réplica; con W = 1 y R = 1 todo es más rápido y disponible, pero una lectura puede devolver un dato viejo. Así se ajusta el punto entre latencia y consistencia según cada caso de uso.",
    respuestaEn:
      "CAP only covers behavior during a partition, which is rare. PACELC completes the other half: if there's a Partition, choose between Availability and Consistency; Else, in normal operation, choose between Latency and Consistency. Because even without failures, guaranteeing strong consistency requires waiting for other replicas to confirm each write, which adds latency, especially across regions. Many systems relax consistency not because of partitions but because of everyday latency. One way to choose per operation is QUORUM CONSISTENCY (Dynamo, Cassandra): with N replicas, a write waits for W confirmations and a read queries R. If R + W > N, the read and write sets always overlap, and the read sees the latest confirmed write. With N = 3, W = 2 and R = 2 you get consistency and tolerate one replica down; with W = 1 and R = 1 everything is faster and more available, but a read may return stale data. That's how you tune the latency-consistency point per use case.",
    codigo: `N = 3 réplicas

W = 2, R = 2  →  R + W = 4 > 3   lectura y escritura se superponen: consistente
W = 1, R = 1  →  R + W = 2 ≤ 3   más rápido, pero la lectura puede ser vieja
W = 3, R = 1  →  lecturas rápidas y consistentes, pero una réplica caída frena las escrituras`,
    tradeoffs:
      "Más réplicas en el quórum dan más consistencia a cambio de latencia y de menos tolerancia a réplicas caídas.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué modelos de consistencia hay entre fuerte y eventual?",
    respuestaEs:
      "Es un espectro, no un sí o no. En un extremo, la consistencia FUERTE o linealizable: el sistema se comporta como si hubiera una sola copia y cada operación ocurre en un instante; es lo más fácil de razonar y lo más caro. En el otro, la EVENTUAL: si no hay más escrituras, las réplicas terminan convergiendo, pero mientras tanto una lectura puede devolver cualquier versión reciente. En el medio hay garantías más débiles que la fuerte pero muy útiles, y muchas se pueden dar por sesión de usuario, que es lo que el usuario percibe. READ-YOUR-WRITES: un usuario siempre ve sus propias escrituras (edita su perfil y lo ve actualizado). LECTURAS MONÓTONAS: un usuario nunca ve un dato más viejo después de haber visto uno más nuevo (no 'retrocede en el tiempo' al cambiar de réplica). CONSISTENCIA CAUSAL: si una operación depende de otra, todos las ven en ese orden (nadie ve la respuesta a un comentario antes que el comentario). Para la mayoría de las aplicaciones, read-your-writes más consistencia causal alcanzan para que la experiencia sea correcta, sin pagar el costo de la consistencia fuerte en todo.",
    respuestaEn:
      "It's a spectrum, not yes or no. At one end, STRONG or linearizable consistency: the system behaves as if there were a single copy and each operation happens at an instant; easiest to reason about and most expensive. At the other, EVENTUAL: if there are no more writes, replicas eventually converge, but meanwhile a read can return any recent version. In between are guarantees weaker than strong but very useful, and many can be provided per user session, which is what the user perceives. READ-YOUR-WRITES: a user always sees their own writes (edits their profile and sees it updated). MONOTONIC READS: a user never sees older data after having seen newer data (no 'going back in time' when switching replicas). CAUSAL CONSISTENCY: if one operation depends on another, everyone sees them in that order (no one sees the reply to a comment before the comment). For most applications, read-your-writes plus causal consistency is enough for a correct experience, without paying for strong consistency everywhere.",
  },
  {
    nivel: 3,
    pregunta: "En un sistema AP, ¿cómo se resuelven los conflictos entre réplicas que divergieron?",
    respuestaEs:
      "Hay varias estrategias, con distinto costo y distinta pérdida de datos. LAST-WRITE-WINS: gana la escritura con el timestamp más nuevo. Es simple, pero descarta en silencio las demás escrituras concurrentes, y depende de relojes que en distintas máquinas nunca están perfectamente sincronizados, así que 'la última' puede no serlo. Sirve cuando perder una escritura concurrente es aceptable. VERSIONADO con relojes vectoriales: cada réplica lleva un contador por nodo; al comparar versiones se puede saber si una es sucesora de otra o si son CONCURRENTES, y en ese caso se conservan las dos para resolverlas, en vez de descartar una. RESOLUCIÓN EN LA APLICACIÓN: el sistema entrega las versiones en conflicto y la lógica de negocio las combina; el ejemplo clásico es un carrito que se une (la unión de los productos de ambas versiones), con el efecto secundario de que un producto borrado en una réplica puede reaparecer. CRDTs: estructuras de datos diseñadas para que cualquier orden de combinación dé el mismo resultado (contadores, conjuntos, textos colaborativos), convergiendo sin coordinación. Son la base de muchos editores colaborativos y apps local-first, a costa de estructuras más complejas y metadatos que crecen.",
    respuestaEn:
      "There are several strategies, with different costs and different data loss. LAST-WRITE-WINS: the write with the newest timestamp wins. It's simple, but silently discards other concurrent writes, and relies on clocks that are never perfectly synchronized across machines, so 'the last' may not be. It works when losing a concurrent write is acceptable. VERSIONING with vector clocks: each replica keeps a counter per node; comparing versions tells whether one descends from another or whether they're CONCURRENT, in which case both are kept for resolution instead of discarding one. APPLICATION-LEVEL RESOLUTION: the system returns the conflicting versions and business logic merges them; the classic example is a cart that's merged (the union of items from both versions), with the side effect that an item deleted on one replica can reappear. CRDTs: data structures designed so any merge order yields the same result (counters, sets, collaborative text), converging without coordination. They underpin many collaborative editors and local-first apps, at the cost of more complex structures and growing metadata.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo logra un sistema CP mantenerse consistente ante fallas? ¿Qué es el consenso?",
    respuestaEs:
      "Con un algoritmo de CONSENSO como Raft o Paxos, que permite que un grupo de nodos acuerde una única secuencia de operaciones aunque algunos fallen. La idea central es el QUÓRUM por mayoría: una operación se confirma cuando la aceptan más de la mitad de los nodos. Como dos mayorías siempre comparten al menos un nodo, es imposible que dos lados de una partición confirmen decisiones contradictorias; el lado minoritario simplemente no puede avanzar. De ahí que los clusters tengan un número impar de nodos: con 2f + 1 nodos se toleran f fallas (3 nodos toleran 1, 5 toleran 2), y un cuarto nodo no agrega tolerancia respecto de tres. En Raft, un nodo es LÍDER elegido por mayoría, todas las escrituras pasan por él y se replican a los seguidores; si el líder cae, los demás eligen uno nuevo, y un número de mandato (term) evita que un líder viejo que quedó aislado siga aceptando escrituras, lo que sería split brain. El costo: cada escritura espera a la mayoría (latencia), y el grupo no está disponible si pierde la mayoría. Por eso el consenso no se usa para todos los datos, sino para lo que necesita un acuerdo inequívoco: configuración, elección de líder, locks y metadatos, con herramientas como etcd, ZooKeeper o Consul, y dentro de bases distribuidas como CockroachDB.",
    respuestaEn:
      "With a CONSENSUS algorithm like Raft or Paxos, which lets a group of nodes agree on a single sequence of operations even if some fail. The core idea is majority QUORUM: an operation is committed when more than half the nodes accept it. Since any two majorities always share at least one node, it's impossible for two sides of a partition to commit contradictory decisions; the minority side simply can't make progress. That's why clusters have an odd number of nodes: with 2f + 1 nodes you tolerate f failures (3 nodes tolerate 1, 5 tolerate 2), and a fourth node adds no tolerance over three. In Raft, one node is the LEADER elected by majority, all writes go through it and are replicated to followers; if the leader dies, the others elect a new one, and a term number keeps an old leader that got isolated from still accepting writes, which would be split brain. The cost: every write waits for the majority (latency), and the group is unavailable if it loses the majority. That's why consensus isn't used for all data, but for what needs unambiguous agreement: configuration, leader election, locks and metadata, with tools like etcd, ZooKeeper or Consul, and inside distributed databases like CockroachDB.",
  },
];
