import type { PreguntaEntrevista } from "../types";

export const entrevistaColasPubSub: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué diferencia hay entre una cola, un pub/sub y un log como Kafka?",
    respuestaEs:
      "Son tres modelos de entrega distintos. Una COLA (SQS, RabbitMQ con una cola, BullMQ) reparte trabajo: cada mensaje lo procesa UN solo consumidor, y cuando lo confirma, desaparece. Sirve para distribuir tareas entre varios workers: enviar emails, procesar imágenes. Un PUB/SUB (SNS, Google Pub/Sub, un exchange fanout de RabbitMQ) difunde: cada mensaje publicado en un tópico llega a TODOS los suscriptores, cada uno con su propia copia. Sirve para que varios sistemas reaccionen al mismo hecho: un pedido creado lo reciben facturación, envíos y analítica. Un LOG distribuido (Kafka, Kinesis, Redpanda) guarda los mensajes en orden durante un tiempo configurable, sin borrarlos al consumirlos; cada grupo de consumidores lleva su propia posición (offset) y puede releer desde cualquier punto. Combina los dos modelos anteriores: dentro de un grupo, los consumidores se reparten el trabajo como en una cola; entre grupos, cada uno recibe todo como en pub/sub. Y agrega algo que los otros no tienen: poder reprocesar el historial, por ejemplo para alimentar un sistema nuevo o corregir un bug volviendo a consumir los eventos de la última semana.",
    respuestaEn:
      "They're three different delivery models. A QUEUE (SQS, RabbitMQ with one queue, BullMQ) distributes work: each message is processed by ONE consumer, and once acknowledged, it's gone. It's for spreading tasks across workers: sending emails, processing images. PUB/SUB (SNS, Google Pub/Sub, a RabbitMQ fanout exchange) broadcasts: each message published on a topic reaches ALL subscribers, each with its own copy. It's for letting several systems react to the same fact: an order created is received by billing, shipping and analytics. A distributed LOG (Kafka, Kinesis, Redpanda) stores messages in order for a configurable time, without deleting them when consumed; each consumer group tracks its own position (offset) and can re-read from any point. It combines the previous two models: within a group, consumers share the work like a queue; across groups, each receives everything like pub/sub. And it adds something the others lack: the ability to reprocess history, for example to feed a new system or fix a bug by re-consuming the last week's events.",
  },
  {
    nivel: 1,
    pregunta: "SQS, SNS, RabbitMQ o Kafka: ¿cómo elegís?",
    respuestaEs:
      "Por el modelo que necesitás y por cuánto querés operar. SQS: una cola totalmente gestionada, sin nada que administrar, que escala sola y se integra con Lambda; es el default para distribuir trabajo en AWS. Su variante FIFO garantiza orden y deduplicación por grupo de mensajes, con menos throughput. SNS: pub/sub gestionado; el patrón típico es SNS con varias colas SQS suscriptas (fan-out), así cada consumidor tiene su propia cola con reintentos y DLQ independientes. RABBITMQ: un broker flexible con ruteo rico (por clave, por patrones, por headers), prioridades y confirmaciones finas; bueno para flujos de mensajería complejos con volumen moderado, a cambio de operarlo o pagarlo gestionado. KAFKA: un log de alto throughput con retención y replay, orden por partición y un ecosistema para procesamiento de streams; encaja con volúmenes muy grandes, event sourcing, pipelines de datos y cuando varios equipos consumen los mismos eventos a su ritmo. Su costo operativo y conceptual es el más alto (particiones, offsets, rebalanceos), aunque hay versiones gestionadas. Mi criterio: SQS y SNS para la mayoría de los casos en AWS; Kafka cuando el replay, el volumen o la cantidad de consumidores lo justifican.",
    respuestaEn:
      "By the model you need and how much you want to operate. SQS: a fully managed queue, nothing to administer, scales on its own and integrates with Lambda; it's the default for distributing work on AWS. Its FIFO variant guarantees ordering and deduplication per message group, with lower throughput. SNS: managed pub/sub; the typical pattern is SNS with several SQS queues subscribed (fan-out), so each consumer gets its own queue with independent retries and DLQ. RABBITMQ: a flexible broker with rich routing (by key, patterns, headers), priorities and fine-grained acknowledgments; good for complex messaging flows at moderate volume, at the cost of operating it or paying for a managed version. KAFKA: a high-throughput log with retention and replay, per-partition ordering and a stream processing ecosystem; it fits very large volumes, event sourcing, data pipelines and when several teams consume the same events at their own pace. Its operational and conceptual cost is the highest (partitions, offsets, rebalances), though managed versions exist. My criterion: SQS and SNS for most cases on AWS; Kafka when replay, volume or number of consumers justifies it.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué significan at-most-once, at-least-once y exactly-once?",
    respuestaEs:
      "Son las garantías de entrega posibles, y dependen de cuándo se confirma el mensaje. AT-MOST-ONCE: se confirma antes de procesarlo; si el consumidor se cae a mitad de camino, el mensaje se pierde, pero nunca se procesa dos veces. Solo sirve para datos donde perder algunos es aceptable, como métricas de bajo valor. AT-LEAST-ONCE: se confirma después de procesarlo; si el consumidor se cae antes de confirmar, el mensaje se vuelve a entregar, así que nunca se pierde pero puede procesarse más de una vez. Es la garantía por defecto de casi todos los sistemas (SQS estándar, Kafka con commit después de procesar). EXACTLY-ONCE de punta a punta, en general, no existe: entre 'procesé' y 'confirmé' siempre hay un momento donde una falla deja la duda. Lo que se logra en la práctica es un efecto exactly-once: entrega at-least-once más un consumidor idempotente, que detecta y descarta los duplicados. Kafka ofrece transacciones que dan exactly-once cuando se lee de un topic y se escribe en otro dentro de Kafka, pero en cuanto el efecto sale de Kafka (escribir en una base, llamar a una API, enviar un email), vuelve a depender de la idempotencia del consumidor.",
    respuestaEn:
      "They're the possible delivery guarantees, and depend on when the message is acknowledged. AT-MOST-ONCE: acknowledged before processing; if the consumer dies midway, the message is lost, but it's never processed twice. It only suits data where losing some is acceptable, like low-value metrics. AT-LEAST-ONCE: acknowledged after processing; if the consumer dies before acknowledging, the message is redelivered, so it's never lost but may be processed more than once. It's the default guarantee of almost every system (standard SQS, Kafka committing after processing). End-to-end EXACTLY-ONCE generally doesn't exist: between 'processed' and 'acknowledged' there's always a moment where a failure leaves doubt. What's achieved in practice is an exactly-once effect: at-least-once delivery plus an idempotent consumer that detects and drops duplicates. Kafka offers transactions giving exactly-once when reading from one topic and writing to another within Kafka, but as soon as the effect leaves Kafka (writing to a database, calling an API, sending an email), it again depends on the consumer's idempotency.",
    tradeoffs:
      "At-most-once pierde mensajes para evitar duplicados; at-least-once acepta duplicados para no perder; el efecto exactly-once se construye con idempotencia del lado del consumidor.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo garantizás el orden de los mensajes y qué cuesta?",
    respuestaEs:
      "El orden global, sobre todos los mensajes, es caro: implica un único punto de procesamiento, que no escala. Lo que casi siempre se necesita es orden POR ENTIDAD: los eventos de un mismo pedido en orden, aunque los de pedidos distintos se procesen en paralelo. En Kafka se logra con la CLAVE DE PARTICIÓN: todos los mensajes con la misma clave (el id del pedido) van a la misma partición, y dentro de una partición el orden se respeta. En SQS FIFO, con el MESSAGE GROUP ID: los mensajes del mismo grupo se entregan en orden y de a uno. Los costos: el paralelismo queda limitado por la cantidad de particiones o de grupos activos; una clave muy frecuente (un cliente enorme) concentra carga en una partición caliente mientras las demás están ociosas; y un mensaje que falla bloquea a los siguientes de su misma clave, porque saltearlo rompería el orden, lo que obliga a decidir entre reintentar indefinidamente o mandarlo a una DLQ aceptando el desorden. También se pierde el orden si los reintentos se hacen reencolando al final. Por eso conviene preguntar si el orden es realmente necesario: muchas veces alcanza con que el consumidor detecte eventos viejos por número de versión y los ignore.",
    respuestaEn:
      "Global ordering, across all messages, is expensive: it means a single processing point, which doesn't scale. What's almost always needed is PER-ENTITY ordering: one order's events in sequence, while different orders' events are processed in parallel. In Kafka you get it with the PARTITION KEY: every message with the same key (the order id) goes to the same partition, and within a partition order is preserved. In SQS FIFO, with the MESSAGE GROUP ID: messages in the same group are delivered in order, one at a time. The costs: parallelism is capped by the number of partitions or active groups; a very frequent key (a huge customer) concentrates load on a hot partition while others idle; and a failing message blocks the following ones with the same key, since skipping it would break order, forcing a choice between retrying indefinitely or sending it to a DLQ and accepting disorder. Order is also lost if retries requeue at the end. That's why it's worth asking whether order is truly needed: often it's enough for the consumer to detect stale events by version number and ignore them.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo escalan los consumidores en Kafka y qué es el consumer lag?",
    respuestaEs:
      "Un topic se divide en particiones, y un CONSUMER GROUP reparte esas particiones entre sus miembros: cada partición la lee exactamente un consumidor del grupo. Por eso la cantidad de particiones es el techo de paralelismo: con 6 particiones, un séptimo consumidor queda ocioso. Agregar particiones después es posible pero cambia a qué partición va cada clave, lo que rompe el orden por clave durante la transición, así que conviene dimensionarlas con margen desde el principio. Cuando un consumidor entra o sale del grupo hay un REBALANCEO: se redistribuyen las particiones, y durante ese momento el consumo se frena; consumidores que tardan demasiado en procesar un lote pueden ser expulsados por el grupo y provocar rebalanceos en cadena. El CONSUMER LAG es la diferencia entre el último mensaje escrito en una partición y el último que el grupo confirmó: cuánto está atrasado. Es la métrica central de un sistema de mensajería: si crece de forma sostenida, los consumidores no dan abasto y hay que escalar (hasta el límite de particiones) u optimizar el procesamiento. Y como Kafka retiene por tiempo o tamaño, un lag que supera la retención significa mensajes que se borran antes de ser leídos.",
    respuestaEn:
      "A topic is split into partitions, and a CONSUMER GROUP distributes those partitions among its members: each partition is read by exactly one consumer in the group. So the partition count is the parallelism ceiling: with 6 partitions, a seventh consumer sits idle. Adding partitions later is possible but changes which partition each key maps to, breaking per-key ordering during the transition, so it's worth sizing them with headroom from the start. When a consumer joins or leaves the group there's a REBALANCE: partitions are redistributed, and consumption pauses meanwhile; consumers that take too long on a batch can be kicked out of the group and cause cascading rebalances. CONSUMER LAG is the difference between the last message written to a partition and the last one the group committed: how far behind it is. It's the core metric of a messaging system: if it grows steadily, consumers can't keep up and you must scale (up to the partition limit) or optimize processing. And since Kafka retains by time or size, a lag exceeding retention means messages deleted before being read.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué pasa en SQS con el visibility timeout, y cómo manejás mensajes que tardan o fallan?",
    respuestaEs:
      "En SQS, cuando un consumidor recibe un mensaje, este no se borra: se vuelve invisible para los demás durante el VISIBILITY TIMEOUT. Si el consumidor lo borra antes de que venza, se da por procesado; si no, el mensaje vuelve a ser visible y otro consumidor lo recibe. Es el mecanismo que da at-least-once. El problema aparece cuando el procesamiento tarda más que el timeout: el mensaje reaparece mientras el primer consumidor todavía trabaja en él, y dos consumidores lo procesan a la vez. Se evita con un timeout mayor al tiempo máximo esperado de procesamiento, o extendiéndolo desde el consumidor mientras trabaja (ChangeMessageVisibility), además de la idempotencia. Para los mensajes que fallan siempre, SQS cuenta cuántas veces se recibió cada uno y, pasado el máximo configurado, lo mueve a una DLQ, para que un mensaje envenenado no se reintente para siempre consumiendo capacidad. Otros detalles de operación: long polling para no pagar por recepciones vacías, lotes de hasta 10 mensajes para reducir costo y latencia, y alarmas sobre la antigüedad del mensaje más viejo, que es el equivalente del consumer lag.",
    respuestaEn:
      "In SQS, when a consumer receives a message, it isn't deleted: it becomes invisible to others for the VISIBILITY TIMEOUT. If the consumer deletes it before it expires, it's considered processed; otherwise the message becomes visible again and another consumer receives it. That's the mechanism giving at-least-once. The problem appears when processing takes longer than the timeout: the message reappears while the first consumer is still working on it, and two consumers process it at once. You avoid it with a timeout longer than the maximum expected processing time, or by extending it from the consumer while working (ChangeMessageVisibility), plus idempotency. For messages that always fail, SQS counts how many times each was received and, past the configured maximum, moves it to a DLQ, so a poison message isn't retried forever consuming capacity. Other operational details: long polling to avoid paying for empty receives, batches of up to 10 messages to cut cost and latency, and alarms on the age of the oldest message, the equivalent of consumer lag.",
  },
];
