import type { PreguntaEntrevista } from "../types";

export const entrevistaEjerciciosGuiados: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Cómo encarás una pregunta de system design de 45 minutos?",
    respuestaEs:
      "Con una estructura explícita, porque lo que se evalúa es cómo pensás, no si llegás a un diagrama perfecto. Primero REQUISITOS, unos 5 minutos: preguntar qué tiene que hacer (funcionales) y con qué calidad (latencia, disponibilidad, consistencia, escala), y acordar qué queda afuera. Un diseño sin requisitos claros es un diseño para nada en particular. Después una ESTIMACIÓN rápida de volumen: requests por segundo, relación de lecturas a escrituras, almacenamiento; son los números que van a justificar las decisiones. Luego la API y el MODELO DE DATOS: qué operaciones existen y cómo se accede a los datos, porque el patrón de acceso define el almacenamiento. Después la ARQUITECTURA de alto nivel: las piezas y el camino de las operaciones principales, empezando simple. Con eso armado, PROFUNDIZAR en una o dos partes difíciles, idealmente las que el entrevistador marque: la generación de ids, el fan-out, la consistencia. Y cerrar con TRADE-OFFS y riesgos: qué se eligió, qué se sacrificó y qué cambiaría con diez veces más escala. Durante todo el proceso, pensar en voz alta y confirmar con el entrevistador antes de profundizar.",
    respuestaEn:
      "With an explicit structure, because what's evaluated is how you think, not whether you reach a perfect diagram. First REQUIREMENTS, about 5 minutes: ask what it must do (functional) and with what quality (latency, availability, consistency, scale), and agree on what's out of scope. A design without clear requirements is a design for nothing in particular. Then a quick volume ESTIMATION: requests per second, read-to-write ratio, storage; these numbers will justify the decisions. Then the API and DATA MODEL: which operations exist and how data is accessed, because the access pattern defines storage. Then the high-level ARCHITECTURE: the pieces and the path of the main operations, starting simple. With that in place, DEEP DIVE into one or two hard parts, ideally the ones the interviewer points to: id generation, fan-out, consistency. And close with TRADE-OFFS and risks: what was chosen, what was sacrificed and what would change at ten times the scale. Throughout, think out loud and check in with the interviewer before going deep.",
  },
  {
    nivel: 1,
    pregunta: "En un acortador de URLs, ¿cómo generás los códigos cortos?",
    respuestaEs:
      "Hay tres enfoques, con distintos trade-offs. HASH de la URL (MD5 o SHA, tomando los primeros caracteres en base62): no necesita estado, pero truncar un hash genera colisiones que hay que detectar y resolver, y la misma URL siempre da el mismo código, lo que puede o no ser deseable (dos usuarios que acortan la misma URL comparten el código y sus estadísticas). CONTADOR convertido a base62: sin colisiones y con códigos cortos, pero secuencial, así que cualquiera puede recorrer todos los códigos y descubrir URLs privadas; y un contador central es un punto de coordinación. Se mitiga reservando rangos por instancia (cada servidor pide un bloque de un millón de números y los usa localmente) y aplicando una permutación reversible para que los códigos consecutivos no parezcan consecutivos. ALEATORIO: generar 7 caracteres base62 al azar e insertar con una restricción UNIQUE, reintentando si choca. Con 3,5 billones de combinaciones y unos miles de millones de URLs, las colisiones son rarísimas, no hay coordinación ni códigos predecibles. Para el volumen típico de este ejercicio, el aleatorio con UNIQUE es la opción más simple y robusta; los rangos pre-asignados aparecen si la escala de escritura fuera mucho mayor.",
    respuestaEn:
      "There are three approaches, with different trade-offs. HASHING the URL (MD5 or SHA, taking the first characters in base62): stateless, but truncating a hash causes collisions that must be detected and resolved, and the same URL always yields the same code, which may or may not be desirable (two users shortening the same URL share the code and its stats). A COUNTER converted to base62: no collisions and short codes, but sequential, so anyone can walk every code and discover private URLs; and a central counter is a coordination point. Mitigated by reserving ranges per instance (each server takes a block of a million numbers and uses them locally) and applying a reversible permutation so consecutive codes don't look consecutive. RANDOM: generate 7 random base62 characters and insert with a UNIQUE constraint, retrying on collision. With 3.5 trillion combinations and a few billion URLs, collisions are extremely rare, with no coordination or predictable codes. For this exercise's typical volume, random with UNIQUE is the simplest and sturdiest option; pre-assigned ranges come in if write scale were far larger.",
  },
  {
    nivel: 2,
    pregunta: "Para un feed social, ¿fan-out on write o fan-out on read?",
    respuestaEs:
      "Depende de la forma del grafo, y la respuesta madura es un híbrido. FAN-OUT ON WRITE: cuando alguien publica, un proceso asíncrono agrega el id del post al feed precalculado de cada seguidor. Leer el feed es tan barato como leer una lista, ideal porque las lecturas superan por mucho a las escrituras. El problema son las cuentas con millones de seguidores: un solo post genera millones de escrituras, tarda en propagarse y consume muchísimos recursos, y además se gasta trabajo en usuarios inactivos que nunca van a leerlo. FAN-OUT ON READ: al leer, se buscan los posts recientes de cada cuenta seguida y se combinan. Publicar es barato, pero leer es caro y lento para quien sigue a cientos de cuentas, justo en la operación más frecuente. HÍBRIDO: fan-out on write para la gran mayoría de las cuentas, y fan-out on read solo para las celebridades, cuyos posts se buscan al leer y se mezclan con el feed precalculado. Así se acota la amplificación de escritura sin castigar la latencia de lectura. Sumado a eso: no precalcular feeds de usuarios inactivos, y guardar solo ids en los feeds, hidratando los posts desde una caché al leer.",
    respuestaEn:
      "It depends on the graph's shape, and the mature answer is a hybrid. FAN-OUT ON WRITE: when someone posts, an async process appends the post id to each follower's precomputed feed. Reading the feed is as cheap as reading a list, ideal since reads far outnumber writes. The problem is accounts with millions of followers: one post triggers millions of writes, takes a while to propagate and consumes huge resources, and work is also spent on inactive users who'll never read it. FAN-OUT ON READ: on read, fetch the recent posts of each followed account and merge them. Posting is cheap, but reading is expensive and slow for someone following hundreds of accounts, right on the most frequent operation. HYBRID: fan-out on write for the vast majority of accounts, and fan-out on read only for celebrities, whose posts are fetched at read time and merged with the precomputed feed. That bounds write amplification without hurting read latency. On top of that: don't precompute feeds for inactive users, and store only ids in feeds, hydrating posts from a cache on read.",
    tradeoffs:
      "On write: lecturas baratas a cambio de amplificación de escritura. On read: escrituras baratas a cambio de lecturas lentas. El híbrido elige según el tamaño de la audiencia de cada autor.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo paginás un feed al que llegan posts nuevos todo el tiempo?",
    respuestaEs:
      "Con paginación por CURSOR, no por offset. Con offset (`página 2 = saltear 20`), si mientras el usuario lee la primera página llegan 5 posts nuevos arriba, la segunda página empieza 5 posiciones antes y repite posts que ya vio; con borrados pasa al revés y se saltean posts. Además, un offset grande obliga a recorrer y descartar todas las filas anteriores. Con cursor, cada página devuelve una referencia al último elemento entregado, y la siguiente pide 'los 20 anteriores a este'. Lo que llega arriba no corre la posición, y cada página cuesta lo mismo sin importar la profundidad. El cursor tiene que identificar una posición única, así que combina la fecha con el id (dos posts pueden tener la misma fecha), y conviene que sea opaco para el cliente (codificado en base64, por ejemplo), para poder cambiar su contenido sin romper la API. Los posts nuevos que llegaron después de cargar la primera página no aparecen en el scroll hacia abajo: se muestran con un aviso de 'hay posts nuevos' que recarga el principio del feed. Y si el feed tiene ranking en vez de orden cronológico, la paginación se complica: se suele fijar el conjunto rankeado al cargar la primera página y paginar sobre esa foto.",
    respuestaEn:
      "With CURSOR pagination, not offset. With offset (`page 2 = skip 20`), if 5 new posts arrive at the top while the user reads the first page, the second page starts 5 positions earlier and repeats posts already seen; with deletions the opposite happens and posts are skipped. Also, a large offset forces walking and discarding every previous row. With a cursor, each page returns a reference to the last item delivered, and the next asks for 'the 20 before this one'. What arrives at the top doesn't shift the position, and each page costs the same regardless of depth. The cursor must identify a unique position, so it combines the date with the id (two posts can share a date), and it should be opaque to the client (base64-encoded, for example), so its contents can change without breaking the API. New posts arriving after the first page loaded don't appear while scrolling down: they're shown with a 'new posts' notice that reloads the top of the feed. And if the feed is ranked instead of chronological, pagination gets harder: the ranked set is usually fixed when the first page loads and paginated over that snapshot.",
    codigo: `// el cursor codifica la posición del último post entregado
const { fecha, id } = decodificar(cursor);

const posts = await db.query(\`
  SELECT * FROM posts
  WHERE autor_id = ANY($1)
    AND (creado_el, id) < ($2, $3)   -- estrictamente anteriores al cursor
  ORDER BY creado_el DESC, id DESC
  LIMIT 20\`, [seguidos, fecha, id]);

const ultimo = posts.at(-1);
return { posts, siguienteCursor: ultimo && codificar(ultimo.creado_el, ultimo.id) };`,
  },
  {
    nivel: 3,
    pregunta: "En un chat, ¿cómo llega un mensaje a un usuario conectado a otro servidor?",
    respuestaEs:
      "Las conexiones WebSocket tienen estado: cada usuario está conectado a un servidor puntual (un gateway), y un mensaje que entra por un gateway tiene que salir por otro. Las piezas: GATEWAYS que solo mantienen conexiones, sin lógica de negocio, para poder escalar la cantidad de conexiones de forma independiente; un REGISTRO DE SESIONES, típicamente en Redis, que sabe en qué gateway está conectado cada usuario (o cada dispositivo, porque uno puede tener varios), actualizado al conectar y desconectar, con un TTL que se renueva con heartbeats para limpiar sesiones de gateways caídos; y un SERVICIO DE MENSAJES que recibe el mensaje del gateway emisor, lo valida, lo persiste, le asigna su número de orden, y lo enruta. El ruteo: busca en qué gateways están los destinatarios y publica el mensaje en el canal de cada uno (pub/sub de Redis o un broker), y cada gateway lo empuja por el socket correspondiente. Si el destinatario no tiene sesión activa, se dispara una notificación push. Persistir antes de enrutar es clave: si el gateway destino se cae justo en ese momento, el mensaje no se pierde, porque el cliente lo recupera del historial al reconectar.",
    respuestaEn:
      "WebSocket connections are stateful: each user is connected to a specific server (a gateway), and a message entering through one gateway must leave through another. The pieces: GATEWAYS that only hold connections, with no business logic, so connection count scales independently; a SESSION REGISTRY, typically in Redis, knowing which gateway each user (or each device, since one can have several) is connected to, updated on connect and disconnect, with a TTL renewed by heartbeats to clean up sessions of dead gateways; and a MESSAGE SERVICE that receives the message from the sender's gateway, validates it, persists it, assigns its sequence number and routes it. Routing: look up which gateways the recipients are on and publish the message on each one's channel (Redis pub/sub or a broker), and each gateway pushes it down the corresponding socket. If the recipient has no active session, trigger a push notification. Persisting before routing is key: if the destination gateway dies right then, the message isn't lost, because the client recovers it from history on reconnect.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo garantizás orden, entrega y ausencia de duplicados en un chat?",
    respuestaEs:
      "Con tres mecanismos que se complementan. ORDEN: el servidor asigna un número secuencial por conversación al persistir cada mensaje, y los clientes ordenan por ese número, no por el reloj del dispositivo, que puede estar desfasado. Como todos los mensajes de una conversación pasan por el mismo punto de asignación (o la misma partición), el orden es único para todos los participantes. ENTREGA: la conexión puede cortarse en cualquier momento, así que no alcanza con empujar el mensaje por el socket. El cliente confirma lo que recibe y recuerda el último número visto por conversación; al reconectar, pide todo lo posterior a ese número y se pone al día. Así, lo que se perdió durante la desconexión se recupera sin que el servidor tenga que rastrear qué llegó a cada dispositivo. DUPLICADOS: del lado del emisor, cada mensaje lleva un id generado por el cliente; si el envío se reintenta porque no llegó la confirmación, el servidor reconoce el id y no lo guarda dos veces (idempotencia). Del lado del receptor, el número secuencial permite descartar lo que ya tiene. Los estados de entregado y leído se modelan igual, como 'último número entregado' y 'último número leído' por usuario, en vez de un estado por mensaje.",
    respuestaEn:
      "With three complementary mechanisms. ORDERING: the server assigns a per-conversation sequence number when persisting each message, and clients order by that number, not the device clock, which can be skewed. Since all messages in a conversation go through the same assignment point (or the same partition), the order is unique for every participant. DELIVERY: the connection can drop at any moment, so pushing the message down the socket isn't enough. The client acknowledges what it receives and remembers the last number seen per conversation; on reconnect, it requests everything after that number and catches up. That way, what was lost during the disconnection is recovered without the server tracking what reached each device. DUPLICATES: on the sender's side, each message carries a client-generated id; if the send is retried because the acknowledgment didn't arrive, the server recognizes the id and doesn't store it twice (idempotency). On the receiver's side, the sequence number lets it drop what it already has. Delivered and read states are modeled the same way, as 'last delivered number' and 'last read number' per user, instead of a state per message.",
    repregunta: "¿Y en un grupo de 50.000 miembros?",
    respuestaRepreguntaEs:
      "El fan-out por mensaje se vuelve el problema: empujar cada mensaje a 50.000 conexiones y mantener 50.000 estados de entrega es carísimo, y la mayoría de los miembros no está mirando el grupo. Se cambia el modelo: los mensajes se persisten una vez, se empujan en tiempo real solo a quienes tienen el grupo abierto (suscripciones activas), y los demás reciben, como mucho, una notificación agregada ('hay 30 mensajes nuevos') y leen el historial al abrirlo. Los estados de lectura individuales se dejan de mostrar o se aproximan, y se limita la frecuencia de envío. Es el mismo razonamiento que el fan-out on read de un feed.",
    respuestaRepreguntaEn:
      "Per-message fan-out becomes the problem: pushing each message to 50,000 connections and keeping 50,000 delivery states is very expensive, and most members aren't looking at the group. The model changes: messages are persisted once, pushed in real time only to those with the group open (active subscriptions), and the rest get at most an aggregated notification ('30 new messages') and read history when they open it. Individual read states stop being shown or are approximated, and send rate is limited. It's the same reasoning as a feed's fan-out on read.",
  },
];
