import type { PreguntaEntrevista } from "../types";

export const entrevistaEstimacion: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es una estimación back of the envelope y para qué sirve en una entrevista de system design?",
    respuestaEs:
      "Es un cálculo rápido, con números redondos, para conocer el orden de magnitud de un sistema antes de diseñarlo: cuántas requests por segundo recibe, cuánto almacenamiento necesita, cuánto ancho de banda consume. No busca precisión, sino decidir con fundamento: no es lo mismo diseñar para 100 requests por segundo que para 100.000, ni para 50 gigabytes que para 5 petabytes. En una entrevista cumple dos funciones. Primero, guía el diseño: si las escrituras son pocas, una base relacional alcanza; si la relación de lecturas a escrituras es 100 a 1, la caché es central; si el almacenamiento se mide en petabytes, hay que pensar en sharding y en almacenamiento de objetos desde el principio. Segundo, muestra criterio: el entrevistador quiere ver que explicitás los supuestos (usuarios activos, acciones por usuario, tamaño de cada registro), que razonás en voz alta y que redondeás sin miedo, porque la conclusión no cambia si el resultado es 1.150 o 1.200 requests por segundo. Lo que no hay que hacer es pasar diez minutos haciendo cuentas exactas: dos o tres números bien elegidos alcanzan.",
    respuestaEn:
      "It's a quick calculation with round numbers to learn a system's order of magnitude before designing it: how many requests per second it gets, how much storage it needs, how much bandwidth it uses. It doesn't aim for precision but for informed decisions: designing for 100 requests per second isn't the same as for 100,000, nor for 50 gigabytes as for 5 petabytes. In an interview it serves two purposes. First, it guides the design: if writes are few, a relational database suffices; if the read-to-write ratio is 100 to 1, caching is central; if storage is measured in petabytes, you must think about sharding and object storage from the start. Second, it shows judgment: the interviewer wants to see you state assumptions (active users, actions per user, record size), reason out loud and round fearlessly, because the conclusion doesn't change whether the result is 1,150 or 1,200 requests per second. What you shouldn't do is spend ten minutes on exact arithmetic: two or three well-chosen numbers are enough.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué números conviene tener en la cabeza para estimar?",
    respuestaEs:
      "Unos pocos órdenes de magnitud resuelven casi todo. TIEMPO: un día tiene 86.400 segundos, que se redondea a 10⁵; por eso 1 millón de acciones por día son unas 10 por segundo, y 100 millones, unas 1.000 por segundo. Un mes son unos 2,5 millones de segundos, y un año unos 30 millones. TAMAÑOS: un carácter ASCII es 1 byte; un registro típico con algunos campos, cientos de bytes; una imagen comprimida, cientos de kilobytes; un minuto de video, decenas de megabytes. Y cada salto de prefijo (kilo, mega, giga, tera, peta) es un factor de mil. LATENCIAS aproximadas: leer de memoria, unos 100 nanosegundos; leer de un SSD, unos 100 microsegundos; una ida y vuelta dentro del mismo datacenter, alrededor de medio milisegundo; una consulta simple a una base con índice, algunos milisegundos; una ida y vuelta entre continentes, del orden de 100 a 150 milisegundos. CAPACIDAD: un servidor de aplicación atiende del orden de miles de requests simples por segundo, y una base relacional bien indexada, miles a decenas de miles de consultas simples por segundo. Son valores de referencia para razonar, no garantías: el hardware y la carga real los mueven.",
    respuestaEn:
      "A few orders of magnitude solve almost everything. TIME: a day has 86,400 seconds, rounded to 10⁵; so 1 million actions a day are about 10 per second, and 100 million, about 1,000 per second. A month is about 2.5 million seconds, a year about 30 million. SIZES: an ASCII character is 1 byte; a typical record with some fields, hundreds of bytes; a compressed image, hundreds of kilobytes; a minute of video, tens of megabytes. And each prefix step (kilo, mega, giga, tera, peta) is a factor of a thousand. Approximate LATENCIES: reading from memory, about 100 nanoseconds; reading from an SSD, about 100 microseconds; a round trip within the same datacenter, about half a millisecond; a simple indexed database query, a few milliseconds; a round trip across continents, on the order of 100 to 150 milliseconds. CAPACITY: an application server handles on the order of thousands of simple requests per second, and a well-indexed relational database, thousands to tens of thousands of simple queries per second. They're reference values for reasoning, not guarantees: hardware and real load shift them.",
    codigo: `1 día            ≈ 10⁵ s        → 1M acciones/día ≈ 10 req/s
memoria          ~100 ns
SSD              ~100 µs
mismo datacenter ~0,5 ms (ida y vuelta)
entre continentes ~100–150 ms
servidor de app  ~miles de req/s simples`,
  },
  {
    nivel: 2,
    pregunta: "Estimá el almacenamiento y el tráfico de un servicio de fotos con 10 millones de usuarios activos diarios.",
    respuestaEs:
      "Primero los supuestos, dichos en voz alta: el 10% de los usuarios sube una foto por día, cada foto pesa 2 MB después de comprimirla, y se guardan además dos miniaturas que suman 200 KB; cada usuario ve unas 50 fotos por día, casi todas en miniatura. ESCRITURAS: 10M × 10% = 1 millón de fotos por día, unas 10 por segundo en promedio. Es un volumen bajo: la base de metadatos no es el problema. ALMACENAMIENTO: 1 millón × 2,2 MB ≈ 2,2 TB por día, unos 800 TB por año, del orden de un petabyte. Eso descarta guardar las imágenes en la base: van a almacenamiento de objetos (S3), y la base guarda solo metadatos (unos cientos de bytes por foto, unos cientos de megabytes por día). Con tres réplicas o la durabilidad del servicio, el costo de almacenamiento pasa a ser una preocupación de diseño: clases más baratas para fotos viejas. LECTURAS: 10M × 50 = 500 millones de vistas por día, unas 5.000 por segundo en promedio y 15.000 en pico. En miniaturas de 100 KB, eso es unos 500 MB/s en promedio de salida. Conclusión: las lecturas dominan por mucho, y un CDN delante del almacenamiento es obligatorio, tanto por latencia como por costo de salida.",
    respuestaEn:
      "First the assumptions, said out loud: 10% of users upload one photo a day, each photo weighs 2 MB after compression, plus two thumbnails totaling 200 KB; each user views about 50 photos a day, almost all as thumbnails. WRITES: 10M × 10% = 1 million photos a day, about 10 per second on average. It's a low volume: the metadata database isn't the problem. STORAGE: 1 million × 2.2 MB ≈ 2.2 TB a day, about 800 TB a year, on the order of a petabyte. That rules out storing images in the database: they go to object storage (S3), and the database keeps only metadata (a few hundred bytes per photo, a few hundred megabytes a day). With three replicas or the service's durability, storage cost becomes a design concern: cheaper classes for old photos. READS: 10M × 50 = 500 million views a day, about 5,000 per second on average and 15,000 at peak. At 100 KB thumbnails, that's about 500 MB/s of average egress. Conclusion: reads dominate by far, and a CDN in front of storage is mandatory, both for latency and egress cost.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo pasás de los números a decisiones de diseño?",
    respuestaEs:
      "Cada número responde una pregunta concreta. Los QPS EN PICO dicen cuántas instancias hacen falta (dividiendo por lo que atiende cada una, con margen) y si una sola base aguanta las consultas o hace falta caché y réplicas. La RELACIÓN LECTURAS/ESCRITURAS dice dónde poner el esfuerzo: con 100 a 1, caché, réplicas de lectura y CDN; con escrituras dominantes (logs, métricas, chat), bases optimizadas para escritura, colas y procesamiento por lotes. Las ESCRITURAS POR SEGUNDO dicen si un primario alcanza: unas miles de escrituras simples por segundo las maneja un Postgres bien dimensionado; cientos de miles ya piden particionar o shardear. El ALMACENAMIENTO dice qué va dónde: si los datos entran en la memoria de una máquina, la caché puede tenerlos todos; si son terabytes, la base necesita planificación; si son petabytes de archivos, almacenamiento de objetos con clases por antigüedad. El ANCHO DE BANDA de salida dice si hace falta un CDN y cuánto va a costar. Y el crecimiento esperado dice cuánto margen dejar. La precisión adicional casi nunca cambia la decisión, así que se redondea para arriba y se sigue.",
    respuestaEn:
      "Each number answers a concrete question. PEAK QPS tells how many instances are needed (dividing by what each handles, with headroom) and whether one database can take the queries or caching and replicas are needed. The READ/WRITE RATIO tells where to invest: at 100 to 1, caching, read replicas and CDN; with dominant writes (logs, metrics, chat), write-optimized databases, queues and batch processing. WRITES PER SECOND tell whether one primary suffices: a well-sized Postgres handles a few thousand simple writes per second; hundreds of thousands call for partitioning or sharding. STORAGE tells what goes where: if the data fits in one machine's memory, the cache can hold it all; if it's terabytes, the database needs planning; if it's petabytes of files, object storage with age-based classes. Egress BANDWIDTH tells whether a CDN is needed and what it'll cost. And expected growth tells how much headroom to leave. Extra precision almost never changes the decision, so round up and move on.",
    tradeoffs:
      "Estimar rápido con supuestos explícitos deja tiempo para diseñar; estimar con precisión consume la entrevista sin cambiar las decisiones.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué errores son típicos al estimar, y cómo los detectás?",
    respuestaEs:
      "DISEÑAR PARA EL PROMEDIO: el tráfico no es uniforme; hay horas pico, campañas, eventos, y el sistema tiene que aguantar el pico, que puede ser varias veces el promedio. OLVIDAR LOS MULTIPLICADORES del almacenamiento: réplicas (normalmente 3), índices (que pueden ocupar tanto como los datos), backups, versiones anteriores y logs. MEZCLAR METADATOS CON ARCHIVOS: estimar una sola cifra de almacenamiento cuando en realidad hay dos problemas distintos, cientos de bytes de metadatos en una base y megabytes de archivos en un almacenamiento de objetos. CONFUNDIR UNIDADES: bits con bytes (el ancho de banda de red se suele expresar en bits por segundo, un factor de 8), o potencias de 10 con potencias de 2 (la diferencia es chica y no suele importar). IGNORAR LA DISTRIBUCIÓN: un promedio de 10 seguidores por usuario esconde a las cuentas con millones, que concentran carga (hot keys). Y NO VERIFICAR EL RESULTADO: la mejor defensa es un chequeo de sentido común al final ('¿tiene sentido que un servicio de notas necesite un petabyte?') y comparar con algo conocido. Si un número parece raro, casi siempre es un error de unidad o un cero de más.",
    respuestaEn:
      "DESIGNING FOR THE AVERAGE: traffic isn't uniform; there are peak hours, campaigns, events, and the system must handle the peak, which can be several times the average. FORGETTING STORAGE MULTIPLIERS: replicas (usually 3), indexes (which can take as much as the data), backups, previous versions and logs. MIXING METADATA WITH FILES: estimating a single storage figure when there are really two problems, hundreds of bytes of metadata in a database and megabytes of files in object storage. CONFUSING UNITS: bits with bytes (network bandwidth is usually given in bits per second, a factor of 8), or powers of 10 with powers of 2 (the difference is small and rarely matters). IGNORING DISTRIBUTION: an average of 10 followers per user hides accounts with millions, which concentrate load (hot keys). And NOT CHECKING THE RESULT: the best defense is a sanity check at the end ('does it make sense that a notes service needs a petabyte?') and comparing with something known. If a number looks off, it's almost always a unit error or an extra zero.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo estimás cuántas conexiones, workers o instancias necesita un componente?",
    respuestaEs:
      "Con la LEY DE LITTLE: la cantidad promedio de trabajos en curso en un sistema es igual a la tasa de llegada por el tiempo que cada uno pasa adentro (L = λ × W). Aplicada a un servidor: si recibe 2.000 requests por segundo y cada una tarda 50 milisegundos, en promedio hay 2.000 × 0,05 = 100 requests en curso al mismo tiempo. Eso dimensiona recursos concretos. CONEXIONES A LA BASE: si cada request tiene la conexión 10 ms y llegan 2.000 por segundo, hacen falta en promedio 20 conexiones ocupadas; con margen para picos y variabilidad, un pool de 40 o 50, repartido entre las instancias, y no 100 por instancia. WORKERS de una cola: si llegan 50 jobs por segundo y cada uno tarda 2 segundos, hacen falta al menos 100 workers ocupados en promedio para no acumular atraso. INSTANCIAS: si cada una atiende cómodamente 100 requests concurrentes, para 100 en curso alcanza con una, pero se usan varias por disponibilidad y para absorber picos. La ley también explica un efecto clave: si la latencia de una dependencia se duplica, la concurrencia se duplica con ella, y un pool dimensionado justo se agota. Por eso los tiempos de respuesta y los límites de concurrencia se diseñan juntos.",
    respuestaEn:
      "With LITTLE'S LAW: the average number of jobs in progress in a system equals the arrival rate times the time each spends inside (L = λ × W). Applied to a server: if it receives 2,000 requests per second and each takes 50 milliseconds, on average 2,000 × 0.05 = 100 requests are in progress at once. That sizes concrete resources. DATABASE CONNECTIONS: if each request holds the connection for 10 ms and 2,000 arrive per second, you need about 20 busy connections on average; with headroom for peaks and variability, a pool of 40 or 50, spread across instances, not 100 per instance. Queue WORKERS: if 50 jobs arrive per second and each takes 2 seconds, you need at least 100 busy workers on average to avoid falling behind. INSTANCES: if each comfortably handles 100 concurrent requests, one suffices for 100 in progress, but you use several for availability and to absorb peaks. The law also explains a key effect: if a dependency's latency doubles, concurrency doubles with it, and a tightly sized pool runs dry. That's why response times and concurrency limits are designed together.",
    codigo: `L = λ × W   (en curso = tasa de llegada × tiempo adentro)

2.000 req/s × 0,050 s = 100 requests concurrentes
2.000 req/s × 0,010 s =  20 conexiones a la base ocupadas
   50 jobs/s × 2 s     = 100 workers ocupados`,
  },
];
