import type { PreguntaEntrevista } from "../types";

export const entrevistaEstrategiasCaching: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué estrategias de escritura con caché conocés y en qué se diferencian?",
    respuestaEs:
      "Se diferencian en quién escribe dónde y cuándo. CACHE-ASIDE: la aplicación escribe en la base y borra la clave del caché; la próxima lectura la vuelve a cargar. Es la más común porque es simple y el caché nunca tiene datos que la base no tenga. WRITE-THROUGH: cada escritura va al caché y a la base en la misma operación; el caché queda siempre actualizado y las lecturas siguientes son hits, a cambio de que cada escritura pague la latencia de ambos y de cachear datos que quizá nadie lea. WRITE-BACK (o write-behind): la escritura va solo al caché, que es rápido, y la base se actualiza después, de forma asíncrona y en lotes; da escrituras muy rápidas y reduce la carga de la base, pero si el caché se cae antes de volcar los cambios, esas escrituras se pierden. WRITE-AROUND: la escritura va solo a la base y no toca el caché; evita llenar el caché con datos que se escriben pero casi no se leen (logs, importaciones masivas), pero si la clave ya estaba cacheada, queda vieja hasta que se invalide o venza. Del lado de la lectura, READ-THROUGH es la variante donde el caché mismo, no la aplicación, va a la base en un miss.",
    respuestaEn:
      "They differ in who writes where and when. CACHE-ASIDE: the application writes to the database and deletes the cache key; the next read reloads it. It's the most common because it's simple and the cache never has data the database lacks. WRITE-THROUGH: every write goes to the cache and the database in the same operation; the cache is always up to date and subsequent reads are hits, at the cost of every write paying both latencies and caching data nobody might read. WRITE-BACK (or write-behind): the write goes only to the cache, which is fast, and the database is updated later, asynchronously and in batches; very fast writes and less database load, but if the cache dies before flushing, those writes are lost. WRITE-AROUND: the write goes only to the database and doesn't touch the cache; it avoids filling the cache with data that's written but rarely read (logs, bulk imports), but if the key was already cached, it goes stale until invalidated or expired. On the read side, READ-THROUGH is the variant where the cache itself, not the application, goes to the database on a miss.",
  },
  {
    nivel: 1,
    pregunta: "¿Por qué la invalidación es difícil y qué estrategias hay?",
    respuestaEs:
      "Porque cada copia de un dato es un lugar donde puede quedar viejo, y hay que saber cuándo cambió el original y qué copias depende de él. Una respuesta cacheada puede depender de muchos datos (una página de producto usa el producto, su categoría, el stock y el precio), y cualquier cambio en cualquiera debería invalidarla. Las estrategias, de más simple a más precisa. TTL: la entrada vence sola después de un tiempo; no requiere saber qué cambió, pero acepta servir datos viejos durante ese tiempo. INVALIDACIÓN EXPLÍCITA por evento: al escribir, se borran las claves afectadas; es precisa pero exige conocer todas las dependencias, y un olvido deja datos viejos (por eso se combina con un TTL de seguridad). CLAVES VERSIONADAS: la versión del dato forma parte de la clave (`producto:7:v42`); al cambiar, se incrementa la versión y las lecturas usan la clave nueva, sin borrar nada; las viejas vencen solas. INVALIDACIÓN POR TAGS: cada entrada se etiqueta con los datos de los que depende, y se invalida todo lo que tenga un tag (`revalidateTag('productos')` en Next.js funciona así). La elección depende de cuánto tiempo es aceptable mostrar un dato viejo.",
    respuestaEn:
      "Because every copy of a piece of data is a place where it can go stale, and you have to know when the original changed and which copies depend on it. A cached response can depend on many pieces of data (a product page uses the product, its category, stock and price), and any change to any of them should invalidate it. The strategies, from simplest to most precise. TTL: the entry expires on its own after a while; it doesn't require knowing what changed, but accepts serving stale data during that time. EXPLICIT event-based INVALIDATION: on write, delete the affected keys; precise but requires knowing every dependency, and a miss leaves stale data (hence combining it with a safety TTL). VERSIONED KEYS: the data's version is part of the key (`product:7:v42`); on change, the version increments and reads use the new key, without deleting anything; old ones expire on their own. TAG-BASED INVALIDATION: each entry is tagged with the data it depends on, and everything with a tag is invalidated (`revalidateTag('products')` in Next.js works this way). The choice depends on how long showing stale data is acceptable.",
  },
  {
    nivel: 2,
    pregunta: "¿Cuándo tiene sentido write-back, y cómo reducís su riesgo?",
    respuestaEs:
      "Cuando la tasa de escritura es tan alta que escribir cada cambio en la base es el cuello de botella, y perder las últimas escrituras en una falla es tolerable o se puede mitigar. Los ejemplos típicos son contadores y métricas (vistas, likes, eventos de analítica): miles de incrementos por segundo sobre la misma fila se acumulan en memoria y se vuelcan como una sola escritura cada pocos segundos, lo que además reduce la contención de locks en la base. También sirve para absorber picos: el caché acepta todo rápido y la base lo recibe a su ritmo. No encaja con datos donde perder una escritura confirmada es inaceptable: pagos, pedidos, cambios de estado que el usuario ya vio confirmados. Para reducir el riesgo: que el caché persista (Redis con AOF, que registra cada escritura en disco) o esté replicado; volcar con frecuencia, acotando cuánto se puede perder; volcar de forma idempotente, para poder reintentar un lote que falló a mitad; y monitorear cuántas escrituras pendientes hay. Una alternativa más robusta con el mismo efecto es escribir los eventos en una cola durable y que un consumidor los agregue y los vuelque a la base.",
    respuestaEn:
      "When the write rate is so high that writing every change to the database is the bottleneck, and losing the latest writes on failure is tolerable or can be mitigated. Typical examples are counters and metrics (views, likes, analytics events): thousands of increments per second on the same row accumulate in memory and are flushed as a single write every few seconds, which also reduces lock contention in the database. It also helps absorb spikes: the cache accepts everything fast and the database receives it at its own pace. It doesn't fit data where losing a confirmed write is unacceptable: payments, orders, state changes the user already saw confirmed. To reduce the risk: make the cache durable (Redis with AOF, logging every write to disk) or replicated; flush frequently, bounding how much can be lost; flush idempotently, so a batch that failed midway can be retried; and monitor how many writes are pending. A sturdier alternative with the same effect is writing the events to a durable queue and having a consumer aggregate and flush them to the database.",
    tradeoffs:
      "Write-back cambia durabilidad inmediata por escrituras rápidas y menos carga en la base; write-through al revés.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo elegís la política de eviction y cómo sabés si el caché está funcionando?",
    respuestaEs:
      "Cuando el caché se llena, la política de EVICTION decide qué sacar. LRU (least recently used) saca lo que hace más tiempo no se usa: es el default razonable, porque lo usado recientemente suele volver a usarse. LFU (least frequently used) saca lo menos usado en total: protege mejor las claves populares de forma sostenida, y resiste mejor un recorrido masivo que en LRU desplazaría todo lo útil (por ejemplo, un job que lee un millón de claves una sola vez). FIFO o por TTL son más simples y a veces alcanzan. Para saber si funciona, la métrica central es el HIT RATIO: qué porcentaje de lecturas se resuelve en el caché. Un hit ratio bajo puede significar que el caché es chico para el working set (el conjunto de datos que se usa activamente), que el TTL es tan corto que las entradas vencen antes de reutilizarse, que la clave incluye algo que varía de más (un timestamp, un parámetro irrelevante), o que simplemente los datos no se repiten y el caché no aporta. También hay que mirar la tasa de evictions (si es alta, falta memoria), la latencia en hit y en miss, y la carga que efectivamente se le quitó a la base, que es el objetivo real.",
    respuestaEn:
      "When the cache fills up, the EVICTION policy decides what to remove. LRU (least recently used) removes what hasn't been used for the longest: it's the reasonable default, since recently used data tends to be used again. LFU (least frequently used) removes what's used least overall: it better protects persistently popular keys and better resists a bulk scan that would push out everything useful under LRU (for example, a job reading a million keys once). FIFO or TTL-based are simpler and sometimes enough. To know whether it works, the core metric is the HIT RATIO: what percentage of reads are served from cache. A low hit ratio can mean the cache is too small for the working set (the data actively used), the TTL is so short entries expire before reuse, the key includes something that varies too much (a timestamp, an irrelevant parameter), or simply the data doesn't repeat and the cache adds nothing. Also watch the eviction rate (if high, memory is short), latency on hit and miss, and the load actually taken off the database, which is the real goal.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué problemas aparecen cuando hay varias capas de caché?",
    respuestaEs:
      "Una respuesta puede estar cacheada en el navegador, en el CDN, en memoria de cada instancia de la aplicación y en un caché distribuido como Redis. Cada capa ahorra latencia y carga, pero los problemas se suman. VENTANAS DE INCONSISTENCIA ACUMULADAS: si cada capa tiene su TTL, el peor caso de dato viejo es la suma, y un cambio urgente (un precio mal cargado) tarda en desaparecer de todas. INVALIDACIÓN COORDINADA: borrar en Redis no borra la copia en memoria de diez instancias ni la del CDN; para las cachés en proceso se publica un evento de invalidación por pub/sub que cada instancia escucha, y el CDN se invalida por tag o se evita cachear ahí lo que cambia seguido. Y el navegador no se puede invalidar desde el servidor: lo que se le permitió cachear queda hasta que venza. HOT KEYS: una clave muy leída puede saturar el nodo de Redis que la tiene; una capa de caché local en cada instancia, con TTL de pocos segundos, absorbe esa carga a cambio de una ventana corta de inconsistencia. CACHEO NEGATIVO: guardar también los 'no existe' evita que requests a claves inexistentes, incluidas las de un atacante, lleguen siempre a la base, pero con un TTL corto para que un dato recién creado aparezca rápido.",
    respuestaEn:
      "A response may be cached in the browser, the CDN, each application instance's memory, and a distributed cache like Redis. Each layer saves latency and load, but the problems add up. ACCUMULATED INCONSISTENCY WINDOWS: if each layer has its TTL, the worst-case staleness is the sum, and an urgent change (a mispriced item) takes a while to disappear from all of them. COORDINATED INVALIDATION: deleting in Redis doesn't delete the copy in ten instances' memory or on the CDN; for in-process caches you publish an invalidation event via pub/sub that every instance listens to, and the CDN is invalidated by tag or you avoid caching frequently changing content there. And the browser can't be invalidated from the server: what it was allowed to cache stays until it expires. HOT KEYS: a heavily read key can saturate the Redis node holding it; a local cache layer on each instance, with a TTL of a few seconds, absorbs that load at the cost of a short inconsistency window. NEGATIVE CACHING: also caching 'doesn't exist' keeps requests for nonexistent keys, including an attacker's, from always hitting the database, but with a short TTL so newly created data shows up quickly.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo mantenés el caché consistente con la base ante escrituras concurrentes?",
    respuestaEs:
      "El problema clásico en cache-aside: una lectura hace miss, consulta la base y obtiene el valor viejo; mientras tanto una escritura actualiza la base y borra la clave; recién después la lectura guarda en el caché el valor viejo que había leído. Ahora el caché tiene un dato viejo que nadie va a invalidar hasta que venza. Hay varias defensas, de más simple a más robusta. TTL corto como red de seguridad, que acota cuánto dura. ESCRITURA CONDICIONAL POR VERSIÓN: guardar en el caché la versión del dato (un contador o el timestamp de actualización de la fila) y solo escribir si la versión es más nueva que la que ya está, con una operación atómica en Redis. LEASES: en un miss, el caché entrega un token al lector y solo acepta el set de quien tiene un token válido; una invalidación posterior anula los tokens, así el lector lento no puede guardar su valor viejo. Es la técnica que describe Facebook en su paper sobre memcache. INVALIDACIÓN POR CDC: en vez de que la aplicación borre las claves (y pueda olvidarse o fallar entre la escritura y el borrado), un proceso lee el log de cambios de la base (el WAL, con herramientas como Debezium) e invalida en consecuencia, así toda escritura confirmada genera su invalidación, venga de donde venga.",
    respuestaEn:
      "The classic cache-aside problem: a read misses, queries the database and gets the old value; meanwhile a write updates the database and deletes the key; only then does the read store the old value it read into the cache. Now the cache holds stale data nobody will invalidate until it expires. There are several defenses, from simplest to sturdiest. A short TTL as a safety net, bounding how long it lasts. CONDITIONAL WRITE BY VERSION: store the data's version in the cache (a counter or the row's update timestamp) and only write if the version is newer than the one already there, with an atomic Redis operation. LEASES: on a miss, the cache hands the reader a token and only accepts a set from a valid token holder; a later invalidation voids the tokens, so the slow reader can't store its stale value. It's the technique Facebook describes in its memcache paper. CDC-DRIVEN INVALIDATION: instead of the application deleting keys (and possibly forgetting or failing between the write and the delete), a process reads the database's change log (the WAL, with tools like Debezium) and invalidates accordingly, so every committed write produces its invalidation, wherever it came from.",
  },
];
