import type { PreguntaEntrevista } from "../types";

export const entrevistaIdempotenciaRateLimiting: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Por qué la idempotencia es un requisito de diseño y no un detalle de implementación?",
    respuestaEs:
      "Porque en un sistema distribuido los reintentos son inevitables, y sin idempotencia cada reintento puede duplicar un efecto. Un request puede fallar después de haber hecho su trabajo (el servidor cobró, pero la respuesta se perdió por un timeout), y el cliente no tiene forma de saber si se aplicó o no: la única respuesta segura es reintentar. Lo mismo pasa por todos lados: el balanceador reintenta en otra instancia, la cola entrega un mensaje de nuevo porque el consumidor no llegó a confirmarlo, el usuario hace doble click, una app mobile reenvía al recuperar la señal. Si la operación no es idempotente, cada uno de esos casos se convierte en un cobro doble, un pedido repetido o un email enviado dos veces. Por eso se decide al diseñar la API y los flujos, no después: qué operaciones reciben una clave de idempotencia, dónde se guarda, cuánto tiempo vive y qué se responde ante un duplicado. Muchas operaciones ya son idempotentes por naturaleza (poner un estado, un PUT que reemplaza el recurso); las que no lo son, como crear, cobrar o incrementar, necesitan un mecanismo explícito.",
    respuestaEn:
      "Because in a distributed system retries are unavoidable, and without idempotency every retry can duplicate an effect. A request can fail after doing its work (the server charged, but the response was lost to a timeout), and the client has no way of knowing whether it applied: the only safe response is to retry. The same happens everywhere: the load balancer retries on another instance, the queue redelivers a message because the consumer didn't acknowledge it, the user double-clicks, a mobile app resends on regaining signal. If the operation isn't idempotent, each of those becomes a double charge, a repeated order or an email sent twice. That's why it's decided when designing the API and flows, not afterwards: which operations take an idempotency key, where it's stored, how long it lives and what's returned for a duplicate. Many operations are naturally idempotent (setting a state, a PUT replacing the resource); those that aren't, like creating, charging or incrementing, need an explicit mechanism.",
  },
  {
    nivel: 1,
    pregunta: "¿Dónde ponés el rate limiting en una arquitectura, y con qué criterio lo repartís?",
    respuestaEs:
      "En varias capas, cada una con un propósito distinto. En el BORDE (CDN, WAF, API gateway), límites gruesos por IP para frenar abuso y ataques antes de que consuman recursos. En la API, límites por identidad (usuario, API key, tenant), que son los que expresan el contrato con el cliente: cuántas requests puede hacer según su plan. Dentro de cada servicio, límites por endpoint según su costo: no es lo mismo un GET barato que la generación de un reporte o una búsqueda compleja, así que se limitan por separado o se asigna un costo en 'unidades' a cada operación. Y del lado de las DEPENDENCIAS, límites salientes: si un proveedor externo acepta 100 requests por segundo, tu sistema tiene que respetarlo para no recibir bloqueos, lo que se resuelve con una cola o un token bucket compartido por todas las instancias. El criterio de reparto es la EQUIDAD: que un cliente no pueda consumir la capacidad de todos los demás. En un SaaS multi-tenant, esto es tan importante como proteger al sistema, porque el problema típico no es un atacante sino un cliente legítimo con un script mal hecho que degrada el servicio para todos.",
    respuestaEn:
      "In several layers, each with its own purpose. At the EDGE (CDN, WAF, API gateway), coarse per-IP limits to stop abuse and attacks before they consume resources. In the API, per-identity limits (user, API key, tenant), which express the contract with the client: how many requests they can make by plan. Inside each service, per-endpoint limits by cost: a cheap GET isn't the same as generating a report or a complex search, so they're limited separately or each operation is assigned a cost in 'units'. And on the DEPENDENCY side, outbound limits: if an external provider accepts 100 requests per second, your system must honor it to avoid getting blocked, solved with a queue or a token bucket shared by all instances. The allocation criterion is FAIRNESS: no client should be able to consume everyone else's capacity. In a multi-tenant SaaS, that's as important as protecting the system, because the typical problem isn't an attacker but a legitimate customer with a badly written script degrading the service for everyone.",
  },
  {
    nivel: 2,
    pregunta: "Diseñá el almacenamiento de las idempotency keys para una API de pagos.",
    respuestaEs:
      "Una tabla (o un almacén con operaciones atómicas) con: la clave, el cliente al que pertenece (las claves son por cliente, no globales), una HUELLA del request (hash del método, la ruta y el cuerpo), un ESTADO (en proceso, completada), la respuesta guardada (status y cuerpo) y la fecha de creación. El flujo: al llegar un request, se intenta INSERTAR la clave en estado 'en proceso'; la restricción de unicidad hace que, entre requests concurrentes, solo uno gane. Si la inserción falla, la clave existe: si está completada y la huella coincide, se devuelve la respuesta guardada; si la huella no coincide, es un error del cliente (422); si está en proceso, se responde 409 para que reintente después. El que ganó ejecuta la operación y guarda la respuesta como completada. Detalles que importan: si la operación falla con un error reintentable (el proveedor no respondió), se borra la clave o se marca para permitir el reintento, en vez de guardar el error como definitivo; una clave 'en proceso' abandonada porque la instancia se cayó necesita un vencimiento; y las claves se conservan un tiempo acotado (24 horas es habitual) para no crecer sin límite. Idealmente, el registro de la clave y el efecto (el pago en la base) se guardan en la misma transacción.",
    respuestaEn:
      "A table (or a store with atomic operations) with: the key, the client it belongs to (keys are per client, not global), a request FINGERPRINT (hash of method, path and body), a STATE (in progress, completed), the stored response (status and body) and the creation date. The flow: when a request arrives, try to INSERT the key in the 'in progress' state; the uniqueness constraint ensures only one of several concurrent requests wins. If the insert fails, the key exists: if it's completed and the fingerprint matches, return the stored response; if the fingerprint doesn't match, it's a client error (422); if it's in progress, respond 409 so it retries later. The winner executes the operation and stores the response as completed. Details that matter: if the operation fails with a retryable error (the provider didn't respond), delete the key or mark it to allow the retry, instead of storing the error as final; an 'in progress' key abandoned because the instance died needs an expiry; and keys are kept for a bounded time (24 hours is common) so they don't grow forever. Ideally, the key record and the effect (the payment in the database) are saved in the same transaction.",
    codigo: `CREATE TABLE claves_idempotencia (
  cliente_id   bigint      NOT NULL,
  clave        text        NOT NULL,
  huella       text        NOT NULL,        -- hash de método + ruta + cuerpo
  estado       text        NOT NULL,        -- 'en_proceso' | 'completada'
  respuesta    jsonb,
  creada_el    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (cliente_id, clave)           -- la carrera la resuelve la base
);`,
  },
  {
    nivel: 2,
    pregunta: "¿Cómo repartís la capacidad entre tenants para que uno no degrade a los demás?",
    respuestaEs:
      "Con límites por tenant, no solo globales. Un límite global protege al sistema, pero cuando se alcanza castiga a todos por igual, incluso a los que no causaron el pico. Lo que se busca es AISLAMIENTO: que el consumo de un cliente afecte lo menos posible a los demás. Las herramientas: límites por tenant según su plan (con un token bucket que permita ráfagas cortas por encima del promedio); límites por costo, asignando unidades a cada operación, así un tenant que hace pocas requests pero carísimas también queda acotado; colas separadas o con prioridad por tenant para el trabajo asíncrono, de modo que el backlog de uno no demore a los demás (fair queuing); y, para clientes muy grandes, recursos dedicados: sus propios workers, su propia partición o incluso su propio shard. También importa la respuesta: 429 con `Retry-After` y headers que indiquen cuánto queda de la cuota, para que un cliente bien hecho se autorregule. El trade-off es de utilización: reservar capacidad por tenant deja recursos ociosos cuando ese tenant no los usa, así que se suele combinar un mínimo garantizado con la posibilidad de usar capacidad libre del pool compartido.",
    respuestaEn:
      "With per-tenant limits, not just global ones. A global limit protects the system, but when hit it punishes everyone equally, including those who didn't cause the spike. What you want is ISOLATION: one customer's usage affecting others as little as possible. The tools: per-tenant limits by plan (with a token bucket allowing short bursts above average); cost-based limits, assigning units to each operation, so a tenant making few but very expensive requests is also bounded; separate or per-tenant prioritized queues for async work, so one's backlog doesn't delay others (fair queuing); and for very large customers, dedicated resources: their own workers, partition or even shard. The response matters too: 429 with `Retry-After` and headers showing remaining quota, so a well-built client self-regulates. The trade-off is utilization: reserving capacity per tenant leaves resources idle when that tenant doesn't use them, so you usually combine a guaranteed minimum with the ability to use spare capacity from the shared pool.",
    tradeoffs:
      "Reservar capacidad por tenant da aislamiento a cambio de utilización; compartir todo maximiza el uso a cambio de que un cliente pueda degradar a los demás.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo mantenés la idempotencia en un flujo de varios pasos con servicios externos?",
    respuestaEs:
      "Cada paso tiene que ser idempotente por separado, y la clave tiene que propagarse. Si tu API recibe un request con una idempotency key y adentro llama a un proveedor de pagos, esa llamada también se tiene que poder reintentar sin cobrar dos veces: se le pasa una clave de idempotencia derivada (la del cliente más el nombre del paso, o un id de operación generado y guardado antes de llamar), porque los proveedores serios la aceptan. Si el proveedor no la acepta, se guarda el estado de cada paso antes y después de llamarlo, y ante un reintento se consulta al proveedor si la operación ya existe (buscando por una referencia propia que se le envió) antes de repetirla. Para los efectos internos, una TABLA DE DEDUPLICACIÓN por id de mensaje o de operación evita aplicar dos veces lo mismo, y conviene guardar la marca en la misma transacción que el efecto. Cuando se puede, se prefieren CLAVES NATURALES en vez de sintéticas: un UNIQUE sobre (pedido_id, tipo_de_notificación) hace imposible el duplicado sin lógica adicional. Y el flujo completo se modela como una máquina de estados persistida, donde reintentar significa retomar desde el último estado confirmado, no empezar de nuevo, que es lo que hacen los orquestadores de workflows como Temporal.",
    respuestaEn:
      "Each step must be idempotent on its own, and the key must be propagated. If your API receives a request with an idempotency key and internally calls a payment provider, that call must also be retryable without double charging: pass it a derived idempotency key (the client's plus the step name, or an operation id generated and stored before calling), since serious providers accept one. If the provider doesn't, store each step's state before and after calling it, and on retry ask the provider whether the operation already exists (searching by your own reference sent to it) before repeating. For internal effects, a DEDUPLICATION TABLE by message or operation id prevents applying the same thing twice, ideally stored in the same transaction as the effect. When possible, prefer NATURAL keys over synthetic ones: a UNIQUE on (order_id, notification_type) makes duplicates impossible with no extra logic. And the whole flow is modeled as a persisted state machine, where retrying means resuming from the last confirmed state, not starting over, which is what workflow orchestrators like Temporal do.",
  },
  {
    nivel: 3,
    pregunta: "En una entrevista de system design te piden diseñar un rate limiter. ¿Cómo lo encarás?",
    respuestaEs:
      "Primero REQUISITOS: ¿limita por usuario, por IP, por API key, por tenant? ¿Qué granularidad (por segundo, por minuto, por día)? ¿Es para proteger al sistema o para aplicar planes comerciales? ¿Cuánta precisión hace falta: se tolera pasarse un poco en el límite a cambio de latencia? ¿Qué volumen: cuántas requests por segundo y cuántos clientes distintos? Después la UBICACIÓN: un middleware en cada servicio, o un servicio o gateway central. Luego el ALGORITMO: token bucket si se quieren ráfagas controladas, ventana deslizante si se quiere precisión. Después el ESTADO, que es el núcleo del problema: los contadores tienen que ser compartidos entre todas las instancias, típicamente en Redis, con la lectura y la actualización en una sola operación atómica (un script Lua) para que no haya carreras. Con la ESCALA aparecen los trade-offs: una llamada a Redis por request suma latencia y convierte a Redis en dependencia crítica; se puede mitigar con contadores locales que se sincronizan cada tanto (menos precisos), sharding de las claves, y una decisión explícita de qué hacer si Redis no responde: dejar pasar (fail open, prioriza disponibilidad) o rechazar (fail closed, prioriza protección). Y por último la INTERFAZ: 429, `Retry-After`, headers de cuota restante, y métricas de cuántas requests se rechazan por cliente.",
    respuestaEn:
      "First REQUIREMENTS: does it limit by user, IP, API key, tenant? What granularity (per second, minute, day)? Is it to protect the system or enforce commercial plans? How much precision is needed: is slightly exceeding the limit acceptable in exchange for latency? What volume: how many requests per second and how many distinct clients? Then the LOCATION: middleware in each service, or a central service or gateway. Then the ALGORITHM: token bucket for controlled bursts, sliding window for precision. Then the STATE, the core of the problem: counters must be shared across every instance, typically in Redis, with read and update in a single atomic operation (a Lua script) to avoid races. With SCALE come the trade-offs: a Redis call per request adds latency and makes Redis a critical dependency; you can mitigate with local counters synced periodically (less precise), sharding the keys, and an explicit decision on what to do if Redis doesn't answer: let requests through (fail open, favors availability) or reject them (fail closed, favors protection). And finally the INTERFACE: 429, `Retry-After`, remaining-quota headers, and metrics on how many requests are rejected per client.",
    tradeoffs:
      "Fail open prioriza disponibilidad y arriesga sobrecarga; fail closed protege al sistema y arriesga rechazar tráfico legítimo cuando falla el limitador.",
  },
];
