import type { PreguntaEntrevista } from "../types";

export const entrevistaLoadBalancing: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué diferencia hay entre escalar vertical y horizontalmente?",
    respuestaEs:
      "Escalar VERTICALMENTE es darle más recursos a la misma máquina: más CPU, más memoria, discos más rápidos. Es lo más simple, porque no cambia nada en la arquitectura ni en el código, y para una base de datos suele ser la primera opción. Sus límites: hay un techo (la máquina más grande que existe), el costo crece más rápido que la capacidad en los tamaños grandes, cambiar de tamaño suele requerir un reinicio, y sigue siendo un único punto de falla. Escalar HORIZONTALMENTE es agregar más máquinas y repartir la carga entre ellas con un balanceador. No tiene un techo práctico, permite agregar y quitar capacidad según la demanda, y da tolerancia a fallas: si una instancia se cae, las demás siguen. Su costo es de diseño: la aplicación tiene que poder correr en varias copias a la vez, lo que exige que no guarde estado local. En la práctica se combinan: la capa de aplicación, sin estado, escala horizontalmente con facilidad; la base de datos, que tiene estado, se escala primero verticalmente y recién después con réplicas o sharding.",
    respuestaEn:
      "Scaling VERTICALLY means giving the same machine more resources: more CPU, more memory, faster disks. It's the simplest, since nothing changes in architecture or code, and for a database it's usually the first option. Its limits: there's a ceiling (the biggest machine available), cost grows faster than capacity at large sizes, resizing usually requires a restart, and it's still a single point of failure. Scaling HORIZONTALLY means adding more machines and spreading load across them with a load balancer. It has no practical ceiling, lets you add and remove capacity with demand, and provides fault tolerance: if one instance dies, the others continue. Its cost is in design: the application must be able to run as several copies at once, which requires not keeping local state. In practice they're combined: the stateless application layer scales horizontally with ease; the stateful database scales vertically first and only later with replicas or sharding.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué tiene que cumplir una aplicación para escalar horizontalmente?",
    respuestaEs:
      "Que cualquier instancia pueda atender cualquier request, o sea, que no guarde estado propio que otra instancia necesite. En concreto: las SESIONES van a un almacén compartido (Redis, la base) o en un token firmado, no en la memoria del proceso; si no, el usuario pierde la sesión cuando el balanceador lo manda a otra instancia. Los ARCHIVOS que suben los usuarios van a un storage compartido como S3, no al disco local. Las CACHÉS en memoria son aceptables solo si pueden estar desactualizadas un rato, o se reemplazan por una caché compartida. Las TAREAS PROGRAMADAS no pueden correr en cada instancia, porque se ejecutarían N veces; se sacan a un scheduler o worker aparte, o se coordinan con un lock distribuido. Las CONEXIONES a la base se multiplican por la cantidad de instancias, así que hace falta un pool dimensionado o un pooler. Y las operaciones tienen que tolerar reintentos, porque el balanceador puede reenviar una request a otra instancia si la primera falló a mitad de camino. Una buena prueba: si podés matar cualquier instancia en cualquier momento sin que ningún usuario lo note, la aplicación está lista.",
    respuestaEn:
      "That any instance can serve any request, meaning it keeps no local state another instance would need. Concretely: SESSIONS go to a shared store (Redis, the database) or a signed token, not process memory; otherwise the user loses the session when the load balancer sends them to another instance. User-uploaded FILES go to shared storage like S3, not the local disk. In-memory CACHES are acceptable only if they can be stale for a while, or they're replaced by a shared cache. SCHEDULED TASKS can't run on every instance, since they'd execute N times; they move to a separate scheduler or worker, or are coordinated with a distributed lock. Database CONNECTIONS multiply by the number of instances, so you need a sized pool or a pooler. And operations must tolerate retries, since the balancer may resend a request to another instance if the first failed midway. A good test: if you can kill any instance at any time without any user noticing, the application is ready.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué algoritmos de balanceo hay y cuándo conviene cada uno?",
    respuestaEs:
      "ROUND-ROBIN reparte en orden, una request a cada servidor. Es simple y funciona bien cuando todas las requests cuestan parecido y los servidores son iguales; falla cuando no: si las requests pesadas siguen un patrón, pueden caer siempre en el mismo servidor, y reparte la misma cantidad de requests, no la misma carga. Con servidores de distinta capacidad se usa su variante ponderada. LEAST CONNECTIONS manda cada request al servidor con menos requests activas: se adapta solo a requests de duración muy variable y a servidores más lentos, porque uno ocupado acumula conexiones y deja de recibir. Es un buen default para APIs con cargas heterogéneas. LEAST RESPONSE TIME o variantes similares miran además la latencia reciente. ALEATORIO con 'dos opciones' (elegir dos servidores al azar y mandar al menos cargado) da un reparto casi óptimo con muy poca coordinación, útil cuando hay muchos balanceadores que no comparten estado. Y el balanceo por HASH (de IP, de usuario, de una clave) manda siempre la misma entidad al mismo servidor, lo que sirve para aprovechar cachés locales o para estado de sesión, pero se desbalancea si una entidad genera mucho más tráfico que las demás.",
    respuestaEn:
      "ROUND-ROBIN distributes in order, one request per server. It's simple and works well when all requests cost about the same and servers are identical; it fails when they don't: if heavy requests follow a pattern, they can always land on the same server, and it evens out request counts, not load. With servers of different capacity you use its weighted variant. LEAST CONNECTIONS sends each request to the server with the fewest active requests: it adapts on its own to highly variable request durations and slower servers, since a busy one accumulates connections and stops receiving. It's a good default for APIs with heterogeneous load. LEAST RESPONSE TIME or similar variants also look at recent latency. RANDOM with 'two choices' (pick two servers at random and send to the less loaded) gives near-optimal distribution with very little coordination, useful when there are many load balancers that don't share state. And HASH-based balancing (by IP, user or a key) always sends the same entity to the same server, which helps exploit local caches or session state, but becomes unbalanced if one entity generates far more traffic than the rest.",
    tradeoffs:
      "Algoritmos simples (round-robin) no necesitan estado pero ignoran la carga real; los que miran la carga (least connections) se adaptan mejor a cambio de más información por request.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué son las sticky sessions y por qué conviene evitarlas?",
    respuestaEs:
      "Son una configuración del balanceador que manda todas las requests de un mismo usuario a la misma instancia, normalmente con una cookie. Se usan para que funcione una aplicación que guarda estado en memoria: la sesión, un carrito, un wizard a medio completar. El problema es que esconden la falta de un diseño sin estado y traen costos. REPARTO DESPAREJO: los usuarios quedan atados a su instancia aunque esté sobrecargada, y las instancias nuevas del autoscaling reciben solo usuarios nuevos, así que tardan en ayudar. FALLAS: si la instancia se cae o se reemplaza en un deploy, sus usuarios pierden el estado. DEPLOYS más lentos: hay que esperar a que las sesiones se vacíen antes de sacar una instancia. La alternativa es no depender de la afinidad: el estado en un almacén compartido. Hay casos donde la afinidad es legítima: las conexiones WebSocket, que viven en una instancia mientras duran, y los diseños donde se enruta a propósito por una clave para aprovechar una caché local (por ejemplo, un shard de datos en memoria), aunque ahí se usa consistent hashing, que tolera mejor los cambios en la cantidad de instancias.",
    respuestaEn:
      "They're a load balancer setting that sends all of a user's requests to the same instance, usually with a cookie. They're used to make an application that keeps state in memory work: the session, a cart, a half-completed wizard. The problem is they hide the lack of a stateless design and bring costs. UNEVEN DISTRIBUTION: users stay tied to their instance even when it's overloaded, and new autoscaled instances only get new users, so they're slow to help. FAILURES: if the instance dies or is replaced in a deploy, its users lose their state. SLOWER DEPLOYS: you must wait for sessions to drain before removing an instance. The alternative is not depending on affinity: state in a shared store. There are cases where affinity is legitimate: WebSocket connections, which live on one instance while they last, and designs that intentionally route by key to exploit a local cache (for example, an in-memory data shard), although there consistent hashing is used, which handles changes in instance count better.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es el consistent hashing y qué problema resuelve?",
    respuestaEs:
      "Cuando se reparten claves entre servidores con `hash(clave) % N`, cambiar N (agregar o quitar un servidor) cambia el destino de casi todas las claves: pasar de 4 a 5 servidores mueve alrededor del 80%. En un caché distribuido eso es un desastre, porque de golpe casi todo es miss y la base recibe toda la carga. El CONSISTENT HASHING ubica servidores y claves sobre un mismo anillo (el espacio de valores del hash), y cada clave va al primer servidor que encuentra avanzando en el anillo. Al agregar un servidor, solo se mueven las claves que caen entre él y su antecesor, en promedio 1/N del total; al quitarlo, solo las suyas pasan al siguiente. Con pocos servidores, sus posiciones en el anillo pueden quedar desparejas, así que se usan NODOS VIRTUALES: cada servidor aparece en muchas posiciones, lo que empareja el reparto y permite asignar más posiciones a servidores más potentes. Se usa en cachés distribuidos, en bases como Cassandra y DynamoDB para repartir particiones, y en balanceadores que quieren afinidad por clave sin reorganizar todo cuando escalan.",
    respuestaEn:
      "When keys are spread across servers with `hash(key) % N`, changing N (adding or removing a server) changes the destination of almost every key: going from 4 to 5 servers moves around 80%. In a distributed cache that's a disaster, since suddenly nearly everything misses and the database takes all the load. CONSISTENT HASHING places servers and keys on the same ring (the hash's value space), and each key goes to the first server found moving along the ring. When a server is added, only the keys between it and its predecessor move, on average 1/N of the total; when one is removed, only its keys pass to the next. With few servers, their ring positions can be uneven, so VIRTUAL NODES are used: each server appears at many positions, evening out the distribution and allowing more positions for more powerful servers. It's used in distributed caches, in databases like Cassandra and DynamoDB to spread partitions, and in load balancers wanting key affinity without reshuffling everything as they scale.",
    codigo: `// módulo: pasar de 4 a 5 servidores mueve casi todas las claves
claves.filter((k) => hash(k) % 4 !== hash(k) % 5).length / claves.length; // ≈ 0,8

// consistent hashing: se mueven solo las claves del tramo del servidor nuevo
// en promedio 1/5 de las claves (≈ 0,2)`,
  },
  {
    nivel: 3,
    pregunta: "¿Qué se rompe cuando escalás horizontalmente, y cómo protegés el sistema de la sobrecarga?",
    respuestaEs:
      "Escalar la capa sin estado desplaza el cuello de botella a lo que no escala igual: la base de datos (más instancias, más conexiones y más consultas contra el mismo primario), un servicio externo con rate limit, o un recurso compartido como un lock. Por eso escalar la aplicación sin mirar sus dependencias puede empeorar las cosas. Y ante un pico que supera la capacidad, el sistema tiene que degradarse bien en vez de caerse entero. HEALTH CHECKS bien diseñados: si dependen de la base, una lentitud momentánea marca a todas las instancias como caídas a la vez y el balanceador se queda sin destinos, un fallo en cascada. REINTENTOS con backoff exponencial, jitter y un límite, porque reintentos inmediatos multiplican la carga justo cuando el sistema está saturado (una tormenta de reintentos). LOAD SHEDDING: rechazar rápido, con un 503 y `Retry-After`, lo que excede la capacidad, priorizando lo importante (el checkout antes que las recomendaciones), en vez de aceptar todo y responder lento para todos. BACKPRESSURE: colas con límite que frenan al productor cuando el consumidor no da abasto. Y CIRCUIT BREAKERS hacia dependencias lentas, para dejar de esperarlas y fallar rápido mientras se recuperan. El balanceo global, entre regiones, suma DNS o anycast para mandar a cada usuario a la región sana más cercana.",
    respuestaEn:
      "Scaling the stateless layer shifts the bottleneck to what doesn't scale the same way: the database (more instances, more connections and more queries against the same primary), a rate-limited external service, or a shared resource like a lock. That's why scaling the application without looking at its dependencies can make things worse. And when a spike exceeds capacity, the system must degrade gracefully instead of falling over entirely. Well-designed HEALTH CHECKS: if they depend on the database, a momentary slowdown marks every instance as down at once and the balancer is left with no targets, a cascading failure. RETRIES with exponential backoff, jitter and a cap, because immediate retries multiply load exactly when the system is saturated (a retry storm). LOAD SHEDDING: quickly reject, with a 503 and `Retry-After`, what exceeds capacity, prioritizing what matters (checkout before recommendations), instead of accepting everything and answering slowly for everyone. BACKPRESSURE: bounded queues that slow the producer when the consumer can't keep up. And CIRCUIT BREAKERS toward slow dependencies, to stop waiting on them and fail fast while they recover. Global balancing, across regions, adds DNS or anycast to send each user to the nearest healthy region.",
  },
];
