import type { PreguntaEntrevista } from "../types";

export const entrevistaCleanHexagonal: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué es la arquitectura hexagonal (puertos y adaptadores)?",
    respuestaEs:
      "Es una forma de organizar una aplicación para que la lógica de negocio no dependa de la tecnología. En el centro está el dominio y los casos de uso. Cuando el núcleo necesita algo del exterior (guardar un pedido, cobrar, mandar un mail), no lo llama directamente: declara un PUERTO, una interfaz que describe lo que necesita (`PedidosRepo.guardar`, `PasarelaPagos.cobrar`). Afuera, los ADAPTADORES implementan esos puertos con tecnología concreta: un repositorio con Prisma, un cliente de Stripe. También hay adaptadores de entrada, como un controller HTTP o un consumidor de una cola, que traducen del mundo exterior a los casos de uso. Un único lugar, el composition root, conecta cada puerto con su adaptador. El resultado: se puede cambiar la base o el proveedor de pagos sin tocar la lógica, y testear los casos de uso con adaptadores en memoria, sin infraestructura.",
    respuestaEn:
      "It's a way to organize an application so business logic doesn't depend on technology. At the center are the domain and use cases. When the core needs something external (saving an order, charging, sending an email), it doesn't call it directly: it declares a PORT, an interface describing what it needs (`OrdersRepo.save`, `PaymentGateway.charge`). Outside, ADAPTERS implement those ports with concrete technology: a Prisma repository, a Stripe client. There are also inbound adapters, like an HTTP controller or a queue consumer, translating from the outside world to use cases. A single place, the composition root, wires each port to its adapter. The result: you can swap the database or payment provider without touching the logic, and test use cases with in-memory adapters, without infrastructure.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué dice la regla de dependencias de Clean Architecture?",
    respuestaEs:
      "Que las dependencias de código fuente apuntan siempre hacia ADENTRO: las capas externas (frameworks, base de datos, UI, controllers) conocen a las internas (casos de uso, entidades), pero nunca al revés. Una entidad de dominio no importa nada de Prisma, de Express ni de React; un caso de uso no sabe si lo llamó un endpoint HTTP o un job. Cuando el núcleo necesita algo de afuera, se aplica inversión de dependencias: el núcleo define la interfaz y la capa externa la implementa, así la flecha del import sigue apuntando hacia adentro aunque el flujo de ejecución vaya hacia afuera. Clean Architecture (Robert Martin), hexagonal (Alistair Cockburn) y onion architecture son variaciones de la misma idea: proteger la lógica de negocio, que es lo que más valor tiene y lo que más tiempo vive, de los detalles que cambian (frameworks, proveedores, bases).",
    respuestaEn:
      "That source code dependencies always point INWARD: outer layers (frameworks, database, UI, controllers) know the inner ones (use cases, entities), never the reverse. A domain entity imports nothing from Prisma, Express or React; a use case doesn't know whether an HTTP endpoint or a job called it. When the core needs something external, dependency inversion applies: the core defines the interface and the outer layer implements it, so the import arrow keeps pointing inward even though execution flows outward. Clean Architecture (Robert Martin), hexagonal (Alistair Cockburn) and onion architecture are variations of the same idea: protecting business logic, the most valuable and longest-lived part, from details that change (frameworks, providers, databases).",
  },
  {
    nivel: 2,
    pregunta: "¿Cuándo vale la pena aplicar Clean o Hexagonal, y cuándo es sobre-ingeniería?",
    respuestaEs:
      "Vale la pena cuando hay lógica de negocio real y duradera: reglas de dominio complejas (seguros, finanzas, logística), sistemas que van a vivir años y pasar por varios proveedores o frameworks, varios canales de entrada para los mismos casos de uso (API, jobs, CLI, colas), o cuando se necesita testear mucha lógica rápido y sin infraestructura. Es sobre-ingeniería en un CRUD donde casi no hay reglas (el 'caso de uso' solo pasa datos del controller a la base), en prototipos, o en equipos chicos donde las capas extra, las interfaces con una única implementación y el mapeo entre DTOs y entidades agregan más ceremonia que valor. Una postura pragmática: aplicar las ideas donde duelen (aislar a los proveedores externos detrás de un adaptador, sacar la lógica de negocio de los controllers) sin imponer todas las capas a todo el sistema.",
    respuestaEn:
      "It's worth it when there's real, lasting business logic: complex domain rules (insurance, finance, logistics), systems that will live for years and go through several providers or frameworks, multiple entry channels for the same use cases (API, jobs, CLI, queues), or when lots of logic needs testing fast without infrastructure. It's over-engineering in a CRUD with almost no rules (the 'use case' just passes data from controller to database), in prototypes, or in small teams where extra layers, interfaces with a single implementation and mapping between DTOs and entities add more ceremony than value. A pragmatic stance: apply the ideas where it hurts (isolate external providers behind an adapter, move business logic out of controllers) without imposing every layer on the whole system.",
    tradeoffs:
      "Las capas dan independencia y testeabilidad a cambio de indirección: más archivos, más mapeos y más saltos para seguir un flujo. En dominios simples, ese costo no se recupera.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué es el composition root y por qué conviene tener uno solo?",
    respuestaEs:
      "Es el único lugar de la aplicación donde se construyen los objetos concretos y se conectan entre sí: se crea el `PrismaPedidosRepo`, el `StripePasarela`, y se pasan al constructor de `CrearPedido`. Todo el resto del código recibe sus dependencias ya armadas (inyección de dependencias) y solo conoce interfaces. Tenerlo en un solo lugar (el `main.ts`, el módulo raíz de NestJS o un contenedor de DI) hace que cambiar una implementación sea tocar una línea, que los tests puedan armar el mismo caso de uso con adaptadores en memoria, y que sea fácil ver qué implementación se usa en cada entorno. Si los objetos se crean con `new` en cualquier parte, las dependencias concretas quedan esparcidas y la inversión de dependencias se rompe en silencio. No hace falta un framework de DI: en muchas apps alcanza con construir todo a mano en un archivo.",
    respuestaEn:
      "It's the single place in the app where concrete objects are built and wired together: `PrismaOrdersRepo` and `StripeGateway` are created and passed to `CreateOrder`'s constructor. The rest of the code receives its dependencies already built (dependency injection) and only knows interfaces. Keeping it in one place (`main.ts`, NestJS's root module or a DI container) means swapping an implementation is a one-line change, tests can build the same use case with in-memory adapters, and it's easy to see which implementation each environment uses. If objects are created with `new` anywhere, concrete dependencies get scattered and dependency inversion silently breaks. No DI framework is needed: in many apps building everything by hand in one file is enough.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo se aplican estas ideas en un frontend React?",
    respuestaEs:
      "La regla de dependencias sirve igual, adaptada. La lógica de negocio (cálculos, validaciones, reglas de qué se puede hacer) va en funciones o módulos puros, sin React ni fetch, fáciles de testear. El acceso a datos va detrás de una capa propia (un cliente o 'repositorio' de API) en vez de `fetch` esparcido por los componentes, así cambiar de REST a GraphQL o de endpoint toca un solo lugar. Los hooks actúan como casos de uso de la UI: orquestan la lógica y los datos, y los componentes quedan como adaptadores de presentación, que solo renderizan y delegan eventos. Los SDKs de terceros (analytics, pagos, feature flags) se envuelven en un módulo propio. No hace falta replicar todas las capas de un backend: un frontend típico no tiene tanto dominio, y la sobre-abstracción ahí es un riesgo real. Pero separar reglas de negocio, acceso a datos y presentación rinde mucho en apps grandes.",
    respuestaEn:
      "The dependency rule applies just the same, adapted. Business logic (calculations, validations, rules about what's allowed) goes in pure functions or modules, with no React or fetch, easy to test. Data access goes behind your own layer (an API client or 'repository') instead of `fetch` scattered across components, so switching from REST to GraphQL or changing an endpoint touches one place. Hooks act as UI use cases: they orchestrate logic and data, and components become presentation adapters that only render and delegate events. Third-party SDKs (analytics, payments, feature flags) get wrapped in your own module. There's no need to replicate every backend layer: a typical frontend doesn't have that much domain, and over-abstraction there is a real risk. But separating business rules, data access and presentation pays off greatly in large apps.",
  },
  {
    nivel: 3,
    pregunta: "¿Las entidades de dominio deberían ser los mismos objetos que usa el ORM?",
    respuestaEs:
      "En Clean estricto, no: las entidades de dominio no conocen la persistencia, y el adaptador del repositorio mapea entre la entidad y el modelo del ORM (con sus decoradores, relaciones y detalles de columnas). Eso protege al dominio de cambios en el esquema o en el ORM y permite que la entidad tenga comportamiento e invariantes propios (un `Pedido` que no se puede crear sin ítems). El costo es el mapeo, que duplica estructuras y agrega código en cada repositorio. En la práctica muchos equipos usan los tipos del ORM como entidades cuando el dominio es simple, y separan solo cuando la lógica crece o el modelo de persistencia empieza a imponer restricciones al dominio. Lo que sí conviene siempre es no dejar que los objetos del ORM (con lazy loading, métodos de guardado, campos internos) se filtren hasta las respuestas de la API: ahí va un DTO explícito.",
    respuestaEn:
      "In strict Clean, no: domain entities don't know about persistence, and the repository adapter maps between the entity and the ORM model (with its decorators, relations and column details). That shields the domain from schema or ORM changes and lets the entity have its own behavior and invariants (an `Order` that can't be created without items). The cost is mapping, which duplicates structures and adds code in every repository. In practice many teams use ORM types as entities when the domain is simple, and separate only when logic grows or the persistence model starts imposing constraints on the domain. What's always wise is not letting ORM objects (with lazy loading, save methods, internal fields) leak into API responses: an explicit DTO goes there.",
  },
];
