import type { PreguntaEntrevista } from "../types";

export const entrevistaEstructuraCarpetas: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Qué diferencia hay entre organizar el código por capas y por features?",
    respuestaEs:
      "Por capas (layer-based) agrupa por TIPO TÉCNICO de archivo: todos los componentes en `components/`, todos los hooks en `hooks/`, los servicios en `services/`, los tipos en `types/`. Es intuitivo al empezar y funciona bien en proyectos chicos. Por features (feature-based) agrupa por FUNCIONALIDAD de negocio: `features/carrito/` contiene los componentes, hooks, llamadas a la API, tipos y utilidades del carrito, y lo compartido de verdad va a `shared/`. La diferencia se nota al crecer: en capas, un cambio en el carrito toca cinco carpetas mezcladas con archivos de todas las demás features, y es difícil saber qué pertenece a qué; en features, lo que cambia junto vive junto (alta cohesión), un equipo puede ser dueño de una carpeta, y borrar una funcionalidad es borrar una carpeta. Para proyectos medianos y grandes, feature-based suele escalar mejor.",
    respuestaEn:
      "By layer groups files by TECHNICAL TYPE: all components in `components/`, all hooks in `hooks/`, services in `services/`, types in `types/`. It's intuitive at first and works well for small projects. By feature groups by business FUNCTIONALITY: `features/cart/` holds the cart's components, hooks, API calls, types and utilities, and truly shared code goes to `shared/`. The difference shows as it grows: by layer, a cart change touches five folders mixed with files from every other feature, and it's hard to tell what belongs where; by feature, what changes together lives together (high cohesion), a team can own a folder, and removing a feature means deleting a folder. For medium and large projects, feature-based usually scales better.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué va en `shared/` y qué no?",
    respuestaEs:
      "En `shared/` va lo que es genérico y no pertenece a ninguna feature: componentes de UI del design system (botón, modal, input), utilidades puras (formatear fechas o moneda), el cliente HTTP base, hooks genéricos (`useDebounce`, `useMediaQuery`) y la configuración. No va código de negocio de una feature 'por si otra lo necesita': eso convierte a `shared/` en un cajón de sastre que termina acoplando todo. La regla práctica: algo se mueve a `shared/` recién cuando dos o más features lo usan de verdad, y conviene que no importe nada de las features (las dependencias van de features hacia shared, nunca al revés). Si un componente compartido empieza a recibir props como `modoCarrito` o `esCheckout`, es señal de que en realidad son dos componentes distintos.",
    respuestaEn:
      "`shared/` holds what's generic and belongs to no feature: design system UI components (button, modal, input), pure utilities (formatting dates or currency), the base HTTP client, generic hooks (`useDebounce`, `useMediaQuery`) and config. It doesn't hold a feature's business code 'in case another needs it': that turns `shared/` into a junk drawer that ends up coupling everything. The practical rule: something moves to `shared/` only when two or more features truly use it, and it shouldn't import anything from features (dependencies go from features to shared, never the reverse). If a shared component starts receiving props like `cartMode` or `isCheckout`, it's a sign it's really two different components.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo evitás que las features se acoplen entre sí?",
    respuestaEs:
      "Con una API pública por feature y reglas que la hagan cumplir. Cada feature expone lo que otras pueden usar desde un `index.ts` (el componente `<ResumenCarrito />`, el hook `useCantidadEnCarrito`), y el resto es interno: nadie importa `features/carrito/components/CarritoItem` desde afuera. Así se puede reorganizar el interior de una feature sin romper a las demás. Las reglas se verifican automáticamente con ESLint (`eslint-plugin-boundaries`, `import/no-restricted-paths`) o dependency-cruiser, fallando el CI ante imports prohibidos. También conviene definir la dirección permitida entre capas: `app/` (rutas) usa features, features usan `shared/`, `shared/` no usa nada de arriba; y entre features, evitar dependencias circulares. Si dos features se necesitan mucho mutuamente, quizás deberían ser una sola, o la parte compartida es una tercera.",
    respuestaEn:
      "With a public API per feature and rules enforcing it. Each feature exposes what others may use from an `index.ts` (the `<CartSummary />` component, the `useCartCount` hook), and the rest is internal: nobody imports `features/cart/components/CartItem` from outside. So a feature's internals can be reorganized without breaking the others. Rules are verified automatically with ESLint (`eslint-plugin-boundaries`, `import/no-restricted-paths`) or dependency-cruiser, failing CI on forbidden imports. It's also wise to define the allowed direction between layers: `app/` (routes) uses features, features use `shared/`, `shared/` uses nothing above; and between features, avoid circular dependencies. If two features need each other a lot, maybe they should be one, or the shared part is a third.",
    tradeoffs:
      "Los barrel files (`index.ts`) ordenan la API pública pero pueden empeorar el tree-shaking y los tiempos de compilación; conviene mantenerlos chicos y sin re-exportar todo.",
  },
  {
    nivel: 2,
    pregunta: "¿Cómo encaja la estructura por features con el App Router de Next.js?",
    respuestaEs:
      "El directorio `app/` define las RUTAS, y conviene que quede delgado: cada `page.tsx` compone piezas que vienen de las features en vez de contener la lógica. Por ejemplo, `app/carrito/page.tsx` importa `<Carrito />` desde `features/carrito` y como mucho resuelve params o metadata. Así el routing (que Next impone por convención) queda separado de la organización del dominio, y una feature puede aparecer en varias rutas. Next permite colocar archivos dentro de `app/` sin que sean rutas (solo `page` y `route` exponen URLs), y las carpetas privadas con guion bajo (`_components`) excluyen explícitamente del routing, así que para piezas que solo usa una ruta, colocarlas al lado también es válido. La combinación habitual: `app/` para rutas y layouts, `features/` para el dominio, `shared/` para lo genérico.",
    respuestaEn:
      "The `app/` directory defines ROUTES, and it's best kept thin: each `page.tsx` composes pieces from features rather than containing logic. For example, `app/cart/page.tsx` imports `<Cart />` from `features/cart` and at most resolves params or metadata. That separates routing (imposed by Next's conventions) from domain organization, and a feature can appear in several routes. Next allows colocating files inside `app/` without them becoming routes (only `page` and `route` expose URLs), and underscore-prefixed private folders (`_components`) explicitly opt out of routing, so for pieces used by a single route, colocating them alongside is also valid. The common combination: `app/` for routes and layouts, `features/` for the domain, `shared/` for generic code.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué es Feature-Sliced Design y qué aporta sobre un 'features/' simple?",
    respuestaEs:
      "Es una metodología que formaliza la organización por features con capas jerárquicas y reglas de importación estrictas: `app` (inicialización, providers), `pages` (composición de rutas), `widgets` (bloques grandes de UI que combinan features), `features` (acciones del usuario con valor de negocio, como 'agregar al carrito'), `entities` (conceptos del dominio: producto, usuario, pedido) y `shared` (lo genérico). Una capa solo puede importar de las que están DEBAJO, y dentro de cada capa los 'slices' no se importan entre sí. Aporta sobre un `features/` plano una respuesta clara a dónde va cada cosa (especialmente la distinción entre entidad y feature, que en estructuras simples genera discusiones) y una dirección de dependencias verificable. El costo es la curva de aprendizaje y más ceremonia; para equipos grandes o proyectos de larga vida suele valer, para una app chica es demasiado.",
    respuestaEn:
      "It's a methodology formalizing feature-based organization with hierarchical layers and strict import rules: `app` (initialization, providers), `pages` (route composition), `widgets` (large UI blocks combining features), `features` (user actions with business value, like 'add to cart'), `entities` (domain concepts: product, user, order) and `shared` (generic code). A layer may only import from those BELOW it, and within a layer, 'slices' don't import each other. Over a flat `features/`, it offers a clear answer to where each thing goes (especially the entity vs feature distinction, which sparks debate in simpler structures) and a verifiable dependency direction. The cost is the learning curve and more ceremony; for large teams or long-lived projects it's often worth it, for a small app it's too much.",
  },
  {
    nivel: 3,
    pregunta: "Heredás un proyecto grande organizado por capas. ¿Lo migrás a features? ¿Cómo?",
    respuestaEs:
      "Solo si el dolor es real: si los cambios típicos tocan muchas carpetas, hay mucho código muerto, o varios equipos se pisan. Si el proyecto está estable y casi no cambia, una migración masiva es riesgo sin retorno. Si se decide, que sea incremental: empezar por la feature que más se está tocando o por las nuevas (todo lo nuevo nace en `features/`), mover de a una feature con sus componentes, hooks, servicios y tipos, dejando reexports temporales en las ubicaciones viejas para no romper imports (o usar un codemod o el refactor del editor para actualizar todos los imports de una vez). Cada movimiento en un PR chico, sin cambios de lógica mezclados, para que la revisión sea trivial y el historial de git se pueda seguir. Y agregar las reglas de límites de a poco, primero como warning y después como error. Mezclar reorganización con cambios de comportamiento es la forma segura de introducir bugs difíciles de encontrar.",
    respuestaEn:
      "Only if the pain is real: if typical changes touch many folders, there's lots of dead code, or several teams step on each other. If the project is stable and barely changes, a massive migration is risk without return. If you go for it, make it incremental: start with the feature being touched the most or with new ones (everything new is born in `features/`), move one feature at a time with its components, hooks, services and types, leaving temporary re-exports at old locations so imports don't break (or use a codemod or the editor's refactor to update all imports at once). Each move in a small PR, without mixed logic changes, so review is trivial and git history remains traceable. And add boundary rules gradually, first as warnings, then as errors. Mixing reorganization with behavior changes is the surest way to introduce hard-to-find bugs.",
  },
];
