import type { PreguntaEntrevista } from "../types";

export const entrevistaMonolitoMicroservicios: PreguntaEntrevista[] = [
  {
    nivel: 1,
    pregunta: "¿Monolito o microservicios? ¿Cómo decidís?",
    respuestaEs:
      "Por el problema concreto, no por moda. Un monolito (una aplicación, un deploy, una base) es más simple de desarrollar, testear, desplegar y depurar: una llamada entre módulos es una llamada a función, no un request de red que puede fallar, y una transacción abarca todo. Los microservicios (servicios independientes, cada uno con su base, comunicados por red) resuelven sobre todo problemas ORGANIZACIONALES y de escala: permiten que muchos equipos desplieguen de forma independiente, escalar por separado las partes con carga distinta y aislar fallas. A cambio, traen los problemas de un sistema distribuido: latencia, fallas parciales, consistencia eventual, observabilidad, versionado de contratos y mucha más infraestructura. Mi default es empezar con un monolito modular, con límites claros entre módulos, y extraer un servicio cuando aparece una razón concreta: un equipo que necesita desplegar independiente, un componente con necesidades de escala o de tecnología muy distintas.",
    respuestaEn:
      "By the concrete problem, not by trend. A monolith (one app, one deploy, one database) is simpler to develop, test, deploy and debug: a call between modules is a function call, not a network request that can fail, and one transaction spans everything. Microservices (independent services, each with its own database, communicating over the network) mainly solve ORGANIZATIONAL and scale problems: they let many teams deploy independently, scale parts with different loads separately and isolate failures. In exchange, they bring distributed-system problems: latency, partial failures, eventual consistency, observability, contract versioning and much more infrastructure. My default is starting with a modular monolith, with clear boundaries between modules, and extracting a service when a concrete reason appears: a team that needs to deploy independently, a component with very different scale or technology needs.",
  },
  {
    nivel: 1,
    pregunta: "¿Qué son los microfrontends y qué problema resuelven?",
    respuestaEs:
      "Son la aplicación de la idea de microservicios al frontend: la interfaz se divide en partes (por sección o por dominio: catálogo, checkout, cuenta) que desarrollan y despliegan equipos distintos de forma independiente, y se integran en una aplicación 'shell'. Resuelven un problema de ESCALA ORGANIZACIONAL: cuando muchos equipos trabajan sobre un mismo frontend, el repo compartido, el CI lento y el deploy único se vuelven un cuello de botella. La integración puede hacerse en el build (paquetes npm, lo que pierde el deploy independiente), en el servidor (composición de fragmentos), o en el cliente en runtime (Module Federation, import maps, web components). Los costos son reales: consistencia visual (hace falta un design system compartido), dependencias duplicadas que engordan el bundle, comunicación entre partes, y performance. Para un equipo o dos, casi nunca compensa.",
    respuestaEn:
      "They apply the microservices idea to the frontend: the UI is split into parts (by section or domain: catalog, checkout, account) that different teams develop and deploy independently, integrated into a 'shell' application. They solve an ORGANIZATIONAL SCALE problem: when many teams work on the same frontend, the shared repo, slow CI and single deploy become a bottleneck. Integration can happen at build time (npm packages, losing independent deploys), on the server (fragment composition), or on the client at runtime (Module Federation, import maps, web components). The costs are real: visual consistency (a shared design system is needed), duplicated dependencies bloating the bundle, communication between parts, and performance. For one or two teams, it rarely pays off.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué es un monolito modular y por qué se lo recomienda tanto?",
    respuestaEs:
      "Es un monolito con límites internos explícitos: el código se organiza en módulos por dominio (pedidos, facturación, catálogo), cada uno con una interfaz pública y su lógica y datos internos privados, y los módulos solo se comunican a través de esas interfaces. Se despliega como una sola unidad, pero se diseña como si pudiera partirse. Da la mayoría de los beneficios de diseño de los microservicios (ownership por equipo, bajo acoplamiento, capacidad de razonar sobre una parte) sin los costos de un sistema distribuido: sin red entre módulos, con transacciones, un solo deploy y un stack de observabilidad simple. Los límites hay que VERIFICARLOS, no solo documentarlos: con reglas de lint de dependencias (dependency-cruiser, ESLint boundaries), o en otros lenguajes con módulos del compilador. Y si algún día hace falta extraer un servicio, el límite ya existe, así que la extracción es mucho más barata.",
    respuestaEn:
      "It's a monolith with explicit internal boundaries: code is organized into domain modules (orders, billing, catalog), each with a public interface and private internal logic and data, and modules only communicate through those interfaces. It deploys as one unit, but is designed as if it could be split. It gives most of the design benefits of microservices (team ownership, low coupling, the ability to reason about one part) without distributed-system costs: no network between modules, with transactions, a single deploy and a simple observability stack. Boundaries must be ENFORCED, not just documented: with dependency lint rules (dependency-cruiser, ESLint boundaries), or in other languages with compiler modules. And if a service ever needs extracting, the boundary already exists, so extraction is much cheaper.",
    tradeoffs:
      "El monolito modular no permite escalar ni desplegar módulos por separado; si ese es el problema real, hace falta partir. Pero es mucho más barato extraer un módulo con límites claros que desarmar un monolito acoplado.",
  },
  {
    nivel: 2,
    pregunta: "¿Qué es un 'monolito distribuido' y cómo se evita?",
    respuestaEs:
      "Es el peor de los dos mundos: microservicios en la forma (varios servicios, varios deploys, red en el medio) pero acoplados como un monolito. Síntomas: no se puede desplegar un servicio sin desplegar otros al mismo tiempo; una feature típica requiere cambios coordinados en cinco servicios; los servicios comparten la misma base de datos o leen las tablas de otros; y hay cadenas largas de llamadas sincrónicas, donde si uno cae, caen todos. Tiene toda la complejidad operativa de los microservicios sin su beneficio principal, la independencia. Se evita partiendo por límites de DOMINIO (bounded contexts de DDD) y no por capas técnicas; dando a cada servicio su propia base; prefiriendo comunicación asincrónica por eventos donde la consistencia inmediata no es necesaria; manteniendo contratos compatibles hacia atrás para poder desplegar por separado; y, sobre todo, no partiendo antes de entender bien el dominio.",
    respuestaEn:
      "It's the worst of both worlds: microservices in form (several services, several deploys, network in between) but coupled like a monolith. Symptoms: a service can't be deployed without deploying others at the same time; a typical feature requires coordinated changes in five services; services share the same database or read each other's tables; and there are long chains of synchronous calls where if one falls, all fall. It has all the operational complexity of microservices without their main benefit, independence. It's avoided by splitting along DOMAIN boundaries (DDD bounded contexts) rather than technical layers; giving each service its own database; preferring asynchronous event communication where immediate consistency isn't needed; keeping contracts backward-compatible to deploy separately; and, above all, not splitting before understanding the domain well.",
  },
  {
    nivel: 3,
    pregunta: "¿Cómo migrarías un monolito grande a microservicios sin frenar el desarrollo?",
    respuestaEs:
      "Con el patrón Strangler Fig: en vez de una reescritura completa (que suele fracasar, porque el sistema viejo sigue cambiando y la nueva versión nunca lo alcanza), se extraen funcionalidades de a una. Se pone una capa de ruteo delante (un API gateway o proxy) que manda todo al monolito; se elige un módulo con buenos límites y buen retorno (uno con necesidades de escala distintas, o de un equipo bloqueado); se implementa como servicio; y se redirige el tráfico de esa funcionalidad al servicio nuevo, idealmente de forma gradual y con posibilidad de volver atrás. La parte difícil son los DATOS: el servicio necesita su propia base, y mientras conviven hay que sincronizar (doble escritura, change data capture o eventos) hasta cortar. Antes de extraer, conviene modularizar ese pedazo dentro del monolito: si no se puede separar en el mismo código, separarlo por red va a ser peor. Y tener observabilidad distribuida desde el primer servicio.",
    respuestaEn:
      "With the Strangler Fig pattern: instead of a full rewrite (which usually fails, since the old system keeps changing and the new version never catches up), functionality is extracted one piece at a time. Put a routing layer in front (an API gateway or proxy) sending everything to the monolith; pick a module with good boundaries and good return (one with different scale needs, or of a blocked team); implement it as a service; and redirect that functionality's traffic to the new service, ideally gradually and with the ability to roll back. The hard part is DATA: the service needs its own database, and while they coexist you have to sync (dual writes, change data capture or events) until cutover. Before extracting, modularize that piece inside the monolith: if it can't be separated within the same code, separating it over a network will be worse. And have distributed observability from the first service.",
  },
  {
    nivel: 3,
    pregunta: "¿Qué relación tiene la Ley de Conway con estas decisiones?",
    respuestaEs:
      "La Ley de Conway dice que las organizaciones diseñan sistemas que copian su estructura de comunicación: si tres equipos construyen un compilador, sale un compilador de tres pasadas. En arquitectura significa que los límites del sistema tienden a coincidir con los límites entre equipos, lo quieras o no. Por eso los microservicios y los microfrontends funcionan bien cuando cada servicio corresponde a un equipo autónomo que es dueño de un dominio, y funcionan mal cuando un servicio lo tocan cinco equipos o un equipo tiene que coordinar con otros cuatro para cada cambio. La 'maniobra inversa de Conway' usa esto a propósito: se diseña primero la estructura de equipos alineada a los dominios de negocio que querés como límites del sistema, y la arquitectura sigue. La consecuencia práctica en una entrevista: la decisión de partir un sistema es tanto organizacional como técnica, y una arquitectura de microservicios con un solo equipo suele ser una señal de sobre-ingeniería.",
    respuestaEn:
      "Conway's Law says organizations design systems that mirror their communication structure: if three teams build a compiler, you get a three-pass compiler. In architecture it means system boundaries tend to match team boundaries, whether you like it or not. That's why microservices and microfrontends work well when each service maps to an autonomous team owning a domain, and poorly when five teams touch one service or a team must coordinate with four others for every change. The 'inverse Conway maneuver' uses this deliberately: first design the team structure aligned to the business domains you want as system boundaries, and architecture follows. The practical takeaway in an interview: splitting a system is as much an organizational decision as a technical one, and a microservices architecture with a single team is usually a sign of over-engineering.",
  },
];
